objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>LD</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
            <value>
                <fullName>TF</fullName>
            </value>
            <value>
                <fullName>Traditional Voice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Contract Renewal Orders</description>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Provisioning_Product__c/Provisioning_Product__c.object-meta.xml
<CustomObject>
    <label>Provisioning Product</label>
    <nameField>
        <label>Provisioning Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provisioning Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Provisioning_Product__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SPC_Product__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>SPC Products</relationshipLabel>
    <relationshipName>SPC_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SPC_Product__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <externalId>true</externalId>
    <label>SalesProductExternalID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Sub_Order__c/fields/Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Install_Date__c</fullName>
    <label>Install Date</label>
    <type>DateTime</type>
</CustomField>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Sub Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

objects/Sub_Order_Group__c/Sub_Order_Group__c.object-meta.xml
<CustomObject>
    <label>Sub-Order Group</label>
    <nameField>
        <label>Sub-Order Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Order Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order_Group__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Sub_Order_Group__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Sub_Order_Group__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Sub-Order Groups</relationshipLabel>
    <relationshipName>Sub_Order_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <formula>Workstep_Library__r.External_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Workstep__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <formula>Sub_Order__r.SPC_Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SPC Product</label>
    <type>Text</type>
</CustomField>

objects/Workstep__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Workstep__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Workstep_Template__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/Workstep_Library__c.field-meta.xml
<CustomField>
    <fullName>Workstep_Library__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workstep Library</label>
    <referenceTo>Workstep_Library__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Workstep_Issue__c/Workstep_Issue__c.object-meta.xml
<CustomObject>
    <label>Workstep Issue</label>
    <nameField>
        <displayFormat>WI-{0000}</displayFormat>
        <label>Workstep Issues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workstep Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Workstep_Issue__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <formula>HYPERLINK( 
Workstep__r.Sub_Order__r.Id, 
Workstep__r.Sub_Order__r.Name )</formula>
    <label>Sub-Order</label>
    <type>Text</type>
</CustomField>

main/default/objects/Workstep_Library__c/Workstep_Library__c.object-meta.xml
<CustomObject>
    <label>Workstep Library</label>
    <nameField>
        <label>Workstep Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workstep Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Workstep_Library__c/fields/Complete_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Complete_Date_Field__c</fullName>
    <label>Complete Date Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Workstep_Template__c/Workstep_Template__c.object-meta.xml
<CustomObject>
    <label>Workstep Template</label>
    <nameField>
        <label>Workstep Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workstep Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep_Template__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Workstep_Template__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <formula>Workplan_Template__r.Provisioning_Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provisioning Product</label>
    <type>Text</type>
</CustomField>

main/default/objects/Workstep_Template__c/fields/Workstep_Library__c.field-meta.xml
<CustomField>
    <fullName>Workstep_Library__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Workstep Library</label>
    <referenceTo>Workstep_Library__c</referenceTo>
    <relationshipLabel>Workstep Templates</relationshipLabel>
    <relationshipName>Workstep_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/classes/Test_WorkstepTriggers.cls
@isTest
public with sharing class Test_WorkstepTriggers {
    
    static testMethod void testTriggers() {
        Mocks testData = new Mocks();
        test.startTest();
        Opportunity opp = testData.opportunity;
        Order__c ord = new Order__c(Opportunity__c = opp.Id);
        insert ord;
        
        SPC_Product__c spc = new SPC_Product__c(
            SalesProductExternalID__c = -1
            ,Provisioning_Product__c = testData.mpProvProd.get('Standard').Id
        );
        insert spc;
        
        Sub_Order__c so = new Sub_Order__c(
            Service_Location__c = testData.serviceLocation.Id
            ,Order__c = ord.Id
            ,SPC_Product__c = spc.Id
            ,Workplan_Start_Date__c = Date.today()
            ,Install_Date__c  = Date.today()
        );
        insert so;
        
        Sub_Order_Group__c sog = new Sub_Order_Group__c(
            Sub_Order__c = so.Id
            ,Quantity__c = 10
            ,Product__c = 'The Pickles'
            ,External_ID__c = '1'
        );
        insert sog;
        
        Workstep_Library__c wsl = new Workstep_Library__c(
            External_Id__c = -1
            ,Complete_Date_Field__c ='Sub_Order__c.Install_Date__c'
        );
        
        insert wsl;
        
        Workstep_Template__c wst = new Workstep_Template__c(
            External_Id__c = -1
            ,Workstep_Library__c = wsl.Id
        );
        insert wst;
        
        List<Workstep__c> ws = new List<Workstep__c>();
        ws.add(new Workstep__c(
            Order__c = ord.Id
            ,Sub_Order__c = so.Id
            ,Template__c = wst.Id
            ,Workstep_Library__c = wsl.Id
            , Status__c = 'Integrating'
            ,CTP_Attribute__c = 'Start'
        ));
        
        ws.add(new Workstep__c(
            Order__c = ord.Id
            ,Sub_Order__c = so.Id
            ,Template__c = wst.Id
            ,Workstep_Library__c = wsl.Id
            , Status__c = 'Open'
            ,CTP_Attribute__c = 'Start'
        ));
        
        
        ws.add(new Workstep__c(
            Order__c = ord.Id
            ,Sub_Order__c = so.Id
            ,Template__c = wst.Id
            ,Workstep_Library__c = wsl.Id
            ,Name = 'Activate with Customer'
            , Status__c = 'Complete'
            ,CTP_Attribute__c = 'End'
        ));
        
        wsl.Complete_Date_Field__c = '999';
        update wsl;
        ws.add(new Workstep__c(
            Order__c = ord.Id
            ,Sub_Order__c = so.Id
            ,Template__c = wst.Id
            ,Workstep_Library__c = wsl.Id
            ,Name = 'Activate with Customer'
            , Status__c = 'Cancelled'
            ,CTP_Attribute__c = 'End'
        ));
        
        ws.add(new Workstep__c(
            Order__c = ord.Id
            ,Sub_Order__c = so.Id
        ));
        
        insert ws;
        
        Predecessor__c pred = new Predecessor__c(
            Predecessor_Workstep__c = ws[0].Id
            , Dependent_Workstep__c = ws[3].Id
        );
        insert pred;
        
        Workstep__c up1 = ws[0];		        
        up1.Status__c ='Blocked';		
        update up1;		
        
        //Workstep_Issue__c wi = new Workstep_Issue__c( Workstep__c = ws[0].ID		
        //                                                    );		
        //insert wi;		
        Workstep__c up2 = ws[0];		
        up2.Status__c ='Cancelled';		
        update up2;
        
        Test.stopTest();
    }
    
    static testmethod void testTriggers2(){
        Mocks Testdata = new Mocks();
        
        Order__c ord = Testdata.order;
        Order__c ord2 = new Order__c(RecordTypeId = OrderUtils.BuildOrderRecordTypeID, Opportunity__c = Testdata.opportunity.Id, Building__c = Testdata.building.Id);
        insert ord2;
        
        SPC_Product__c spc = new SPC_Product__c(
            SalesProductExternalID__c = -1
            ,Provisioning_Product__c = testData.mpProvProd.get('Standard').Id
        );
        insert spc;
        
        Sub_Order__c so = new Sub_Order__c(
            Service_Location__c = testData.serviceLocation.Id
            ,Order__c = ord.Id
            ,SPC_Product__c = spc.Id
            ,Workplan_Start_Date__c = Date.today()
        );
        insert so;
        
        Sub_Order_Group__c sog = new Sub_Order_Group__c(
            Sub_Order__c = so.Id
            ,Quantity__c = 10
            ,Product__c = 'The Pickles'
            ,External_ID__c = '1'
        );
        insert sog;
        
        Workstep_Library__c wsl = new Workstep_Library__c(
            External_Id__c = -1,
            Complete_Date_Field__c = '999',
            Start_Date_Driving_Fields__c = '999',
            Start_Date_Driven_Duration__c = 1
        );
        
        insert wsl;
        
        Workstep_Template__c wst = new Workstep_Template__c(
            External_Id__c = -1
            ,Workstep_Library__c = wsl.Id
        );
        insert wst;
        
        Test.startTest();
        List<Workstep__c> ws = new List<Workstep__c>();
        ws.add(new Workstep__c(
            Order__c = ord.Id
            ,Sub_Order__c = so.Id
            ,Template__c = wst.Id
            ,Workstep_Library__c = wsl.Id
            ,Status__c = 'Blocked'
            ,CTP_Attribute__c = 'Start'
        ));
        
        ws.add(new Workstep__c(
            Order__c = ord.Id
            ,Sub_Order__c = so.Id
            ,Template__c = wst.Id
            ,Workstep_Library__c = wsl.Id
            ,Name = 'Activate with Customer'
            , Status__c = 'Blocked'
            ,CTP_Attribute__c = 'End'
        ));
        ws.add(new Workstep__c(
            Order__c = ord2.Id
            ,Template__c = wst.Id
            ,Workstep_Library__c = wsl.Id
            ,Name = 'Activate with Customer'
            , Status__c = 'Complete'
            ,CTP_Attribute__c = 'End'
        ));
        insert ws;
        
        Workstep_Issue__c wsi = new Workstep_Issue__c(Workstep__c = ws[1].Id);
        insert wsi;
        
        ws[0].Status__c = 'Open';
        ws[1].Status__c = 'Cancelled';
        
        update ws;
        delete ws;
    }
    
    static testmethod void testWorkstepCalloutResult(){
        Mocks Testdata = new Mocks();
        Test.startTest();
        Workstep_Library__c wsl = new Workstep_Library__c(
            External_Id__c = -1,
            Complete_Date_Field__c = '999',
            Start_Date_Driving_Fields__c = '999',
            Start_Date_Driven_Duration__c = 1
        );
        insert wsl;
        Workstep__c ws = new Workstep__c(
            Order__c = Testdata.order.Id
            ,Workstep_Library__c = wsl.Id
            ,Status__c = 'Open'
        );
        insert ws;
        
        WorkstepTriggers.WorkstepCalloutResult inst = new WorkstepTriggers.WorkstepCalloutResult(ws);
        integraWS.SFSubOrderGroupStatusView inst2 = new integraWS.SFSubOrderGroupStatusView();
        inst2.ResultMessage = 'Test Message';
        inst2.ResultStatus = 'Fail';
        inst.AddResult(inst2);
        String holder = inst.FailureMessage;
        holder = inst.FailureEmailBody;
        holder = inst.FailureEmailSubject;
        System.assert(!inst.IsSuccessful);
    }
}