objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Stage of the sales process you are currently working</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Working</fullName>
            </value>
            <value>
                <fullName>Sales Complete</fullName>
            </value>
            <value>
                <fullName>Indirect - Sales Complete</fullName>
            </value>
            <value>
                <fullName>Completed to Billing/Billing Only</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Referred to SE</fullName>
            </value>
            <value>
                <fullName>SSS Held</fullName>
            </value>
            <value>
                <fullName>SE Received</fullName>
            </value>
            <value>
                <fullName>SE Held</fullName>
            </value>
            <value>
                <fullName>SE Complete</fullName>
            </value>
            <value>
                <fullName>SSS SE Received</fullName>
            </value>
            <value>
                <fullName>Order to Pending</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Records Updated Only/No Order</fullName>
            </value>
            <value>
                <fullName>Returned to Account Specialists - Wholesale</fullName>
            </value>
            <value>
                <fullName>Order Accepted</fullName>
            </value>
            <value>
                <fullName>SSS Reviewing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Workstep__c/fields/Attribute__c.field-meta.xml
<CustomField>
    <fullName>Attribute__c</fullName>
    <label>Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activate with Customer</fullName>
            </value>
            <value>
                <fullName>CCD Driven</fullName>
            </value>
            <value>
                <fullName>CLICK Activation Date Driven</fullName>
            </value>
            <value>
                <fullName>Exclude From PDD Calculation</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>FOC Driven</fullName>
            </value>
            <value>
                <fullName>Hardware Install and Test</fullName>
            </value>
            <value>
                <fullName>Schedule Resources</fullName>
            </value>
            <value>
                <fullName>Schedule Install Resources</fullName>
            </value>
            <value>
                <fullName>Schedule Activation Resources</fullName>
            </value>
            <value>
                <fullName>Estimated Permit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Workstep__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Expected End Date</label>
    <type>Date</type>
</CustomField>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <label>SLA</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Workstep__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

objects/Workstep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Workstep__c/fields/workstep_tag__c.field-meta.xml
<CustomField>
    <fullName>workstep_tag__c</fullName>
    <inlineHelpText>Enter a tag here that will help you identify or note this workstep</inlineHelpText>
    <label>Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Workstep_Issue__c/Workstep_Issue__c.object-meta.xml
<CustomObject>
    <label>Workstep Issue</label>
    <nameField>
        <displayFormat>WI-{0000}</displayFormat>
        <label>Workstep Issues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workstep Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep_Issue__c/fields/Estimated_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Resolution__c</fullName>
    <label>Estimated Resolution</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Expected_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Follow_Up_Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <description>Expected Follow Up Date</description>
    <label>Expected Follow Up Date</label>
    <type>DateTime</type>
</CustomField>

objects/Workstep_Issue__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Risk_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Quote</fullName>
            </value>
            <value>
                <fullName>3rd Party Quote Expired</fullName>
            </value>
            <value>
                <fullName>Address Verification Needed</fullName>
            </value>
            <value>
                <fullName>A la Carte Open - Not Ready to Work</fullName>
            </value>
            <value>
                <fullName>ASD - 3rd Party Quote</fullName>
            </value>
            <value>
                <fullName>ASD - Clarification</fullName>
            </value>
            <value>
                <fullName>ASD - ETF</fullName>
            </value>
            <value>
                <fullName>Build (Carrier)</fullName>
            </value>
            <value>
                <fullName>Build (Customer)</fullName>
            </value>
            <value>
                <fullName>Building Construction</fullName>
            </value>
            <value>
                <fullName>Circuit Design</fullName>
            </value>
            <value>
                <fullName>Colo Cabinet Issue</fullName>
            </value>
            <value>
                <fullName>Customer/Vendor Not Ready</fullName>
            </value>
            <value>
                <fullName>Design Review</fullName>
            </value>
            <value>
                <fullName>Engineering Review</fullName>
            </value>
            <value>
                <fullName>Equipment Not Ready</fullName>
            </value>
            <value>
                <fullName>ETF</fullName>
            </value>
            <value>
                <fullName>Facility (Carrier)</fullName>
            </value>
            <value>
                <fullName>Facility (Customer)</fullName>
            </value>
            <value>
                <fullName>Fiber Build</fullName>
            </value>
            <value>
                <fullName>Field Review</fullName>
            </value>
            <value>
                <fullName>Inside Wiring</fullName>
            </value>
            <value>
                <fullName>LEC Order</fullName>
            </value>
            <value>
                <fullName>LEC Workforce</fullName>
            </value>
            <value>
                <fullName>LNP Review (Carrier)</fullName>
            </value>
            <value>
                <fullName>LNP Review (Customer)</fullName>
            </value>
            <value>
                <fullName>LNP Review (Integra)</fullName>
            </value>
            <value>
                <fullName>MOP Required</fullName>
            </value>
            <value>
                <fullName>Network Capacity (Carrier)</fullName>
            </value>
            <value>
                <fullName>Network Capacity (Integra)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep_Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Workstep__c.field-meta.xml
<CustomField>
    <fullName>Workstep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workstep</label>
    <referenceTo>Workstep__c</referenceTo>
    <relationshipLabel>Workstep Issues</relationshipLabel>
    <relationshipName>Workstep_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/SubOrder_WorkstepsController.cls
public with sharing class SubOrder_WorkstepsController {
    public Boolean standAlonePage {get; set;}
    public Boolean viewZeroDuration {get; set;}
    public Boolean isWSI {get; set;}
    public List<Workstep__c> defaultWorksteps {get; set;}
    public List<Workstep__c> zeroDurWorksteps {get; set;}
    public List<Workstep_Issue__c> wsi  {get; set;}
    public SubOrder_WorkstepsController(ApexPages.StandardController controller) {
        String cPage = ApexPages.currentPage().getparameters().get('so');
        if(cPage != null)       
            standAlonePage = cPage == 'true' ? true : false; 
        toggleZeroWorksteps();
        wsi = getWorkstepIssues();        
    } 
           
    Id myId = apexpages.currentpage().getparameters().get('id');      
//Get the API name of the sObject (Order__c or SubOrder__c) for query below //
    String objectType = myId.getSObjectType().getDescribe().getName();

    public List<Workstep__c> getWorksteps() {

        List<Workstep__c> results = Database.query(
            'SELECT Name, Start_Date__c, End_Date__c, Owner.Name, Owner.Type, Duration__c, SLA__c, Status__c, Attribute__c, workstep_tag__c  ' +
            'FROM Workstep__c ' +
            'WHERE Workstep__c.' + objectType + ' = ' + '\'' + (string)myId + '\'' +
            ' ORDER BY ' + sortOrder
        );
        return results;
    }

    public PageReference toggleZeroWorksteps() {
        if(viewZeroDuration == null){viewZeroDuration = false;}
        
        if(viewZeroDuration){            
            defaultWorksteps = Database.query(
            'SELECT Name, Start_Date__c, End_Date__c, Owner.Name, Owner.Type, Duration__c, SLA__c, Status__c, Attribute__c, workstep_tag__c  ' +
            'FROM Workstep__c ' +
            'WHERE Workstep__c.' + objectType + ' = ' + '\'' + (string)myId + '\'' +   
            ' ORDER BY ' + sortOrder
        	);           
        }
        else if(!viewZeroDuration){             
			defaultWorksteps = Database.query(
            'SELECT Name, Start_Date__c, End_Date__c, Owner.Name, Owner.Type, Duration__c, SLA__c, Status__c, Attribute__c, workstep_tag__c  ' +
            'FROM Workstep__c ' +
            'WHERE Duration__c != 0 AND Workstep__c.' + objectType + ' = ' + '\'' + (string)myId + '\'' +
            ' ORDER BY ' + sortOrder
        	);                 
       }
        viewZeroDuration = viewZeroDuration == true ? false : true;
        
        return null;
    }
        
    public List<Workstep_Issue__c> getWorkstepIssues() {
    
        List<Workstep_Issue__c> results = Database.query(
            'SELECT Name, Status__c, Expected_Follow_Up_Date__c, Reason__c, Estimated_Resolution__c, Workstep__r.Name, Workstep__r.Id, Owner.Name, Owner.Type ' +
            'FROM Workstep_Issue__c ' +
            'WHERE Workstep_Issue__c.Workstep__r.' + objectType + ' = ' + '\'' + (string)myId + '\'' +
            ' ORDER BY ' + sortWSIOrder 
        );
        return results;
    }

 /* -- WORKSTEP COLUMN SORTING -- */        
    public String sortColumn { get; set; }
    private String sortOrder = 'End_Date__c ASC';
    
     public void sortResults() {  
         if ( this.sortOrder != sortColumn + ' ASC') {
                   this.sortOrder = sortColumn + ' ASC' ;
                    }
                else {
                    this.sortOrder = sortColumn + ' DESC';
                }
    }
    
 /* -- WSI COLUMN SORTING -- */    
    public String sortWSIColumn { get; set; }
    private String sortWSIOrder = 'Expected_Follow_Up_Date__c ASC';
    
     public void sortWSIResults() {  
         if ( this.sortWSIOrder != sortWSIColumn + ' ASC') {
                   this.sortWSIOrder = sortWSIColumn + ' ASC' ;
                    }
                else {
                    this.sortWSIOrder = sortWSIColumn + ' DESC';
                }
    }
    
}