objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/classes/Test_AssignWorksteps.cls
@isTest
public with sharing class Test_AssignWorksteps extends TestUtils.TestClass {

	static testMethod void testController(){
		Mocks testData = new Mocks();
		test.startTest();
		
		Workstep__c ws = new Workstep__c(Name = 'Test WS', Order__c = testData.order.Id);
		insert ws;
		
		Apexpages.StandardSetController sc = new Apexpages.StandardSetController(new List<Workstep__c>{ws});
    	AssignWorksteps aw = new AssignWorksteps(sc);
    	system.assert(!aw.isError, 'AssignWorksteps has loaded in an errored state');
    	system.assert(aw.workstepWrapperList.size() == 1);
    	aw.workstepWrapperList[0].isSelected = true;
    	aw.sendNotification = true;
    	aw.dummyWS.OwnerId = [select Id from User where Name = 'Unassigned'].Id;
    	aw.Save();
    	aw.workstepWrapperList[0].isSelected = true;
    	aw.QuickSave();
    	aw.Cancel();
    	
		test.stopTest();
	}
}