objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order__c/fields/Hardware_Install_and_Test_Date__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Install_and_Test_Date__c</fullName>
    <label>CLICK Install Date</label>
    <type>Date</type>
</CustomField>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/Test_MassUpdateSubOrders.cls
@isTest
public with sharing class Test_MassUpdateSubOrders extends TestUtils.TestClass {

	static testMethod void testController(){
		Mocks testData = new Mocks();
		test.startTest();
		
		PageReference pageReference = Page.NotesViewer;
		pageReference.getParameters().put('id', testData.order.Id);
		
		insert new Sub_Order__c(Order__c = testData.order.Id);
		
		test.setCurrentPage(pageReference);
		
		MassUpdateSubOrders mu = new MassUpdateSubOrders();
		system.assert(mu.subOrderWrapperList.size() == 1);
		mu.subOrderWrapperList[0].isSelected = true;
		mu.dummySO.Hardware_Install_and_Test_Date__c = Date.today();
		mu.UpdateSelected();
		mu.Save();
		mu.QuickSave();
		mu.Cancel();
    	
		test.stopTest();
	}
}