objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An explicit account lookup that should only be used if the order is not opportunity driven.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account-based Orders</relationshipLabel>
    <relationshipName>Account_Based_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/CaseforOrderController.cls
public without sharing class CaseforOrderController{
    public String caseId {get; set;}
    public String returnURL {get; set;}
    public Case currentCase {get; set;}
    public Boolean canCreateOrder {get; set;}

    
    
    public CaseforOrderController(){
        caseId = ApexPages.currentPage().getParameters().get('caseId');            

        canCreateOrder =true;        
        currentCase = [Select Id, CaseNumber, AccountId,Account.name, Subject, Description, Order__c, Order__r.Name from Case where Id =:caseId];        
        if(!String.isEmpty(currentCase.Order__c)|| String.isEmpty(currentCase.AccountId)){
            returnURL = ApexPages.currentPage().getParameters().get('retURL');
            if(currentCase.Order__c != null) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'This Case has already been attached to an Order. You cannot create a new order.'));
                canCreateOrder = false;
            }
            if(String.isEmpty(currentCase.AccountId)){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Please select an account before creating an order.'));
                canCreateOrder = false;            
            }
        }
    }
    
    public void createOrder(){
        Id integrationOnlyRecordTypeID = OrderUtils.IntegrationOnlyRecordTypeID;
        Order__c caseOrder = new Order__c(Account__c = currentCase.AccountId, RecordTypeID = integrationOnlyRecordTypeID);
        insert caseOrder;

        if (caseOrder.Id != null){
        currentCase.Status = 'Working';
            currentCase.Order__c = caseOrder.Id;
            update currentCase;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'An Order has been created'));
            canCreateOrder = false;
        }
    
    }
    
}