objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Customer_Commit_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Commit_Date__c</fullName>
    <label>Customer Commit Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Order__c/fields/Expedited__c.field-meta.xml
<CustomField>
    <fullName>Expedited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expedited</label>
    <type>Checkbox</type>
</CustomField>

objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Stage of the sales process you are currently working</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Working</fullName>
            </value>
            <value>
                <fullName>Sales Complete</fullName>
            </value>
            <value>
                <fullName>Indirect - Sales Complete</fullName>
            </value>
            <value>
                <fullName>Completed to Billing/Billing Only</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Referred to SE</fullName>
            </value>
            <value>
                <fullName>SSS Held</fullName>
            </value>
            <value>
                <fullName>SE Received</fullName>
            </value>
            <value>
                <fullName>SE Held</fullName>
            </value>
            <value>
                <fullName>SE Complete</fullName>
            </value>
            <value>
                <fullName>SSS SE Received</fullName>
            </value>
            <value>
                <fullName>Order to Pending</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Records Updated Only/No Order</fullName>
            </value>
            <value>
                <fullName>Returned to Account Specialists - Wholesale</fullName>
            </value>
            <value>
                <fullName>Order Accepted</fullName>
            </value>
            <value>
                <fullName>SSS Reviewing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order__c/fields/Activate_with_Customer_Date__c.field-meta.xml
<CustomField>
    <fullName>Activate_with_Customer_Date__c</fullName>
    <label>CLICK Activate Date</label>
    <type>Date</type>
</CustomField>

objects/Sub_Order__c/fields/Customer_Acceptance_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Acceptance_Date__c</fullName>
    <label>Customer Acceptance Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Customer_Commit_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Commit_Date__c</fullName>
    <label>Customer Commit Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Customer_Commit_Date_Change_Reason__c.field-meta.xml
<CustomField>
    <fullName>Customer_Commit_Date_Change_Reason__c</fullName>
    <label>Customer Commit Date Change Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>200 – Cust – Site Readiness</fullName>
            </value>
            <value>
                <fullName>202 – Cust – New Construction</fullName>
            </value>
            <value>
                <fullName>205 – Cust – Requested Date</fullName>
            </value>
            <value>
                <fullName>207 – Cust – Related Orders/Locations</fullName>
            </value>
            <value>
                <fullName>208 – Cust – No Access</fullName>
            </value>
            <value>
                <fullName>209 – Cust – MSA</fullName>
            </value>
            <value>
                <fullName>300 - Integra - Order Issue</fullName>
            </value>
            <value>
                <fullName>301 - Integra -  Network</fullName>
            </value>
            <value>
                <fullName>302 - Integra - Product Not Available</fullName>
            </value>
            <value>
                <fullName>303 - Integra - Technical ICB</fullName>
            </value>
            <value>
                <fullName>304 - Integra - Potential Breakage</fullName>
            </value>
            <value>
                <fullName>305 - Integra - Interval Set Wrong</fullName>
            </value>
            <value>
                <fullName>306 - Integra - System Constraint</fullName>
            </value>
            <value>
                <fullName>307 - Integra - Provisioning Resource</fullName>
            </value>
            <value>
                <fullName>308 – Field/Warehouse Resource</fullName>
            </value>
            <value>
                <fullName>309 – ITS/BTS PM Resource</fullName>
            </value>
            <value>
                <fullName>310 - Integra - Pulling Order In</fullName>
            </value>
            <value>
                <fullName>400 - LEC - Centurylink</fullName>
            </value>
            <value>
                <fullName>401 - LEC - Verizon/Frontier</fullName>
            </value>
            <value>
                <fullName>402 - LEC - ATT</fullName>
            </value>
            <value>
                <fullName>403 - LEC - Other Carriers</fullName>
            </value>
            <value>
                <fullName>404 - LEC - Carrier Freeze</fullName>
            </value>
            <value>
                <fullName>405 - LEC - Build Required</fullName>
            </value>
            <value>
                <fullName>500 - Sales - Discrepancy/Follow up Required</fullName>
            </value>
            <value>
                <fullName>501 - Sales - Order Clarification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Order__c/fields/Customer_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Date__c</fullName>
    <label>Customer Requested Date</label>
    <type>DateTime</type>
</CustomField>

objects/Sub_Order__c/fields/Customer_Requested_Date_Change_Reason__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Date_Change_Reason__c</fullName>
    <label>Customer Requested Date Change Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>200 – Cust – Site Readiness</fullName>
            </value>
            <value>
                <fullName>202 – Cust – New Construction</fullName>
            </value>
            <value>
                <fullName>205 – Cust – Requested Date</fullName>
            </value>
            <value>
                <fullName>207 – Cust – Related Orders/Locations</fullName>
            </value>
            <value>
                <fullName>208 – Cust – No Access</fullName>
            </value>
            <value>
                <fullName>209 – Cust – MSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Order__c/fields/Expedited__c.field-meta.xml
<CustomField>
    <fullName>Expedited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expedited</label>
    <type>Checkbox</type>
</CustomField>

objects/Sub_Order__c/fields/Hardware_Install_and_Test_Date__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Install_and_Test_Date__c</fullName>
    <label>CLICK Install Date</label>
    <type>Date</type>
</CustomField>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sub_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending Sales</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
            </value>
            <value>
                <fullName>Pending DM</fullName>
            </value>
            <value>
                <fullName>Waiting for Telco</fullName>
            </value>
            <value>
                <fullName>Waiting for Translations</fullName>
            </value>
            <value>
                <fullName>Waiting for Circuit Design</fullName>
            </value>
            <value>
                <fullName>Waiting For - Facilities: ILEC</fullName>
            </value>
            <value>
                <fullName>Waiting For - Task/Stage Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

main/default/classes/MassUpdateSubOrders.cls
public with sharing class MassUpdateSubOrders implements TestUtils.ITestableClass {
	
	public String orderId;
	public List<SubOrderWrapper> subOrderWrapperList { get; set; }
	//public boolean isCanceled { get; set; }
	public Boolean adminControls {get; private set;}
	
	public Sub_Order__c dummySO { get; set; }
	
	public MassUpdateSubOrders() {
		dummySO = new Sub_Order__c();
		orderId = ApexPages.currentPage().getParameters().get('id');
		Profile p = [select Name from Profile where Id =: userInfo.getProfileId()];
		adminControls = p.Name == 'System Administrator' || p.Name == 'Power User';			//todo: drop and let the page determine security
		
		subOrderWrapperList = new List<SubOrderWrapper>();
		sObjectType objType = Sub_Order__c.getsObjectType();
		for (Sub_Order__c so : (List<Sub_Order__c>)ApexUtils.retrieveObjectsFromFieldSets(objType
        													,new List<Set<String>>
        														{
        															SchemaUtils.RetrieveFullObjectFieldSet(objType)
        														}
        													,'Order__c=\'' + orderId + '\''
        													,null))
			subOrderWrapperList.add(new SubOrderWrapper(so, false));
	}
	
	public PageReference Save() {
		return SaveAction(new PageReference('/' + orderId));
	}
	
	public PageReference Cancel() {
		return new PageReference('/' + orderId);
	}
	
	public PageReference QuickSave() {
		return SaveAction(new PageReference('/' + orderId));
	}
	
	private final Set<String> modifiableFields = new Set<String>{'Activate_with_Customer_Date__c'
																,'Customer_Acceptance_Date__c'
																,'Customer_Commit_Date__c'
																,'Customer_Commit_Date_Change_Reason__c'
																,'Customer_Requested_Date__c'
																,'Customer_Requested_Date_Change_Reason__c'
																,'Expedited__c'
																,'Hardware_Install_and_Test_Date__c'
																,'Status__c'
																,'Workplan_Start_Date__c'};
	public PageReference SaveAction(PageReference pageRef) {
		List<Sub_Order__c> soForUpdate = new List<Sub_Order__c>();
		for (SubOrderWrapper sow : subOrderWrapperList) {
			Boolean updated = false;
			for(String f : modifiableFields)
				updated = updated || sow.so.get(f) != sow.soOld.get(f);
			if(updated)
				soForUpdate.add(sow.so);
		}
		try{
			if (soForUpdate.size() > 0)
				update soForUpdate;
		}
		catch(Exception e){
			return null;
		}
		
		return pageRef;
	}
	
	public void UpdateSelected() {
		for (SubOrderWrapper sow : subOrderWrapperList) {
			if (sow.isSelected) {
				sow.isSelected = false;
				
				/*if (isCanceled)
					sow.so.Status__c = 'Cancelled';*/
				
				for(String f : modifiableFields){
					if(f != 'Status__c' && dummySO.get(f) != null && string.valueOf(dummySO.get(f)) != '')
						sow.so.put(f, dummySO.get(f));
				}
			}
		}
		
		
		for(String f : modifiableFields)
			dummySO.put(f, null);
		//isCanceled = null;
	}
	
	public class SubOrderWrapper {
		public Sub_Order__c so { get; set; }
		public Sub_Order__c soOld { get; set; }
		public boolean isSelected { get; set; }
		
		public SubOrderWrapper(Sub_Order__c so, boolean isSelected) {
			this.so = so;
			this.soOld = so.clone();
			this.isSelected = isSelected;
		}
	}
	
	/* TestUtils.ITestableClass methods */
	public TestUtils.TestClass getTestClass(){ return new Test_MassUpdateSubOrders(); }
}