objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Contract Renewal Orders</description>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Stage of the sales process you are currently working</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Working</fullName>
            </value>
            <value>
                <fullName>Sales Complete</fullName>
            </value>
            <value>
                <fullName>Indirect - Sales Complete</fullName>
            </value>
            <value>
                <fullName>Completed to Billing/Billing Only</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Referred to SE</fullName>
            </value>
            <value>
                <fullName>SSS Held</fullName>
            </value>
            <value>
                <fullName>SE Received</fullName>
            </value>
            <value>
                <fullName>SE Held</fullName>
            </value>
            <value>
                <fullName>SE Complete</fullName>
            </value>
            <value>
                <fullName>SSS SE Received</fullName>
            </value>
            <value>
                <fullName>Order to Pending</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Records Updated Only/No Order</fullName>
            </value>
            <value>
                <fullName>Returned to Account Specialists - Wholesale</fullName>
            </value>
            <value>
                <fullName>Order Accepted</fullName>
            </value>
            <value>
                <fullName>SSS Reviewing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Provisioning_Product__c/Provisioning_Product__c.object-meta.xml
<CustomObject>
    <label>Provisioning Product</label>
    <nameField>
        <label>Provisioning Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provisioning Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Provisioning_Product__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SPC_Product__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>SPC Products</relationshipLabel>
    <relationshipName>SPC_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SPC_Product__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <externalId>true</externalId>
    <label>SalesProductExternalID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Sub_Order__c/fields/Has_Blocked_Workstep__c.field-meta.xml
<CustomField>
    <fullName>Has_Blocked_Workstep__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the suborder has any blocked worksteps</description>
    <label>Has Blocked Workstep</label>
    <type>Checkbox</type>
</CustomField>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Sub Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending Sales</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
            </value>
            <value>
                <fullName>Pending DM</fullName>
            </value>
            <value>
                <fullName>Waiting for Telco</fullName>
            </value>
            <value>
                <fullName>Waiting for Translations</fullName>
            </value>
            <value>
                <fullName>Waiting for Circuit Design</fullName>
            </value>
            <value>
                <fullName>Waiting For - Facilities: ILEC</fullName>
            </value>
            <value>
                <fullName>Waiting For - Task/Stage Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <formula>Workstep_Library__r.External_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Workstep__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <formula>Sub_Order__r.SPC_Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SPC Product</label>
    <type>Text</type>
</CustomField>

objects/Workstep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Workstep__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Workstep_Template__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/Workstep_Library__c.field-meta.xml
<CustomField>
    <fullName>Workstep_Library__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workstep Library</label>
    <referenceTo>Workstep_Library__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Workstep_Template__c/Workstep_Template__c.object-meta.xml
<CustomObject>
    <label>Workstep Template</label>
    <nameField>
        <label>Workstep Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workstep Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep_Template__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Workstep_Template__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <formula>Workplan_Template__r.Provisioning_Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provisioning Product</label>
    <type>Text</type>
</CustomField>

main/default/objects/Workstep_Template__c/fields/Workstep_Library__c.field-meta.xml
<CustomField>
    <fullName>Workstep_Library__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Workstep Library</label>
    <referenceTo>Workstep_Library__c</referenceTo>
    <relationshipLabel>Workstep Templates</relationshipLabel>
    <relationshipName>Workstep_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/classes/Test_SubOrder_PDD.cls
@isTest
public with sharing class Test_SubOrder_PDD extends TestUtils.TestClass{
	static testMethod void testSchedule_PDD_TrueUp(){
        Mocks testData = new Mocks();
		Opportunity opp = testData.opportunity;				
    	Order__c ord = new Order__c(Opportunity__c = opp.Id);
    	insert ord;
    	
    	SPC_Product__c spc = new SPC_Product__c(
    									SalesProductExternalID__c = -1
    									,Provisioning_Product__c = testData.mpProvProd.get('Standard').Id
    									);   									
    	insert spc;
    	
    	Sub_Order__c so = new Sub_Order__c(
    									Service_Location__c = testData.serviceLocation.Id
    									,Order__c = ord.Id
    									,SPC_Product__c = spc.Id
    									,Has_Blocked_Workstep__c = true
    									,Workplan_Start_Date__c = Date.today().addDays(-23) 
    									);  									
    	insert so;
    	
    	Sub_Order__c soOne = new Sub_Order__c(
    									Service_Location__c = testData.serviceLocation.Id
    									,Order__c = ord.Id
    									,SPC_Product__c = spc.Id
    									,Has_Blocked_Workstep__c = false
    									,Workplan_Start_Date__c = Date.today().addDays(-7) 
    									);     									 									
    	insert soOne;
 	    	Sub_Order__c soTwo = new Sub_Order__c(
    									Service_Location__c = testData.serviceLocation.Id
    									,Order__c = ord.Id
    									,SPC_Product__c = spc.Id
    									,Has_Blocked_Workstep__c = true
    									,Workplan_Start_Date__c = Date.today().addDays(13) 
    									);      																		
    	insert soTwo;
		
		Workstep_Library__c wsl = new Workstep_Library__c(
															Name = 'PDD TrueUp Test'
															,External_Id__c = -1
															);																
		insert wsl;
		
		Workstep_Template__c wst = new Workstep_Template__c(
															Name = 'WST PDD TrueUp test'
															,External_Id__c = -1
															,Workstep_Library__c = wsl.Id
															);																														
		insert wst;
		
		List<Workstep__c> ws = new List<Workstep__c>();
    	ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = so.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										, Status__c = 'Integrating'
										,CTP_Attribute__c = 'Start'
										));

		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = so.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										, Status__c = 'Open'
										,CTP_Attribute__c = 'Start'
										));
    	
		
		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = so.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										,Name = 'Activate with Customer'
										, Status__c = 'Open'
										,CTP_Attribute__c = 'End'
										));
		
		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = so.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										,Name = 'Send to Billing'
										, Status__c = 'Blocked'
										));
		
		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = so.Id
		));
		
		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = soOne.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										, Status__c = 'Integrating'
										,CTP_Attribute__c = 'Start'
										));

		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = soOne.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										, Status__c = 'Open'
										,CTP_Attribute__c = 'Start'
										));
    	
		
		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = soOne.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										,Name = 'Activate with Customer'
										, Status__c = 'Open'
										,CTP_Attribute__c = 'End'
										));
		
		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = soOne.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										,Name = 'Send to Billing'
										, Status__c = 'Blocked'
										));
		
		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = soOne.Id
		));
		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = soTwo.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										, Status__c = 'Integrating'
										,CTP_Attribute__c = 'Start'
										));

		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = soTwo.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										, Status__c = 'Open'
										,CTP_Attribute__c = 'Start'
										));
    	
		
		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = soTwo.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										,Name = 'Activate with Customer'
										, Status__c = 'Open'
										,CTP_Attribute__c = 'End'
										));
		
		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = soTwo.Id
										,Template__c = wst.Id
										,Workstep_Library__c = wsl.Id
										,Name = 'Send to Billing'
										, Status__c = 'Blocked'
										));
		
		ws.add(new Workstep__c(
										Order__c = ord.Id
										,Sub_Order__c = soTwo.Id
		));
					
		insert ws;

				
		test.startTest();		
		Schedule_PDD_TrueUp.getActiveSubOrders(soTwo.Id);		
		test.stopTest();
	}
}