objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An explicit account lookup that should only be used if the order is not opportunity driven.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account-based Orders</relationshipLabel>
    <relationshipName>Account_Based_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Stage of the sales process you are currently working</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Working</fullName>
            </value>
            <value>
                <fullName>Sales Complete</fullName>
            </value>
            <value>
                <fullName>Indirect - Sales Complete</fullName>
            </value>
            <value>
                <fullName>Completed to Billing/Billing Only</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Referred to SE</fullName>
            </value>
            <value>
                <fullName>SSS Held</fullName>
            </value>
            <value>
                <fullName>SE Received</fullName>
            </value>
            <value>
                <fullName>SE Held</fullName>
            </value>
            <value>
                <fullName>SE Complete</fullName>
            </value>
            <value>
                <fullName>SSS SE Received</fullName>
            </value>
            <value>
                <fullName>Order to Pending</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Records Updated Only/No Order</fullName>
            </value>
            <value>
                <fullName>Returned to Account Specialists - Wholesale</fullName>
            </value>
            <value>
                <fullName>Order Accepted</fullName>
            </value>
            <value>
                <fullName>SSS Reviewing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order_Property__c/Order_Property__c.object-meta.xml
<CustomObject>
    <label>Order Property</label>
    <nameField>
        <label>Order Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Order_Property__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Properties</relationshipLabel>
    <relationshipName>Order_Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Order_Property__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Order Properties</relationshipLabel>
    <relationshipName>Order_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Sub_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Order__r.Account_Link__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/External_Order__c.field-meta.xml
<CustomField>
    <fullName>External_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>External Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>External orders must belong to the same order</errorMessage>
        <filterItems>
            <field>Order_Property__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Order</value>
        </filterItems>
        <filterItems>
            <field>Order_Property__c.Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order_Property__c</referenceTo>
    <relationshipLabel>Sub Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/External_Products__c.field-meta.xml
<CustomField>
    <fullName>External_Products__c</fullName>
    <label>External Products</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending Sales</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
            </value>
            <value>
                <fullName>Pending DM</fullName>
            </value>
            <value>
                <fullName>Waiting for Telco</fullName>
            </value>
            <value>
                <fullName>Waiting for Translations</fullName>
            </value>
            <value>
                <fullName>Waiting for Circuit Design</fullName>
            </value>
            <value>
                <fullName>Waiting For - Facilities: ILEC</fullName>
            </value>
            <value>
                <fullName>Waiting For - Task/Stage Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Order__r.Account_Link__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Workstep__c/fields/External_Order__c.field-meta.xml
<CustomField>
    <fullName>External_Order__c</fullName>
    <formula>Sub_Order__r.External_Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External Order</label>
    <type>Text</type>
</CustomField>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Workstep_Issue__c/Workstep_Issue__c.object-meta.xml
<CustomObject>
    <label>Workstep Issue</label>
    <nameField>
        <displayFormat>WI-{0000}</displayFormat>
        <label>Workstep Issues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workstep Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep_Issue__c/fields/External_Order__c.field-meta.xml
<CustomField>
    <fullName>External_Order__c</fullName>
    <formula>Workstep__r.External_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External Order</label>
    <type>Text</type>
</CustomField>

objects/Workstep_Issue__c/fields/Risk_Type__c.field-meta.xml
<CustomField>
    <fullName>Risk_Type__c</fullName>
    <label>RespOrg</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Integra</fullName>
                <label>Allstream</label>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep_Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <formula>HYPERLINK( 
Workstep__r.Sub_Order__r.Id, 
Workstep__r.Sub_Order__r.Name )</formula>
    <label>Sub-Order</label>
    <type>Text</type>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Workstep__c.field-meta.xml
<CustomField>
    <fullName>Workstep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workstep</label>
    <referenceTo>Workstep__c</referenceTo>
    <relationshipLabel>Workstep Issues</relationshipLabel>
    <relationshipName>Workstep_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/MassBlockCreation.cls
public with sharing class MassBlockCreation implements TestUtils.ITestableClass{
	
	public String orderId;
	public List<wsWrapper> wsWrapperList { get; set; }
	public List<Workstep__c> wStep {get; set;}
	public Workstep_Issue__c dummyWSI { get; set; }
	 
	public MassBlockCreation() {
		dummyWSI = new Workstep_Issue__c();
		orderId = ApexPages.currentPage().getParameters().get('id');
		wsWrapperList = new List<wsWrapper>();
		List<Sub_Order__c> so = new List<Sub_Order__c>();
		so = [Select Id From Sub_Order__c Where Order__c =: orderId];
		wStep = Database.query(
			'SELECT Id, Name, Sub_Order__r.Service_Location__r.Name, Sub_Order__r.Service_Location__r.Account__r.Name, Sub_Order__r.External_Products__c, Sub_Order__r.Name, Sub_Order__r.External_Order__r.Name, Order__r.Name, Owner.Name, Order__r.OwnerId, Status__c ' +
			'FROM Workstep__c '+
			'WHERE Sub_Order__c IN:so And Duration__c !=0  AND (Status__c =\'Open\' OR Status__c = \'Blocked\') '+			
			' ORDER BY ' + sortOrder);

		for(Workstep__c works : wStep){ 			      													
			wsWrapperList.add(new wsWrapper(works, false));
		}
	}
	
	public PageReference Save() {
		return SaveAction(new PageReference('/' + orderId));
	}
	
	public PageReference Cancel() {
		return new PageReference('/' + orderId);
	}
	
	public PageReference QuickSave() {
		PageReference pageReference = Page.MassBlockCreation;
        pageReference.getParameters().put('Id', orderId);
        pageReference.setRedirect(true);
		return SaveAction(PageReference);		
	}

	public PageReference ExitSave() {
		return SaveAction(new PageReference('/' + orderId));
	}
	
	private final Set<String> modifiableFields = new Set<String>{'Risk_Type__c'
																,'Reason__c'
																,'Reason_Subcategory__c'
																,'Expected_Follow_Up_Date__c'
																,'Comments__c'
																,'OwnerId'};
	public PageReference SaveAction(PageReference pageRef) {
		List<Workstep_Issue__c> wsiForInsert = new List<Workstep_Issue__c>();
		List<Workstep__c> sWorksteps = new List<Workstep__c>();
		Boolean anyChecked = false;
		try {
			List<String> errors = new List<String>();
			
			if (string.IsEmpty(dummyWSI.Risk_Type__c))
				errors.add('RespOrg: You must enter a value');
			if (dummyWSI.OwnerId == null)
				errors.add('Owner: You must enter a value');
			if (string.IsEmpty(dummyWSI.Comments__c))
				errors.add('Comments: You must enter a value');
			if(dummyWSI.Expected_Follow_Up_Date__c == null)
				errors.add('You must enter an expected follow up date');
			for (wsWrapper wss : wsWrapperList) {
				if (wss.isSelected) 
					anyChecked = true;
			}
			if(!anyChecked)
				errors.add('Please check at least 1 checkbox to create Workstep Issues for!');
			if (errors.size() > 0) {
				system.debug('errors: ' + errors);
				for(String error : errors)
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, error));
				return null;
			}
			
		} 
		catch (DMLException e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,e.getMessage()));
			return null;
		}
		for (wsWrapper wss : wsWrapperList) {
			if (wss.isSelected) 
				sWorksteps.add(wss.ws);
		}
		try{
			if (sWorksteps.size() > 0){
				for(Workstep__c work : sWorksteps){ 
					Workstep_Issue__c wsiTemplate = new Workstep_Issue__c();	
					wsiTemplate.Risk_Type__c = dummyWSI.Risk_Type__c;
					wsiTemplate.Reason__c = dummyWSI.Reason__c;
					wsiTemplate.Reason_Subcategory__c = dummyWSI.Reason_Subcategory__c;
					wsiTemplate.Expected_Follow_Up_Date__c = dummyWSI.Expected_Follow_Up_Date__c;
					wsiTemplate.Comments__c = dummyWSI.Comments__c;
					wsiTemplate.OwnerId = dummyWSI.OwnerId;
					wsiTemplate.Carrier__c = dummyWSI.Carrier__c;
					wsiTemplate.Status__c = 'Open';
					wsiTemplate.Workstep__c = work.Id;
					wsiForInsert.add(wsiTemplate);						
				}							
				insert wsiForInsert;
			}
		}
		catch(Exception e){			
			return null;
		}
		if(wsiForInsert.size() > 0)
			sendEmail(wsiForInsert);

		return pageRef;
	}

	public class wsWrapper {
		public Workstep__c ws { get; set; }
		public Workstep__c wsOld { get; set; }
		public boolean isSelected { get; set; }
		
		public wsWrapper(Workstep__c ws, boolean isSelected) {
			this.ws = ws;
			this.wsOld = ws.clone();
			this.isSelected = isSelected;
		}
	}
	private void sendEmail(List<Workstep_Issue__c> wsiForInsert) {
		List<Messaging.SingleEmailMessage> listmail = new List<Messaging.SingleEmailMessage> ();
		User wsUser = [SELECT Id, Email, IsActive FROM User WHERE Id = :dummyWSI.OwnerId];
		List<Workstep_Issue__c> emailToSend = [SELECT Id, OwnerId FROM Workstep_Issue__c WHERE OwnerId = :dummyWSI.OwnerId AND Status__c = :'Open' AND Expected_Follow_Up_Date__c = :dummyWSI.Expected_Follow_Up_Date__c AND Risk_Type__c = :dummyWSI.Risk_Type__c AND Reason__c = :dummyWSI.Reason__c];
		for (Workstep_Issue__c ets : emailToSend) {
			String objName = SchemaUtils.GetSObjectNameByID(ets.Id);
		String emailBody = (objName == 'Workstep__c') 
								? 'Workstep has been assigned to you. Please click on the link below to view the record. \n\n'
								: 'Workstep Issue has been created. Please click on the link below to view the record. \n\n';
			emailBody += URL.getSalesforceBaseUrl().toExternalForm() + '/' + ets.Id + '\n\n';
			String objOwn = SchemaUtils.GetSObjectNameByID(dummyWSI.OwnerId);
			if (objOwn == 'User') {
				Messaging.SingleEmailMessage m = ApexUtils.createEmailMessage(new String[] { wsUser.Email }
																								,null
																								,(objName == 'Workstep__c') ? 'Workstep assigned to you.' : 'Workstep Issue has been created.'
																								,emailBody
																								,false
				                                                              , UserInfo.getUserEmail());

				listmail.add(m);
			}
		}
		if (!Test.isRunningTest())
			ApexUtils.sendEmails(listmail);
	}

	public String sortColumn { get; set; }
    private String sortOrder = 'Sub_Order__c ASC';
    private Boolean ordinal = true;
     public void sortResults() {  
         if ( this.sortOrder != sortColumn + ' ASC') {
                   this.sortOrder = sortColumn + ' ASC' ;
                    }
                else {
                    this.sortOrder = sortColumn + ' DESC';
					ordinal = false;
                }

        wStep = ApexUtils.sortByComparableField(wStep, sortColumn, ordinal, true);

		wsWrapperList.clear();
		for(Workstep__c works : wStep){ 			      													
			wsWrapperList.add(new wsWrapper(works, false));
		}
    }
	
	/* TestUtils.ITestableClass methods */
	public TestUtils.TestClass getTestClass(){ return new Test_MassBlockCreation(); }
}