objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Stage of the sales process you are currently working</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Working</fullName>
            </value>
            <value>
                <fullName>Sales Complete</fullName>
            </value>
            <value>
                <fullName>Indirect - Sales Complete</fullName>
            </value>
            <value>
                <fullName>Completed to Billing/Billing Only</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Referred to SE</fullName>
            </value>
            <value>
                <fullName>SSS Held</fullName>
            </value>
            <value>
                <fullName>SE Received</fullName>
            </value>
            <value>
                <fullName>SE Held</fullName>
            </value>
            <value>
                <fullName>SE Complete</fullName>
            </value>
            <value>
                <fullName>SSS SE Received</fullName>
            </value>
            <value>
                <fullName>Order to Pending</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Records Updated Only/No Order</fullName>
            </value>
            <value>
                <fullName>Returned to Account Specialists - Wholesale</fullName>
            </value>
            <value>
                <fullName>Order Accepted</fullName>
            </value>
            <value>
                <fullName>SSS Reviewing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sub_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending Sales</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
            </value>
            <value>
                <fullName>Pending DM</fullName>
            </value>
            <value>
                <fullName>Waiting for Telco</fullName>
            </value>
            <value>
                <fullName>Waiting for Translations</fullName>
            </value>
            <value>
                <fullName>Waiting for Circuit Design</fullName>
            </value>
            <value>
                <fullName>Waiting For - Facilities: ILEC</fullName>
            </value>
            <value>
                <fullName>Waiting For - Task/Stage Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Workstep__c/fields/Attribute__c.field-meta.xml
<CustomField>
    <fullName>Attribute__c</fullName>
    <label>Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activate with Customer</fullName>
            </value>
            <value>
                <fullName>CCD Driven</fullName>
            </value>
            <value>
                <fullName>CLICK Activation Date Driven</fullName>
            </value>
            <value>
                <fullName>Exclude From PDD Calculation</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>FOC Driven</fullName>
            </value>
            <value>
                <fullName>Hardware Install and Test</fullName>
            </value>
            <value>
                <fullName>Schedule Resources</fullName>
            </value>
            <value>
                <fullName>Schedule Install Resources</fullName>
            </value>
            <value>
                <fullName>Schedule Activation Resources</fullName>
            </value>
            <value>
                <fullName>Estimated Permit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Workstep__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Expected End Date</label>
    <type>Date</type>
</CustomField>

objects/Workstep__c/fields/Lag__c.field-meta.xml
<CustomField>
    <fullName>Lag__c</fullName>
    <label>Lag</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <label>SLA</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Workstep__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

objects/Workstep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/Work_Group__c.field-meta.xml
<CustomField>
    <fullName>Work_Group__c</fullName>
    <label>Work Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Work Group 1</fullName>
            </value>
            <value>
                <fullName>Work Group 2</fullName>
            </value>
            <value>
                <fullName>Work Group 3</fullName>
            </value>
            <value>
                <fullName>Work Group 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/fields/Workstep_Library__c.field-meta.xml
<CustomField>
    <fullName>Workstep_Library__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workstep Library</label>
    <referenceTo>Workstep_Library__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Workstep_Library__c/Workstep_Library__c.object-meta.xml
<CustomObject>
    <label>Workstep Library</label>
    <nameField>
        <label>Workstep Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workstep Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep_Library__c/fields/Attribute__c.field-meta.xml
<CustomField>
    <fullName>Attribute__c</fullName>
    <label>Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accept Order</fullName>
            </value>
            <value>
                <fullName>Access Design</fullName>
            </value>
            <value>
                <fullName>Activate with Customer</fullName>
            </value>
            <value>
                <fullName>BLA</fullName>
            </value>
            <value>
                <fullName>Build Site Survey</fullName>
            </value>
            <value>
                <fullName>CCD Driven</fullName>
            </value>
            <value>
                <fullName>CLICK Activation Date Driven</fullName>
            </value>
            <value>
                <fullName>CLICK ITS Install Date Driven</fullName>
            </value>
            <value>
                <fullName>CLICK SIP Activation Date Driven</fullName>
            </value>
            <value>
                <fullName>Customer Data Gather</fullName>
            </value>
            <value>
                <fullName>Customer Kick Off</fullName>
            </value>
            <value>
                <fullName>Design Facility</fullName>
            </value>
            <value>
                <fullName>Enter Order</fullName>
            </value>
            <value>
                <fullName>Estimated BLA</fullName>
            </value>
            <value>
                <fullName>Estimated Construction</fullName>
            </value>
            <value>
                <fullName>Estimated Permit</fullName>
            </value>
            <value>
                <fullName>Exclude From Expedite</fullName>
            </value>
            <value>
                <fullName>Exclude From PDD Calculation</fullName>
            </value>
            <value>
                <fullName>Fiber SMP</fullName>
            </value>
            <value>
                <fullName>Finalize Order</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>FOC Driven</fullName>
            </value>
            <value>
                <fullName>Hardware Install and Test</fullName>
            </value>
            <value>
                <fullName>ITS Program Meeting Date</fullName>
            </value>
            <value>
                <fullName>NIE SMP</fullName>
            </value>
            <value>
                <fullName>Order Facility</fullName>
            </value>
            <value>
                <fullName>Order LPN</fullName>
            </value>
            <value>
                <fullName>Permit</fullName>
            </value>
            <value>
                <fullName>Power SMP</fullName>
            </value>
            <value>
                <fullName>Project Network Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep_Library__c/fields/Non_Access_Duration__c.field-meta.xml
<CustomField>
    <fullName>Non_Access_Duration__c</fullName>
    <label>Non-Access Duration</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Workstep_Library__c/fields/Non_Access_Lag__c.field-meta.xml
<CustomField>
    <fullName>Non_Access_Lag__c</fullName>
    <label>Non-Access Lag</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Workstep_Library__c/fields/Non_Access_SLA__c.field-meta.xml
<CustomField>
    <fullName>Non_Access_SLA__c</fullName>
    <label>Non-Access SLA</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Workstep_Library__c/fields/Work_Group__c.field-meta.xml
<CustomField>
    <fullName>Work_Group__c</fullName>
    <label>Work Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>Carrier Support</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>SAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/NewWorkstep.cls
public class NewWorkstep {
	public Sub_Order__c suborder;
	
	public List<String> currentWorksteps { get; set; }
	public List<SelectOption> currentWorkstepList { get; set; }
	public List<String> selectedWorksteps { get; set; } 
	public List<SelectOption> selectedWorkstepList { get; set; }
	
	public Map<Id, Workstep_Library__c> allWorkstepsMap;
	public String subOrderId;
	public String orderId;
	
	public NewWorkstep() {
		subOrderId = ApexPages.currentPage().getParameters().get('id');
		orderId = ApexPages.currentPage().getParameters().get('oid');
		if(subOrderId != null) {
			suborder = [SELECT Id, Order__c FROM Sub_Order__c WHERE Id = :subOrderId];
			if(suborder != null)
				orderId = suborder.Order__c;
		}
		
		
		currentWorksteps = new List<String>();
		selectedWorkstepList = new List<SelectOption>();
		selectedWorksteps = new List<String>();
		currentWorkstepList = getWorkstepLibrary();
		allWorkstepsMap = getAllWorkstepsMap();
	}
	
	public List<SelectOption> getWorkstepLibrary() {
		List<SelectOption> options = new List<SelectOption>();
		for (Workstep_Library__c wsl : [SELECT Id, Name FROM Workstep_Library__c WHERE Id NOT IN :selectedWorksteps order by Name])
			options.add(new SelectOption(wsl.Id,wsl.Name));
		return options;
	}
	
	public Map<Id,Workstep_Library__c> getAllWorkstepsMap() {
		Map<Id,Workstep_Library__c> workstepsMap = new Map<Id,Workstep_Library__c>();
		for (Workstep_Library__c ws : [SELECT Id, Name, Non_Access_SLA__c, Non_Access_Lag__c, Non_Access_Duration__c, OwnerId, Work_Group__c, Attribute__c FROM Workstep_Library__c])
			workstepsMap.put(ws.Id, ws);
		return workstepsMap;
	}
	
	public void addWorksteps() {
		for (String ws : currentWorksteps)
			selectedWorkstepList.add(new SelectOption(ws, allWorkstepsMap.get(ws).Name));
		
		for (SelectOption so : selectedWorkstepList)
			selectedWorksteps.add(so.getValue());
		
		currentWorkstepList = getWorkstepLibrary();
		currentWorksteps = new List<String>();
		selectedWorksteps = new List<String>();
	}
	
	public void removeWorksteps() {
		Map<String, String> selectedWorkstepMap = new Map<String,String>();
		for (String ws : selectedWorksteps)
			selectedWorkstepMap.put(ws,ws);
		
		List<SelectOption> l = selectedWorkstepList;
		selectedWorksteps = new List<String>();
		selectedWorkstepList = new List<SelectOption>();
		for (SelectOption so : l) {
			if (!selectedWorkstepMap.containsKey(so.getValue())) {
				selectedWorkstepList.add(so);
				selectedWorksteps.add(so.getValue());
			}
		}
		currentWorkstepList = getWorkstepLibrary();
		currentWorksteps = new List<String>();
		selectedWorksteps = new List<String>();
	}
	
	public PageReference Save() {
		List<Workstep__c> wstList = new List<Workstep__c>();
		for (SelectOption so : selectedWorkstepList) {
			Workstep_Library__c lib = allWorkstepsMap.get(so.getValue());
			
			//calculate start and end date
			Date startd = Date.today();
			Date endd = startd;
			if(lib.Non_Access_Duration__c != null)
				endd = endd.addDays((Integer)lib.Non_Access_Duration__c);
			
			wstList.add(new Workstep__c(Order__c = orderId
								,Sub_Order__c = subOrderId
								,Name = lib.Name
								,Workstep_Library__c = lib.Id
								,Status__c = WorkstepUtils.STATUS_OPEN
								,Work_Group__c = lib.Work_Group__c
								,Lag__c = lib.Non_Access_Lag__c
								,Duration__c = lib.Non_Access_Duration__c
								,SLA__c = lib.Non_Access_SLA__c
								,Attribute__c = lib.Attribute__c
								,Start_Date__c = startd
								,End_Date__c = endd
								));
		}
		try {
			if (wstList.size() > 0)
				insert wstList;
			
			if(suborder != null)
		{
			return new PageReference('/' + subOrderId);
		}
		else{
			return new PageReference('/' + orderId);
		}
		} catch (DMLException e) {
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, e.getMessage()));
		}
		return null;
	}
	
	public PageReference Cancel() {
		if(suborder == null)
		{
			return new PageReference('/' + subOrderId);
		}
		else{
			return new PageReference('/' + orderId);
		}
		
	}
}