objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Stage of the sales process you are currently working</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Working</fullName>
            </value>
            <value>
                <fullName>Sales Complete</fullName>
            </value>
            <value>
                <fullName>Indirect - Sales Complete</fullName>
            </value>
            <value>
                <fullName>Completed to Billing/Billing Only</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Referred to SE</fullName>
            </value>
            <value>
                <fullName>SSS Held</fullName>
            </value>
            <value>
                <fullName>SE Received</fullName>
            </value>
            <value>
                <fullName>SE Held</fullName>
            </value>
            <value>
                <fullName>SE Complete</fullName>
            </value>
            <value>
                <fullName>SSS SE Received</fullName>
            </value>
            <value>
                <fullName>Order to Pending</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Records Updated Only/No Order</fullName>
            </value>
            <value>
                <fullName>Returned to Account Specialists - Wholesale</fullName>
            </value>
            <value>
                <fullName>Order Accepted</fullName>
            </value>
            <value>
                <fullName>SSS Reviewing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sub_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending Sales</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
            </value>
            <value>
                <fullName>Pending DM</fullName>
            </value>
            <value>
                <fullName>Waiting for Telco</fullName>
            </value>
            <value>
                <fullName>Waiting for Translations</fullName>
            </value>
            <value>
                <fullName>Waiting for Circuit Design</fullName>
            </value>
            <value>
                <fullName>Waiting For - Facilities: ILEC</fullName>
            </value>
            <value>
                <fullName>Waiting For - Task/Stage Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Workstep__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Expected End Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Workstep__c/fields/On_time_Late_Workstep__c.field-meta.xml
<CustomField>
    <fullName>On_time_Late_Workstep__c</fullName>
    <formula>IF(ISBLANK(Actual_Completion_Date__c),   End_Date__c - TODAY(), End_Date__c - Actual_Completion_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>On-time/Late Workstep</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

objects/Workstep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/WorkstepFlowChartController.cls
public with sharing class WorkstepFlowChartController implements TestUtils.ITestableClass{
	
	public String jsonPCWorkstepList { get; set; }
	public String jsonPCDependentMap { get; set; }
	public String jsonReversedWorkstepLevelMap { get; set; }
	public Integer wsCount { get; set; }

	public WorkstepFlowChartController(){
		Id recordID = (Id)ApexPages.currentPage().getParameters().get('id');
		
		String recordName = SchemaUtils.GetSObjectNameByID(recordID);
		Set<Id> wsIDs = null;
		if(recordName == 'Workstep__c') wsIDs = new Set<Id>{recordID};
		else if(recordName == 'Order__c' || recordName == 'Sub_Order__c') wsIDs = (new Map<Id, Workstep__c>([select Id from Workstep__c where Order__c =: recordID or Sub_Order__c =: recordID])).keyset();	//Just get one to return the whole chain
		
		WorkstepUtils.PredecessorChain pc = WorkstepUtils.getPredecessorChain(wsIDs);	
		jsonPCWorkstepList = JSON.serialize(new Map<Id, Workstep__c>([select Id, Name, Start_Date__c, End_Date__c, Status__c, Duration__c, On_time_Late_Workstep__c from Workstep__c where Id in: pc.WorkstepList.keyset()]), true);	
		jsonPCDependentMap = JSON.serialize(pc.DependentMap, true);
		jsonReversedWorkstepLevelMap = JSON.serialize(pc.GetReversedWorkstepLevelMap(), true);
		wsCount = pc.WorkstepList.size();		
		/*System.debug(pc);
		System.debug(jsonPCWorkstepList);
		System.debug(jsonPCDependentMap);
		System.debug(jsonReversedWorkstepLevelMap);*/
	}
	
	/* TestUtils.ITestableClass methods */
	public TestUtils.TestClass getTestClass(){ return new Test_WorkstepFlowChart(); }
}