objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Workstep_Issue__c/Workstep_Issue__c.object-meta.xml
<CustomObject>
    <label>Workstep Issue</label>
    <nameField>
        <displayFormat>WI-{0000}</displayFormat>
        <label>Workstep Issues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workstep Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Workstep_Issue__c/fields/Workstep__c.field-meta.xml
<CustomField>
    <fullName>Workstep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workstep</label>
    <referenceTo>Workstep__c</referenceTo>
    <relationshipLabel>Workstep Issues</relationshipLabel>
    <relationshipName>Workstep_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/Test_AssignWorkstepIssues.cls
@isTest
public with sharing class Test_AssignWorkstepIssues extends TestUtils.TestClass {

	static testMethod void testController(){
		Mocks testData = new Mocks();
		test.startTest();
		
		Workstep__c ws = new Workstep__c(Name = 'Test WS', Order__c = testData.order.Id);
		insert ws;
		
		Workstep_Issue__c wsi = new Workstep_Issue__c(Workstep__c = ws.Id);
		insert wsi;
		
		Apexpages.StandardSetController sc = new Apexpages.StandardSetController(new List<Workstep_Issue__c>{wsi});
    	AssignWorkstepIssues awi = new AssignWorkstepIssues(sc);
    	system.assert(!awi.isError, 'AssignWorkstepIssues has loaded in an errored state');
    	system.assert(awi.issueWrapperList.size() == 1);
    	awi.issueWrapperList[0].isSelected = true;
    	awi.sendNotification = true;
    	awi.dummyWSIssue.OwnerId = [select Id from User where Name = 'Unassigned'].Id;
    	awi.Save();
    	awi.issueWrapperList[0].isSelected = true;
    	awi.QuickSave();
    	awi.Cancel();
    	
		test.stopTest();
	}
}