objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Stage of the sales process you are currently working</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Working</fullName>
            </value>
            <value>
                <fullName>Sales Complete</fullName>
            </value>
            <value>
                <fullName>Indirect - Sales Complete</fullName>
            </value>
            <value>
                <fullName>Completed to Billing/Billing Only</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Referred to SE</fullName>
            </value>
            <value>
                <fullName>SSS Held</fullName>
            </value>
            <value>
                <fullName>SE Received</fullName>
            </value>
            <value>
                <fullName>SE Held</fullName>
            </value>
            <value>
                <fullName>SE Complete</fullName>
            </value>
            <value>
                <fullName>SSS SE Received</fullName>
            </value>
            <value>
                <fullName>Order to Pending</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Records Updated Only/No Order</fullName>
            </value>
            <value>
                <fullName>Returned to Account Specialists - Wholesale</fullName>
            </value>
            <value>
                <fullName>Order Accepted</fullName>
            </value>
            <value>
                <fullName>SSS Reviewing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep__c/fields/Lag__c.field-meta.xml
<CustomField>
    <fullName>Lag__c</fullName>
    <label>Lag</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <label>SLA</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Workstep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/Test_WorkstepManagement.cls
@isTest
public with sharing class Test_WorkstepManagement extends TestUtils.TestClass {
	
	static testMethod void testController(){
        Mocks testData = new Mocks();
    	test.startTest();
    	
    	createWorkstep(testData.order.Id);
		
		PageReference pageReference = Page.WorkstepManagement;
		pageReference.getParameters().put('orderId', testData.order.Id);
		test.setCurrentPage(pageReference);
		
		WorkstepManagementController wsm = new WorkstepManagementController();
		wsm.getWorkstepFilterOptions(new List<String>{'Id != null'});
		
		system.assertNotEquals(wsm.wsParams.config.GetDynamicTable, null);
		system.assertNotEquals(wsm.wsParams.config.configSection.GetSelectedTable, null);
		
		wsm.wsWrapperList[0].isSelected = true;
		wsm.CompleteSelectedWorksteps();
		wsm.SortChanged('wsTable');
		wsm.FieldConfigChanged('wsTable');
        wsm.AssignSelectedWorksteps();
        wsm.Test_Save() ;
		
		test.stopTest();
	}
	
	private static Id createWorkstep(Id orderID){
    	Workstep__c ws = new Workstep__c(
    									Name='Test Workstep'
    									,Order__c = orderID
    									,Duration__c = 4
    									,Lag__c = 0
    									,SLA__c = 4
    									,Status__c = WorkstepUtils.STATUS_OPEN
    									);
    	insert ws;
		
		system.assert(ws.Status__c == WorkstepUtils.STATUS_OPEN, 'Workstep was not created with an open status');
		
		return ws.Id;
	}
}