main/default/objects/Feature__c/Feature__c.object-meta.xml
<CustomObject>
    <label>Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Feature_Duration__c/Feature_Duration__c.object-meta.xml
<CustomObject>
    <label>Feature Duration</label>
    <nameField>
        <label>Feature Duration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feature Durations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Feature_Duration__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <referenceTo>Feature__c</referenceTo>
    <relationshipLabel>Feature Durations</relationshipLabel>
    <relationshipName>Feature_Durations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Feature_Duration__c/fields/Workstep_Library__c.field-meta.xml
<CustomField>
    <fullName>Workstep_Library__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workstep Library</label>
    <referenceTo>Workstep_Library__c</referenceTo>
    <relationshipLabel>Feature Durations</relationshipLabel>
    <relationshipName>Feature_Durations</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending Sales</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
            </value>
            <value>
                <fullName>Pending DM</fullName>
            </value>
            <value>
                <fullName>Waiting for Telco</fullName>
            </value>
            <value>
                <fullName>Waiting for Translations</fullName>
            </value>
            <value>
                <fullName>Waiting for Circuit Design</fullName>
            </value>
            <value>
                <fullName>Waiting For - Facilities: ILEC</fullName>
            </value>
            <value>
                <fullName>Waiting For - Task/Stage Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Order_Feature__c/Sub_Order_Feature__c.object-meta.xml
<CustomObject>
    <label>Sub-Order Feature</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sub-Order Feature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub-Order Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order_Feature__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <referenceTo>Feature__c</referenceTo>
    <relationshipName>SubOrder_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sub_Order_Feature__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Sub-Order Features</relationshipLabel>
    <relationshipName>Sub_Order_Features</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/Workstep_Library__c.field-meta.xml
<CustomField>
    <fullName>Workstep_Library__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workstep Library</label>
    <referenceTo>Workstep_Library__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Workstep_Library__c/Workstep_Library__c.object-meta.xml
<CustomObject>
    <label>Workstep Library</label>
    <nameField>
        <label>Workstep Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workstep Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/classes/SubOrderFeatureTriggers.cls
public with sharing class SubOrderFeatureTriggers {
	
   public static void SubOrderFeatureModified(List<Sub_Order_Feature__c> tNew, List<Sub_Order_Feature__c> tOld, Boolean isUpdate, Boolean isBefore, Boolean isDelete){
		
    	if(!ApexUtils.executeTriggerMethods('Sub_Order_Feature__c', isBefore, false)) return;
	   	
    	if(isBefore){
			if(isDelete)
				preventCompletedWorkstepFeatureDeletion(tOld);
    	}
    	else{
    		Map<Id, Sub_Order_Feature__c> tOldMap = tOld != null ? new Map<Id, Sub_Order_Feature__c>(tOld) : new Map<Id, Sub_Order_Feature__c>();
            updateWorkstep(tNew, tOldMap, isDelete);
    		
			ApexUtils.afterTriggerComplete('Sub_Order_Feature__c', false);
    	}
    }
	
	private static void updateWorkstep(List<Sub_Order_Feature__c> tNew, Map<Id, Sub_Order_Feature__c> tOldMap, Boolean isDelete) {
		List<Sub_Order_Feature__c> l = (isDelete ? tOldMap.values() : tNew);
		Set<Id> subordersSet = new Set<Id>();
		for (Sub_Order_Feature__c sof : l) {
			subordersSet.add(sof.Sub_Order__c);
		}
		
		if(subordersSet.size() > 0) {
			List<Workstep__c> wsUpdates = WorkstepUtils.calculateRelatedWorkstepOffsets(subordersSet);
		
			/*List<Workstep__c> workStep = new List<Workstep__c>();
			for(Sub_Order_Feature__c sof : l){
				for(Workstep__c ws : wsUpdates){
					if(sof.Sub_Order__c == ws.Sub_Order__c){
						workStep.add(ws);
					}
				}
				update workStep;
			}*/
			
			if(wsUpdates.size() > 0) update wsUpdates;
		}
	}
	
	private static void preventCompletedWorkstepFeatureDeletion(List<Sub_Order_Feature__c> tOld){
		
		Map<Id, Boolean> soMap = new Map<Id, Boolean>();		//SubOrderId=>ValidForDelete
		Map<Id, Set<Id>> deleteMap = new Map<Id, Set<Id>>();	//FeatureId=>Set<SubOrderId>
		for(Sub_Order_Feature__c sof : tOld){
			soMap.put(sof.Sub_Order__c, true);
			
			Set<Id> s = deleteMap.get(sof.Feature__c) != null ? deleteMap.get(sof.Feature__c) : new Set<Id>();
			s.add(sof.Sub_Order__c);
			deleteMap.put(sof.Feature__c, s);
		}
		
		Map<Id, Set<Id>> featureDurationMap = new Map<Id, Set<Id>>();	//WorkstepLibraryId=>Set<FeatureId>
		for(Feature_Duration__c fd : [select Feature__c, Workstep_Library__c from Feature_Duration__c where Feature__c in: deleteMap.keyset()]){
			Set<Id> s = featureDurationMap.get(fd.Workstep_Library__c) != null ? featureDurationMap.get(fd.Workstep_Library__c) : new Set<Id>();
			s.add(fd.Feature__c);
			featureDurationMap.put(fd.Workstep_Library__c, s);
		}
		
		if(featureDurationMap.size() > 0){
			for(Workstep__c ws : [select Id, Sub_Order__c, Workstep_Library__c from Workstep__c where Sub_Order__c in: soMap.keyset() and Workstep_Library__c in : featureDurationMap.keyset() and Status__c =: WorkstepUtils.STATUS_COMPLETE]){
				for(Id featureID : featureDurationMap.get(ws.Workstep_Library__c)){
					if(deleteMap.get(featureID).contains(ws.Sub_Order__c))
						soMap.put(ws.Sub_Order__c, false);
				}
			}
		}
		
		for(Sub_Order_Feature__c sof : tOld){
			if(soMap.get(sof.Sub_Order__c) != true)
				sof.addError('Sub-Order features cannot be removed once they are associated with a completed workstep.');
		}
	}
}