objects/CN__c/CN__c.object-meta.xml
<CustomObject>
    <label>CN</label>
    <nameField>
        <label>CN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CN__c/fields/Opportunity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line Item</label>
    <referenceTo>OLI__c</referenceTo>
    <relationshipLabel>CNs</relationshipLabel>
    <relationshipName>CNs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/CN__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>CNs</relationshipLabel>
    <relationshipName>CNs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/CN_Feature__c/CN_Feature__c.object-meta.xml
<CustomObject>
    <label>CN Feature</label>
    <nameField>
        <label>CN Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CN Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CN_Feature__c/fields/CN__c.field-meta.xml
<CustomField>
    <fullName>CN__c</fullName>
    <label>CN</label>
    <referenceTo>CN__c</referenceTo>
    <relationshipLabel>CN Features</relationshipLabel>
    <relationshipName>CN_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/CN_Feature__c/fields/Opportunity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line Item</label>
    <referenceTo>OLI__c</referenceTo>
    <relationshipLabel>CN Features</relationshipLabel>
    <relationshipName>CN_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Technical_Information__c/Technical_Information__c.object-meta.xml
<CustomObject>
    <label>Technical Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Technical_Information__c/fields/Opportunity_Site__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Technical Information</relationshipLabel>
    <relationshipName>Technical_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Technical_Information__c/recordTypes/Features_Schedule.recordType-meta.xml
<RecordType>
    <fullName>Features_Schedule</fullName>
    <active>true</active>
    <label>02 – Features Schedule</label>
</RecordType>

main/default/classes/Test_PrintOrder.cls
@isTest
public with sharing class Test_PrintOrder extends TestUtils.TestClass {
	
    static testMethod void testController() {
        
        Mocks testData = new Mocks();
        RecordType rt = [select Id from RecordType WHERE SobjectType = 'Technical_Information__c' and DeveloperName != 'Features_Schedule' limit 1];
        List<Technical_Information__c> tis = new List<Technical_Information__c>{new Technical_Information__c(Name = '02-Features_Schedule', Opportunity_Site__c = testData.location.id,  RecordTypeId = rt.Id)};
		insert tis;
        
        List<CN__c> lstCN = new List<CN__c>{
		        	new CN__c(Opportunity_Location__c = testData.location.id, Opportunity_Line_Item__c = testData.lstLineItems[0].id, name='310-555-1111')
		        	,new CN__c(Opportunity_Location__c = testData.location.id, Opportunity_Line_Item__c = testData.lstLineItems[0].id, name='310-555-2222')
					,new CN__c(Opportunity_Location__c = testData.location.id, Opportunity_Line_Item__c = testData.lstLineItems[4].id, name='310-555-3333')
		        };
        insert lstCN;
        
		List<CN_Feature__c>   pLstCNFeature = new List<CN_Feature__c>{
            new CN_Feature__c(CN__c = lstCN[0].id, Opportunity_Line_Item__c = testData.lstLineItems[0].id, Additional_Info__c = 'Prompt Value', Name = '310-555-1111 - Feature 1')
                ,new CN_Feature__c(CN__c = lstCN[0].id, Opportunity_Line_Item__c = testData.lstLineItems[1].id, Additional_Info__c = '', Name = '310-555-1111 - Feature Package 1 - Line')
                ,new CN_Feature__c(CN__c = lstCN[1].id, Opportunity_Line_Item__c = testData.lstLineItems[1].id, Additional_Info__c = '', Name = '310-555-2222 - Feature Package 1 - Line')
                ,new CN_Feature__c(CN__c = lstCN[1].id, Opportunity_Line_Item__c = testData.lstLineItems[2].id, Additional_Info__c = '', Name = '310-555-2222 - Feature Package 2 - Account')
                ,new CN_Feature__c(CN__c = lstCN[0].id, Opportunity_Line_Item__c = testData.lstLineItems[3].id, Additional_Info__c = '', Name = '310-555-1111 - Feature Package Content 1 - Line')
                ,new CN_Feature__c(CN__c = lstCN[1].id, Opportunity_Line_Item__c = testData.lstLineItems[3].id, Additional_Info__c = '', Name = '310-555-2222 - Feature Package Content 1 - Line')
                ,new CN_Feature__c(CN__c = lstCN[1].id, Opportunity_Line_Item__c = testData.lstLineItems[3].id, Additional_Info__c = '', Name = '310-555-2222 - Feature Package Content 2 - Account')
                ,new CN_Feature__c(CN__c = lstCN[2].id, Opportunity_Line_Item__c = testData.lstLineItems[4].id, Additional_Info__c = '', Name = '310-555-2222 - Test Desc')
                };
        insert pLstCNFeature;
        
        
        test.startTest();
        
        PageReference pageReference = Page.PrintOrder;
        pageReference.getParameters().put('oppid', testData.opportunity.Id);
        pageReference.getParameters().put('solutionid', testData.lstconfig[0].Id);
        Test.setCurrentPage(pageReference);        
        
		string s = PrintOrderController.DEFAULT_RESPONSIBLE_PARTY;
		PrintOrderController.orderWrapper ow = new PrintOrderController.orderWrapper(testData.order);
		PrintOrderController.solutionWrapper sw = new PrintOrderController.solutionWrapper(testData.lstconfig[0]);
		List<QuoteWrapper.Product> qwps = new List<QuoteWrapper.Product>();
		QuoteWrapper.Product qwp = new QuoteWrapper.Product();
		qwp.Name = 'Test';
		qwp.ProductID = '1';
		qwp.externalID = '1';
		qwp.productFamilyId = '1';
		qwp.Salesproduct = 'Test Product';
		qwp.SalesProductGroup = 'Test Product Groups';
		QuoteWrapper.QuoteLineItem qli = new QuoteWrapper.QuoteLineItem(testData.lstLineItems[0]);
		qwp.lines.add(qli);
		qwps.add(qwp);
    
        PrintOrderController pc = new PrintOrderController();
		pc.configureProductApproval(qwps,sw);
     		
		PrintOrderController.contactWrapper cw = new PrintOrderController.contactWrapper(testData.parentAccountContact,'test');
    
		
        test.stopTest();
    }
}