objects/Account_Partner__c/Account_Partner__c.object-meta.xml
<CustomObject>
    <label>Account Partner</label>
    <nameField>
        <displayFormat>Partner-{00000000}</displayFormat>
        <label>Account Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Account_Partner__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Partners</relationshipLabel>
    <relationshipName>Account_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Account_Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4 AND 5)</booleanFilter>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Indirect Channel Agency</value>
        </filterItems>
        <filterItems>
            <field>Account.AgentId__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>ICC/iSell Assignment</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Guest</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Accounts</relationshipLabel>
    <relationshipName>Partner_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Service_Location__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Owned_Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/Test_AccountTransfer.cls
@isTest
public with sharing class Test_AccountTransfer extends TestUtils.TestClass {

    static testMethod void testController() {
        Mocks testData = new Mocks();
        
        User toOwner = [select Id from User where UserType LIKE:'%Standard%' and IsActive = true limit 1];
        User fromOwner = [select Id from User where UserType LIKE:'%Standard%' and IsActive = true and Id !=: toOwner.Id limit 1];
        
        Account a1 = getAccount(toOwner.Id);
        Account a2 = getAccount(fromOwner.Id);
        Service_Location__c sLoc = getServiceLoc(a2.Id, testData.loc.Id, fromOwner.Id);
        
        insert new List<AccountTeamMember>{new AccountTeamMember(UserId = toOwner.Id, AccountId = a1.Id, TeamMemberRole = ICCWrapper.roleAccountConsultant)
                                        ,new AccountTeamMember(UserId = fromOwner.Id, AccountId = a2.Id)};
        
        test.starttest();
        
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(testData.parentAccount);
        AccountTransferController atc = new AccountTransferController();
        
        atc.toAccount = a1;
        atc.fromAccount = a2;
        
        Account_Partner__c ap = new Account_Partner__c();
        ap.Account__c = a2.id;
        ap.Partner__c = a2.id;
        
        insert ap;
        
        atc.fromLoc.Owner__c = fromOwner.Id;
        atc.search();
        
        atc.toLoc.Owner__c = toOwner.Id;
        atc.ownerChanged();
        
        Accounttransfercontroller.accountWrapper aw1 = new Accounttransfercontroller.AccountWrapper(a2);
        aw1.selected = true;
        Accounttransfercontroller.serviceLocationWrapper slw1 = new Accounttransfercontroller.ServiceLocationWrapper(sLoc);
        slw1.selected = true;
        atc.accounts = new List<Accounttransfercontroller.accountWrapper>{aw1};
        atc.sLocs = new List<Accounttransfercontroller.serviceLocationWrapper>{slw1};
        
        atc.toPartner.Partner__c = a2.Id;
        atc.transferOwnership();
        
        atc.toCAM.UserId = toOwner.Id;
        atc.toCAM.TeamMemberRole = ICCWrapper.roleCustomerAccountManager;
        atc.transferCAM();
        
        system.debug(atc.getTestClass());
    }
    
    static testMethod void testBatch_CalculateAccountOwnership(){
        Mocks testData = new Mocks();
        
        User toOwner = [select Id from User where UserType LIKE:'%Standard%' and IsActive = true limit 1];
        
        Account a = getAccount(toOwner.Id);
        
        Database.executeBatch(new Batch_CalculateAccountOwnership(new Set<Id>{a.Id}), Batch_CalculateAccountOwnership.DefaultBatchSize);
    }
    
    private static Account getAccount(Id ownerID){
        Account a = new Account(Name='Account', OwnerId=ownerID, ShippingStreet='1', ShippingCity='Nowhwere', ShippingCountryCode = 'US', ShippingState='WA', ShippingPostalCode='12345', Phone='(000) 000-0000', Industry='Z - Unclassified');
        insert a;
        return a;
    }
    
    private static Service_Location__c getServiceLoc(Id accountID, Id locationID, Id ownerID){
        Service_Location__c sLoc = new Service_Location__c(Name='Service Loc', Account__c=accountID, Location__c=locationID, Owner__c=ownerID, Phone__c='(000) 000-0000');
        insert sLoc;
        return sLoc;
    }
}