objects/Account_Partner__c/Account_Partner__c.object-meta.xml
<CustomObject>
    <label>Account Partner</label>
    <nameField>
        <displayFormat>Partner-{00000000}</displayFormat>
        <label>Account Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Account_Partner__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Partners</relationshipLabel>
    <relationshipName>Account_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Account_Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4 AND 5)</booleanFilter>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Indirect Channel Agency</value>
        </filterItems>
        <filterItems>
            <field>Account.AgentId__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>ICC/iSell Assignment</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Guest</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Accounts</relationshipLabel>
    <relationshipName>Partner_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Contact__c/Customer_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>Customer Contact {0000000000}</displayFormat>
        <label>Customer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Customer_Detail__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <description>To leverage account security on this object, we set the parent account of this object to the root of the hierarchy associated with it OR a system account if it is detached.</description>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Customer Details</relationshipLabel>
    <relationshipName>Child_Customer_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

classes/AccountPartnerTriggers.cls
public without sharing class AccountPartnerTriggers{
	
    public static void AccountPartnerModified(List<Account_Partner__c> tNew, List<Account_Partner__c> tOld, Boolean isUpdate, Boolean isBefore, Boolean isDelete){
		
    	if(!ApexUtils.executeTriggerMethods('Account_Partner__c', isBefore, isDelete)) return;
		
    	if(isBefore){
			if(isDelete){
				preventDeletes(new Map<Id, Account_Partner__c>(tOld));
			}
			else{
				handleUpserts(tNew);
			}
    	}
    	else{
	        handleOwnershipRecalculation(isDelete ? tOld : tNew);
			ApexUtils.afterTriggerComplete('Account_Partner__c', isDelete);
    	}
	}
	
	private static Id agentRT = null;
	private static Id guestRT = null;
	private static Boolean rtsLoaded = false;
	private static Boolean isAgency(Account_Partner__c p){
		retrieveRecordTypes();
		return p.RecordTypeId == agentRT;
	}
	
	private static Boolean isGuest(Account_Partner__c p){
		retrieveRecordTypes();
		return p.RecordTypeId == guestRT;
	}
	
	private static void retrieveRecordTypes(){
		if(!rtsLoaded){
			for(RecordType rt : [select Id, DeveloperName from RecordType where sObjectType = 'Account_Partner__c' and DeveloperName in: ICCWrapper.PartnerAgentTypes]){
				if(rt.DeveloperName == ICCWrapper.partnerAgent) agentRT = rt.Id;
				if(rt.DeveloperName == ICCWrapper.partnerGuestAgent) guestRT = rt.Id;
			}
			rtsLoaded = true;
		}
	}
	
	private static void preventDeletes(Map<Id, Account_Partner__c> tOldMap){
		Set<Id> accountIDs = new Set<Id>();
		Set<Id> partnerIDs = new Set<Id>();
		for(Account_Partner__c p : tOldMap.values()){
			accountIDs.add(p.Account__c);
			partnerIDs.add(p.Partner__c);
		}
		
		Map<Id, Set<String>> erroredIDs = new Map<Id, Set<String>>();
		for(Customer_Detail__c cd : [select Id, (select Id, Contact__c, Contact__r.AccountId from Customer_Contacts__r where Contact__r.AccountId in: partnerIDs and Contact__r.AccountId != null) from Customer_Detail__c where Parent_Account__c in: accountIDs]){
			for(Customer_Contact__c cc : cd.Customer_Contacts__r != null ? cd.Customer_Contacts__r : new List<Customer_Contact__c>()){
				Set<String> s = erroredIDs.get(cc.Contact__r.AccountId) != null ? erroredIDs.get(cc.Contact__r.AccountId) : new Set<String>();
				s.add(cc.Contact__c);
				erroredIDs.put(cc.Contact__r.AccountId, s);
			}
		}
		
		for(Account_Partner__c p : tOldMap.values()){
			if(erroredIDs.containsKey(p.Partner__c)){
				p.addError('The following contacts from the partner account are being used by the assigned account\'s customer details: ' + String.join(new List<String>(erroredIDs.get(p.Partner__c)), ', '));
			}
		}
	}
	
	private static void handleUpserts(List<Account_Partner__c> tNew){
		
		Map<Id, Boolean> aMap = new Map<Id, Boolean>();
		for(Account_Partner__c p : tNew){
			if(isAgency(p) || isGuest(p)){
				aMap.put(p.Account__c, aMap.get(p.Account__c) != null);		//Prevent dupes within the current set
				/*if(p.Split_Ownership_Percentage__c == null){
					if(isAgency(p)) p.Split_Ownership_Percentage__c =  50;
					if(isGuest(p)) p.Split_Ownership_Percentage__c =  0;
				}*/
			}
		}
		
		for(Account_Partner__c p : [select Account__c from Account_Partner__c where Account__c in: aMap.keyset() and Id not in: tNew and RecordType.DeveloperName in: ICCWrapper.PartnerAgentTypes])
			aMap.put(p.Account__c, true);
		
		for(Account_Partner__c p : tNew){
			if((isAgency(p) || isGuest(p)) && aMap.get(p.Account__c)){
				p.addError('Only one external agency partner type is allowed on an account at once.');
			}
		}
	}
	
    private static void handleOwnershipRecalculation(List<Account_Partner__c> l){
    	
    	Set<Id> accountIDs = new Set<Id>();
    	for(Account_Partner__c a : l){
			if(isAgency(a) || isGuest(a)) accountIDs.add(a.Account__c);
    	}
		
		Batch_CalculateAccountOwnership.RecalculateAccounts(accountIDs);
    }
}