objects/Account_Partner__c/Account_Partner__c.object-meta.xml
<CustomObject>
    <label>Account Partner</label>
    <nameField>
        <displayFormat>Partner-{00000000}</displayFormat>
        <label>Account Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Account_Partner__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Partners</relationshipLabel>
    <relationshipName>Account_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Account_Partner__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4 AND 5)</booleanFilter>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Indirect Channel Agency</value>
        </filterItems>
        <filterItems>
            <field>Account.AgentId__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>ICC/iSell Assignment</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Guest</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Accounts</relationshipLabel>
    <relationshipName>Partner_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Contact__c/Customer_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>Customer Contact {0000000000}</displayFormat>
        <label>Customer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>After Hours</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Contact</fullName>
            </value>
            <value>
                <fullName>Authorized User</fullName>
            </value>
            <value>
                <fullName>AutoDialer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>BTS Contact</fullName>
            </value>
            <value>
                <fullName>CPNI Contact</fullName>
            </value>
            <value>
                <fullName>Customer Data</fullName>
            </value>
            <value>
                <fullName>Customer Voice</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Local Contact</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Network Notification Email</fullName>
            </value>
            <value>
                <fullName>Network Notification Primary</fullName>
            </value>
            <value>
                <fullName>Network Notification SMS</fullName>
            </value>
            <value>
                <fullName>Open View Contact</fullName>
            </value>
            <value>
                <fullName>Payweb Email</fullName>
            </value>
            <value>
                <fullName>Responsible Party</fullName>
            </value>
            <value>
                <fullName>SMP Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Data</fullName>
            </value>
            <value>
                <fullName>Vendor Voice</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Customer_Contact__c/fields/ICC_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Contact_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Contact ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <description>To leverage account security on this object, we set the parent account of this object to the root of the hierarchy associated with it OR a system account if it is detached.</description>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Customer Details</relationshipLabel>
    <relationshipName>Child_Customer_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Parent_Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Parent_Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Service Location</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__r.ICC_Subscriber_ID__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__r.ICC_Account_Number__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/CustomerContactConfigurationController.cls
public with sharing class CustomerContactConfigurationController implements TestUtils.ITestableClass {
	
	public Contact c {get; private set;}
	public Map<Id, Map<String, List<Customer_Contact__c>>> customerContactsByDetailID {get; private set;}
	public Map<Id, Customer_Detail__c> details {get; private set;}
	public Map<Id, String> detailDesriptions {get; private set;}
    public Customer_Contact__c newCustomerContact {get; set;}
    
	public List<SelectOption> availableCustomers {get; private set;}
	public List<SelectOption> emails {get; private set;}
	public List<SelectOption> phoneNumbers {get; private set;}
    public List<String> selectedCustomers {get; set;}
    public List<SelectOption> availableContactTypes {get; private set;}
    public List<String> selectedContactTypes {get; set;}
    
    public string selectedRoleIds {get;set;}
	
	public CustomerContactConfigurationController(Apexpages.StandardController sc){
		c = (Contact)sc.getRecord();
		system.debug('c: ' + c);
		refreshData();
	}
	
	private void refreshData(){
		List<Contact> contacts = ((List<Contact>)ApexUtils.retrieveFullObjects(Contact.getsObjectType(), 'Id=\'' + c.Id + '\''));
		c = contacts.size() > 0 ? contacts[0] : c;
		
		customerContactsByDetailID = new Map<Id, Map<String, List<Customer_Contact__c>>>();
		details = new Map<Id, Customer_Detail__c>();
		detailDesriptions = new Map<Id, String>();
		newCustomerContact = new Customer_Contact__c();
		availableCustomers = new List<SelectOption>();
		
		Set<Id> accountIDs = new Set<Id>();
		if(c.AccountId != null){
			accountIDs.add(c.AccountId);
			for(Account_Partner__c p : [select Id, Account__c from Account_Partner__c where Partner__c =: c.AccountId]) accountIDs.add(p.Account__c);
		}
		
		emails = getPicklistValues(c.Additional_Email_Addresses__c, !string.isEmpty(c.Email) ? new Set<String>{ c.Email } : null);
		
		Set<String> pNums = new Set<String>();
		for(String s : new List<String>{ c.Phone, c.AssistantPhone, c.HomePhone, c.MobilePhone, c.OtherPhone }){
			if(!String.isEmpty(s)) pNums.add(s);
		}
		phoneNumbers = getPicklistValues(c.Additional_Phone_Numbers__c, pNums);
		
		if(c != null){
			details = new Map<Id, Customer_Detail__c>([select Id from Customer_Detail__c where Parent_Account__c in: accountIDs]);
			
			for(Customer_Contact__c cc : [select Id, Email__c, Phone__c, Contact__r.Id, Contact__r.Name, Contact_Type__c, Customer_Detail__c, ICC_Contact_ID__c from Customer_Contact__c
												where Contact__c =: c.Id and Customer_Detail__c != null
												order by Contact_Type__c, ICC_Contact_ID__c]){
				//Always instantiate
				if(customerContactsByDetailID.get(cc.Customer_Detail__c) == null) customerContactsByDetailID.put(cc.Customer_Detail__c, new Map<String, List<Customer_Contact__c>>());
				
				if(cc.Contact_Type__c != ICCWrapper.ResonsiblePartyContactType){
					Map<String, List<Customer_Contact__c>> m = customerContactsByDetailID.get(cc.Customer_Detail__c) != null ? customerContactsByDetailID.get(cc.Customer_Detail__c) : new Map<String, List<Customer_Contact__c>>();
					String modifier = CustomerDetailExtensionController.getCustomerContactModifier(cc);
					List<Customer_Contact__c> l = m.get(modifier) != null ? m.get(modifier) : new List<Customer_Contact__c>();
					l.add(cc);
					m.put(modifier, l);
					customerContactsByDetailID.put(cc.Customer_Detail__c, m);
					details.put(cc.Customer_Detail__c, null);
				}
			}
			
			details = new Map<Id, Customer_Detail__c>([select Id
															,Name
															,ICC_Subscriber_ID__c
															,(select Id, Name from Accounts__r)
															,(select Id, Name from Service_Locations__r)
															,(select Contact__r.Id, Contact__r.Name from Customer_Contacts__r where Contact_Type__c =: ICCWrapper.ResonsiblePartyContactType limit 1)
														from Customer_Detail__c where Id in : details.keyset() order by ICC_Subscriber_ID__c, Name]);
			
			for(Customer_Detail__c cd : details.values()){
				String n = ((cd.Accounts__r != null && cd.Accounts__r.size() > 0)
					? cd.Accounts__r[0].Name
					: ((cd.Service_Locations__r != null && cd.Service_Locations__r.size() > 0) ? cd.Service_Locations__r[0].Name : cd.Name))
					+ (!string.IsEmpty(cd.ICC_Subscriber_ID__c) ? (' [' + cd.ICC_Subscriber_ID__c + ']') : '');
				detailDesriptions.put(cd.Id, n);
				availableCustomers.add(new SelectOption(cd.Id, n));
			}
		}
		
		availableContactTypes = new List<SelectOption>();
		for(Schema.PicklistEntry ple : Customer_Contact__c.Contact_Type__c.getDescribe().getPicklistValues()){
			if(ple.getLabel() != ICCWrapper.ResonsiblePartyContactType)
				availableContactTypes.add(new SelectOption(ple.getLabel(), ple.getValue()));
		}
	}
	
	private List<SelectOption> getPicklistValues(String fieldValue, Set<String> additionalVals){
		List<SelectOption> retval = new List<SelectOption>{new SelectOption('', '[Default]')};
		for(String s : additionalVals != null ? additionalVals : new Set<String>())
			retval.add(new SelectOption(s, s));
		try{
			List<String> additionalValues = !String.isEmpty(fieldValue) ? fieldValue.split('\n') : new List<String>();
			additionalValues.sort();
			for(String s : additionalValues){
				List<String> parts = s.contains('\t') ? s.split('\t') : new List<String>();
				if(parts.size() > 0) retval.add(new SelectOption(parts[1], parts[0] + ': ' + parts[1]));
			}
		} catch(Exception e) { system.debug('Exception: ' + e); }
		
		return retval;
	}
	
	public PageReference createNewCustomerContacts(){
		if(selectedCustomers != null && selectedCustomers.size() > 0 && selectedContactTypes != null && selectedContactTypes.size() > 0){
			List<Customer_Contact__c> newCustomerContacts = new List<Customer_Contact__c>();
			
			for(String customerID : selectedCustomers){
				Map<String, Set<String>> existingTypes = new Map<String, Set<String>>();
				Map<String, List<Customer_Contact__c>> ccs = customerContactsByDetailID.get(customerID);
				if(ccs != null){
					for(String mod : ccs.keyset()){
						Set<String> modSet = new Set<String>();
						for(Customer_Contact__c cc : ccs.get(mod))
							modSet.add(cc.Contact_Type__c);
						existingTypes.put(mod, modSet);
					}
				}
				
				for(String t : selectedContactTypes){
					Customer_Contact__c cc = new Customer_Contact__c(Customer_Detail__c = customerID
																	,Contact__c = c.Id
																	,Email__c = newCustomerContact.Email__c
																	,Phone__c = newCustomerContact.Phone__c
																	,Contact_Type__c = t);
					String mod = CustomerDetailExtensionController.getCustomerContactModifier(cc);
					if(existingTypes.get(mod) == null || !existingTypes.get(mod).contains(t))
						newCustomerContacts.add(cc);
				}
			}
			
			insert newCustomerContacts;
		}
		
		return refresh();
	}
	
	public PageReference updateResponsibleParties(){
		if(selectedCustomers != null && selectedCustomers.size() > 0){
			List<Customer_Contact__c> respParties = new List<Customer_Contact__c>();
			List<Customer_Contact__c> oldRespParties = new List<Customer_Contact__c>();
			for(Customer_Detail__c cd : [select Id, (select Id from Customer_Contacts__r where Contact_Type__c =: ICCWrapper.ResonsiblePartyContactType limit 1) from Customer_Detail__c where Id in: selectedCustomers]){
				Customer_Contact__c r = null; 
				if(cd.Customer_Contacts__r != null && cd.Customer_Contacts__r.size() > 0)
					r = cd.Customer_Contacts__r[0];
				else
					r = new Customer_Contact__c(Customer_Detail__c = cd.Id, Contact_Type__c = ICCWrapper.ResonsiblePartyContactType);
				r.Contact__c = c.Id;
				r.Email__c = newCustomerContact.Email__c;
				r.Phone__c = newCustomerContact.Phone__c;
				respParties.add(r);
			}
			
			upsert respParties;
		}
		
		return refresh();
	}
	
	public PageReference updateRoles(){
		List<Customer_Contact__c> tContacts = selectedRoleIds != null ? [select Id from Customer_Contact__c  where Id in :selectedRoleIds.split(',')] : new List<Customer_Contact__c>();
		for(Customer_Contact__c cc : tContacts){
			cc.Email__c = newCustomerContact.Email__c;
			cc.Phone__c = newCustomerContact.Phone__c;
		}
		
		if(tContacts.size() > 0) update tContacts;
		
		return refresh();
	}
	
	public PageReference removeRoles(){
		List<Customer_Contact__c> tContacts = selectedRoleIds != null ? [select Id
																		,Customer_Detail__c
																		,Contact__c
																		,Email__c
																		,Phone__c
																  from Customer_Contact__c
																  where Id in :selectedRoleIds.split(',')]
																 : new List<Customer_Contact__c>();
		for(Customer_Contact__c cc : tContacts){
			customerContactsByDetailId.remove(cc.Customer_Detail__c);	
		}
		
		if(tContacts.size() > 0) delete tContacts;
		
		return refresh();
	}
	
	private PageReference refresh(){
		refreshData();
		return null;
		/*PageReference nextPage = ApexPages.currentPage();
        nextPage.setRedirect(true);
		return nextPage;*/
	}
	
	/* TestUtils.ITestableClass methods */
	public TestUtils.TestClass getTestClass(){ return new Test_CustomerContactConfiguration(); }
}