main/default/objects/Customer_Contact__c/Customer_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>Customer Contact {0000000000}</displayFormat>
        <label>Customer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>After Hours</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Contact</fullName>
            </value>
            <value>
                <fullName>Authorized User</fullName>
            </value>
            <value>
                <fullName>AutoDialer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>BTS Contact</fullName>
            </value>
            <value>
                <fullName>CPNI Contact</fullName>
            </value>
            <value>
                <fullName>Customer Data</fullName>
            </value>
            <value>
                <fullName>Customer Voice</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Local Contact</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Network Notification Email</fullName>
            </value>
            <value>
                <fullName>Network Notification Primary</fullName>
            </value>
            <value>
                <fullName>Network Notification SMS</fullName>
            </value>
            <value>
                <fullName>Open View Contact</fullName>
            </value>
            <value>
                <fullName>Payweb Email</fullName>
            </value>
            <value>
                <fullName>Responsible Party</fullName>
            </value>
            <value>
                <fullName>SMP Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Data</fullName>
            </value>
            <value>
                <fullName>Vendor Voice</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Email_Lists__c/Email_Lists__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Email Lists</label>
</CustomObject>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/Test_IntegrationUtils.cls
@isTest
public with sharing class Test_IntegrationUtils extends TestUtils.TestClass {
	
    class SuperException extends Exception {}
	
	static testMethod void testUtils(){
		
		insert new Email_Lists__c(Name='testEmailList', Type__c='IntegrationError', Email__c='email@email.com');
		
		Test.startTest();
		
		System.debug(IntegrationUtils.CustomerDetailIntegrationFieldSet);
		
		try{
			throw new SuperException('Testing exception handling');
		}
		catch(Exception e){
			IntegrationUtils.emailIntegrationException(e, 'email@email.com', 'Something blowed up');
		}
		
		System.debug(new IntegrationUtils().getTestClass());
	}
	
	static testMethod void testIntegrationErrors(){
		Mocks testData = new Mocks();
		
		Account a = testData.parentAccount;
		Service_Location__c sLoc = testData.serviceLocation;
		Contact c = testData.parentAccountContact;
		Customer_Detail__c cd = testData.customerDetail;
		
		Customer_Contact__c cc = new Customer_Contact__c(Contact__c = c.Id, Customer_Detail__c = cd.Id, Contact_Type__c = 'Big Jerk');
		insert cc;
		
		Opportunity_Location__c oppLoc = testData.location;
		
		IntegrationUtils.createUpdateIntegrationErrors(new Set<Id>{a.Id, sLoc.Id, c.Id, cc.Id, cd.Id, oppLoc.Id}, 'ERROR ERROR ERROR', null);
		
		Test.startTest();
		
		IntegrationUtils.reintegrateObjects(new Set<String>{a.Id, sLoc.Id, c.Id, cc.Id, cd.Id, oppLoc.Id});
	}
	
	/*static testMethod void testSchedule_IntegrationErrorsRetry(){
		Mocks testData = new Mocks();
		
		Account a = testData.parentAccount;
		
		IntegrationUtils.createUpdateIntegrationErrors(new Set<Id>{a.Id}, 'ERROR ERROR ERROR', null);
		
		Test.startTest();
		
		Schedule_IntegrationErrorsRetry.retryIntegrationErrors();
	}*/
	
	static testMethod void testReactivateAccounts(){
		Mocks testData = new Mocks();
		
		Account a = testData.parentAccount;
		a.Customer_Detail__c = testData.customerDetail.Id;
		a.Type = 'Former Customer';
		AccountTriggers.DisableTrigger = true;
		update a;
		AccountTriggers.DisableTrigger = false;
		
		Service_Location__c sLoc = testData.serviceLocation;
		Contact c = testData.parentAccountContact;
		
		insert new Customer_Contact__c(Contact__c = c.Id, Customer_Detail__c = a.Customer_Detail__c, Contact_Type__c = 'Master of Disaster');
		
		Test.startTest();
		
		IntegrationUtils.reactivateAccounts(new Set<Id>{a.Id});
	}
	
	private static Integer subID = 0;
	public static List<integraWS.SFSubscriberView> getMockSubscriberResults(List<integraWS.SFSubscriberView> subs){
		for(integraWS.SFSubscriberView s : subs){
			s.SubscriberID = 9000 + subID++;
			if(s.Children != null && s.Children.SFSubscriberView != null)
				getMockSubscriberResults(s.Children.SFSubscriberView);
		}
		return subs;
	}
}