main/default/objects/Customer_Contact__c/Customer_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>Customer Contact {0000000000}</displayFormat>
        <label>Customer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>After Hours</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Contact</fullName>
            </value>
            <value>
                <fullName>Authorized User</fullName>
            </value>
            <value>
                <fullName>AutoDialer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>BTS Contact</fullName>
            </value>
            <value>
                <fullName>CPNI Contact</fullName>
            </value>
            <value>
                <fullName>Customer Data</fullName>
            </value>
            <value>
                <fullName>Customer Voice</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Local Contact</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Network Notification Email</fullName>
            </value>
            <value>
                <fullName>Network Notification Primary</fullName>
            </value>
            <value>
                <fullName>Network Notification SMS</fullName>
            </value>
            <value>
                <fullName>Open View Contact</fullName>
            </value>
            <value>
                <fullName>Payweb Email</fullName>
            </value>
            <value>
                <fullName>Responsible Party</fullName>
            </value>
            <value>
                <fullName>SMP Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Data</fullName>
            </value>
            <value>
                <fullName>Vendor Voice</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Service_Location__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

classes/Test_ServiceLocationExtensionController.cls
@isTest
public with sharing class Test_ServiceLocationExtensionController extends TestUtils.TestClass {
	
	static testMethod void testController(){
        Mocks testData = new Mocks();
		
		Service_Location__c sLoc = testData.serviceLocation;
		
		Test.startTest();
		
		Apexpages.StandardController sc = new Apexpages.StandardController(sLoc);
    	ServiceLocationExtensionController slec = new ServiceLocationExtensionController(sc);
		slec.reactivateLocation();
	}
	
 	static testMethod void testNewCustomerDetails() {
        Mocks testData = new Mocks();
		
		Service_Location__c sLoc = testData.serviceLocation;
		
		Test.startTest();
		
		Apexpages.StandardController sc = new Apexpages.StandardController(sLoc);
    	ServiceLocationExtensionController slec = new ServiceLocationExtensionController(sc);
    	slec.generateDetails();
    	slec = new ServiceLocationExtensionController(sc);
		
		System.debug(slec.getTestClass());
    }
	
 	static testMethod void testCloneParentCustomerDetails() {
        Mocks testData = new Mocks();
		
		Service_Location__c sLoc = testData.serviceLocation;
		
		Test.startTest();
		
		Apexpages.StandardController sc = new Apexpages.StandardController(sLoc);
    	ServiceLocationExtensionController slec = new ServiceLocationExtensionController(sc);
		
		CustomerDetailUtils.updateCustomerDetails(new List<Set<Id>>{new Set<Id>{sLoc.Account__c}}, null);
		
    	PageReference pageReference = Page.ServiceLocationExtensionController;
        pageReference.getParameters().put('cloneFromParent', 'true');
        Test.setCurrentPage(pageReference);
		
    	slec.generateDetails();
    	slec = new ServiceLocationExtensionController(sc);
		
		System.debug(slec.getTestClass());
    }
		
	static testMethod void testMove(){
        Mocks testData = new Mocks();
		
		Service_Location__c sLoc = testData.serviceLocation;
		sLoc.Billable__c = true;
		update sLoc;
		
		CustomerDetailUtils.updateCustomerDetails(new List<Set<Id>>{new Set<Id>{sLoc.Account__c}, new Set<Id>{sLoc.Id}}, null);
		
		List<Customer_Detail__c> cdList = [select Id from Customer_Detail__c];
		for(Integer i=0; i<cdList.size(); i++){
			cdList[i].ICC_Subscriber_ID__c = String.valueOf(-999 - i);
		}
		update cdList;
		
		sObjectType sLocType = Service_Location__c.getsObjectType();
		sLoc = ((List<Service_Location__c>)ApexUtils.retrieveFullObjects(sLocType, 'Id = \'' + sLoc.Id + '\''))[0];
		
		Account a = [select Id, ICC_Account_Number__c, Customer_Detail__c from Account where Id =: sLoc.Account__c];
		a.Billable__c = false;
		update a;
		
		AccountTeamMember atm = new AccountTeamMember(AccountId = a.Id
													,TeamMemberRole = ICCWrapper.roleCustomerAccountManager
													,UserId = testData.user.Id);
		insert atm;
		
		Contact c = testData.parentAccountContact;
		Customer_Contact__c cc = new Customer_Contact__c(Contact__c=c.Id
														,Contact_Type__c='Type'
														,Customer_Detail__c=sLoc.Customer_Detail__c);
		insert cc;
		
		Test.startTest();
		
		Apexpages.StandardController sc = new Apexpages.StandardController(sLoc);
    	ServiceLocationExtensionController slec = new ServiceLocationExtensionController(sc);
		System.assert(slec.canMove, 'Service location cannot be moved');
		
    	PageReference pageReference = Page.ServiceLocationExtensionController;
        //pageReference.getParameters().put('id', sLoc.Id);
        Test.setCurrentPage(pageReference);
		
		//Detach
        pageReference.getParameters().put('parentSubscriberID', '');
		slec.move();
		System.assert([select Account__c from Service_Location__c where Id =: sLoc.Id].Account__c != a.Id, 'Service location did not detach');
		
		//Attach/merge
		sc = new Apexpages.StandardController(sLoc);
    	slec = new ServiceLocationExtensionController(sc);
		System.assert(slec.canMove, 'Service location cannot be moved');
		
		pageReference.getParameters().clear();
        pageReference.getParameters().put('parentSubscriberID', a.ICC_Account_Number__c);
		slec.move();
	}
	
	public static List<integraWS.SFSubscriberView> simulateHierarchyUpdate(Map<Integer, Integer> parentSubscriberIDBySubscriberID){
		Set<String> ids = new Set<String>();
		for(Integer i : parentSubscriberIDBySubscriberID.keySet())
			ids.add(String.valueOf(i));
		
		for(Integer i : parentSubscriberIDBySubscriberID.values()){
			if(i != null)
				ids.add(String.valueOf(i));
		}
		
		List<Service_Location__c> sLocs = [select Id, Account__r.Id, Account__r.ICC_Account_Number__c, ICC_Subscriber_ID__c from Service_Location__c where ICC_Subscriber_ID__c in: ids];
		
		List<integraWS.SFSubscriberView> results = new List<integraWS.SFSubscriberView>();
		Map<Id, Account> accounts = new Map<Id, Account>();
		for(Service_Location__c sLoc : sLocs){
			accounts.put(sLoc.Account__r.Id, sLoc.Account__r);
			
			integraWS.SFSubscriberView r = new integraWS.SFSubscriberView();
			r.SubscriberID = Integer.valueOf(sLoc.ICC_Subscriber_ID__c);
			r.SalesforceID = sLoc.Id;
			r.SubscriberType = 'SubType';
			results.add(r);
		}
		
		for(Account acc : accounts.values()){
			integraWS.SFSubscriberView r = new integraWS.SFSubscriberView();
			r.SubscriberID = Integer.valueOf(acc.ICC_Account_Number__c);
			r.SalesforceID = acc.Id;
			r.SubscriberType = 'SubType';
			results.add(r);
		}
		
		return results;
	}
}