main/default/objects/Customer_Contact__c/Customer_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>Customer Contact {0000000000}</displayFormat>
        <label>Customer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>After Hours</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Contact</fullName>
            </value>
            <value>
                <fullName>Authorized User</fullName>
            </value>
            <value>
                <fullName>AutoDialer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>BTS Contact</fullName>
            </value>
            <value>
                <fullName>CPNI Contact</fullName>
            </value>
            <value>
                <fullName>Customer Data</fullName>
            </value>
            <value>
                <fullName>Customer Voice</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Local Contact</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Network Notification Email</fullName>
            </value>
            <value>
                <fullName>Network Notification Primary</fullName>
            </value>
            <value>
                <fullName>Network Notification SMS</fullName>
            </value>
            <value>
                <fullName>Open View Contact</fullName>
            </value>
            <value>
                <fullName>Payweb Email</fullName>
            </value>
            <value>
                <fullName>Responsible Party</fullName>
            </value>
            <value>
                <fullName>SMP Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Data</fullName>
            </value>
            <value>
                <fullName>Vendor Voice</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Parent_Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Parent_Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Service Location</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__r.ICC_Subscriber_ID__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__r.ICC_Account_Number__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/Test_TreeView.cls
@isTest
public with sharing class Test_TreeView extends TestUtils.TestClass {
	
	private class RawTreeView extends TreeViewController.TreeViewImplementation{
		public RawTreeView(){
			divID = 'raw';
			loadMoreEnabled = true;
		}
		
		public override List<TreeNode> getNodes(){
			TreeNode t = new TreeNode('a node', null);
			t.setAttribute('att', 'val');
			t.hiddenAttributes.put('hidden', 'hiddenval');
			
			TreeNode c = new TreeNode();
			t.addChildNode(c, '');
			return new List<TreeNode>{t};
		}
	}
	
	static testMethod void testController(){
        TreeViewController tvc = new TreeViewController();
		tvc.TreeViewsByDivID = new Map<String, TreeViewController.TreeViewImplementation>{'raw'=>new RawTreeView()};
		tvc.loadMore_divID = 'raw';
		System.debug(tvc.loadNodes());
		tvc.loadMore_path = 'nowhere';
		tvc.loadMore_currentlyLoaded = '1,2';
		System.debug(tvc.loadNodes());
		System.debug(tvc.ActionMappings);
		System.debug(tvc.IconMappings);
		System.debug(tvc.AllJSONTrees);
		System.debug(tvc.TreesNodeCounts);
		
		TreeNode t = new TreeNode(null, null);
		TreeViewController.addActionsToNode(t, new List<String>{'action'});
	}
	
	static testMethod void testCustomerHierarchy(){
		Mocks testData = new Mocks();
		Account a = testData.parentAccount;
		
		Contact c = testData.parentAccountContact;
		c.Default_Responsible_Party__c = true;
		update c;
		
		Service_Location__c sLoc = testData.serviceLocation;
		
		sObjectType sLocType = Service_Location__c.getsObjectType();
		sLoc = ((List<Service_Location__c>)ApexUtils.retrieveFullObjects(sLocType, 'Id = \'' + sLoc.Id + '\''))[0];
		
		List<Service_Location__c> sLocs = new List<Service_Location__c>();
		for(Integer i=0; i<500; i++){
			Service_Location__c child = (Service_Location__c)ApexUtils.deepCopyFields(sLocType, sLoc, new Service_Location__c(), null);
			child.Parent_Service_Location__c = sLoc.Id;
			sLocs.add(child);
		}
		upsert sLocs;
		
		CustomerDetailUtils.updateCustomerDetails(new List<Set<Id>>{new Set<Id>{a.Id, sLoc.Id}, new Set<Id>{sLocs[0].Id}, new Set<Id>{sLocs[1].Id}}, new Map<Id, List<Customer_Contact__c>>{sLocs[1].Id=>new List<Customer_Contact__c>{new Customer_Contact__c(Contact__c=c.Id, Contact_Type__c=ICCWrapper.ResonsiblePartyContactType), new Customer_Contact__c(Contact__c=c.Id, Contact_Type__c='Authorized User')}});
		Customer_Detail__c cd = [select Id, Customer_Detail__r.Id from Service_Location__c where Id=: sLoc.Id limit 1].Customer_Detail__r;
		cd.ICC_Subscriber_ID__c = '-999';
		update cd;
		
		Test.startTest();
		
        TreeViewController tvc = new TreeViewController();
		tvc.TreeViewsByDivID = new Map<String, TreeViewController.TreeViewImplementation>{'hierarchy'=>new CustomerHierarchyController.TreeViewImplementation(a.Id)};
		tvc.loadMore_divID = 'hierarchy';
		System.debug(tvc.loadNodes());
		tvc.loadMore_path = a.Id + ':{Contacts}';
		tvc.loadMore_currentlyLoaded = '1,2';
		System.debug(tvc.loadNodes());
		System.debug(tvc.ActionMappings);
		System.debug(tvc.IconMappings);
		System.debug(tvc.AllJSONTrees);
		System.debug(tvc.TreesNodeCounts);
		
		CustomerHierarchyController chc = new CustomerHierarchyController();
	}
}