main/default/objects/Customer_Contact__c/Customer_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>Customer Contact {0000000000}</displayFormat>
        <label>Customer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>After Hours</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Contact</fullName>
            </value>
            <value>
                <fullName>Authorized User</fullName>
            </value>
            <value>
                <fullName>AutoDialer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>BTS Contact</fullName>
            </value>
            <value>
                <fullName>CPNI Contact</fullName>
            </value>
            <value>
                <fullName>Customer Data</fullName>
            </value>
            <value>
                <fullName>Customer Voice</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Local Contact</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Network Notification Email</fullName>
            </value>
            <value>
                <fullName>Network Notification Primary</fullName>
            </value>
            <value>
                <fullName>Network Notification SMS</fullName>
            </value>
            <value>
                <fullName>Open View Contact</fullName>
            </value>
            <value>
                <fullName>Payweb Email</fullName>
            </value>
            <value>
                <fullName>Responsible Party</fullName>
            </value>
            <value>
                <fullName>SMP Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Data</fullName>
            </value>
            <value>
                <fullName>Vendor Voice</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Customer_Detail__c/fields/Billing_Main_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_City__c</fullName>
    <label>Billing Main City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Country__c</fullName>
    <label>Billing Main Country</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Postal_Code__c</fullName>
    <label>Billing Main Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Billing_Main_Room_Suite__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Room_Suite__c</fullName>
    <label>Billing Main Room/Suite</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_State__c</fullName>
    <label>Billing Main State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Billing_Main_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Street__c</fullName>
    <label>Billing Main Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Customer_Main_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Main_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subscriber Address Type &#39;Customer Main&#39;</description>
    <label>Customer Main Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Customer Details (Customer Main Address)</relationshipLabel>
    <relationshipName>Customer_Main_Address_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

classes/Test_CustomerContactConfiguration.cls
@isTest
public with sharing class Test_CustomerContactConfiguration extends TestUtils.TestClass {
	
 	static testMethod void testController() {
        Mocks testData = new Mocks();
    	test.startTest();
    	
    	Customer_Detail__c cd = new Customer_Detail__c(ICC_Subscriber_ID__c='-9999'
    													,Customer_Main_Address__c=testData.loc.Id
    													,Billing_Main_City__c='abcd'
                                                        ,Billing_Main_Country__c = 'US'
    													,Billing_Main_State__c='OR'
    													,Billing_Main_Street__c='1234'
    													,Billing_Main_Postal_Code__c='00000'
    													,Billing_Main_Room_Suite__c='1');
    	insert cd;
    	
    	testData.parentAccount.Customer_Detail__c = cd.Id;
    	update testData.parentAccount;
    	
    	Contact c = new Contact(FirstName='Francis'
    							,LastName='Morgan'
    							,Email='justcallmeyork@everybodydoes.com'
    							,AccountId=testData.parentAccount.Id);
    	insert c;
    	
    	List<Customer_Contact__c> ccs = new List<Customer_Contact__c>{
    										new Customer_Contact__c(Contact__c=testdata.parentAccountContact.Id, Customer_Detail__c=cd.Id, Contact_Type__c=ICCWrapper.ResonsiblePartyContactType, Email__c='fake@fakeadress.com')
    										,new Customer_Contact__c(Contact__c=c.Id, Customer_Detail__c=cd.Id, Contact_Type__c='Authorized Agent')
    									};
    	insert ccs;
    	
        PageReference pageReference = Page.CustomerContactConfiguration;
        Test.setCurrentPage(pageReference);
        
		Apexpages.StandardController sc = new Apexpages.StandardController(c);
    	CustomerContactConfigurationController cc = new CustomerContactConfigurationController(sc);
    	cc.selectedContactTypes = new List<String>{'Bravest and strongest man'};
    	cc.selectedCustomers = new List<String>{string.valueOf(cd.Id)};
    	cc.createNewCustomerContacts();
    	cc.updateResponsibleParties();
        pageReference.getParameters().put('roleIDs', string.valueOf(ccs[0].Id));
    	cc.removeRoles();
    	
    	test.stopTest();
    }
}