main/default/objects/Customer_Contact__c/Customer_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>Customer Contact {0000000000}</displayFormat>
        <label>Customer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>After Hours</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Contact</fullName>
            </value>
            <value>
                <fullName>Authorized User</fullName>
            </value>
            <value>
                <fullName>AutoDialer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>BTS Contact</fullName>
            </value>
            <value>
                <fullName>CPNI Contact</fullName>
            </value>
            <value>
                <fullName>Customer Data</fullName>
            </value>
            <value>
                <fullName>Customer Voice</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Local Contact</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Network Notification Email</fullName>
            </value>
            <value>
                <fullName>Network Notification Primary</fullName>
            </value>
            <value>
                <fullName>Network Notification SMS</fullName>
            </value>
            <value>
                <fullName>Open View Contact</fullName>
            </value>
            <value>
                <fullName>Payweb Email</fullName>
            </value>
            <value>
                <fullName>Responsible Party</fullName>
            </value>
            <value>
                <fullName>SMP Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Data</fullName>
            </value>
            <value>
                <fullName>Vendor Voice</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Customer_Detail__c/fields/Bill_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Bill_Cycle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill Cycle</label>
    <referenceTo>Customer_Setting__c</referenceTo>
    <relationshipLabel>Customer Details</relationshipLabel>
    <relationshipName>Bill_Cycle_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Care_Organization__c.field-meta.xml
<CustomField>
    <fullName>Care_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Organization</label>
    <referenceTo>Customer_Setting__c</referenceTo>
    <relationshipLabel>Customer Details (Care Organization)</relationshipLabel>
    <relationshipName>Care_Organization_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Collection_Code__c.field-meta.xml
<CustomField>
    <fullName>Collection_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Code</label>
    <referenceTo>Customer_Setting__c</referenceTo>
    <relationshipLabel>Customer Details</relationshipLabel>
    <relationshipName>Collection_Code_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Customer_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Managed_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Exchange__c.field-meta.xml
<CustomField>
    <fullName>Exchange__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exchange</label>
    <referenceTo>Customer_Setting__c</referenceTo>
    <relationshipLabel>Customer Details</relationshipLabel>
    <relationshipName>Exchange_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Detail__c/fields/Government_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Government_Contract_Type__c</fullName>
    <label>Government Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CALNET3</fullName>
            </value>
            <value>
                <fullName>GSA R8 LSA 2</fullName>
            </value>
            <value>
                <fullName>GSA R8 LSA 2 (+Disaster Purchasing Program)</fullName>
            </value>
            <value>
                <fullName>IT Schedule 70</fullName>
            </value>
            <value>
                <fullName>IT Schedule 70 (+Disaster Purchasing Program)</fullName>
            </value>
            <value>
                <fullName>MiCTA</fullName>
            </value>
            <value>
                <fullName>State of AZ</fullName>
            </value>
            <value>
                <fullName>State of Idaho</fullName>
            </value>
            <value>
                <fullName>State of Oregon</fullName>
            </value>
            <value>
                <fullName>State of Utah MA110</fullName>
            </value>
            <value>
                <fullName>State of WA K1677</fullName>
            </value>
            <value>
                <fullName>State of WA T12-PCH-739</fullName>
            </value>
            <value>
                <fullName>St of MN Backbone 55583</fullName>
            </value>
            <value>
                <fullName>St of MN PRI 66842</fullName>
            </value>
            <value>
                <fullName>Univ of MN PRI 66842</fullName>
            </value>
            <value>
                <fullName>UW-IT Ethernet Services</fullName>
            </value>
            <value>
                <fullName>GOO MGS: OSS_00411380</fullName>
            </value>
            <value>
                <fullName>Canada: Legal Aid</fullName>
            </value>
            <value>
                <fullName>OACCAC</fullName>
            </value>
            <value>
                <fullName>WSIB</fullName>
            </value>
            <value>
                <fullName>Canada Federal Govt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Government_Segment__c.field-meta.xml
<CustomField>
    <fullName>Government_Segment__c</fullName>
    <label>Government Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Province</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Customer_Detail__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pre-Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Customer_Detail__c/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Type</label>
    <referenceTo>Customer_Setting__c</referenceTo>
    <relationshipLabel>Customer Details</relationshipLabel>
    <relationshipName>Market_Type_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Setting__c/Customer_Setting__c.object-meta.xml
<CustomObject>
    <label>Customer Setting</label>
    <nameField>
        <label>Customer Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Setting__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Settings</relationshipLabel>
    <relationshipName>Customer_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Setting__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <label>External ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Setting__c/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Type</label>
    <referenceTo>Customer_Setting__c</referenceTo>
    <relationshipLabel>Customer Settings</relationshipLabel>
    <relationshipName>Customer_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Setting__c/fields/Reference_ID__c.field-meta.xml
<CustomField>
    <fullName>Reference_ID__c</fullName>
    <label>Reference ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Customer_Setting__c/recordTypes/Subscriber_Setting.recordType-meta.xml
<RecordType>
    <fullName>Subscriber_Setting</fullName>
    <active>true</active>
    <label>Subscriber Setting</label>
</RecordType>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Parent_Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Parent_Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Service Location</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__r.ICC_Subscriber_ID__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__r.ICC_Account_Number__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/CustomerDetailBaseController.cls
public with sharing abstract class CustomerDetailBaseController extends TreeViewController{
    
    protected sObject baseObject {get; set;}
    public Customer_Detail__c detail {get; private set;}
    
    public Customer_Setting__c eRate { get; private set; }
    public Boolean eRateFlag { get; set; }
    
    public List<SelectOption> GovernmentContractTypes{ get{ return SchemaUtils.GetPicklistValues(Schema.Customer_Detail__c.sObjectType.fields.Government_Contract_Type__c, true); } }
    public List<SelectOption> GovernmentSegments{ get{ return SchemaUtils.GetPicklistValues(Schema.Customer_Detail__c.sObjectType.fields.Government_Segment__c, true); } }
    
    protected void loadDetails(){
        
        Id cdID = (SchemaUtils.GetSObjectNameByID(baseObject.Id) == 'Account') ? [select Id, Customer_Detail__c from Account where Id =: baseObject.Id][0].Customer_Detail__c : [select Id, Customer_Detail__c from Service_Location__c where Id =: baseObject.Id][0].Customer_Detail__c;
        detail = [select Id
                        ,Name
                        ,ICC_Subscriber_ID__c
                        ,Integration_Status__c
                        ,(select Id, Name from Accounts__r)
                        ,(select Id, Name from Service_Locations__r)
                        ,(select Id, Contact__r.Id, Contact__r.Name from Customer_Contacts__r where Contact_Type__c =: ICCWrapper.ResonsiblePartyContactType order by CreatedDate, Id)
                        ,(select Id, External_ID__c from Customer_Settings__r where RecordType.DeveloperName = 'Subscriber_Setting' and Reference_ID__c = '41')
                  		,Bill_Cycle__r.Name
                        ,Collection_Code__r.Name
                        ,Customer_Account_Manager__c
                        ,Exchange__r.Name
                        ,Government_Contract_Type__c
                        ,Government_Segment__c
                        ,Market_Type__r.Name
                        ,Care_Organization__r.Name
                        ,Service_Address__c
                        from Customer_Detail__c where Id =: cdID];
        
        
                
        eRate = detail != null && detail.Customer_Settings__r != null && detail.Customer_Settings__r.size() > 0 ? detail.Customer_Settings__r[0] : null;
        eRateFlag = eRate != null;
    }
    
    public PageReference generateDetails(){
        Boolean cloneFromParent = ApexPages.currentPage().getParameters().get('cloneFromParent') == 'true';
        
        Set<Id> frontEndIDs = null;
        if(baseObject.get('Customer_Detail__c') == null){
            CustomerDetailUtils.triggerDetailAddressValidation = false; //Run Synchronous
            
            if(SchemaUtils.GetSObjectNameByID(baseObject.Id) == 'Account'){
                Account a = (Account)baseObject;
                List<Service_Location__c> sLocs = [select Id, Customer_Detail__c from Service_Location__c where Account__c =: a.Id];
                frontEndIDs = (a.ICC_Account_Number__c == null && sLocs.size() == 1) ? new Set<Id>{sLocs[0].Id, baseObject.Id} : new Set<Id>{baseObject.Id};
            }
            else{
                Service_Location__c sLoc = (Service_Location__c)baseObject;
                Account a = sLoc.Account__c != null ? [select Id, ICC_Account_Number__c, Customer_Detail__c, CurrencyISOCode from Account where Id =: sLoc.Account__c] : null;
                if(cloneFromParent){
                    for(Customer_Detail__c cd : CustomerDetailUtils.cloneCustomerDetailsFromParent(new Set<Id>{sLoc.Id}))   //Should only return one
                        sLoc.Customer_Detail__c = cd.Id;
                }
                else frontEndIDs = (a != null && a.ICC_Account_Number__c == null && [select COUNT() from Service_Location__c where Account__c =: sLoc.Account__c] == 1) ? new Set<Id>{sLoc.Id, sLoc.Account__c} : new Set<Id>{sLoc.Id};
                    
            }
            
            if(frontEndIDs != null) CustomerDetailUtils.updateCustomerDetails(new List<Set<Id>>{frontEndIDs});
        }
        
        UpdateGovernmentAndBPIDFields();        
        loadDetails();
        
        return null;
    }
    
    public PageReference updateDetails(){
        if(!eRateFlag && eRate != null){
            if(String.isEmpty(eRate.External_ID__c) || ICCWrapper.deleteSubscriberSettings(new List<Integer>{integer.valueOf(eRate.External_ID__c)}, UserInfo.getSessionID()).size() > 0){
                Database.delete(eRate, false);
            }
            else addCustomMessage(true, 'The E-Rate setting could not be deleted.');
        }
        else if(eRateFlag && eRate == null){
            Id rtID = [select Id from RecordType where DeveloperName = 'Subscriber_Setting'][0].Id;
            List<Customer_Setting_Reference__c> refs = [select Description__c from Customer_Setting_Reference__c where ID__c = '41' and Category__c = 'SubscriberSetting'];
            Customer_Setting__c setting = new Customer_Setting__c(Name = refs[0].Description__c, Customer_Detail__c = detail.Id, RecordTypeId = rtID, Reference_ID__c = '41');
            
            String errorMessage = CustomerDetailUtils.integrateSubscriberSetting(detail, setting);
            if(String.isEmpty(errorMessage)) Database.insert(setting);
            else addCustomMessage(true, errorMessage);
        }
        
        UpdateGovernmentAndBPIDFields();
            
        Database.update(detail, false);
        loadDetails();
        return null;
    }
    
    private void UpdateGovernmentAndBPIDFields(){
        if(SchemaUtils.GetSObjectNameByID(baseObject.Id) == 'Service_Location__c'){ 
            Service_Location__c sLocation = [Select Id, Customer_Detail__r.Id, Account__r.Customer_Detail__r.BPID__c, Account__r.Customer_Detail__r.Government_Contract_Type__c, Account__r.Customer_Detail__r.Government_Segment__c From Service_Location__c Where Id =: baseObject.Id Limit 1];
            Customer_Detail__c sLocDetail = [Select BPID__c, Government_Contract_Type__c, Government_Segment__c From Customer_Detail__c Where Id =: sLocation.Customer_Detail__r.Id Limit 1];
            sLocDetail.BPID__c = sLocation.Account__r.Customer_Detail__r.BPID__c;
            sLocDetail.Government_Contract_Type__c = sLocation.Account__r.Customer_Detail__r.Government_Contract_Type__c;
            sLocDetail.Government_Segment__c = sLocation.Account__r.Customer_Detail__r.Government_Segment__c;
            Database.update(sLocDetail);
        }
    }
    
    protected PageReference refresh(){
        PageReference nextPage = ApexPages.currentPage();
        nextPage.getParameters().clear();
        nextPage.getParameters().put('Id', baseObject.Id);
        nextPage.setRedirect(true);
        return nextPage;
    }
    
    public virtual void addCustomMessage(Boolean isError, String message){
        ApexPages.addMessage(new ApexPages.Message(isError ? ApexPages.Severity.ERROR : ApexPages.Severity.INFO, message));
    }
}