main/default/objects/Customer_Contact__c/Customer_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>Customer Contact {0000000000}</displayFormat>
        <label>Customer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>After Hours</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Contact</fullName>
            </value>
            <value>
                <fullName>Authorized User</fullName>
            </value>
            <value>
                <fullName>AutoDialer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>BTS Contact</fullName>
            </value>
            <value>
                <fullName>CPNI Contact</fullName>
            </value>
            <value>
                <fullName>Customer Data</fullName>
            </value>
            <value>
                <fullName>Customer Voice</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Local Contact</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Network Notification Email</fullName>
            </value>
            <value>
                <fullName>Network Notification Primary</fullName>
            </value>
            <value>
                <fullName>Network Notification SMS</fullName>
            </value>
            <value>
                <fullName>Open View Contact</fullName>
            </value>
            <value>
                <fullName>Payweb Email</fullName>
            </value>
            <value>
                <fullName>Responsible Party</fullName>
            </value>
            <value>
                <fullName>SMP Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Data</fullName>
            </value>
            <value>
                <fullName>Vendor Voice</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Customer_Contact__c/fields/ICC_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Contact_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Contact ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Logon_Name__c.field-meta.xml
<CustomField>
    <fullName>Logon_Name__c</fullName>
    <description>Used by external systems to map a user to a specific contact.</description>
    <label>Logon Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/External_User__c/External_User__c.object-meta.xml
<CustomObject>
    <label>External User</label>
    <nameField>
        <label>External User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/External_User__c/fields/Logon_Name__c.field-meta.xml
<CustomField>
    <fullName>Logon_Name__c</fullName>
    <externalId>true</externalId>
    <label>Logon Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Integration_Error__c/Integration_Error__c.object-meta.xml
<CustomObject>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Integration_Error__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Integration_Error__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <description>This is a general purpose field for storing what we were trying to do when integrating when we failed.  Both Action and the related object are taken into account when reading the values here:

Object(Action): Value
---------------------
Account(Update): Comma delimited field names
Contact(Update): N/A
Contact(Delete): ICC Contact ID
Service Location(Insert): Closed Won Opportunity ID (earliest closed date)
Service Location(Update): Comma delimited field names</description>
    <label>Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Integration_Error__c/fields/ObjectID__c.field-meta.xml
<CustomField>
    <fullName>ObjectID__c</fullName>
    <label>ObjectID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

classes/Test_ContactTriggers.cls
@isTest
public with sharing class Test_ContactTriggers extends TestUtils.TestClass {

	//Also tests IntegrationErrorsController.integrateBatch()
    static testMethod void testContactUpdate() {
        // create test data
        Mocks testData = new Mocks();
        
        test.startTest();
    	
        List<Contact> tNew = new List<Contact>{testData.parentAccountContact};
        
		integraWSEndpointMediator.simulateIntegrationException = true;
    	update tNew;
    	
    	//This won't actually create the IntegrationError object so let's make it
    	Integration_Error__c error = new Integration_Error__c(ObjectID__c = tNew[0].Id, Action__c = 'Update');
    	insert error;
    	
    	IntegrationErrorsController errorController = new IntegrationErrorsController();
    	errorController.objectTypeSelection = 'Contact';
    	errorController.integrateBatch();
    	
    	Customer_Contact__c cc = new Customer_Contact__c(Contact__c=tNew[0].Id, Customer_Detail__c=testData.customerDetail.Id, Contact_Type__c='Test type', ICC_Contact_ID__c='-1');
    	insert cc;
    	
		integraWSEndpointMediator.simulateIntegrationException = false;
		update tNew;

        test.stopTest();
    }
    
	//Also tests IntegrationErrorsController.integrateSingle()
    static testMethod void testContactDelete() {
        // create test data
        Mocks testData = new Mocks();
        
        List<Contact> tNew = new List<Contact>{testData.parentAccountContact};
    	Customer_Contact__c cc = new Customer_Contact__c(Contact__c=tNew[0].Id, Customer_Detail__c=testData.customerDetail.Id, Contact_Type__c='Test type', ICC_Contact_ID__c='-1');
    	insert cc;
        
        test.startTest();
        
        if(tNew.size() > 0){
			integraWSEndpointMediator.simulateIntegrationException = true;
        	delete tNew;
        	
	    	//This won't actually create the IntegrationError object so let's make it
	    	/*Integration_Error__c error = new Integration_Error__c(ObjectID__c = tNew[0].Id, Action__c = 'Delete', Info__c = tNew[0].ICCContactID__c);
	    	insert error;*/
	    	
	    	IntegrationErrorsController errorController = new IntegrationErrorsController();
	    	errorController.objectID = tNew[0].Id;
	    	errorController.integrateSingle();
        }

        test.stopTest();
    }
	
    static testMethod void testExternalUserContact() {
        Mocks testData = new Mocks();
        
        test.startTest();
		
		External_User__c u = new External_User__c(
													Logon_Name__c = 'testuser'
													,First_Name__c = 'External'
													,Last_Name__c = 'Flexternal'
													,Email__c = 'test@test.com'
												);
		insert u;
    	u.Last_Name__c = 'Flexternalist';
		update u;
        List<Contact> tNew = new List<Contact>{testData.parentAccountContact};
        
		tNew[0].External_User__c = u.Id;
    	update tNew;
		
        test.stopTest();
    }
}