main/default/objects/Customer_Contact__c/Customer_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>Customer Contact {0000000000}</displayFormat>
        <label>Customer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>After Hours</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Contact</fullName>
            </value>
            <value>
                <fullName>Authorized User</fullName>
            </value>
            <value>
                <fullName>AutoDialer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>BTS Contact</fullName>
            </value>
            <value>
                <fullName>CPNI Contact</fullName>
            </value>
            <value>
                <fullName>Customer Data</fullName>
            </value>
            <value>
                <fullName>Customer Voice</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Local Contact</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Network Notification Email</fullName>
            </value>
            <value>
                <fullName>Network Notification Primary</fullName>
            </value>
            <value>
                <fullName>Network Notification SMS</fullName>
            </value>
            <value>
                <fullName>Open View Contact</fullName>
            </value>
            <value>
                <fullName>Payweb Email</fullName>
            </value>
            <value>
                <fullName>Responsible Party</fullName>
            </value>
            <value>
                <fullName>SMP Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Data</fullName>
            </value>
            <value>
                <fullName>Vendor Voice</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An explicit account lookup that should only be used if the order is not opportunity driven.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account-based Orders</relationshipLabel>
    <relationshipName>Account_Based_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Build Location</description>
    <inlineHelpText>Build Location</inlineHelpText>
    <label>Location</label>
    <type>TextArea</type>
</CustomField>

objects/Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>LD</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
            <value>
                <fullName>TF</fullName>
            </value>
            <value>
                <fullName>Traditional Voice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order_Property__c/Order_Property__c.object-meta.xml
<CustomObject>
    <label>Order Property</label>
    <nameField>
        <label>Order Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Order_Property__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Properties</relationshipLabel>
    <relationshipName>Order_Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Order_Property__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Order Properties</relationshipLabel>
    <relationshipName>Order_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Service__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Sub_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Order__r.Account_Link__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/External_Order__c.field-meta.xml
<CustomField>
    <fullName>External_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>External Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>External orders must belong to the same order</errorMessage>
        <filterItems>
            <field>Order_Property__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Order</value>
        </filterItems>
        <filterItems>
            <field>Order_Property__c.Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order_Property__c</referenceTo>
    <relationshipLabel>Sub Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Service_Location__r.Location__r.Name</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order_Group__c/Sub_Order_Group__c.object-meta.xml
<CustomObject>
    <label>Sub-Order Group</label>
    <nameField>
        <label>Sub-Order Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Order Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order_Group__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Sub_Order_Group__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Sub_Order_Group__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Sub-Order Groups</relationshipLabel>
    <relationshipName>Sub_Order_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

classes/Test_CustomerHierarchyController.cls
@isTest
public class Test_CustomerHierarchyController {
    
    static testmethod void testgetCanLoadTree(){
        Test.startTest();
        Mocks Testdata = new Mocks();
        CustomerHierarchyController.TreeViewImplementation inst = new CustomerHierarchyController.TreeViewImplementation(Testdata.parentAccount.Id);
        List<Service_Location__c> sLocs = new List<Service_Location__c>();
        sLocs.add(new Service_Location__c(Account__c = Testdata.parentAccount.Id, Location__c = Testdata.loc.Id));
        insert sLocs;
        System.assertEquals(inst.getCanLoadTree(), true);
        
        for (Integer i = 0; i < 1000; ++i){
            sLocs.add(new Service_Location__c(Account__c = Testdata.parentAccount.Id, Location__c = Testdata.loc.Id));
        }
        upsert sLocs;
        System.assertEquals(inst.getCanLoadTree(), false);
        Test.stopTest();
    }    
    
    static testmethod void testGetIntegrationHierarchiesFromIDs1(){
        Test.startTest();
        Mocks Testdata = new Mocks();            
        Contact c = Testdata.parentAccountContact;
        Testdata.serviceLocation.Customer_Detail__c = Testdata.customerDetail.Id;
        update Testdata.serviceLocation;
        Testdata.parentAccount.Customer_Detail__c = new Customer_Detail__c().Id;
        update Testdata.parentAccount;
        
        CustomerHierarchyController.TreeViewImplementation inst = new CustomerHierarchyController.TreeViewImplementation(Testdata.parentAccount.Id);
        System.assertNotEquals(inst.getNodes(), new List<TreeNode>());
        System.assert(!inst.getNodes().isEmpty());
        
        Testdata.parentAccount.Customer_Detail__c = Testdata.customerDetail.Id;
        update Testdata.parentAccount;
        System.assertNotEquals(inst.getNodes(), new List<TreeNode>());
        System.assert(!inst.getNodes().isEmpty());
               
        Testdata.parentAccount.RecordTypeId = [Select Id from RecordType where Name = 'System' Limit 1].Id;
        update Testdata.parentAccount;
        System.assertEquals(inst.getNodes(), new List<TreeNode>());
        Test.stopTest();
    }
    
    static testmethod void testGetIntegrationHierarchiesFromIDs2(){
        Test.startTest();
        Mocks Testdata = new Mocks();            
        Testdata.parentAccountContact.Default_Responsible_Party__c = true;
        update Testdata.parentAccountContact;
        Testdata.serviceLocation.Customer_Detail__c = Testdata.customerDetail.Id;
        update Testdata.serviceLocation;
        Testdata.parentAccount.Customer_Detail__c = Testdata.customerDetail.Id;
        update Testdata.parentAccount;
        Customer_Contact__c cc = new Customer_Contact__c(Contact__c = Testdata.parentAccountContact.Id, Customer_Detail__c = Testdata.customerDetail.Id, Contact_Type__c = 'ISP');
        insert cc;
        Opportunity op = new Opportunity(Account = Testdata.parentAccount, Name = 'Test', StageName = 'Open', CloseDate = Date.today().addDays(5));
        insert op;
        Order__c order = new Order__c(Account__c = Testdata.parentAccount.Id, Opportunity__c = op.Id);
        insert order;
        Order_Property__c orderProp = new Order_Property__c(Order__c = order.Id, External_ID__c = '1234567');
        insert orderProp;
        Sub_Order__c subOrder = new Sub_Order__c(Order__c = order.Id, Customer_Detail__c = Testdata.customerDetail.Id, Service_Location__c = Testdata.serviceLocation.Id, External_Order__c = orderProp.Id);
        insert subOrder;
        Sub_Order_Group__c subOrderGroup = new Sub_Order_Group__c(Sub_Order__c = subOrder.Id, Quantity__c = 5, Product__c = 'Expensive Product');
        insert subOrderGroup;
        Service__c service = new Service__c(Customer_Detail__c = Testdata.customerDetail.Id, Product_Name__c = 'Prod Name');
        insert service;
        OpportunityContactRole OCR = new OpportunityContactRole(OpportunityId = op.Id, ContactId = Testdata.parentAccountContact.Id);
        insert OCR;
        
        CustomerHierarchyController.TreeViewImplementation inst = new CustomerHierarchyController.TreeViewImplementation(Testdata.parentAccount.Id);
        List<TreeNode> Result = inst.getNodes();
        System.assertNotEquals(result, new List<TreeNode>());
        System.assert(!result.isEmpty());
        Test.stopTest();
    }
    
    static testmethod void testgetContactNodes(){
        Test.startTest();
        Mocks Testdata = new Mocks();
        Customer_Contact__c cc = new Customer_Contact__c(Contact__c = Testdata.parentAccountContact.Id, Contact_Type__c = 'ISP', Customer_Detail__c = Testdata.customerDetail.Id);
        insert cc;
        
        CustomerHierarchyController.getContactNodes(new TreeNode(), new List<Customer_Contact__c>{cc});        
        Test.stopTest();
    }
    
    static testmethod void testgetMoreNodes(){
        Test.startTest();
        Mocks Testdata = new Mocks();
        CustomerHierarchyController.TreeViewImplementation inst = new CustomerHierarchyController.TreeViewImplementation(Testdata.parentAccount.Id);
        inst.getMoreNodes('String');
        Test.stopTest();
    }
    
    static testmethod void testgetActionMap(){
        Test.startTest();
        Mocks Testdata = new Mocks();
        CustomerHierarchyController.TreeViewImplementation inst = new CustomerHierarchyController.TreeViewImplementation(Testdata.parentAccount.Id);
        inst.getActionMap();
        Test.stopTest();
    }
    
    static testmethod void testgetIconMap(){
        Test.startTest();
        Mocks Testdata = new Mocks();
        CustomerHierarchyController.TreeViewImplementation inst = new CustomerHierarchyController.TreeViewImplementation(Testdata.parentAccount.Id);
        inst.getIconMap();
        Test.stopTest();
    }
}