objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Sub_Order__c/fields/External_Products__c.field-meta.xml
<CustomField>
    <fullName>External_Products__c</fullName>
    <label>External Products</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sub_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending Sales</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
            </value>
            <value>
                <fullName>Pending DM</fullName>
            </value>
            <value>
                <fullName>Waiting for Telco</fullName>
            </value>
            <value>
                <fullName>Waiting for Translations</fullName>
            </value>
            <value>
                <fullName>Waiting for Circuit Design</fullName>
            </value>
            <value>
                <fullName>Waiting For - Facilities: ILEC</fullName>
            </value>
            <value>
                <fullName>Waiting For - Task/Stage Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Order_Group__c/Sub_Order_Group__c.object-meta.xml
<CustomObject>
    <label>Sub-Order Group</label>
    <nameField>
        <label>Sub-Order Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Order Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order_Group__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Sub_Order_Group__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activate</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Final Validation</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Order</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Validate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Sub_Order_Group__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Sub-Order Groups</relationshipLabel>
    <relationshipName>Sub_Order_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

classes/SubOrderGroupTriggers.cls
public with sharing class SubOrderGroupTriggers {
	
    public static void SubOrderGroupModified(List<Sub_Order_Group__c> tNew, List<Sub_Order_Group__c> tOld, Boolean isUpdate, Boolean isBefore, Boolean isDelete){
		
    	if(!ApexUtils.executeTriggerMethods('Sub_Order_Group__c', isBefore, isDelete)) return;
		
        if(isBefore){
        }
        else{
        	Map<Id, Sub_Order_Group__c> tOldMap = isUpdate ? new Map<Id, Sub_Order_Group__c>(tOld) : new Map<Id, Sub_Order_Group__c>();
        	updateSubOrderFields(isDelete ? tOld : tNew, tOldMap);
        	
			ApexUtils.afterTriggerComplete('Sub_Order_Group__c', isDelete);
    	}
    }
    
    public static void updateSubOrderFields(List<Sub_Order_Group__c> tNew, Map<Id, Sub_Order_Group__c> tOldMap){
    	
    	Set<Id> updateStatus = new Set<Id>();
    	Set<Id> updateProducts = new Set<Id>();
		
    	for(Sub_Order_Group__c sog : tNew){
    		Sub_Order_Group__c sogOld = tOldMap.get(sog.Id);
			Boolean newOrMoved = (sogOld == null || sog.Sub_Order__c != sogOld.Sub_Order__c);
			getSubOrdersToUpdate(newOrMoved || sog.Status__c != sogOld.Status__c, sog, sogOld, updateStatus);
			getSubOrdersToUpdate(newOrMoved || sog.Product__c != sogOld.Product__c, sog, sogOld, updateProducts);
    	}
		
		if(updateStatus.size() > 0)
    		OrderUtils.refreshOrderStatusesBySubOrderID(updateStatus);
		
		if(updateProducts.size() > 0)
			setSubOrderExternalProducts(updateProducts);
    }
	
	private static void getSubOrdersToUpdate(Boolean updated, Sub_Order_Group__c sog, Sub_Order_Group__c sogOld, Set<Id> out){
		if(updated){
			out.add(sog.Sub_Order__c);
			if(sogOld != null) out.add(sogOld.Sub_Order__c);
		}
	}
    
	private static void setSubOrderExternalProducts(Set<Id> soIDs){
    	List<Sub_Order__c> soUpdates = new List<Sub_Order__c>();
		for(Sub_Order__c so : [select Id, External_Products__c, (select Id, Product__c from Sub_Order_Groups__r) from Sub_Order__c where Id in: soIDs]){
			Set<String> products = new Set<String>();
			for(Sub_Order_Group__c sog : so.Sub_Order_Groups__r != null ? so.Sub_Order_Groups__r : new List<Sub_Order_Group__c>())
				products.add(sog.Product__c);
			
			String productString = String.join(new List<String>(products), '; ');
			if(so.External_Products__c != productString){
				so.External_Products__c = productString;
				soUpdates.add(so);
			}
		}
		
		if(soUpdates.size() > 0) update soUpdates;
    }
}