objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <description>Carrier that we are ordering the facility from for the customer order</description>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>360 Networks</fullName>
            </value>
            <value>
                <fullName>ACS Alaska</fullName>
            </value>
            <value>
                <fullName>AT&amp;T (Cafe)</fullName>
            </value>
            <value>
                <fullName>AT&amp;T (WebLex)</fullName>
            </value>
            <value>
                <fullName>Beanfield (CDA)</fullName>
            </value>
            <value>
                <fullName>Bell/MTS (CDA)</fullName>
            </value>
            <value>
                <fullName>Bell (CDA)</fullName>
            </value>
            <value>
                <fullName>Bell Aliant (CDA)</fullName>
            </value>
            <value>
                <fullName>Bend Broadband</fullName>
            </value>
            <value>
                <fullName>Birch</fullName>
            </value>
            <value>
                <fullName>CenturyLink (EASE)</fullName>
            </value>
            <value>
                <fullName>CenturyLink (IMA)</fullName>
            </value>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Click!</fullName>
            </value>
            <value>
                <fullName>CLINK (Remote Control)</fullName>
            </value>
            <value>
                <fullName>Cologix</fullName>
            </value>
            <value>
                <fullName>Comcast</fullName>
            </value>
            <value>
                <fullName>Consolidated</fullName>
            </value>
            <value>
                <fullName>Coresite</fullName>
            </value>
            <value>
                <fullName>COX</fullName>
            </value>
            <value>
                <fullName>DGEB</fullName>
            </value>
            <value>
                <fullName>East Slope</fullName>
            </value>
            <value>
                <fullName>Enmax owned by Shaw (CDA)</fullName>
            </value>
            <value>
                <fullName>Enventis</fullName>
            </value>
            <value>
                <fullName>Equinix</fullName>
            </value>
            <value>
                <fullName>Fibrenoire owned by Videotron (CDA)</fullName>
            </value>
            <value>
                <fullName>First Digital</fullName>
            </value>
            <value>
                <fullName>Frontier</fullName>
            </value>
            <value>
                <fullName>Inteliquent</fullName>
            </value>
            <value>
                <fullName>Iristel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Workstep_Issue__c/Workstep_Issue__c.object-meta.xml
<CustomObject>
    <label>Workstep Issue</label>
    <nameField>
        <displayFormat>WI-{0000}</displayFormat>
        <label>Workstep Issues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workstep Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Workstep_Issue__c/fields/Current_Action__c.field-meta.xml
<CustomField>
    <fullName>Current_Action__c</fullName>
    <description>Current Action</description>
    <label>Current Action</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Workstep_Issue__c/fields/Estimated_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Resolution__c</fullName>
    <label>Estimated Resolution</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Expected_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Follow_Up_Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <description>Expected Follow Up Date</description>
    <label>Expected Follow Up Date</label>
    <type>DateTime</type>
</CustomField>

objects/Workstep_Issue__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Risk_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Quote</fullName>
            </value>
            <value>
                <fullName>3rd Party Quote Expired</fullName>
            </value>
            <value>
                <fullName>Address Verification Needed</fullName>
            </value>
            <value>
                <fullName>A la Carte Open - Not Ready to Work</fullName>
            </value>
            <value>
                <fullName>ASD - 3rd Party Quote</fullName>
            </value>
            <value>
                <fullName>ASD - Clarification</fullName>
            </value>
            <value>
                <fullName>ASD - ETF</fullName>
            </value>
            <value>
                <fullName>Build (Carrier)</fullName>
            </value>
            <value>
                <fullName>Build (Customer)</fullName>
            </value>
            <value>
                <fullName>Building Construction</fullName>
            </value>
            <value>
                <fullName>Circuit Design</fullName>
            </value>
            <value>
                <fullName>Colo Cabinet Issue</fullName>
            </value>
            <value>
                <fullName>Customer/Vendor Not Ready</fullName>
            </value>
            <value>
                <fullName>Design Review</fullName>
            </value>
            <value>
                <fullName>Engineering Review</fullName>
            </value>
            <value>
                <fullName>Equipment Not Ready</fullName>
            </value>
            <value>
                <fullName>ETF</fullName>
            </value>
            <value>
                <fullName>Facility (Carrier)</fullName>
            </value>
            <value>
                <fullName>Facility (Customer)</fullName>
            </value>
            <value>
                <fullName>Fiber Build</fullName>
            </value>
            <value>
                <fullName>Field Review</fullName>
            </value>
            <value>
                <fullName>Inside Wiring</fullName>
            </value>
            <value>
                <fullName>LEC Order</fullName>
            </value>
            <value>
                <fullName>LEC Workforce</fullName>
            </value>
            <value>
                <fullName>LNP Review (Carrier)</fullName>
            </value>
            <value>
                <fullName>LNP Review (Customer)</fullName>
            </value>
            <value>
                <fullName>LNP Review (Integra)</fullName>
            </value>
            <value>
                <fullName>MOP Required</fullName>
            </value>
            <value>
                <fullName>Network Capacity (Carrier)</fullName>
            </value>
            <value>
                <fullName>Network Capacity (Integra)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Reason_Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Reason_Subcategory__c</fullName>
    <label>Reason Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Address Discrepancies</fullName>
            </value>
            <value>
                <fullName>APOT/CFA</fullName>
            </value>
            <value>
                <fullName>Awaiting Equipment</fullName>
            </value>
            <value>
                <fullName>Await NST Work</fullName>
            </value>
            <value>
                <fullName>BLA</fullName>
            </value>
            <value>
                <fullName>BLA not issued</fullName>
            </value>
            <value>
                <fullName>Capacity - HPBX</fullName>
            </value>
            <value>
                <fullName>Capacity – Issue or Non Existent</fullName>
            </value>
            <value>
                <fullName>Carrier Change</fullName>
            </value>
            <value>
                <fullName>CCD not populated</fullName>
            </value>
            <value>
                <fullName>CFA in use/incorrect</fullName>
            </value>
            <value>
                <fullName>Click scheduling conflict</fullName>
            </value>
            <value>
                <fullName>CLR/GLR Issue</fullName>
            </value>
            <value>
                <fullName>COLO x-connect needed</fullName>
            </value>
            <value>
                <fullName>Comcast NNI</fullName>
            </value>
            <value>
                <fullName>Conditioning</fullName>
            </value>
            <value>
                <fullName>Construction process</fullName>
            </value>
            <value>
                <fullName>CPE</fullName>
            </value>
            <value>
                <fullName>Customer End User Requirements</fullName>
            </value>
            <value>
                <fullName>Customer Implementation Plan</fullName>
            </value>
            <value>
                <fullName>Customer in Contract</fullName>
            </value>
            <value>
                <fullName>Customer un-responsive</fullName>
            </value>
            <value>
                <fullName>Design Template Missing/Incomplete</fullName>
            </value>
            <value>
                <fullName>Distance Does Not Qualify</fullName>
            </value>
            <value>
                <fullName>DMARC information Missing</fullName>
            </value>
            <value>
                <fullName>EELCAP</fullName>
            </value>
            <value>
                <fullName>End User Requirements not met</fullName>
            </value>
            <value>
                <fullName>Engineering Delay</fullName>
            </value>
            <value>
                <fullName>Entrance Facilities/Customer provided</fullName>
            </value>
            <value>
                <fullName>Entrance facilities/LEC provided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep_Issue__c/fields/Risk_Type__c.field-meta.xml
<CustomField>
    <fullName>Risk_Type__c</fullName>
    <label>RespOrg</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Integra</fullName>
                <label>Allstream</label>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <formula>HYPERLINK( 
Workstep__r.Sub_Order__r.Id, 
Workstep__r.Sub_Order__r.Name )</formula>
    <label>Sub-Order</label>
    <type>Text</type>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Workstep__c.field-meta.xml
<CustomField>
    <fullName>Workstep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workstep</label>
    <referenceTo>Workstep__c</referenceTo>
    <relationshipLabel>Workstep Issues</relationshipLabel>
    <relationshipName>Workstep_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/MassBlockManagement.cls
public with sharing class MassBlockManagement implements TestUtils.ITestableClass {

	public String orderId;
	public List<wsiWrapper> wsiWrapperList { get; set; }
	public Workstep_Issue__c dummyWSI { get; set; }
	public boolean sendNotification { get; set; }
	public List<Workstep_Issue__c> iss { get; set; }
	public List<Sub_Order__c> so { get; set; }
	public MassBlockManagement() {
		dummyWSI = new Workstep_Issue__c();
		orderId = ApexPages.currentPage().getParameters().get('id');
		wsiWrapperList = new List<wsiWrapper> ();
		String status = 'Open';
		so = new List<Sub_Order__c> ([Select Id From Sub_Order__c Where Order__c = :orderId]);
		sObjectType objType = Workstep_Issue__c.getsObjectType();

		iss = [Select Workstep__r.Sub_Order__r.Name, Workstep__r.Name, Name, Risk_Type__c, Reason__c, Reason_Subcategory__c,
		       Expected_Follow_Up_Date__c, Estimated_Resolution__c, Current_Action__c, Carrier__c, Owner.Name, OwnerId
		       FROM Workstep_Issue__c Where Workstep__r.Sub_Order__c IN :so AND Status__c = :'Open'];
		for (Workstep_Issue__c wsi : iss) {
			wsiWrapperList.add(new wsiWrapper(wsi, false));
		}
	}

	public PageReference Save() {
		return SaveAction(new PageReference('/' + orderId));
	}

	public PageReference Cancel() {
		return new PageReference('/' + orderId);
	}

	public PageReference QuickSave() {
		PageReference pageReference = Page.MassBlockManagement;
		pageReference.getParameters().put('Id', orderId);
		pageReference.setRedirect(true);
		return SaveAction(PageReference);
	}

	public PageReference ExitSave() {
		return SaveAction(new PageReference('/' + orderId));
	}

	private final Set<String> modifiableFields = new Set<String> { 'Risk_Type__c'
		, 'Reason__c'
		, 'Reason_Subcategory__c'
		, 'Expected_Follow_Up_Date__c'
		, 'Estimated_Resolution__c'
		, 'Current_Action__c'
		, 'OwnerId' };
	public PageReference SaveAction(PageReference pageRef) {
		Boolean anyChecked = false;
		sendNotification = false;
		try {
			List<String> errors = new List<String> ();

			for (wsiWrapper wss : wsiWrapperList) {
				if (wss.isSelected)
				anyChecked = true;
			}
			if (!anyChecked)
			errors.add('Please check at least 1 checkbox to perform updates on!');
			if (errors.size() > 0) {
				system.debug('errors: ' + errors);
				for (String error : errors)
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, error));
				return null;
			}

		}
		catch(DMLException e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, e.getMessage()));
			return null;
		}
		List<Workstep_Issue__c> wsiForUpdate = new List<Workstep_Issue__c> ();
		List<Workstep_Issue__c> sWSI = new List<Workstep_Issue__c> ();
		Map<Id, Workstep_Issue__c> wsiDummyMap = new Map<Id, Workstep_Issue__c> ();
		Set<Id> emailIds = new Set<Id> ();
		for (wsiWrapper wsis : wsiWrapperList) {
			Boolean updated = false;
			for (String f : modifiableFields) {
				if (wsis.isSelected) {
					updated = updated || wsis.wsi.get(f) != wsis.wsiOld.get(f);
					if (f == 'OwnerId' && wsis.wsi.get(f) != wsis.wsiOld.get(f) && sendNotification) {
						emailIds.add(wsis.wsi.OwnerId);
					}
				}
			}
			if (updated) {
				wsis.isSelected = false;
				wsiForUpdate.add(wsis.wsi);
			}
			else {
				if (wsis.isSelected) {
					wsis.isSelected = false;
					sWSI.add(wsis.wsi);
				}
				if (sWSI.size() > 0) {
					for (Workstep_Issue__c work : sWSI) {
						Workstep_Issue__c tWSI = wsiDummyMap.get(work.Id);
						if (tWSI == null) {
							work.Risk_Type__c = dummyWSI.Risk_Type__c != null ? dummyWSI.Risk_Type__c : work.Risk_Type__c;
							work.Carrier__c = dummyWSI.Carrier__c != null ? dummyWSI.Carrier__c : work.Carrier__c;
							work.Reason__c = dummyWSI.Reason__c != null ? dummyWSI.Reason__c : work.Reason__c;
							work.Reason_Subcategory__c = dummyWSI.Reason_Subcategory__c != null ? dummyWSI.Reason_Subcategory__c : work.Reason_Subcategory__c;
							work.Expected_Follow_Up_Date__c = dummyWSI.Expected_Follow_Up_Date__c != null ? dummyWSI.Expected_Follow_Up_Date__c : work.Expected_Follow_Up_Date__c;
							work.Estimated_Resolution__c = dummyWSI.Estimated_Resolution__c != null ? dummyWSI.Estimated_Resolution__c : work.Estimated_Resolution__c;
							work.OwnerId = dummyWSI.OwnerId != null ? dummyWSI.OwnerId : work.OwnerId;
							work.Current_Action__c = dummyWSI.Current_Action__c != null ? work.Current_Action__c != null ? dummyWSI.Current_Action__c + '\n' + work.Current_Action__c : dummyWSI.Current_Action__c : work.Current_Action__c;
							wsiDummyMap.put(work.Id, work);

							if (work.OwnerId != dummyWSI.OwnerId && sendNotification)
							emailIds.add(dummyWSI.OwnerId);
						}
					}

				}
			}

		}
		try {
			for (Workstep_Issue__c wI : wsiDummyMap.values()) {
				wsiForUpdate.add(wI);
			}

			update wsiForUpdate;
		}
		catch(Exception e) {
			return null;
		}
		if (emailIds.size() > 0)
		getEmail(emailIds, wsiForUpdate);

		return pageRef;
	}

	public class wsiWrapper extends ApexUtils.SortableClass {
		public Workstep_Issue__c wsi { get; set; }
		public Workstep_Issue__c wsiOld { get; set; }
		public boolean isSelected { get; set; }

		public wsiWrapper(Workstep_Issue__c wsi, boolean isSelected) {
			this.wsi = wsi;
			this.wsiOld = wsi.clone();
			this.isSelected = isSelected;
		}
	}

	private void getEmail(Set<Id> eml, List<Workstep_Issue__c> wsiForUpdate) {
		List<Messaging.SingleEmailMessage> listmail = new List<Messaging.SingleEmailMessage> ();
		List<User> wsUsers = [SELECT Id, Email, IsActive FROM User WHERE Id IN :eml];
		List<Workstep_Issue__c> emailToSend = [SELECT Id, OwnerId FROM Workstep_Issue__c WHERE Id IN :wsiForUpdate];
		for (Workstep_Issue__c ets : emailToSend) {
			String objName = SchemaUtils.GetSObjectNameByID(ets.Id);
			String emailBody = (objName == 'Workstep__c')
			? 'Workstep has been assigned to you. Please click on the link below to view the record. \n\n'
			: 'Workstep Issue has been created. Please click on the link below to view the record. \n\n';
			emailBody += URL.getSalesforceBaseUrl().toExternalForm() + '/' + ets.Id + '\n\n';
			String objOwn = SchemaUtils.GetSObjectNameByID(ets.OwnerId);
			if (objOwn == 'User') {
				for (User u : wsUsers) {
					if (u.Id == ets.OwnerId) {
						Messaging.SingleEmailMessage m = ApexUtils.createEmailMessage(new String[] { u.Email }
						                                                              , null
						                                                              , (objName == 'Workstep__c') ? 'Workstep assigned to you.' : 'Workstep Issue has been created.'
						                                                              , emailBody
						                                                              , false
						                                                              , UserInfo.getUserEmail());

						listmail.add(m);
					}
				}
			}
		}
		if (!Test.isRunningTest())
			ApexUtils.sendEmails(listmail);
	}

	public String sortColumn { get; set; }
	private String sortOrder = 'Sub_Order__c ASC';
	public List<Workstep_Issue__c> wIss = new List<Workstep_Issue__c> ();
	private Boolean ordinal = true;
	public void sortResults() {
		if (this.sortOrder != sortColumn + ' ASC') {
			this.sortOrder = sortColumn + ' ASC';
		}
		else {
			this.sortOrder = sortColumn + ' DESC';
			ordinal = false;
		}
		List<Id> sid = new List<Id> ();
		for (Sub_Order__c soi : so) {
			sid.add(soi.Id);
		}

		String query = 'Select Workstep__r.Sub_Order__r.Name, Workstep__r.Name, Name, Risk_Type__c, Reason__c, Reason_Subcategory__c, ' +
		'Expected_Follow_Up_Date__c, Estimated_Resolution__c, Current_Action__c, Carrier__c, Owner.Name, OwnerId ' +
		'FROM Workstep_Issue__c ' +
		'Where Workstep__r.Sub_Order__c IN: sid  AND Status__c = \'Open\' ' +
		'Order By ' + this.sortOrder;
		wIss = database.query(query);
		wsiWrapperList.clear();
		for (Workstep_Issue__c works : wIss) {
			wsiWrapperList.add(new wsiWrapper(works, false));
		}
	}

	/* TestUtils.ITestableClass methods */
	public TestUtils.TestClass getTestClass() { return new Test_MassBlockManagement(); }
}