main/default/objects/DiscountAuthorityLevels__c/DiscountAuthorityLevels__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Percentage values allowed by persons of the level, to adjust the MRC / NRC towards the floor of respective values. Value -1 levels are exempt from floor pricing</description>
    <label>Discount Authority Levels</label>
</CustomObject>

main/default/objects/DiscountAuthorityLevels__c/fields/Allowed_Level_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Level_Percentage__c</fullName>
    <label>Allowed Level Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

objects/DiscountAuthorityLevels__c/fields/IsApprovalLevel__c.field-meta.xml
<CustomField>
    <fullName>IsApprovalLevel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsApprovalLevel</label>
    <type>Checkbox</type>
</CustomField>

objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OLI__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean value to be used for validation of approval</description>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/OLI__c/fields/Off_Footprint__c.field-meta.xml
<CustomField>
    <fullName>Off_Footprint__c</fullName>
    <formula>(( 
CONTAINS(PP_Feature_Group__c , &#39;Access/Bandwidth&#39;) 
&amp;&amp; 
CONTAINS( PP_Sales_Rate_Plan_Description__c , &#39;Extended&#39;) 
) 
|| 
( 
CONTAINS(PP_Feature_Group__c , &#39;Access/Bandwidth&#39;) 
&amp;&amp; 
CONTAINS( PP_Sales_Rate_Plan_Description__c , &#39;EoTDM&#39;) 
&amp;&amp; 
NOT(OpportunityLocationConfiguration__r.Opportunity_Location__r.Service_Location__r.Location__r.Building__r.Serving_LSO__r.In_Market__c ) 
)) 
&amp;&amp; 
( 
TEXT( OpportunityLocationConfiguration__r.Opportunity_Location__r.Opportunity__r.Account.Type) == &#39;Prospect&#39; 
||
TEXT( OpportunityLocationConfiguration__r.Opportunity_Location__r.Opportunity__r.Account.Type) == &#39;Former Customer&#39; 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Off Footprint</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/OLI__c/fields/Off_Footprint_Approved__c.field-meta.xml
<CustomField>
    <fullName>Off_Footprint_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Off Footprint Approved</label>
    <type>Checkbox</type>
</CustomField>

objects/OLI__c/fields/OpportunityLocationConfiguration__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLocationConfiguration__c</fullName>
    <label>OpportunityLocationConfiguration</label>
    <referenceTo>OpportunityLocationConfiguration__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/OpportunityLocationConfiguration__c/OpportunityLocationConfiguration__c.object-meta.xml
<CustomObject>
    <description>A configuration for an OpportunityLocation.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OpportunityLocationConfiguration__c/fields/Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Date__c</fullName>
    <description>Date Approval was granted</description>
    <label>Approval_Date</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/OpportunityLocationConfiguration__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Solutions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/SolutionApprovalUtils.cls
public class SolutionApprovalUtils implements TestUtils.ITestableClass{

	private static Map<Id,DiscountAuthorityLevels__c> approvalLevels = null;

	public static DiscountAuthorityLevels__c getApprovalLevel(Id UserId) {
        //load property with user instance
		if(approvalLevels == null) approvalLevels = new Map<Id,DiscountAuthorityLevels__c>();
		if(!approvalLevels.containsKey(UserId)){
			String userlvl = string.valueOf([SELECT Discount_Level_Authority__c FROM User WHERE Id =: UserId].Discount_Level_Authority__c);
			approvalLevels.put(UserId,!String.IsEmpty(userlvl)? DiscountAuthorityLevels__c.getInstance(userlvl) : new DiscountAuthorityLevels__c(Allowed_Level_Percentage__c=100,IsApprovalLevel__c=false,Name='Sales Rep'));
		}
        return approvalLevels.get(UserId);
    }

	public static void ApproveSoluitonFromOLIs(List<OLI__c> olis){
		//need to find one's that need updating so can set approver/date on opportunityLocationConfiguration
		Set<Id> olc = new Set<Id>();
		for(OLI__c oli : olis){
			olc.add(oli.OpportunityLocationConfiguration__c);
			oli.Approved__c = true;
			oli.Off_Footprint_Approved__c = oli.Off_Footprint__c && true;
		}
		
		update olis;
		
		List<OpportunityLocationConfiguration__c> listOLCs =  new List<OpportunityLocationConfiguration__c>();
		for(OpportunityLocationConfiguration__c oppLC : [Select Approval_Date__c, Approver__c From  OpportunityLocationConfiguration__c  Where Id In : olc]){
			oppLC.Approval_Date__c = System.today().format();
			oppLC.Approver__c = UserInfo.getUserId();
			listOLCs.add(oppLC);
		}
		
		update listOLCs;
	}

	public static void RequestApprovals(Id oppId){
		Opportunity opp = [select Id, Owner.Sales_Channel__c, Owner.ManagerId from Opportunity where Id = :oppId];
		Id sendToId = opp.Owner.Sales_Channel__c == 'Indirect Sales'? GetIndirectSalesManagerId():opp.Owner.ManagerId;
		Messaging.SingleEmailMessage email = ApexUtils.createTemplatedEmailMessage(sendToId, GetApprovalRequestTemplateId(), oppId);
		ApexUtils.sendEmails(new List<Messaging.SingleEmailMessage>{email});
	}

	private static Id IndirectSalesManagerId = null;
	public static Id GetIndirectSalesManagerId(){
		if(IndirectSalesManagerId == null){
			string ntid = CustomSettingUtils.getSingleProcessConfigurationValue('ApprovalProcess','Indirect',false);
			IndirectSalesManagerId = [select Id from User where NTID__c = :ntid limit 1].Id;
		}
		return IndirectSalesManagerId;
	}

	private static Id ApprovalRequestTemplateId = null;
	public static Id GetApprovalRequestTemplateId(){
		if(ApprovalRequestTemplateId == null){
			ApprovalRequestTemplateId = [Select Id from EmailTemplate where DeveloperName = 'Solution_Approval_Request' limit 1].Id;
		}
		return ApprovalRequestTemplateId;
	}

	private static Decimal SMCompetitiveBuildingDiscount = null;
	public static Decimal GetSMCompetitiveBuildingDiscount(){
		if(SMCompetitiveBuildingDiscount == null){
			string decimalValue = CustomSettingUtils.getSingleProcessConfigurationValue('CompetitiveBuildingDiscount', 'Discount', false);
			SMCompetitiveBuildingDiscount = string.isEmpty(decimalValue)? 0.0d : decimal.ValueOf(decimalValue);
		}
		return SMCompetitiveBuildingDiscount;
	}

	public TestUtils.TestClass getTestClass(){ return new Test_SolutionApprovalUtils(); }
}