main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

main/default/objects/Project__c/fields/Project_Issues_Overall_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Issues_Overall_Status__c</fullName>
    <description>Combined status of Project Issues Magnitude field for all Project Issues associated with this project.</description>
    <inlineHelpText>Combined status of Project Issues Magnitude field for all Project Issues associated with this project.</inlineHelpText>
    <label>Issues</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <color>#009900</color>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
                <color>#FFCC33</color>
                <label>Yellow</label>
            </value>
            <value>
                <fullName>Red</fullName>
                <color>#CC0000</color>
                <label>Red</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the project</description>
    <inlineHelpText>Status of the project</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Project_Issue__c/Project_Issue__c.object-meta.xml
<CustomObject>
    <label>Project Issue</label>
    <nameField>
        <label>Project Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Issue__c/fields/Magnitude__c.field-meta.xml
<CustomField>
    <fullName>Magnitude__c</fullName>
    <inlineHelpText>What is the magnitude of this issue?  Select &quot;High&quot; if it is a show-stopper.  Select &quot;Medium&quot; if it is an issue, but a work around exists.  Select &quot;Low&quot; if it is a nice-to-have.</inlineHelpText>
    <label>Magnitude</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Project_Issue__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Issues</relationshipLabel>
    <relationshipName>Project_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Project_Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Identified</fullName>
                <default>true</default>
                <label>Identified</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/ProjectRelatedTriggers.cls
public with sharing class ProjectRelatedTriggers {
	public static final String magnitudeHigh = 'High';
	public static final String magnitudeMedium = 'Medium';
	public static final String magnitudeLow = 'Low';
	
	public static final String statusRed = 'Red';
	public static final String statusYellow = 'Yellow';
	public static final String statusGreen = 'Green';
	
	public static void ProjectIssueModified(Map<Id, Project_Issue__c> tNew, Map<Id, Project_Issue__c> tOld, Boolean isUpdate, Boolean isBefore){
		
    	if(!ApexUtils.executeTriggerMethods('Project_Issue__c', isBefore, false)) return;
    	
		if(!isBefore){
			UpdateCombinedIssuesStatus(tNew);
			
			ApexUtils.afterTriggerComplete('Project_Issue__c', false);
		}
    }

	public static void UpdateCombinedIssuesStatus(Map<Id, Project_Issue__c> newSol){
		
		Set<Id> projectIDs = new Set<Id>();
		for(Project_Issue__c pi : newSol.values()){
			if(pi.Project__c != null)
				projectIDs.add(pi.Project__c);
		}
		
		if(projectIDs.size() > 0){
	        List<Project__c> projectList = new List<Project__c>();
			for(Project__c proj : [select Id
										,Project_Issues_Overall_Status__c
										,(select Magnitude__c, Status__c from Project_Issues__r)
										from Project__c Where id in :projectIDs]){
				Set<String> magnitudes = new Set<String>();
				if(proj.Project_Issues__r != null){
					for(Project_Issue__c Issue : proj.Project_Issues__r){
						if((Issue.Magnitude__c == magnitudeHigh || Issue.Magnitude__c == magnitudeMedium) && Issue.Status__c != 'Resolved'){
							magnitudes.add(Issue.Magnitude__c);
						}
						else {
							magnitudes.add(magnitudeLow);
						}
					}
				}
				
				proj.Project_Issues_Overall_Status__c = (magnitudes.contains(magnitudeHigh)
															? statusRed
															: (magnitudes.contains(magnitudeMedium)
																? statusYellow
																: statusGreen));
				projectList.add(proj);
			}
			if(projectList.size() > 0)
				update projectList;
		}
		
	}
}