main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <description>The user name of the resource working on the project</description>
    <label>Project Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Project Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Project_Resource__c/fields/Actual_Hours__c.field-meta.xml
<CustomField>
    <fullName>Actual_Hours__c</fullName>
    <label>Actual Hours</label>
    <summarizedField>Project_Resource_Hours__c.Actual_Hours__c</summarizedField>
    <summaryForeignKey>Project_Resource_Hours__c.Resource__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Project_Resource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Project_Resource__c/fields/Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Business Process Analyst</fullName>
            </value>
            <value>
                <fullName>Core Team Member</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Infra Oracle DBA</fullName>
            </value>
            <value>
                <fullName>Infra SQL DBA</fullName>
            </value>
            <value>
                <fullName>Infra Unix</fullName>
            </value>
            <value>
                <fullName>Infra Windows</fullName>
            </value>
            <value>
                <fullName>IT Analyst</fullName>
            </value>
            <value>
                <fullName>IT Architect</fullName>
            </value>
            <value>
                <fullName>IT BI</fullName>
            </value>
            <value>
                <fullName>IT Developer</fullName>
            </value>
            <value>
                <fullName>IT Manager</fullName>
            </value>
            <value>
                <fullName>Project Leader</fullName>
            </value>
            <value>
                <fullName>QA Analyst</fullName>
            </value>
            <value>
                <fullName>Salesforce Admin</fullName>
            </value>
            <value>
                <fullName>Solution Manager</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Project_Resource__c/fields/Resource_User__c.field-meta.xml
<CustomField>
    <fullName>Resource_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User name of the resource.</description>
    <label>Resource User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Project_Resource_Hours__c/Project_Resource_Hours__c.object-meta.xml
<CustomObject>
    <label>Project Resource Hours</label>
    <nameField>
        <displayFormat>RH-{0000}</displayFormat>
        <label>Resource Hour Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resource Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Project_Resource_Hours__c/fields/Actual_Hours__c.field-meta.xml
<CustomField>
    <fullName>Actual_Hours__c</fullName>
    <label>Actual Hours</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Project_Resource_Hours__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Project_Resource__c</referenceTo>
    <relationshipLabel>Project Resource Hours</relationshipLabel>
    <relationshipName>Resource_Hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Project_Resource_Hours__c/fields/Resource_Week__c.field-meta.xml
<CustomField>
    <fullName>Resource_Week__c</fullName>
    <description>The week the hours were worked</description>
    <label>Resource Week</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

classes/Test_Hours.cls
@isTest
public with sharing class Test_Hours extends TestUtils.TestClass{
	
	static testMethod void testController(){
        Mocks testData = new Mocks();
		
		User u = testData.user;
		
		Project__c p = new Project__c(Name='World Peace');
		insert p;
		
		Project_Resource__c pr = new Project_Resource__c(Project__c=p.Id, Resource_User__c=u.Id, Resource_Role__c='A Somebody');
		insert pr;
		
		Project_Resource_Hours__c prh = new Project_Resource_Hours__c(Resource__c=pr.Id, Actual_Hours__c=0, Resource_Week__c=Date.today());
		insert prh;
		
    	test.startTest();
    	
		PageReference pageReference = Page.Hours;
		pageReference.getParameters().put('ntids', testData.user.NTID__c);
		test.setCurrentPage(pageReference);
		
		HoursController hc = new HoursController();
		hc.selectedProjectOption = 'All projects';
		hc.getUserResources();
		
		hc.saveChanges();
		
		System.debug(hc.projectViewOptions);
		System.debug(hc.projectSelectionOptions);
		System.debug(hc.getTestClass());
		
		test.stopTest();
	}
	
	static testMethod void testSchedule_ProjectHoursOverdue(){
        Mocks testData = new Mocks();
		
		User u = testData.user;
		u.Project_Hours_Manager__c = true;
		update u;
		
		test.startTest();
		
		Schedule_ProjectHoursOverdue.alertUsersWithoutWeeklyHoursSet();
	}
}