main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

main/default/objects/Project_Issue__c/Project_Issue__c.object-meta.xml
<CustomObject>
    <label>Project Issue</label>
    <nameField>
        <label>Project Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Issue__c/fields/Magnitude__c.field-meta.xml
<CustomField>
    <fullName>Magnitude__c</fullName>
    <inlineHelpText>What is the magnitude of this issue?  Select &quot;High&quot; if it is a show-stopper.  Select &quot;Medium&quot; if it is an issue, but a work around exists.  Select &quot;Low&quot; if it is a nice-to-have.</inlineHelpText>
    <label>Magnitude</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Project_Issue__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Issues</relationshipLabel>
    <relationshipName>Project_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/Test_ProjectRelatedTriggers.cls
@isTest
public with sharing class Test_ProjectRelatedTriggers {
	
    static testMethod void ProjectIssueModified() {
    	ProjectRelatedTriggers prt = new ProjectRelatedTriggers();
    	test.startTest();
    	Project__c p = new Project__c();
    	insert p;


    	Project_Issue__c pi = new Project_Issue__c(Magnitude__c = ProjectRelatedTriggers.magnitudeHigh, Project__c = p.Id);
    	insert pi;
    	Map<Id, Project_Issue__c> mpi = new Map<Id, Project_Issue__c>();
    	for(Project_Issue__c proj : [Select Id, Magnitude__c, Name, Project__c From Project_Issue__c where Project__c =: p.Id Limit 1]){
    		mpi.put(proj.Id, proj);
    	}
		ProjectRelatedTriggers.UpdateCombinedIssuesStatus(mpi);
    	test.stopTest();
    }
    
    static testmethod void UpdateCombinedIssuesStatusTest(){
    	test.startTest();

    	Map<Id, Project_Issue__c> mpi = new Map<Id, Project_Issue__c>();
    	for(Project_Issue__c proj : [Select Id, Magnitude__c, Name, Project__c From Project_Issue__c  Limit 1]){
    		mpi.put(proj.Id, proj);
    	}
    	
    	test.stopTest();
    
    }
}