objects/ACR_DOA_Approval_Mapping__mdt/ACR_DOA_Approval_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Used in Mapping in batch apex for DOA processing</description>
    <label>ACR_DOA_Approval_Mapping</label>
    <pluralLabel>ACR_DOA_Approval_Mapping</pluralLabel>
</CustomObject>

objects/ACR_DOA_Approval_Mapping__mdt/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <inlineHelpText>This should be the API Name of the DOA Mapping field.</inlineHelpText>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Approval_Matrix__c/Approval_Matrix__c.object-meta.xml
<CustomObject>
    <description>[Perficient, Scott Roose, 03/11/2019]  This object was created as part of the project to move the .NET app iApproval into Salesforce.</description>
    <label>Approval Matrix</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Approval Matrix Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Approval_Matrix__c/fields/DOA_Matched_Job_Title__c.field-meta.xml
<CustomField>
    <fullName>DOA_Matched_Job_Title__c</fullName>
    <inlineHelpText>This is the job title that matched between the User and the DOA Mapping object at the last run of the batch job</inlineHelpText>
    <label>DOA Matched Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Approval_Matrix__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Approval_Matrix__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>User ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/DOA_Mapping__c/DOA_Mapping__c.object-meta.xml
<CustomObject>
    <description>[Perficient, Scott Roose, 03/12/2019] This object was created as part of the project to move the .NET app iApproval into Salesforce.</description>
    <label>DOA Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>DOA Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOA Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DOA_Mapping__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

classes/ACR_DOAProcessingBatch.cls
/***********************************************************************************************************
* Name       : ACR_DOAProcessingBatch
* Purpose    : Creating Approval Matrix record and Triggering email
************************************************************************************************************
* Author                 | Version    | Created Date    | Description
************************************************************************************************************
* Satya                  | 1.0        | 19/03/2019      | Initial version
* Santoshi - Added upsert logic. Changed the select queries for DOA and few other clean up.
* Santoshi - Modified error handling codes.
***********************************************************************************************************/

global class ACR_DOAProcessingBatch implements Database.Batchable<sObject> {
    
    String QUERY = 'Select Id, Name,Title,Title_Not_Found_in_DOA__c FROM USER WHERE Excludes_From_Batch_Processing__c=False AND Ready_For_DOA_Processing__c=True ';
    
    public ACR_DOAProcessingBatch(){
        
    }
    public ACR_DOAProcessingBatch(String UserId){
        QUERY = 'Select Id, Name,Title,Title_Not_Found_in_DOA__c FROM USER WHERE Id = \''+UserId+'\'';
        
    }
    // Start method for batch class
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(QUERY) ;
    }
    
    //Execute method for batch class
    global void execute(Database.BatchableContext BC, List<User> retriveUser) {
        
        try{
            //Fetching DOA mappings
            ACR_DomainLayer.QueryEditor jobTitleQueryEditor = new ACR_DomainLayer.QueryEditor('DOA_Mapping__c',' ','SELECT');
            List<DOA_Mapping__c> jobTitle = (List<DOA_Mapping__c>) jobTitleQueryEditor.ResultSet;  
            ACR_DomainLayer.QueryEditor CustomMetadaRecords = new ACR_DomainLayer.QueryEditor('ACR_DOA_Approval_Mapping__mdt',' ','SELECT','Source_Field__c,Target_Field__c ');
            List<ACR_DOA_Approval_Mapping__mdt> metadataRecords = (List<ACR_DOA_Approval_Mapping__mdt>) CustomMetadaRecords.ResultSet;     
            Map<String,String> srcVsdest = new Map<String,String>();
            //Storing the Source and Target values in Map
            for(ACR_DOA_Approval_Mapping__mdt mapping : metadataRecords){
                srcVsdest.put((String)mapping.get('Source_Field__c'), (String)mapping.get('Target_Field__c'));
            }     
            Map<Id,User> titleNotFoundUsers= new Map<Id,User>();
            List<Approval_Matrix__c> newApprovalMatrix=new List<Approval_Matrix__c>();
            
            //Creating Approval Matrix Record if JobTitle matches 
            for(User user:retriveUser)
            {
                for(DOA_Mapping__c doa:jobTitle)
                {
                    if(user.Title == doa.Job_Title__c)
                    {
                        user.Title_Not_Found_in_DOA__c=false;
                        titleNotFoundUsers.remove(user.Id);
                        Approval_Matrix__c approvalMatrix= new Approval_Matrix__c();  
                        approvalMatrix.DOA_Matched_Job_Title__c=doa.Job_Title__c;
                        approvalMatrix.Employee__c = user.Id;
                        approvalMatrix.User_Id__c = user.Id;
                        for(String src : srcVsdest.keyset()){
                            approvalMatrix.put(srcVsdest.get(src),doa.get(src));
                        }
                        newApprovalMatrix.add(approvalMatrix); 
                        break;
                    }
                    //Updates two checkbox fields in User if title doesn't match
                    else
                    {
                        user.Title_Not_Found_in_DOA__c = True;
                        user.Ready_For_DOA_Processing__c = False;
                        titleNotFoundUsers.put(user.Id,user);                    
                    }
                }
            } 
            //Upserts the Approval Matrix Record
            Schema.SObjectField externalField = Approval_Matrix__c.Fields.User_Id__c;
            Database.UpsertResult [] UpsertResult = Database.upsert(newApprovalMatrix,externalField, false);
            List<Id> userId=new List<Id>();
            String concatenatedObjId;
            String fuctionalityName;
            String errorCode;
            String operation;
            //Fetching User Id's of successfully created record
            for(Integer index = 0, size = UpsertResult.size(); index < size; index++) {      
                if(UpsertResult[index].isSuccess()) {
                        Id approvalUserId=newApprovalMatrix[index].User_Id__c;
                        userId.add(approvalUserId); 	  
                }
                else if(UpsertResult[index].getErrors().size() > 0){
                    for(Database.Error err : UpsertResult[index].getErrors())
                    {
                        concatenatedObjId=UpsertResult[index].getId()+',';
                        errorCode=err.getMessage();
                    }
                }
            }
            if(!String.isBlank(concatenatedObjId)){
                fuctionalityName=ACR_ConstantDeclarations.HR_ERROR_FUNCTIONALITY_NAME;
                concatenatedObjId.removeEnd(',');
                operation = ACR_ConstantDeclarations.OPERATION_NAME_BATCH_UPSERT;
                ACR_DomainLayer.PRFT_Error errorLog = new ACR_DomainLayer.PRFT_Error(fuctionalityName,concatenatedObjId,errorCode,operation); 
            }
            //Fetches Users who belongs to that record
            List<User> lstUsersToBeUpdate= new List<User>(); 
            //Updates Ready_For_DOA_Processing__c as False for the users
            for( Id id : userId)
            {
                User user=new User(Id=id,Ready_For_DOA_Processing__c=False);
                lstUsersToBeUpdate.add(user);
            }update lstUsersToBeUpdate;
            Database.SaveResult [] updateResult = Database.update(titleNotFoundUsers.values(), false);           
            if(Test.isRunningTest())
            {
                NullPointerException throwError = new NullPointerException();
                throwError.setMessage('This is a constructed exception!');
                throw throwError;
            }   
        }
        // Catching the Exception
        catch(Exception ex){
            String fuctionalityName=ACR_ConstantDeclarations.HR_ERROR_FUNCTIONALITY_NAME;
            String stackTrace= ex.getStackTraceString();           
            String errorCode= ex.getTypeName();
            ACR_DomainLayer.PRFT_Error errorLog = new ACR_DomainLayer.PRFT_Error(fuctionalityName,stackTrace,errorCode,ACR_ConstantDeclarations.OPERATION_NAME_BATCH_UPSERT );
        } 
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}