main/default/objects/Issue_to_Queue_Mapping__c/Issue_to_Queue_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom object identifies the Issue Type, Reason and Sub-Category to the queue to which it should be assigned.</description>
    <label>Issue to Queue Mapping</label>
</CustomObject>

objects/Issue_to_Queue_Mapping__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <label>Issue Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Issue_to_Queue_Mapping__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Issue_to_Queue_Mapping__c/fields/Reason_Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Reason_Subcategory__c</fullName>
    <label>Reason Subcategory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Sub_Order__c/fields/Has_Blocked_Workstep__c.field-meta.xml
<CustomField>
    <fullName>Has_Blocked_Workstep__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the suborder has any blocked worksteps</description>
    <label>Has Blocked Workstep</label>
    <type>Checkbox</type>
</CustomField>

objects/Sub_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending Sales</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
            </value>
            <value>
                <fullName>Pending DM</fullName>
            </value>
            <value>
                <fullName>Waiting for Telco</fullName>
            </value>
            <value>
                <fullName>Waiting for Translations</fullName>
            </value>
            <value>
                <fullName>Waiting for Circuit Design</fullName>
            </value>
            <value>
                <fullName>Waiting For - Facilities: ILEC</fullName>
            </value>
            <value>
                <fullName>Waiting For - Task/Stage Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep__c/fields/BlockedPendingValidationByCode__c.field-meta.xml
<CustomField>
    <fullName>BlockedPendingValidationByCode__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BlockedPendingValidationByCode</label>
    <type>Checkbox</type>
</CustomField>

objects/Workstep__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

objects/Workstep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Workstep__c/fields/Unblocked_Date__c.field-meta.xml
<CustomField>
    <fullName>Unblocked_Date__c</fullName>
    <description>This date is added when a workstep issue is resolved to show the latest unblocked date.</description>
    <label>Unblocked Date</label>
    <type>Date</type>
</CustomField>

objects/Workstep_Issue__c/Workstep_Issue__c.object-meta.xml
<CustomObject>
    <label>Workstep Issue</label>
    <nameField>
        <displayFormat>WI-{0000}</displayFormat>
        <label>Workstep Issues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workstep Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep_Issue__c/fields/Caused_By__c.field-meta.xml
<CustomField>
    <fullName>Caused_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caused By</label>
    <referenceTo>Workstep__c</referenceTo>
    <relationshipLabel>Caused By (Workstep Issues)</relationshipLabel>
    <relationshipName>CausedBy</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Workstep_Issue__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Risk_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Quote</fullName>
            </value>
            <value>
                <fullName>3rd Party Quote Expired</fullName>
            </value>
            <value>
                <fullName>Address Verification Needed</fullName>
            </value>
            <value>
                <fullName>A la Carte Open - Not Ready to Work</fullName>
            </value>
            <value>
                <fullName>ASD - 3rd Party Quote</fullName>
            </value>
            <value>
                <fullName>ASD - Clarification</fullName>
            </value>
            <value>
                <fullName>ASD - ETF</fullName>
            </value>
            <value>
                <fullName>Build (Carrier)</fullName>
            </value>
            <value>
                <fullName>Build (Customer)</fullName>
            </value>
            <value>
                <fullName>Building Construction</fullName>
            </value>
            <value>
                <fullName>Circuit Design</fullName>
            </value>
            <value>
                <fullName>Colo Cabinet Issue</fullName>
            </value>
            <value>
                <fullName>Customer/Vendor Not Ready</fullName>
            </value>
            <value>
                <fullName>Design Review</fullName>
            </value>
            <value>
                <fullName>Engineering Review</fullName>
            </value>
            <value>
                <fullName>Equipment Not Ready</fullName>
            </value>
            <value>
                <fullName>ETF</fullName>
            </value>
            <value>
                <fullName>Facility (Carrier)</fullName>
            </value>
            <value>
                <fullName>Facility (Customer)</fullName>
            </value>
            <value>
                <fullName>Fiber Build</fullName>
            </value>
            <value>
                <fullName>Field Review</fullName>
            </value>
            <value>
                <fullName>Inside Wiring</fullName>
            </value>
            <value>
                <fullName>LEC Order</fullName>
            </value>
            <value>
                <fullName>LEC Workforce</fullName>
            </value>
            <value>
                <fullName>LNP Review (Carrier)</fullName>
            </value>
            <value>
                <fullName>LNP Review (Customer)</fullName>
            </value>
            <value>
                <fullName>LNP Review (Integra)</fullName>
            </value>
            <value>
                <fullName>MOP Required</fullName>
            </value>
            <value>
                <fullName>Network Capacity (Carrier)</fullName>
            </value>
            <value>
                <fullName>Network Capacity (Integra)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Reason_Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Reason_Subcategory__c</fullName>
    <label>Reason Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Address Discrepancies</fullName>
            </value>
            <value>
                <fullName>APOT/CFA</fullName>
            </value>
            <value>
                <fullName>Awaiting Equipment</fullName>
            </value>
            <value>
                <fullName>Await NST Work</fullName>
            </value>
            <value>
                <fullName>BLA</fullName>
            </value>
            <value>
                <fullName>BLA not issued</fullName>
            </value>
            <value>
                <fullName>Capacity - HPBX</fullName>
            </value>
            <value>
                <fullName>Capacity – Issue or Non Existent</fullName>
            </value>
            <value>
                <fullName>Carrier Change</fullName>
            </value>
            <value>
                <fullName>CCD not populated</fullName>
            </value>
            <value>
                <fullName>CFA in use/incorrect</fullName>
            </value>
            <value>
                <fullName>Click scheduling conflict</fullName>
            </value>
            <value>
                <fullName>CLR/GLR Issue</fullName>
            </value>
            <value>
                <fullName>COLO x-connect needed</fullName>
            </value>
            <value>
                <fullName>Comcast NNI</fullName>
            </value>
            <value>
                <fullName>Conditioning</fullName>
            </value>
            <value>
                <fullName>Construction process</fullName>
            </value>
            <value>
                <fullName>CPE</fullName>
            </value>
            <value>
                <fullName>Customer End User Requirements</fullName>
            </value>
            <value>
                <fullName>Customer Implementation Plan</fullName>
            </value>
            <value>
                <fullName>Customer in Contract</fullName>
            </value>
            <value>
                <fullName>Customer un-responsive</fullName>
            </value>
            <value>
                <fullName>Design Template Missing/Incomplete</fullName>
            </value>
            <value>
                <fullName>Distance Does Not Qualify</fullName>
            </value>
            <value>
                <fullName>DMARC information Missing</fullName>
            </value>
            <value>
                <fullName>EELCAP</fullName>
            </value>
            <value>
                <fullName>End User Requirements not met</fullName>
            </value>
            <value>
                <fullName>Engineering Delay</fullName>
            </value>
            <value>
                <fullName>Entrance Facilities/Customer provided</fullName>
            </value>
            <value>
                <fullName>Entrance facilities/LEC provided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep_Issue__c/fields/Risk_Type__c.field-meta.xml
<CustomField>
    <fullName>Risk_Type__c</fullName>
    <label>RespOrg</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Integra</fullName>
                <label>Allstream</label>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Workstep_Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <formula>HYPERLINK( 
Workstep__r.Sub_Order__r.Id, 
Workstep__r.Sub_Order__r.Name )</formula>
    <label>Sub-Order</label>
    <type>Text</type>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Workstep__c.field-meta.xml
<CustomField>
    <fullName>Workstep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workstep</label>
    <referenceTo>Workstep__c</referenceTo>
    <relationshipLabel>Workstep Issues</relationshipLabel>
    <relationshipName>Workstep_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/WorkstepIssueTriggers.cls
public with sharing class WorkstepIssueTriggers {
	
	public static void WorkstepIssueModified(List<Workstep_Issue__c> tNew, List<Workstep_Issue__c> tOld, Boolean isUpdate, Boolean isBefore, Boolean isDelete){
		
		if (!ApexUtils.executeTriggerMethods('Workstep_Issue__c', isBefore, false)) return ;
		
        Map<Id, Workstep_Issue__c> tOldMap = tOld != null ? new Map<Id, Workstep_Issue__c>(tOld) : new Map<Id, Workstep_Issue__c>();
		if(isBefore){
			if(!isDelete)
				updateBefore(tNew, tOldMap, isUpdate);
		}
		else{
			updateWorksteps(tNew, tOldMap, isUpdate, isDelete);
			
			ApexUtils.afterTriggerComplete('Workstep_Issue__c', false);
		}
	}
	
	private static void updateBefore(List<Workstep_Issue__c> tNew, Map<Id, Workstep_Issue__c> tOldMap, Boolean isUpdate){
    	
    	List<Workstep_Issue__c> setDefaultOwner = new List<Workstep_Issue__c>();
    	
    	for(Workstep_Issue__c wi : tNew){
    		Workstep_Issue__c wiOld = wi.Id != null ? tOldMap.get(wi.Id) : null;
    		if(wi.Status__c == 'Resolved' && (wiOld == null || wiOld.Status__c != wi.Status__c))
    			wi.Date_Resolved__c = Date.today();
    			wi.OwnerId = wi.OwnerId;
		
    		if(!isUpdate)
    			setDefaultOwner.add(wi);
    	}
    	
    	if(setDefaultOwner.size() > 0){
    		List<Issue_to_Queue_Mapping__c> iqms = Issue_to_Queue_Mapping__c.getall().values();
    		List<String> ownerDefs = new List<String>();
    		Map<Id, Workstep__c> causeMap = new Map<Id, Workstep__c>();
    		
    		for(Workstep_Issue__c wi : setDefaultOwner){
    			if(wi.Caused_By__c != null){
    				ownerDefs.add(string.valueOf(wi.Caused_By__c));
    				causeMap.put(wi.Caused_By__c, null);
    			}
    			else{
    				String queue = null;
	    			for(Issue_to_Queue_Mapping__c iqm : iqms){
	    				if(iqm.Issue_Type__c == wi.Risk_Type__c && iqm.Reason__c == wi.Reason__c && (string.isEmpty(wi.Reason_Subcategory__c) || iqm.Reason_Subcategory__c == wi.Reason_Subcategory__c)){
	    					queue = iqm.Queue__c;
	    					break;
	    				}
	    			}
	    			
	    			if(queue != null)
	    				ownerDefs.add(queue);
	    			else
	    				ownerDefs.add(null);
    			}
    		}
    		
    		causeMap = new Map<Id, Workstep__c>([select Id, OwnerId from Workstep__c where Id in: causeMap.keyset()]);
    		
    		Map<String, Id> qMap = new Map<String, Id>();
    		for(Group q : [select Id, DeveloperName from Group where Type = 'Queue' and DeveloperName in: ownerDefs])
    			qMap.put(q.DeveloperName, q.Id);
    		
    		for(Integer i=0; i<ownerDefs.size(); i++){
    			String def = ownerDefs[i];
    			if(def == null) continue;
    			
    			Id qId = qMap.get(def);
    			setDefaultOwner[i].OwnerId = tNew[i].OwnerId;
    			if(setDefaultOwner[i].OwnerId == null)
    				setDefaultOwner[i].OwnerId = (qId != null) ? qId : (ApexUtils.isValidId(def) ? causeMap.get(def).OwnerId : setDefaultOwner[i].OwnerId);			
    		}
    	}
    	
	}
	
	private static void updateWorksteps(List<Workstep_Issue__c> tNew, Map<Id, Workstep_Issue__c> tOldMap, Boolean isUpdate, Boolean isDelete){
    	Map<Id, Workstep__c> wsMap = new Map<Id, Workstep__c>();
		Set<Id> wsResolved = new Set<Id>();
		Set<Id> sos = new Set<Id>();
    	
    	List<Workstep_Issue__c> m = isDelete ? tOldMap.values() : tNew;
    	for(Workstep_Issue__c wi : m){
    		Workstep_Issue__c wiOld = wi.Id != null ? tOldMap.get(wi.Id) : null;
    		if(isDelete || wiOld == null || wiOld.Status__c != wi.Status__c)
    			wsMap.put(wi.Workstep__c, null);
			if(wi.Status__c == WorkstepUtils.ISSUE_RESOLVED)
				wsResolved.add(wi.Workstep__c);
    	}
    	
    	if(wsMap.size() > 0){
    		wsMap = new Map<Id, Workstep__c>([select Id, Status__c, Sub_Order__c, (select Id from Workstep_Issues__r where Status__c != 'Resolved' limit 1) from Workstep__c where Id in: wsMap.keyset()]);
    		for(Workstep__c ws : wsMap.values())
			{
				ws.Status__c = (ws.Workstep_Issues__r != null && ws.Workstep_Issues__r.size() > 0) ? WorkstepUtils.STATUS_BLOCKED : WorkstepUtils.STATUS_OPEN;
				if(wsResolved.contains(ws.Id))
					ws.Unblocked_Date__c = Date.today();
			}
    		
    		update wsMap.values();   		
    	}
    	    Map<Id, Sub_Order__c> so = new Map<Id, Sub_Order__c>();
    		for(Workstep__c ws : wsMap.values())
			{				
				Sub_Order__c bSO = new Sub_Order__c();
				bSO.Id = ws.Sub_Order__c;
				if(ws.Status__c == 'BLOCKED'){
					bSO.Has_Blocked_Workstep__c =  true;
					if(bSO.Id != null)
						so.put(bSO.Id, bSO);
				}
				else
					sos.add(ws.Sub_Order__c);
			}	

			//check if the SO has any blocked ws before removing the Has_Block from the SO	
			Set<Id> blkSO = new Set<Id>();
			for(Workstep__c oWS : [Select Sub_Order__c FROM Workstep__c WHERE Status__c IN ('Blocked') AND Sub_Order__c IN: sos AND Id NOT IN: wsMap.keyset()]){				
				blkSO.add(oWS.Sub_Order__c);
			}
			if(blkSO.size() <= 0){
				for(Id sub : sos){
					Sub_Order__c bSO = new Sub_Order__c();
					bSO.Id = sub;
					bSO.Has_Blocked_Workstep__c =  false;
					if(bSO.Id != null)
						so.put(bSO.Id, bSO);
				}
			}
			update so.values();
	}
	
	/*private static void evaluateStatus(Set<Id> wsIds){
		List<Workstep_Issue__c> wiList = [SELECT Id, Status__c, Workstep__c, Date_Resolved__c FROM Workstep_Issue__c WHERE Workstep__c IN :wsIds];
		//List of issues that will need to be updated if status changed
		List<Workstep_Issue__c> updatewiList = new List<Workstep_Issue__c>();
		//List of Workstpes that will need to be updated if Wiorkstepp issue status changed
		Set<Id> updateWorkSteps = new Set<Id>();
		
		for(Workstep_Issue__c wi : wiList){
			if(wi.Status__c == WorkstepUtils.STATUS_RESOLVED)
			{
				//need to put date resolved if not set
				if (wi.Date_Resolved__c == null)
					wi.Date_Resolved__c = Date.today();
				//add issue to update and Workstep to update list
				updatewiList.add(wi);
				updateWorkSteps.add(wi.Workstep__c);
			}
		}
		//Need to go through and remove and Worksteps that have an open issue if there are multiple issues on a workstep
		for(Workstep_Issue__c wi : wiList){
			if(wi.Status__c != WorkstepUtils.STATUS_RESOLVED && updateWorkSteps.contains(wi.Workstep__c))
			{
				updateWorkSteps.remove(wi.Workstep__c);
			}
		}
		
		List<Workstep__c> wsList = [SELECT Id, Status__c, Start_Date__c, Owner.email FROM Workstep__c WHERE Id IN :updateWorkSteps];
		for(Workstep__c ws : wsList) {
			ws.Status__c = WorkstepUtils.STATUS_OPEN;
			ws.Start_Date__c = date.today();
			//ws.BlockedPendingValidationByCode__c = true;
		}
		if(updatewiList.size() > 0)
			update updatewiList;
		
		if(wsList.size()>0)
			update wsList;
		
		for(Workstep__c ws :wsList)
			sendEmail(ws.Owner.email, ws.Id);
	}
	
	private static void sendEmail(String userEmail, Id wsId){
		if (!Test.isRunningTest())
			ApexUtils.sendEmails(new Messaging.SingleEmailMessage[]{ ApexUtils.createEmailMessage(new List<String>{ userEmail }, null, 'Workstep issues resolved', 'All issues related to the workstep '+ wsId + ' have been resolved and are waiting validation.', false, null)});
	}*/
}