objects/Test_Case__c/Test_Case__c.object-meta.xml
<CustomObject>
    <label>Test Case</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Test Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Test_Case__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Test_Case__c/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

objects/Test_Case__c/fields/Functional_Testing_Areas__c.field-meta.xml
<CustomField>
    <fullName>Functional_Testing_Areas__c</fullName>
    <label>Functional Testing Area(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Integration</fullName>
            </value>
            <value>
                <fullName>Case Management</fullName>
            </value>
            <value>
                <fullName>Contract PDF</fullName>
            </value>
            <value>
                <fullName>CPQ/Approval</fullName>
            </value>
            <value>
                <fullName>CPQ/Configuration</fullName>
            </value>
            <value>
                <fullName>CPQ/PDF</fullName>
            </value>
            <value>
                <fullName>CPQ/Tech Details</fullName>
            </value>
            <value>
                <fullName>Docusign</fullName>
            </value>
            <value>
                <fullName>ICB</fullName>
            </value>
            <value>
                <fullName>Lead Management</fullName>
            </value>
            <value>
                <fullName>Notes/Attachments</fullName>
            </value>
            <value>
                <fullName>Opportunity Management</fullName>
            </value>
            <value>
                <fullName>Order Management</fullName>
            </value>
            <value>
                <fullName>Order TOV</fullName>
            </value>
            <value>
                <fullName>Order Workflow</fullName>
            </value>
            <value>
                <fullName>QoS Tool</fullName>
            </value>
            <value>
                <fullName>Sales Product Catalog</fullName>
            </value>
            <value>
                <fullName>Sales Reporting</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Test_Case__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Auto-filled by the system. Do not edit this field.</inlineHelpText>
    <label>Parent Test Case</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Must be a Test Case record type, not a Test Case Assignment</errorMessage>
        <filterItems>
            <field>Test_Case__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Test Case Template</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipLabel>Test Case Assignments</relationshipLabel>
    <relationshipName>Test_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Test_Case__c/fields/Test_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Test_Instructions__c</fullName>
    <label>Test Instructions</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

objects/Test_Case__c/fields/Test_Summary__c.field-meta.xml
<CustomField>
    <fullName>Test_Summary__c</fullName>
    <label>Test Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/Test_copyParentTestCase.cls
@isTest
private class Test_copyParentTestCase {

    @isTest static void assignTest() {
    
     id testCaseAssignmentRecordType = Schema.SObjectType.Test_Case__c.getRecordTypeInfosByName().get('Test Case Assignment').getRecordTypeId();
     id testAssignExistingTestCaseRecordType = Schema.SObjectType.Test_Case__c.getRecordTypeInfosByName().get('Assign Existing Test Case').getRecordTypeId();
     id testCaseTemplate = Schema.SObjectType.Test_Case__c.getRecordTypeInfosByName().get('Test Case Template').getRecordTypeId();
     id assignedUser = UserInfo.getUserId();
    
        Test_Case__c template = new Test_Case__c();         
            template.RecordTypeId                = testCaseTemplate;
            template.Test_Summary__c             = 'testing';
            template.Functional_Testing_Areas__c = 'Case Management;Lead Management;Opportunity Management';
            template.Test_Instructions__c        = 'testing test instructions';
            template.Expected_Result__c          = 'testing expected result';
        insert template; 
        
        Test_Case__c assignment = new Test_Case__c();               
            assignment.RecordTypeId   = testAssignExistingTestCaseRecordType;
            assignment.Test_Case__c   = template.Id; 
            assignment.Assigned_To__c = assignedUser;
        insert assignment;    

        assignment = [
            SELECT RecordTypeId,Test_Summary__c,Test_Instructions__c,Expected_Result__c,Functional_Testing_Areas__c,Assigned_To__c,OwnerId 
            FROM Test_Case__c
            WHERE Id=:assignment.id
            ];
        
        System.assertEquals(testCaseAssignmentRecordType, assignment.RecordTypeId);      
        System.assertEquals(template.Test_Summary__c, assignment.Test_Summary__c);
        System.assertEquals(template.Test_Instructions__c, assignment.Test_Instructions__c);
        System.assertEquals(template.Expected_Result__c, assignment.Expected_Result__c);
        System.assertEquals(template.Functional_Testing_Areas__c, assignment.Functional_Testing_Areas__c); 
        System.assertEquals(assignment.Assigned_To__c, assignment.OwnerId);
    }
}