objects/Capital_Project__c/Capital_Project__c.object-meta.xml
<CustomObject>
    <label>Capital Project</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Capital Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Customer_Contact__c/Customer_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>Customer Contact {0000000000}</displayFormat>
        <label>Customer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Customer_Contact__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Integration_Error__c/Integration_Error__c.object-meta.xml
<CustomObject>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Integration_Error__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Integration_Error__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <description>This is a general purpose field for storing what we were trying to do when integrating when we failed.  Both Action and the related object are taken into account when reading the values here:

Object(Action): Value
---------------------
Account(Update): Comma delimited field names
Contact(Update): N/A
Contact(Delete): ICC Contact ID
Service Location(Insert): Closed Won Opportunity ID (earliest closed date)
Service Location(Update): Comma delimited field names</description>
    <label>Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Integration_Error__c/fields/ObjectID__c.field-meta.xml
<CustomField>
    <fullName>ObjectID__c</fullName>
    <label>ObjectID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/classes/IntegrationErrorsController.cls
public with sharing class IntegrationErrorsController {
	
	public String integrationEndpoint {get;set;}
	public String totalCount {get;set;}
	public String selectedCount {get;Set;}
	public Integer batchLimit {get; set;}
	public List<Integration_Error__c> errors {get;set;}
	public List<Integration_Error__c> selectedErrors {get;set;}
	public Map<String, String> objectTypes {get;set;}	//Local copy of ApexUtils.sObjectNameByID
	
	private final String AccountPrefix = Account.sObjectType.getDescribe().getKeyPrefix() + '%';
	private final String ContactPrefix = Contact.sObjectType.getDescribe().getKeyPrefix() + '%';
	private final String CustomerContactPrefix = Customer_Contact__c.sObjectType.getDescribe().getKeyPrefix() + '%';
	private final String CustomerDetailPrefix = Customer_Detail__c.sObjectType.getDescribe().getKeyPrefix() + '%';
	private final String CasePrefix = Case.sObjectType.getDescribe().getKeyPrefix() + '%';
	private final String CaseCommentPrefix = CaseComment.sObjectType.getDescribe().getKeyPrefix() + '%';
	private final String CapitalProjectPrefix = Capital_Project__c.sObjectType.getDescribe().getKeyPrefix() + '%';
	
	private final Set<String> ValidPrefixes = new Set<String>{ AccountPrefix, ContactPrefix, CustomerContactPrefix, CustomerDetailPrefix, CasePrefix, CaseCommentPrefix, CapitalProjectPrefix };
    
    public IntegrationErrorsController() {
    	batchLimit = 200;
    	integrationEndpoint = CustomSettingUtils.IntegraWSEndpoint;
        getErrors();
    }
    
    private void getErrors(){
    	errors = new List<Integration_Error__c>();
    	objectTypes = new Map<String, String>();
		
		String whereClause = 'ObjectID__c like :AccountPrefix'
								+ ' or ObjectID__c like :ContactPrefix'
								+ ' or ObjectID__c like :CustomerContactPrefix'
								+ ' or ObjectID__c like :CustomerDetailPrefix'
								+ ' or ObjectID__c like :CasePrefix'
								+ ' or ObjectID__c like :CaseCommentPrefix'
								+ ' or ObjectID__c like :CapitalProjectPrefix';
    	for(Integration_Error__c error : (List<Integration_Error__c>)Database.query('select Id, Name, ObjectID__c, Info__c, Message__c, Action__c, CreatedDate from Integration_Error__c where ' + whereClause + ' limit 10000')){
			//Double check to filter out case insensitive prefix matches
			//if(ValidPrefixes.contains(error.ObjectID__c.substring(0, 3) + '%')){
	    		objectTypes.put(error.ObjectID__c, SchemaUtils.GetSObjectNameByID(error.ObjectID__c));
	    		errors.add(error);
					
				if(errors.size() == 1000) break;
			//}
    	}
    	totalCount = string.valueOf(Database.countQuery('select COUNT() from Integration_Error__c where ' + whereClause));
        refresh();
    }
    
    public String objectTypeSelection {get;set;}
    public void refresh() {
    	selectedErrors = new List<Integration_Error__c>();
    	
    	system.debug(objectTypeSelection);
    	Boolean anyMode = String.IsEmpty(objectTypeSelection);
    	for(Integration_Error__c error : errors){
    		if(anyMode || objectTypeSelection == objectTypes.get(error.ObjectID__c)){
    			selectedErrors.add(error);
    		}
    	}
		selectedCount = String.valueOf(selectedErrors.size());
    }
    
    public String objectID {get; set;}
    public void integrateSingle() {
		if(!String.IsEmpty(objectID))
			integrateIDs(new Set<String>{objectID});
    }
    
    public void integrateBatch() {
    	Set<String> objIDs = new Set<String>();
    	
    	refresh();
    	for(Integration_Error__c error : selectedErrors){
    		objIDs.add(error.ObjectID__c);
	    		
	    	if(objIDs.size() == batchLimit) break;
    	}
    	
    	integrateIDs(objIDs);
    }
    
    private void integrateIDs(Set<String> ids){
    	if(ids.size() == 0) return;
    	
		List<String> messages = IntegrationUtils.reintegrateObjects(ids);
		for(String m : messages)
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, m));
		
		getErrors();
    }
}