objects/Refund_Credit__c/Refund_Credit__c.object-meta.xml
<CustomObject>
    <description>This object is used for processing Refunds &amp; Credits for Customers.</description>
    <label>Refund/Credit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Refund/Credit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refund/Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Refund_Credit__c/fields/Next_Approver__c.field-meta.xml
<CustomField>
    <fullName>Next_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Next Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Refund_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ACR_Utils.cls
/***********************************************************************************************************
* Name       : ACR_Utils
* Purpose    : Utility Class
************************************************************************************************************
* Author                 | Version    | Created Date    | Description
************************************************************************************************************
* Rahul Sekar                  | 1.0        | April 17, 2019     | Initial version
***********************************************************************************************************/
public with sharing class ACR_Utils {
    /*
     *  Determines the button access based on the current user criteria
     */
    public static Boolean determineApproveButtonAccess(Id recordIds, String recordType, String approvalMethodName){
        String currentUserId=UserInfo.getUserId();
        String recordId=(String)recordIds;
        list<User> delApp = new list<User>();
        list<Refund_Credit__c> rec= new list<Refund_Credit__c>();
        list<User> currUser = new list<User>();
        ACR_DomainLayer.QueryEditor existingUser = new ACR_DomainLayer.QueryEditor('User','WHERE Id=\''+currentUserId+'\'','Select','Profile.Name ');
        currUser=(list<User>)existingUser.ResultSet;
        ACR_DomainLayer.QueryEditor refundCredit = new  ACR_DomainLayer.QueryEditor('Refund_Credit__c','WHERE Id=\''+recordId+'\'','SELECT','Next_Approver__c ');
        rec=(list<Refund_Credit__c>)refundCredit.ResultSet;
        If(rec[0].Next_Approver__c!=Null)
        {  
            ACR_DomainLayer.QueryEditor delAppUser = new  ACR_DomainLayer.QueryEditor('User','WHERE Id=\''+rec[0].Next_Approver__c+'\'','SELECT','Id ');
            delApp= (list<User>)delAppUser.ResultSet;
        }
        If(!currUser.isEmpty() && !delApp.isEmpty() && 
           (currUser[0].Profile.Name==ACR_ConstantDeclarations.SYSTEM_ADMIN || currentUserId==rec[0].Next_Approver__c || currentUserId == delApp[0].Id) )
        {
            return true;
        }
        else{
            return false;
        }        
    }

    
}