objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OLI__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>Opportunity_Product__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Opportunity_Product__c/Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{0000000}</displayFormat>
        <label>Opportunity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Opportunity__r.Account.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

objects/OpportunityLocationConfiguration__c/OpportunityLocationConfiguration__c.object-meta.xml
<CustomObject>
    <description>A configuration for an OpportunityLocation.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityLocationConfiguration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Opportunity_Location__r.Opportunity__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/OpportunityLocationConfiguration__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
                <default>true</default>
                <label>24</label>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>Month to Month</fullName>
            </value>
            <value>
                <fullName>Coterminous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An explicit account lookup that should only be used if the order is not opportunity driven.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account-based Orders</relationshipLabel>
    <relationshipName>Account_Based_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Contract_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed_Date__c</fullName>
    <formula>Opportunity__r.Contract_Signed_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Signed Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Order_Property__c/Order_Property__c.object-meta.xml
<CustomObject>
    <label>Order Property</label>
    <nameField>
        <label>Order Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Order_Property__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Properties</relationshipLabel>
    <relationshipName>Order_Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Order_Property__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>iCert</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order_Property__c/recordTypes/External_Order.recordType-meta.xml
<RecordType>
    <fullName>External_Order</fullName>
    <active>true</active>
    <label>External Order</label>
</RecordType>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Sub_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Order__r.Account_Link__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/External_Order__c.field-meta.xml
<CustomField>
    <fullName>External_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>External Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>External orders must belong to the same order</errorMessage>
        <filterItems>
            <field>Order_Property__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>External_Order</value>
        </filterItems>
        <filterItems>
            <field>Order_Property__c.Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order_Property__c</referenceTo>
    <relationshipLabel>Sub Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/External_Products__c.field-meta.xml
<CustomField>
    <fullName>External_Products__c</fullName>
    <label>External Products</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Survey__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Survey__c/fields/Survey_Name__c.field-meta.xml
<CustomField>
    <fullName>Survey_Name__c</fullName>
    <label>Survey Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

main/default/objects/Survey__c/fields/Surveyed_Contact__c.field-meta.xml
<CustomField>
    <fullName>Surveyed_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Surveyed Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact needs to be on this account.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Order__r.Account_Link__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Workstep__c/fields/External_Order__c.field-meta.xml
<CustomField>
    <fullName>External_Order__c</fullName>
    <formula>Sub_Order__r.External_Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External Order</label>
    <type>Text</type>
</CustomField>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/Test_CustomerSurveyUtils.cls
@isTest
public with sharing class Test_CustomerSurveyUtils extends TestUtils.TestClass {
	private static Mocks testData = new Mocks();
	private static Contact zOCCon = null;
	private static Contact OCcon {
		get{
			if(zOCCon == null){
				Contact c = new Contact();
				c.AccountId = testData.parentAccount.Id;
				c.Default_Responsible_Party__c = true;
				c.Email = 'kit.randall@integratelecom.com';
				c.HasOptedOutOfEmail = false;
				c.FirstName = 'kit';
				c.LastName = 'randall';
				insert c;
				zOCCon = c;
			}
			return zOCCon;
		}
	}
	private static Contact zSECon = null;
	private static Contact SEcon {
		get{
			if(zSECon == null){
				Contact c = new Contact();
				c.AccountId = testData.parentAccount.Id;
				c.Default_Responsible_Party__c = true;
				c.Email = 'kit.randall@integratelecom.com';
				c.HasOptedOutOfEmail = false;
				c.FirstName = 'kit';
				c.LastName = 'randall';
				insert c;
				zSECon = c;
			}
			return zSECon;
		}
	}
	private static Contact zCAMCon = null;
	private static Contact CAMcon {
		get{
			if(zCAMCon == null){
				Contact c = new Contact();
				c.AccountId = testData.parentAccount.Id;
				c.Default_Responsible_Party__c = true;
				c.Email = 'kit.randall@integratelecom.com';
				c.HasOptedOutOfEmail = false;
				c.FirstName = 'kit';
				c.LastName = 'randall';
				insert c;
				zCAMCon = c;
			}
			return zCAMCon;
		}
	}
	private static Contact xCon = null;
	private static Contact noEmailCon{
		get{
			if(xCon == null){
				Contact c = new Contact();
				c.AccountId = testData.parentAccount.Id;
				c.Default_Responsible_Party__c = true;
				c.Email = '';
				c.HasOptedOutOfEmail = false;
				c.FirstName = 'kit';
				c.LastName = 'randall';
				insert c;
				xCon = c;
			}
			return xCon;
		}
	}
	private static Contact xOptedOutCon = null;
	private static Contact optedOutCon{
		get{
			if(xOptedOutCon == null){
				Contact c = new Contact();
				c.AccountId = testData.parentAccount.Id;
				c.Default_Responsible_Party__c = true;
				c.Email = 'kit.randall@integratelecom.com';
				c.HasOptedOutOfEmail = true;
				c.FirstName = 'kit';
				c.LastName = 'randall';
				insert c;
				xOptedOutCon = c;
			}
			return xOptedOutCon;
		}
	}
	
	static testMethod void TestOrderSurveys(){
		
		//general setup
		Account a = testData.parentAccount;
		Order__c o = testData.order;
		o.Account__c = a.Id;
		
		//setup objects for post install surveys
		Id rtExternalOrder = [select Id from RecordType where DeveloperName = 'External_Order' limit 1][0].Id;	
		Order_Property__c op = new Order_Property__c(RecordTypeId = rtExternalOrder, Type__c = 'Install Order', Order__c = o.Id);
		insert op;
		Sub_Order__c so = new Sub_Order__c(External_Order__r = op, Order__c = o.Id, External_Products__c='UC Cloud Voice DID Service');
		//Sub_Order__c so = new Sub_Order__c(External_Order__r = op, Order__c = o.Id);        
		insert so;
		Workstep__c ws = new Workstep__c(Name = 'Confirm Customer Acceptance', Order__c = o.Id);
		insert ws;
		
		Map<Id, Order__c> Ords = new Map<Id, Order__c>();
		Ords.put(o.Id, o);
		List<Sub_Order__c> soList = new List<Sub_Order__c>{so};
		Map<Id, List<Workstep__c>> soWSMap = new Map<Id, List<Workstep__c>>();
		soWSMap.put(so.Id, new List<Workstep__c>{ws});
		
		Test.startTest();
		//call CustomerSurveyUtils Method
		CustomerSurveyUtils.sendOrderSurveys(Ords, soList, soWSMap);
		
		Survey__c svy = new Survey__c(Account__c = a.Id, Name = 'Order Completion Survey', Survey_Name__c = 'Order Completion Survey', Surveyed_Contact__c = OCcon.Id, Sent_Date__c = (Date.today() - 90));
		insert svy;	
		
		CustomerSurveyUtils.sendOrderSurveys(Ords, soList, soWSMap);
		Test.stopTest();
	}
	
	static testMethod void TestOpportunitySurveys(){
		
		//general setup
		Account a = testData.parentAccount;
		Order__c o = testData.order;
		o.Account__c = a.Id;
		Opportunity opp = testData.opportunity;
		Map<Id, Opportunity> tOld = new Map<Id, Opportunity>( [select Id, AccountId, StageName, Order_Status__c, Type, Contract_Signed_Date__c, Amount, Opportunity_Product__c, Term__c from Opportunity where Id = :opp.Id]);
		
		Service_Location__c sloc = testData.serviceLocation;
		sloc.Account__c = a.Id;
		update sloc;
		
		Survey__c svy = new Survey__c(Account__c = a.Id, Name = 'Order Completion Survey', Survey_Name__c = 'Sales Experience Survey', Surveyed_Contact__c = SECon.Id, Sent_Date__c = (Date.today() - 90));
		insert svy;
	
		Opportunity_Product__c oppProd = testData.opptyPrd;
	
		//Opportunity_Location__c oppLoc = testData.location;
		List<OLI__c> olis = testData.lstLineItems;

		OpportunityLocationConfiguration__c oppLocCfg = [select Id, Opportunity_Location__c, MRC_Total__c, opportunity_Location__r.opportunity__r.CPQ_Total__c from OpportunityLocationConfiguration__c where Id = :testData.lstconfig[0].Id limit 1];
		Opportunity_Location__c oppLoc = [select Opportunity__c, MRC_Total__c from Opportunity_Location__c where Id = :testData.location.Id limit 1];
		opp = [select Id, CPQ_Total__c from Opportunity where Id = :opp.Id limit 1];
		
		System.debug('KIT: location matches: ' + String.valueOf(oppLoc.Opportunity__c == opp.Id));
		System.debug('KIT: sol matches: ' + String.valueOf(oppLocCfg.Opportunity_Location__c == oppLoc.Id));
		System.debug('KIT: CPQTotal: ' + opp.CPQ_Total__c);
		System.debug('KIT: MRCTotal: ' + oppLoc.MRC_Total__c);
		System.debug('KIT: solMRCTotal: ' + oppLocCfg.MRC_Total__c);
		for(OLI__c oli : olis){
			System.debug('KIT: oli matches sol: ' + String.valueOf(oli.OpportunityLocationConfiguration__c == oppLocCfg.Id));
			System.debug('KIT: oli total: ' + String.valueOf(oli.qty__c * oli.MRC__c));
		}

		Test.startTest();
		//update the opp to trigger the survey loogic.
		//setup objects for sales experience surveys
		opp.AccountId = a.Id;
		//opp.StageName = OpportunityUtils.STAGE_CLOSED_WON;
		opp.StageName = OpportunityUtils.STAGE_5;
		opp.Order_Status__c = 'Order to Pending';
		opp.Type = 'New Logo';
		opp.Contract_Signed_Date__c = Date.today();
		opp.Amount = 1000;
		opp.Opportunity_Product__c = 'test product';
		opp.Term__c = '36';
		

		//OpportunityTriggers.lastRunMap.clear();
		//ApexUtils.triggerCounts.get('Opportunity').clear();
		//update opp;
		
		CustomerSurveyUtils.sendOpportunitySurveys(new List<Opportunity>{opp}, tOld);
		Test.stopTest();
	}
	/*
	static testMethod void TestCaseSurveys(){
		
		//general setup
		Account a = testData.parentAccount;
		
		//setup objects for customer account manager surveys
		Case cNew = new Case(Status = 'New', Commit_Date__c = Date.today(), Origin = 'Account Review Visit', Type = 'Proactive', ContactId = SEcon.Id, AccountId = a.Id);
		insert cNew;
		cNew.Status = 'Closed';
		
		Test.startTest();
		//update the case to trigger the survey logic.
		update cNew;
		
		Survey__c svy = new Survey__c(Account__c = a.Id, Name = 'Customer Account Manager Survey', Survey_Name__c = 'Order Completion Survey', Surveyed_Contact__c = optedOutCon.Id, Sent_Date__c = (Date.today() - 90));
		insert svy;
		
		cNew.Status = 'New';
		cNew.ContactId = CAMcon.Id;
		cNew.Closed_Case_Change_Confirmation__c = true;
		update cNew;
		//a.Account_Sales_Channel__c = 'Government and Education';
		update a;
		cNew.Status = 'Closed';
		update cNew;
		
		cNew.Status = 'New';
		cNew.Origin = 'Email';
		cNew.Type = 'Billing';
		cNew.Closed_Case_Change_Confirmation__c = true;
		update cNew;
		//a.Account_Sales_Channel__c = 'Integra Business';
		update a;
		cNew.Status = 'Closed';
		update cNew;
		
		Test.stopTest();
	}
	*/
	static testMethod void testSurveyError(){
		Account a = testData.parentAccount;
		Order__c o = testData.order;
		o.Account__c = a.Id;
		
		Survey__c svy = new Survey__c(Account__c = a.Id, Name = 'Order Completion Survey', Survey_Name__c = 'Order Completion Survey', Surveyed_Contact__c = CAMcon.Id, Sent_Date__c = (Date.today() - 90));
		insert svy;	
		
		Integration_Error__c error = new Integration_Error__c(Message__c = 'test', Info__c = 'test', ObjectID__c = svy.Id, RelatedID__c = o.Id);
		insert error;
		
		Test.startTest();
		CustomerSurveyUtils.resendFailedSurveys(new List<Integration_Error__c>{error});
		Test.stopTest();
	}

    static testMethod void TestContactSurveys(){

    	Contact c = new Contact();
		c.AccountId = testData.parentAccount.Id;
		c.Email = 'marc.kirouac@allstream.com';
		c.HasOptedOutOfEmail = false;
		c.FirstName = 'Marc';
		c.LastName = 'Kirouac';
		insert c;

		Test.startTest();
        CustomerSurveyUtils.createContactSurveys(new List<Contact> {c}, CustomerSurveyUtils.SurveyType.RECOMMEND_ALLSTREAM_SURVEY_NAME);
		Test.stopTest();
	}
    
}