objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OLI__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>quote needs to be green or approved to print a quote</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Sales Management Approval Required</fullName>
            </value>
            <value>
                <fullName>Offer Management Approval Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OLI__c/fields/OpportunityLocationConfiguration__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLocationConfiguration__c</fullName>
    <label>OpportunityLocationConfiguration</label>
    <referenceTo>OpportunityLocationConfiguration__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/OLI__c/fields/PP_SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>PP_SalesProductExternalID__c</fullName>
    <label>PP_ SalesProductExternalID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/OLI__c/fields/SPC_Component__c.field-meta.xml
<CustomField>
    <fullName>SPC_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SPC Component</label>
    <referenceTo>SPC_Component__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/OLI__c/fields/SPC_Sales_Product_Component_Id__c.field-meta.xml
<CustomField>
    <fullName>SPC_Sales_Product_Component_Id__c</fullName>
    <label>SPC_Sales_Product_Component_Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OpportunityLocationConfiguration__c/OpportunityLocationConfiguration__c.object-meta.xml
<CustomObject>
    <description>A configuration for an OpportunityLocation.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityLocationConfiguration__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Solutions</relationshipLabel>
    <relationshipName>OpportunityLocationConfigurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/OpportunityLocationConfiguration__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
                <default>true</default>
                <label>24</label>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>Month to Month</fullName>
            </value>
            <value>
                <fullName>Coterminous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SPC_Component__c/SPC_Component__c.object-meta.xml
<CustomObject>
    <label>SPC Component</label>
    <nameField>
        <label>SPC Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SPC_Component__c/fields/Sales_Product_Component_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product_Component_ID__c</fullName>
    <externalId>true</externalId>
    <label>Sales Product Component ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/SPC_Pricing__c/SPC_Pricing__c.object-meta.xml
<CustomObject>
    <label>SPC Pricing</label>
    <nameField>
        <displayFormat>SPCPrice-{0000}</displayFormat>
        <label>SPC Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPC Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/SPC_Pricing__c/fields/Is_Expired__c.field-meta.xml
<CustomField>
    <fullName>Is_Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Expired</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Sales_Product_Component_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product_Component_ID__c</fullName>
    <label>Sales Product Component ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/SPC_Component__c.field-meta.xml
<CustomField>
    <fullName>SPC_Component__c</fullName>
    <label>SPC Component</label>
    <referenceTo>SPC_Component__c</referenceTo>
    <relationshipLabel>SPC Pricing</relationshipLabel>
    <relationshipName>SPC_Pricing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SPC_Product__c/fields/Hide_In_Wizard__c.field-meta.xml
<CustomField>
    <fullName>Hide_In_Wizard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide In Wizard</label>
    <type>Checkbox</type>
</CustomField>

objects/SPC_Product__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <externalId>true</externalId>
    <label>SalesProductExternalID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

main/default/classes/Test_CloneSolution.cls
@isTest
public with sharing class Test_CloneSolution extends TestUtils.TestClass {

    static testMethod void testController() {
        
        CloneSolutionController cloneSolutionController = null;
        
        // create test data
        Mocks testData = new Mocks();
        Test.startTest();
        // test controller config constructor validation
        PageReference pageReference = Page.CloneSolution;
        Test.setCurrentPage(pageReference);
        try {
            cloneSolutionController = new CloneSolutionController();
        } catch(CloneSolutionController.CloneSolutionControllerException e) {}
        try {
            pageReference.getParameters().put('opportunityLocationConfigurationId', '');
            cloneSolutionController = new CloneSolutionController();
        } catch(CloneSolutionController.CloneSolutionControllerException e) {}
        try {
            pageReference.getParameters().put('opportunityLocationConfigurationId', 'a0aL00000008TQQ');
            cloneSolutionController = new CloneSolutionController();
        } catch(CloneSolutionController.CloneSolutionControllerException e) {}
        
        // construct controller
        pageReference.getParameters().put('opportunityLocationConfigurationId', testData.lstconfig[0].Id);
        cloneSolutionController = new CloneSolutionController();
        
        // exercise general workflows
        
        cloneSolutionController.gotoManageLocationProducts();
        
        // perform a garbage search (expect no results)
        cloneSolutionController.searchMySolutionsOnly = true;
        cloneSolutionController.searchSolutionName = 'test';
        cloneSolutionController.searchOpportunityName = 'test';
        cloneSolutionController.searchAccountName = 'test';
        cloneSolutionController.searchExcludeEmptySolutions = true;
        cloneSolutionController.searchMaxResults = 100;
        cloneSolutionController.searchSolutions();
        System.assert(cloneSolutionController.searchResults.isEmpty());
        
		List<OLI__c> olis = testData.lstLineItems;
		
        // find ourself
		 cloneSolutionController.searchMySolutionsOnly = false;
        cloneSolutionController.searchSolutionName = testData.lstconfig[0].Name;
        cloneSolutionController.searchOpportunityName = '';
        cloneSolutionController.searchAccountName = '';
        cloneSolutionController.searchExcludeEmptySolutions = false;
        cloneSolutionController.searchMaxResults = 100;
		cloneSolutionController.cloneFromSolutionID = 'null';
        cloneSolutionController.searchSolutions();	
        System.debug(cloneSolutionController.searchResults);
		
        System.assert(!cloneSolutionController.searchResults.isEmpty());
        
        // clone ourself
		System.debug('testData.lstconfig[0].Id: ' + testData.lstconfig[0].Id);
        cloneSolutionController.ConfigId_cloneConfig = testData.lstconfig[0].Id;
        cloneSolutionController.Mode_cloneConfig = 'edit';
		cloneSolutionController.solutionsToCloneTo = new List<String>();
        cloneSolutionController.cloneConfig();
		
		CloneSolutionController.LineItemAssembler lia = new CloneSolutionController.LineItemAssembler();
		CloneSolutionController.LineItem li = new CloneSolutionController.LineItem();
		li = lia.fromOLI(testData.lstLineItems[0], testData.marketArea.Id);
		test.stopTest();
    }
    
    static testmethod void testcloneableSolutionsJSON(){
        CloneSolutionController controller = new CloneSolutionController();
        Map<String,OpportunityLocationConfiguration__c> mapping = new Map<String,OpportunityLocationConfiguration__c>();
        mapping.put('Key string with null value', null);
        controller.cloneableSolutions = mapping;
     	System.AssertEquals(controller.cloneableSolutionsJSON, JSON.serialize(mapping, true));   
    }
    
    static testmethod void testcreatSolution(){
        CloneSolutionController controller = new CloneSolutionController();
        controller.opportunityID = 'OPP ID 12345';
        System.AssertEquals(controller.createNewSolution().getParameters().get('OpportunityID'), 'OPP ID 12345');
        System.AssertEquals(controller.createNewSolution().getParameters().values().size(),2);        
    }
    
    static testmethod void testcloneConfig1(){
        Test.startTest();
        
        CloneSolutionController controller = new CloneSolutionController();
        Mocks TestData = new Mocks();
        Map<String,OpportunityLocationConfiguration__c> mapping = new Map<String,OpportunityLocationConfiguration__c>();
        mapping.put(String.valueOf(TestData.lstconfig[0].Id), TestData.lstconfig[0]);
        TestData.lstconfig.remove(1);
        
        controller.searchExcludeEmptySolutions = false;
        controller.searchMySolutionsOnly = false;
        controller.searchSolutionName = '';
        controller.searchOpportunityName = '';
        controller.searchAccountName = '';
        controller.cloneFromSolutionID = null;
        
        OLI__c LItem = new OLI__c(OpportunityLocationConfiguration__c = TestData.lstconfig[0].Id, SPC_Sales_Product_Component_Id__c = 0.602, Approval_Status__c = 'Approved');
        insert LItem;
        controller.ConfigId_cloneConfig = String.valueOf(TestData.lstconfig[0].Id);
        controller.cloneableSolutions = mapping;
        controller.solutionsToCloneTo = new list<String>{TestData.lstconfig[0].Id};
        controller.searchMaxResults = 1;

        SPC_Component__c fieldReq = new SPC_Component__c();
        insert fieldReq;
        SPC_Pricing__c SPCPricing = new SPC_Pricing__c(is_expired__c = false, Term__c = 0, Market__c = TestData.lstconfig[0].Opportunity_Location__r.Service_Location__r.Location__r.Building__r.Market_Area_Name__c, Sales_Product_Component_ID__c = 0.602, SPC_Component__c = fieldReq.Id);
        insert SPCPricing;
        SPC_Pricing__c SPCPricing2 = new SPC_Pricing__c(is_expired__c = false, Term__c = 0, Market__c = TestData.lstconfig[0].Opportunity_Location__r.Service_Location__r.Location__r.Building__r.Market_Area_Name__c, Sales_Product_Component_ID__c = 0.602, SPC_Component__c = fieldReq.Id);
        insert SPCPricing2;
        controller.searchSolutions();
        //System.AssertEquals(controller.cloneConfig(), controller.gotoManageLocationProducts());
        System.AssertNotEquals(controller.cloneConfig(), null);
        System.Assert([Select Id From OLI__c Where Id =: LItem.Id].isEmpty());
              
        Test.stopTest();       
    }
    
    static testmethod void testcloneConfig2(){
        Test.startTest();
        
        CloneSolutionController controller = new CloneSolutionController();
        Mocks TestData = new Mocks();
        Map<String,OpportunityLocationConfiguration__c> mapping = new Map<String,OpportunityLocationConfiguration__c>();
        mapping.put(String.valueOf(TestData.lstconfig[0].Id), TestData.lstconfig[0]);
        TestData.lstconfig.remove(1);
        
        controller.searchExcludeEmptySolutions = false;
        controller.searchMySolutionsOnly = false;
        controller.searchSolutionName = '';
        controller.searchOpportunityName = '';
        controller.searchAccountName = '';
        controller.cloneFromSolutionID = null;
        
        OLI__c LItem = new OLI__c(OpportunityLocationCOnfiguration__c = TestData.lstconfig[0].Id, SPC_Sales_Product_Component_Id__c = 0.602, Approval_Status__c = 'Approved');
        insert LItem;
        controller.ConfigId_cloneConfig = String.valueOf(TestData.lstconfig[0].Id);
        controller.cloneableSolutions = mapping;
        controller.solutionsToCloneTo = new list<String>{TestData.lstconfig[0].Id};
        controller.searchMaxResults = 1;

        SPC_Component__c fieldReq = new SPC_Component__c();
        insert fieldReq;
        SPC_Pricing__c SPCPricing = new SPC_Pricing__c(is_expired__c = false, Term__c = 0, Market__c = TestData.lstconfig[0].Opportunity_Location__r.Service_Location__r.Location__r.Building__r.Market_Area_Name__c, Sales_Product_Component_ID__c = 0.602, SPC_Component__c = fieldReq.Id);
        insert SPCPricing;
        
        SPC_Product__c SPCProd = new SPC_Product__c(SalesProductExternalID__c = 123, Hide_In_Wizard__c = true);
        insert SPCProd;
        LItem.PP_SalesProductExternalID__c = '123';
        update LItem;
        controller.searchSolutions();
        System.AssertEquals(controller.cloneConfig(), null);
        System.Assert([Select Id From OLI__c Where Id =: LItem.Id].isEmpty());
        
        LItem.PP_SalesProductExternalID__c = null;
        undelete LItem;
        upsert LItem;
        SPCPricing.Term__c = null;
        update SPCPricing;
        controller.searchSolutions();
        System.AssertEquals(controller.cloneConfig(), null);
        System.Assert([Select Id From OLI__c Where Id =: LItem.Id].isEmpty());
        
        Test.stopTest();
    }
}