objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OLI__c/fields/MRC__c.field-meta.xml
<CustomField>
    <fullName>MRC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MRC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/OLI__c/fields/NRC__c.field-meta.xml
<CustomField>
    <fullName>NRC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NRC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/OLI__c/fields/Parent_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the parent relationship</description>
    <label>Parent Relationship</label>
    <referenceTo>SPC_Relationship__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/OLI__c/fields/Price_Id__c.field-meta.xml
<CustomField>
    <fullName>Price_Id__c</fullName>
    <description>Price Id From  IntegraWs</description>
    <label>Price Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/OLI__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Qty</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/OLI__c/fields/SPC_Component__c.field-meta.xml
<CustomField>
    <fullName>SPC_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SPC Component</label>
    <referenceTo>SPC_Component__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/OLI__c/fields/SPC_Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Sales_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SPC Sales Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SPC_Component__c/SPC_Component__c.object-meta.xml
<CustomObject>
    <label>SPC Component</label>
    <nameField>
        <label>SPC Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SPC_Component__c/fields/Component_Group__c.field-meta.xml
<CustomField>
    <fullName>Component_Group__c</fullName>
    <label>Component Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SPC_Component__c/fields/Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>SPC Components</relationshipLabel>
    <relationshipName>SPC_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SPC_Component__c/fields/Sales_Product_Component_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product_Component_ID__c</fullName>
    <externalId>true</externalId>
    <label>Sales Product Component ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/SPC_Pricing__c/SPC_Pricing__c.object-meta.xml
<CustomObject>
    <label>SPC Pricing</label>
    <nameField>
        <displayFormat>SPCPrice-{0000}</displayFormat>
        <label>SPC Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPC Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SPC_Pricing__c/fields/Available_In_Wizard__c.field-meta.xml
<CustomField>
    <fullName>Available_In_Wizard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available In Wizard</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Component_Group__c.field-meta.xml
<CustomField>
    <fullName>Component_Group__c</fullName>
    <label>Component Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Is_Expired__c.field-meta.xml
<CustomField>
    <fullName>Is_Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Expired</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Price_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_ID__c</fullName>
    <description>This is the unique identifier created for each pricing row.</description>
    <externalId>true</externalId>
    <label>Price ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Sales_Product_Component_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product_Component_ID__c</fullName>
    <label>Sales Product Component ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SPC_Pricing__c/fields/Sales_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product_ID__c</fullName>
    <label>Sales Product ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/SPC_Component__c.field-meta.xml
<CustomField>
    <fullName>SPC_Component__c</fullName>
    <label>SPC Component</label>
    <referenceTo>SPC_Component__c</referenceTo>
    <relationshipLabel>SPC Pricing</relationshipLabel>
    <relationshipName>SPC_Pricing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/SPC_Pricing__c/fields/Validation_Constraint_Type__c.field-meta.xml
<CustomField>
    <fullName>Validation_Constraint_Type__c</fullName>
    <label>Validation Constraint Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SPC_Product__c/fields/Hide_In_Wizard__c.field-meta.xml
<CustomField>
    <fullName>Hide_In_Wizard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide In Wizard</label>
    <type>Checkbox</type>
</CustomField>

objects/SPC_Product__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <externalId>true</externalId>
    <label>SalesProductExternalID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/SPC_Relationship__c/SPC_Relationship__c.object-meta.xml
<CustomObject>
    <label>SPC Relationship</label>
    <nameField>
        <label>SPC Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SPC_Relationship__c/fields/Parent_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Relationship</label>
    <referenceTo>SPC_Relationship__c</referenceTo>
    <relationshipLabel>SPC Relationships</relationshipLabel>
    <relationshipName>SPC_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SPC_Relationship__c/fields/Primary_Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>SPC Relationships</relationshipLabel>
    <relationshipName>SPC_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/SPC_Relationship__c/fields/Primary_Sales_Product_Component__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Product_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Product Component</label>
    <referenceTo>SPC_Component__c</referenceTo>
    <relationshipLabel>SPC Relationships</relationshipLabel>
    <relationshipName>SPC_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/SPC_Relationship__c/fields/SPC_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>SPC_Relationship_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SPC Relationship Type</label>
    <referenceTo>SPC_Relationship_Type__c</referenceTo>
    <relationshipLabel>SPC Relationships</relationshipLabel>
    <relationshipName>SPC_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SPC_Relationship_Type__c/SPC_Relationship_Type__c.object-meta.xml
<CustomObject>
    <label>SPC Relationship Type</label>
    <nameField>
        <label>SPC Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Relationship Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SPC_Relationship_Type__c/fields/Pick_One__c.field-meta.xml
<CustomField>
    <fullName>Pick_One__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pick One</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/SPC_Relationship_Type__c/fields/Relationship_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type_ID__c</fullName>
    <externalId>true</externalId>
    <label>Relationship Type ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/SPC_Relationship_Type__c/fields/Use_Parent__c.field-meta.xml
<CustomField>
    <fullName>Use_Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Parent</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/Test_ConfigureNewSolution.cls
@isTest
public with sharing class Test_ConfigureNewSolution extends TestUtils.TestClass {
	static testMethod void TestConfigureSoluiton() {
		Mocks testData = new Mocks();
		List<OLI__c> olees = testData.lstLineItems;
		SPC_Product__c product = new SPC_Product__c(
			SalesProductExternalID__c = 185
			,Expiration__c = null
			,Hide_In_Wizard__c = false
			,Name = 'Access Service');
		insert product;
		for(OLI__c oli : olees){
			oli.SPC_Sales_Product__c = product.id;
		}
		update olees;

		SPC_Component__c comp1 = new SPC_Component__c(
			Component_Name__c = 'EoC Access - 40 Mbps'
			,Component_Group__c = 'Access/Bandwidth'
			,Sales_Product__c = product.id
			,Sales_Product_Component_ID__c = 13172
		);		
		insert comp1;
		SPC_Relationship_Type__c rt = new SPC_Relationship_Type__c(
			Relationship_Type_ID__c = '1'
			,Pick_One__c = true
			,Required__c = true
		);
		SPC_Relationship_Type__c rt2 = new SPC_Relationship_Type__c(
			Relationship_Type_ID__c = '2'
			,Use_Parent__c = true
		);
		insert new List<SPC_Relationship_Type__c>{rt,rt2};

		SPC_Relationship__c r = new SPC_Relationship__c(
			Primary_Sales_Product__c = product.id
			,SPC_Relationship_Type__c = rt.id
		);
		insert r;

		SPC_Relationship__c r2 = new SPC_Relationship__c(
			SPC_Relationship_Type__c = rt2.id
			,Parent_Relationship__c = r.id
			,Primary_Sales_Product_Component__c = comp1.id
		);
		insert r2;

		SPC_Pricing__c pricing = new SPC_Pricing__c(
			sales_product_id__c = 185
			,Is_Expired__c = false
			,Validation_Constraint_Type__c = 'test'
			,Price_ID__c = 'SP185CO65321TM0A876AV2291'
			,Market__c = 'Southwest Washington'
			,Available_In_Wizard__c = true
			,SPC_Component__c = comp1.id
			,term__c = 36
		);
		insert new List<SPC_Pricing__c>{pricing};


		test.startTest();
		PageReference pageReference = Page.ConfigureNewSolution;
        pageReference.getParameters().put('opportunityLocationConfigurationId', testData.lstconfig[0].Id);
		pageReference.getParameters().put('term', '36');
		pageReference.getParameters().put('market', 'Southwest Washington');
		
		Test.setCurrentPage(pageReference);
		ConfigureNewSolution controller = new ConfigureNewSolution();

		ConfigureNewSolution.getPricingForProduct('185','Southwest Washington',json.serialize(new List<String>{'36'}),false, false);

		List<ConfigureNewSolution.UIProdView> views = new List<ConfigureNewSolution.UIProdView>();
		for(OLI__c oli : olees){
			ConfigureNewSolution.UIProdView v = new ConfigureNewSolution.UIProdView();
			v.oli = oli;
			v.Children = new List<ConfigureNewSolution.UIProdView>();
			v.MRR = oli.MRC__c;
			v.MRRList = oli.MRC__c;
			v.MRRTotal = oli.MRC__c;
			v.NRR = oli.NRC__c;
			v.NRRList = oli.NRC__c;
			v.NRRTotal = oli.NRC__c;
			v.ParentRelID = '';
			v.PriceId = oli.Price_Id__c;
			v.ProdName = product.Name;
			v.Qty = integer.valueof(oli.Qty__c);
			v.SPCComponentID = '';
			v.SPCProductID = product.id;
			v.UUID = '';
			v.ParentProdName = product.Name;
			v.GroupName = '';
			v.DisplayName = '';
			v.ProdId = 0;
			views.add(v);
		}
		ConfigureNewSolution.GrantApproval(json.serialize(views),'Offer Management',testData.lstconfig[0]);
		ConfigureNewSolution.UpsertOLIs(json.serialize(views),testData.lstconfig[0].Id,testData.lstconfig[0].Opportunity_Location__c );

		
		test.stopTest();
	}
}