objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OLI__c/fields/Price_Id__c.field-meta.xml
<CustomField>
    <fullName>Price_Id__c</fullName>
    <description>Price Id From  IntegraWs</description>
    <label>Price Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/OLI__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Qty</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/OLI__c/fields/SPC_Component__c.field-meta.xml
<CustomField>
    <fullName>SPC_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SPC Component</label>
    <referenceTo>SPC_Component__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SPC_Component__c/SPC_Component__c.object-meta.xml
<CustomObject>
    <label>SPC Component</label>
    <nameField>
        <label>SPC Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SPC_Component__c/fields/Component_Group__c.field-meta.xml
<CustomField>
    <fullName>Component_Group__c</fullName>
    <label>Component Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SPC_Component__c/fields/Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>SPC Components</relationshipLabel>
    <relationshipName>SPC_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SPC_Component__c/fields/Sales_Product_Component_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product_Component_ID__c</fullName>
    <externalId>true</externalId>
    <label>Sales Product Component ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/SPC_Pricing__c/SPC_Pricing__c.object-meta.xml
<CustomObject>
    <label>SPC Pricing</label>
    <nameField>
        <displayFormat>SPCPrice-{0000}</displayFormat>
        <label>SPC Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPC Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SPC_Pricing__c/fields/Available_In_Wizard__c.field-meta.xml
<CustomField>
    <fullName>Available_In_Wizard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available In Wizard</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Component_Group__c.field-meta.xml
<CustomField>
    <fullName>Component_Group__c</fullName>
    <label>Component Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Is_Expired__c.field-meta.xml
<CustomField>
    <fullName>Is_Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Expired</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Price_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_ID__c</fullName>
    <description>This is the unique identifier created for each pricing row.</description>
    <externalId>true</externalId>
    <label>Price ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Sales_Product_Component_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product_Component_ID__c</fullName>
    <label>Sales Product Component ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SPC_Pricing__c/fields/Sales_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product_ID__c</fullName>
    <label>Sales Product ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/SPC_Component__c.field-meta.xml
<CustomField>
    <fullName>SPC_Component__c</fullName>
    <label>SPC Component</label>
    <referenceTo>SPC_Component__c</referenceTo>
    <relationshipLabel>SPC Pricing</relationshipLabel>
    <relationshipName>SPC_Pricing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/SPC_Pricing__c/fields/Validation_Constraint_Type__c.field-meta.xml
<CustomField>
    <fullName>Validation_Constraint_Type__c</fullName>
    <label>Validation Constraint Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SPC_Product__c/fields/Hide_In_Wizard__c.field-meta.xml
<CustomField>
    <fullName>Hide_In_Wizard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide In Wizard</label>
    <type>Checkbox</type>
</CustomField>

objects/SPC_Product__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <externalId>true</externalId>
    <label>SalesProductExternalID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

classes/Test_ConfigureSolution.cls
@isTest
public with sharing class Test_ConfigureSolution extends TestUtils.TestClass {
	static testMethod void TestConfigureSoluiton() {
		Mocks testData = new Mocks();
		SPC_Product__c product = new SPC_Product__c(
			SalesProductExternalID__c = 185
			,Expiration__c = null
			,Hide_In_Wizard__c = false);
		insert product;
		SPC_Component__c comp1 = new SPC_Component__c(
			Component_Name__c = 'EoC Access - 40 Mbps'
			,Component_Group__c = 'Access/Bandwidth'
			,Sales_Product__c = product.id
			,Sales_Product_Component_ID__c = 13172
		);		
		insert comp1;
		List<SPC_Pricing__c> pricings = new List<SPC_Pricing__c>();
		SPC_Pricing__c pricing = new SPC_Pricing__c(
			sales_product_id__c = 185
			,Is_Expired__c = false
			,Validation_Constraint_Type__c = 'test'
			,Price_ID__c = 'SP185CO65321TM0A876AV2291'
			,Market__c = 'asdf'
			,Available_In_Wizard__c = true
			,SPC_Component__c = comp1.id
		);
		pricings.add(pricing);
		SPC_Pricing__c pricing2 = new SPC_Pricing__c(
			sales_product_id__c = 185
			,Is_Expired__c = false
			,Validation_Constraint_Type__c = 'test'
			,Price_ID__c = 'SP185CO65321TM0A876AV2292'
			,Market__c = 'asdf'
			,Available_In_Wizard__c = true
			,SPC_Component__c = comp1.id
		);
		pricings.add(pricing2);
		insert pricings;
	
		List<OLI__c> olees = testData.lstLineItems;
		test.startTest();
		
		PageReference pageReference = Page.ConfigureSolution;
        pageReference.getParameters().put('opportunityLocationConfigurationId', testData.lstconfig[0].Id);
        Test.setCurrentPage(pageReference);
		ConfigureSolutionController controller = new ConfigureSolutionController();
		List<SelectOption> ats = controller.accessTechs;
		Component.Apex.SelectList sl = controller.viewList;
		
		controller.selectedProduct = '185';
		controller.GetPricing();
		
		String cloneKey = '';
		for(string pg : controller.pricingSortOrder.keyset()){
			for(String priceSortKey : controller.pricingSortOrder.get(pg).keyset()){
				for(ConfigureSolutionController.OLIView v : controller.pricingSortOrder.get(pg).get(priceSortKey)){
					v.oli.qty__c = 2;
					v.updated = true;
					if(cloneKey == '')
						cloneKey = v.oli.price_id__c;
				}
			}
		}
		pageReference.getParameters().put('priceID', cloneKey);
		pageReference.getParameters().put('addMode', 'true');
		pageReference.getParameters().put('offset', '0');
		controller.AddRemovePriceRow();
		controller.doValidation = true;
		controller.doValidate();
		
		pageReference.getParameters().put('streetNumber', '5486');
		pageReference.getParameters().put('street', 'sw norris terrace');
		pageReference.getParameters().put('suite', '');
		pageReference.getParameters().put('city', 'Beaverton');
        //MNK added Aug 2017
        pageReference.getParameters().put('country', 'US');
		pageReference.getParameters().put('state', 'OR');
		pageReference.getParameters().put('postalCode', '97007');
		pageReference.getParameters().put('latitude', '0');
		pageReference.getParameters().put('longitude', '0');
		pageReference.getParameters().put('success', 'true');
		controller.SecondaryLocationParsed();
		controller.SaveParsedSecondaryLocation();
		//controller.recalcDiscount();
		controller.save();
		controller.SaveLineItemsAndExit();
		controller.GrantApproval();
		
		test.stopTest();
	}
}