objects/Access_Technology__c/Access_Technology__c.object-meta.xml
<CustomObject>
    <label>Access Technology</label>
    <nameField>
        <label>Access Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Access_Technology__c/fields/Access_Technology_ID__c.field-meta.xml
<CustomField>
    <fullName>Access_Technology_ID__c</fullName>
    <description>External ID for Access Technologies</description>
    <externalId>true</externalId>
    <label>Access Technology ID</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Net_Classification__c.field-meta.xml
<CustomField>
    <fullName>Net_Classification__c</fullName>
    <label>Net Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eNNI</fullName>
            </value>
            <value>
                <fullName>ILEC</fullName>
            </value>
            <value>
                <fullName>Near-net</fullName>
            </value>
            <value>
                <fullName>Off-net</fullName>
            </value>
            <value>
                <fullName>On-net</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Building_Access_Availability__c/Building_Access_Availability__c.object-meta.xml
<CustomObject>
    <label>Building Access Availability</label>
    <nameField>
        <label>Access Availability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building Access Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Building_Access_Availability__c/fields/Access_Technology__c.field-meta.xml
<CustomField>
    <fullName>Access_Technology__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Access Technology related to Access Method (one-to-one).</description>
    <label>Access Technology</label>
    <referenceTo>Access_Technology__c</referenceTo>
    <relationshipName>Access_Availabilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Building Access Availabilities</relationshipLabel>
    <relationshipName>Access_Availabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Net_Classification__c.field-meta.xml
<CustomField>
    <fullName>Net_Classification__c</fullName>
    <formula>Text(Building__r.Net_Classification__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Classification</label>
    <type>Text</type>
</CustomField>

objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OLI__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>Opportunity_Product__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity_BAA_Based_Action__c/Opportunity_BAA_Based_Action__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Perform an action on opportunity going to closed won based off of the opportunity&#39;s related BAAs</description>
    <label>Opportunity BAA Based Action</label>
</CustomObject>

main/default/objects/Opportunity_BAA_Based_Action__c/fields/Send_Task_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Task_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Task Email</label>
    <type>Checkbox</type>
</CustomField>

objects/Opportunity_BAA_Based_Action__c/fields/Task_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Task_Assignee__c</fullName>
    <description>Comma delimited valid values: Owner, InternalKickoffSalesChannelManager, RegionalAE, SalesEngineer or the name of a custom setting in ProcessConfiguration with key &quot;Assignee&quot; and NTID value
DOES NOT SEND IF NO VALUE FOUND</description>
    <label>Task Assignee</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Opportunity_BAA_Based_Action__c/fields/Task_Definition__c.field-meta.xml
<CustomField>
    <fullName>Task_Definition__c</fullName>
    <label>Task Definition</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

main/default/objects/Opportunity_BAA_Based_Action__c/fields/Task_Parent__c.field-meta.xml
<CustomField>
    <fullName>Task_Parent__c</fullName>
    <description>Valid options: Opportunity, Building or Order
Defaults to Order</description>
    <label>Task Parent</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Opportunity_Product__c/Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{0000000}</displayFormat>
        <label>Opportunity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Product__c/fields/Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product__c</fullName>
    <label>Sales Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access Service</fullName>
            </value>
            <value>
                <fullName>Basic Voice Services</fullName>
            </value>
            <value>
                <fullName>Broadband/DSL</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Cloud Firewall Service</fullName>
            </value>
            <value>
                <fullName>Collaboration &amp; Messaging</fullName>
            </value>
            <value>
                <fullName>Colocation Services</fullName>
            </value>
            <value>
                <fullName>Conference Now</fullName>
            </value>
            <value>
                <fullName>CPE MRR</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet</fullName>
            </value>
            <value>
                <fullName>DSL and/or Broadband</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LAN</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LINE Host Site</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LINE Remote Site</fullName>
            </value>
            <value>
                <fullName>Failover – Dedicated Internet</fullName>
            </value>
            <value>
                <fullName>Failover – VPN Solutions</fullName>
            </value>
            <value>
                <fullName>Hosted &amp; Managed PBX</fullName>
            </value>
            <value>
                <fullName>Hosted Voice Services</fullName>
            </value>
            <value>
                <fullName>ISDN/PRI</fullName>
            </value>
            <value>
                <fullName>ISP Services</fullName>
            </value>
            <value>
                <fullName>Legacy Voice or Integrated T1</fullName>
            </value>
            <value>
                <fullName>Long Distance</fullName>
            </value>
            <value>
                <fullName>Managed Prime/Pro</fullName>
            </value>
            <value>
                <fullName>Managed UC</fullName>
            </value>
            <value>
                <fullName>NAA</fullName>
            </value>
            <value>
                <fullName>Need A Product</fullName>
            </value>
            <value>
                <fullName>Network Security Suite</fullName>
            </value>
            <value>
                <fullName>Network Solutions</fullName>
            </value>
            <value>
                <fullName>NGN SIP Trunking</fullName>
            </value>
            <value>
                <fullName>Novus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Opportunity_Product_Task_Mapping__c/Opportunity_Product_Task_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Product Task Mapping</label>
</CustomObject>

objects/Opportunity_Product_Task_Mapping__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Opportunity_Product_Task_Mapping__c/fields/Task_Definition__c.field-meta.xml
<CustomField>
    <fullName>Task_Definition__c</fullName>
    <label>Task Definition</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Opportunity_Task_Definition__c/Opportunity_Task_Definition__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Task Definition</label>
</CustomObject>

main/default/objects/Opportunity_Task_Definition__c/fields/Task_Activity_Date_Offset__c.field-meta.xml
<CustomField>
    <fullName>Task_Activity_Date_Offset__c</fullName>
    <label>Task Activity Date Offset</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Opportunity_Task_Definition__c/fields/Task_Description__c.field-meta.xml
<CustomField>
    <fullName>Task_Description__c</fullName>
    <label>Task Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

objects/Opportunity_Task_Definition__c/fields/Task_Reminder_Date_Offset__c.field-meta.xml
<CustomField>
    <fullName>Task_Reminder_Date_Offset__c</fullName>
    <label>Task Reminder Date Offset</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Opportunity_Task_Definition__c/fields/Task_Subject__c.field-meta.xml
<CustomField>
    <fullName>Task_Subject__c</fullName>
    <label>Task Subject</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Opportunity_Task_Definition__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Process_Configuration__c/Process_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Process Configuration</label>
</CustomObject>

classes/Test_OpportunityTriggerTaskCreation.cls
@isTest
public with sharing class Test_OpportunityTriggerTaskCreation extends TestUtils.TestClass {
    
    static testMethod void testDetermineClosedWonTasksNeeded() {
        List<User> users = new List<User>();
        
        Mocks m = new Mocks();
		User u = m.user;
		
		Opportunity o = m.opportunity;
		Building__c b = m.building;
		List<OLI__c> olis = m.lstLineItems;
		Opportunity_Product__c opProd = m.opptyPrd;
		
		b.Net_Classification__c = 'On-net';
		update b;
		
		Access_Technology__c atech = new Access_Technology__c(Name='Test', Access_Technology_ID__c=2);	//EoF
		insert atech;
		
		Building_Access_Availability__c baa = new Building_Access_Availability__c(Building__c=b.Id, Access_Technology__c=atech.Id);
		insert baa;
		
		Opportunity_Task_Definition__c taskDef = new Opportunity_Task_Definition__c(Name='TestDef', Task_Subject__c='Subject', Task_Description__c='Description', Task_Type__c='TaskType', Task_Activity_Date_Offset__c=1, Task_Reminder_Date_Offset__c=1);
		insert taskDef;
		
		Process_Configuration__c pc = new Process_Configuration__c(Name='Test', Process__c='RegionAE', Key__c='Default', Value__c=u.NTID__c);
		insert pc;
		
		Opportunity_BAA_Based_Action__c bba = new Opportunity_BAA_Based_Action__c(Name='Test', Task_Assignee__c='RegionalAE,Owner', Task_Definition__c='TestDef', Task_Parent__c='Order', Send_Task_Email__c=true);
		insert bba;
		
		Opportunity_Product_Task_Mapping__c optm = new Opportunity_Product_Task_Mapping__c(Name='Test', Product_Name__c=opProd.Sales_Product__c, Task_Definition__c='TestDef');
		insert optm;
		
		test.startTest();
		
        OpportunityTriggerTaskCreation.determineClosedWonTasksNeeded(new Map<Id, Opportunity>{o.Id=>o});
		
		test.stopTest();
    }
	
    static testMethod void testCreateICertsFromOpportunitiesWon() {
        Mocks m = new Mocks();
		
		Opportunity_Location__c oppLoc = m.location;
		oppLoc.Term__c = '12';
		update oppLoc;
		
		Building__c b = m.building;
		b.Net_Classification__c = 'On-net';
		update b;
		
		Opportunity opp = m.opportunity;
		
		test.startTest();
		
		OpportunityTriggerTaskCreation.createICertsFromClosedWonOpportunities(new Set<Id>{opp.Id});
		
		test.stopTest();
	}
}