objects/Access_Technology__c/Access_Technology__c.object-meta.xml
<CustomObject>
    <label>Access Technology</label>
    <nameField>
        <label>Access Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Building_CLLI__c.field-meta.xml
<CustomField>
    <fullName>Building_CLLI__c</fullName>
    <label>Building CLLI</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <label>Building Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meet Point</fullName>
            </value>
            <value>
                <fullName>Commercial Building</fullName>
            </value>
            <value>
                <fullName>ILEC LSO</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Collocated</fullName>
            </value>
            <value>
                <fullName>ILEC Remote Switch</fullName>
            </value>
            <value>
                <fullName>Wireless MSC</fullName>
            </value>
            <value>
                <fullName>Wireless Tower</fullName>
            </value>
            <value>
                <fullName>Integra Hut/Shelter</fullName>
            </value>
            <value>
                <fullName>Pending Build</fullName>
            </value>
            <value>
                <fullName>Carrier POP</fullName>
            </value>
            <value>
                <fullName>Data Center</fullName>
            </value>
            <value>
                <fullName>Integra Switch/Hub</fullName>
            </value>
            <value>
                <fullName>Carrier Hotel</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Off Footprint</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Extended Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Address Component: City</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Is_Serving_LSO__c.field-meta.xml
<CustomField>
    <fullName>Is_Serving_LSO__c</fullName>
    <formula>IF(CASE(Building_Type__c, &#39;ILEC LSO: Collocated&#39;, 1, &#39;ILEC Remote Switch&#39;, 1, &#39;ILEC LSO: Extended&#39;, 1, &#39;ILEC LSO: Extended Special&#39;, 1,&#39;ILEC LSO: Off Footprint&#39;,1, &#39;Integra Switch/Hub&#39;,1, &#39;ILEC Remote Terminal&#39;,1,0) = 1, &#39;true&#39;, &#39;false&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Serving LSO</label>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Net_Classification__c.field-meta.xml
<CustomField>
    <fullName>Net_Classification__c</fullName>
    <label>Net Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eNNI</fullName>
            </value>
            <value>
                <fullName>ILEC</fullName>
            </value>
            <value>
                <fullName>Near-net</fullName>
            </value>
            <value>
                <fullName>Off-net</fullName>
            </value>
            <value>
                <fullName>On-net</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Building_Access_Availability__c/Building_Access_Availability__c.object-meta.xml
<CustomObject>
    <label>Building Access Availability</label>
    <nameField>
        <label>Access Availability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building Access Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Building_Access_Availability__c/fields/Access_Technology__c.field-meta.xml
<CustomField>
    <fullName>Access_Technology__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Access Technology related to Access Method (one-to-one).</description>
    <label>Access Technology</label>
    <referenceTo>Access_Technology__c</referenceTo>
    <relationshipName>Access_Availabilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Building Access Availabilities</relationshipLabel>
    <relationshipName>Access_Availabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Maximum_Bandwidth__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Bandwidth__c</fullName>
    <label>Maximum Bandwidth (Mbps)</label>
    <precision>7</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

objects/Building_Access_Availability__c/fields/Minimum_Required_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Required_Revenue__c</fullName>
    <label>Minimum Required Revenue</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Net_Classification__c.field-meta.xml
<CustomField>
    <fullName>Net_Classification__c</fullName>
    <formula>Text(Building__r.Net_Classification__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Classification</label>
    <type>Text</type>
</CustomField>

main/default/classes/BuildingEndPoint.cls
global class BuildingEndPoint {

    webservice static List<Building__c> GetBuildingByCLLI(string buildingCLLI){
        
        return [Select Id, Address__c, city__c,Is_Serving_LSO__c, Building_Type__c,net_classification__C, (select Maximum_Bandwidth__c, Minimum_Required_Revenue__c, Access_Technology__c from Access_Availabilities__r) from Building__c where Building_CLLI__c = :buildingCLLI];
        
    }

	webservice static Building__c GetBuildingByHash(string buildingHash){
        
        return AddressUtils.GetBuildingByHash(buildingHash);
        
    }

    //webservice static List<Building__c> GetBuildingByCLLIBasic(string buildingCLLI){
    //    return [Select Id, Address__c, city__c,Is_Serving_LSO__c, Building_Type__c from Building__c where Building_CLLI__c  = :buildingCLLI];
    //}


    
}