objects/Access_Technology__c/Access_Technology__c.object-meta.xml
<CustomObject>
    <label>Access Technology</label>
    <nameField>
        <label>Access Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Access_Technology__c/fields/Access_Technology_ID__c.field-meta.xml
<CustomField>
    <fullName>Access_Technology_ID__c</fullName>
    <description>External ID for Access Technologies</description>
    <externalId>true</externalId>
    <label>Access Technology ID</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Building__c/fields/Building_Hash__c.field-meta.xml
<CustomField>
    <fullName>Building_Hash__c</fullName>
    <externalId>true</externalId>
    <label>Building Hash</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Building__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <label>Building Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meet Point</fullName>
            </value>
            <value>
                <fullName>Commercial Building</fullName>
            </value>
            <value>
                <fullName>ILEC LSO</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Collocated</fullName>
            </value>
            <value>
                <fullName>ILEC Remote Switch</fullName>
            </value>
            <value>
                <fullName>Wireless MSC</fullName>
            </value>
            <value>
                <fullName>Wireless Tower</fullName>
            </value>
            <value>
                <fullName>Integra Hut/Shelter</fullName>
            </value>
            <value>
                <fullName>Pending Build</fullName>
            </value>
            <value>
                <fullName>Carrier POP</fullName>
            </value>
            <value>
                <fullName>Data Center</fullName>
            </value>
            <value>
                <fullName>Integra Switch/Hub</fullName>
            </value>
            <value>
                <fullName>Carrier Hotel</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Off Footprint</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Extended Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Building__c/fields/LSO_CLLI__c.field-meta.xml
<CustomField>
    <fullName>LSO_CLLI__c</fullName>
    <label>LSO CLLI</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

objects/Building_Access_Availability__c/Building_Access_Availability__c.object-meta.xml
<CustomObject>
    <label>Building Access Availability</label>
    <nameField>
        <label>Access Availability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building Access Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Building_Access_Availability__c/fields/Access_Technology__c.field-meta.xml
<CustomField>
    <fullName>Access_Technology__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Access Technology related to Access Method (one-to-one).</description>
    <label>Access Technology</label>
    <referenceTo>Access_Technology__c</referenceTo>
    <relationshipName>Access_Availabilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Building Access Availabilities</relationshipLabel>
    <relationshipName>Access_Availabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Maximum_Bandwidth__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Bandwidth__c</fullName>
    <label>Maximum Bandwidth (Mbps)</label>
    <precision>7</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

objects/Building_Access_Availability__c/fields/Minimum_Required_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Required_Revenue__c</fullName>
    <label>Minimum Required Revenue</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/classes/Test_AddressSelector.cls
@isTest
public with sharing class Test_AddressSelector extends TestUtils.TestClass{
 	
	static testMethod void testController() {
    	Mocks testData = new Mocks();
    	
    	Building__c b = testData.building;
    	b.LSO_CLLI__c = 'PTLDOR12';
    	b.Building_Type__c = 'ILEC LSO: Collocated';
		b.Building_Hash__c = 'testclassbuildinghash';
    	update b;
    	
		Access_Technology__c atech = new Access_Technology__c();
		atech.Access_Technology_ID__c = 123;
		atech.Name = 'EoF';
		insert atech;
		
		Building_access_availability__c baa = new Building_Access_Availability__c();
		baa.Access_Technology__c = atech.id;
		baa.Minimum_Required_Revenue__c = 0;
		baa.Maximum_Bandwidth__c = 800;
		baa.Building__c = b.id;
		insert baa;
		
    	//Create
    	Account a = new Account();
    	a.Name = 'Test Class Account';
		a.Billable__c = true;
    	a.Phone = '1234567890';
    	a.ShippingStreet = '1234 Test';
    	a.ShippingCity = 'Portland';
        //MNK Added Aug 2017
        a.ShippingCountryCode = 'US';
    	a.ShippingState = 'OR';
    	a.ShippingPostalCode = '97232';
    	insert a;
      	
        PageReference pageReference = Page.CreateBuildingUsingGoogleAddress;
        Test.setCurrentPage(pageReference);
		pageReference.getParameters().put('Id', a.Id);
		
		AddressSelectorController ascr = new AddressSelectorController();
		boolean canmanuallycreatebuilding = ascr.canManuallyCreateBuilding;
		ascr.readOnlyMode = false;
		ascr.accountID = a.Id;
		ascr.buildingID = b.Id;
		ascr.billable = false;
		
		AddressParser ap = new AddressParser();
		pageReference.getParameters().put('streetNumber', '1201');
		pageReference.getParameters().put('street', 'NE LLOYD BLVD');
		pageReference.getParameters().put('city', 'Portland');
        //MNK Added Aug 2017
        pageReference.getParameters().put('country', 'US');
		pageReference.getParameters().put('state', 'OR');
		pageReference.getParameters().put('postalCode', '97232');

		ascr.SearchBuildings();
		ascr.CreateLocOnExistingBuild();
		
		//error on no lat/lng
		ascr.ValidateBuildingAddress();
		
		pageReference.getParameters().put('latitude', '45.5296809');
		pageReference.getParameters().put('longitude', '-122.6532694');
		ascr.ValidateBuildingAddress();
		
		failLocView = true;
		ascr.ValidateBuildingAddress();
		
    }
    
	public static Boolean failLocView = false;
	
	public static integraWS.SFLocationView  SetupLocationTestData(integraWS.SFLocationView locView){
	 	locView.Success = true; 
        locView.BuildingHash = failLocView ? null : 'testclassbuildinghash';
        locView.LSOCLLI = 'PTLDOR12';
		integraws.ArrayOfLocationAccessAndBandwithResults al = new integraws.ArrayOfLocationAccessAndBandwithResults();
		al.LocationAccessAndBandwithResults = new List<integraWS.LocationAccessAndBandwithResults>();
		integraWS.LocationAccessAndBandwithResults v = new integraWS.LocationAccessAndBandwithResults();
		v.AvailiableBandwidth = 20000;
		v.AccessTechnologyID = 1;
		al.LocationAccessAndBandwithResults.add(v);
		locView.AccessAndBandwidthResults = al;
	
		return locView;
	}
    	
}