objects/Access_Technology__c/Access_Technology__c.object-meta.xml
<CustomObject>
    <label>Access Technology</label>
    <nameField>
        <label>Access Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Access_Technology__c/fields/Access_Technology_ID__c.field-meta.xml
<CustomField>
    <fullName>Access_Technology_ID__c</fullName>
    <description>External ID for Access Technologies</description>
    <externalId>true</externalId>
    <label>Access Technology ID</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Access_Types__c/Access_Types__c.object-meta.xml
<CustomObject>
    <label>Access Types</label>
    <nameField>
        <label>Access Types Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Access_Types__c/fields/Access_Technology__c.field-meta.xml
<CustomField>
    <fullName>Access_Technology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access Technology</label>
    <referenceTo>Access_Technology__c</referenceTo>
    <relationshipLabel>Access Types</relationshipLabel>
    <relationshipName>Access_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Address Component: City</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Area</label>
    <referenceTo>Market_Area__c</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings_del</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Building__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Address Component: State</description>
    <inlineHelpText>Use 2-digit abbreviation for State</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building_Access_Availability__c/Building_Access_Availability__c.object-meta.xml
<CustomObject>
    <label>Building Access Availability</label>
    <nameField>
        <label>Access Availability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building Access Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Building_Access_Availability__c/fields/Access_Technology__c.field-meta.xml
<CustomField>
    <fullName>Access_Technology__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Access Technology related to Access Method (one-to-one).</description>
    <label>Access Technology</label>
    <referenceTo>Access_Technology__c</referenceTo>
    <relationshipName>Access_Availabilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Building Access Availabilities</relationshipLabel>
    <relationshipName>Access_Availabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Building_Sales_Product__c/Building_Sales_Product__c.object-meta.xml
<CustomObject>
    <label>Building Sales Product</label>
    <nameField>
        <label>Building Sales Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building Sales Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Building_Sales_Product__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Building Sales Products</relationshipLabel>
    <relationshipName>Building_Sales_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Building_Sales_Product__c/fields/Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Product</label>
    <referenceTo>SalesProduct__c</referenceTo>
    <relationshipLabel>Building Sales Products</relationshipLabel>
    <relationshipName>Building_Sales_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Building_Sales_Product__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <formula>SPC_Product__r.SalesProductExternalID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SalesProductExternalID</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Product_Pricing__c/Product_Pricing__c.object-meta.xml
<CustomObject>
    <label>Product Pricing</label>
    <nameField>
        <label>Product Pricing</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Product_Pricing__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <label>Market Area</label>
    <referenceTo>Market_Area__c</referenceTo>
    <relationshipLabel>Product Pricing</relationshipLabel>
    <relationshipName>Sales_Rate_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Product_Pricing__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <formula>Sales_Product_Rate_Plan__r.Sales_Product__r.Product_Family__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

main/default/objects/Product_Pricing__c/fields/Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product__c</fullName>
    <formula>Sales_Product_Rate_Plan__r.Sales_Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Product</label>
    <type>Text</type>
</CustomField>

objects/Product_Pricing__c/fields/Sales_Product_Rate_Plan__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product_Rate_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Product Rate Plan</label>
    <referenceTo>Sales_Product_Rate_Plan__c</referenceTo>
    <relationshipLabel>Product Pricing</relationshipLabel>
    <relationshipName>Product_Pricing</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sales_Product_Rate_Plan__c/Sales_Product_Rate_Plan__c.object-meta.xml
<CustomObject>
    <label>Sales Product Rate Plan</label>
    <nameField>
        <displayFormat>SPRP-{0000}</displayFormat>
        <label>Sales Product Rate Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Sales_Product_Rate_Plan__c/fields/Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product__c</fullName>
    <label>Sales Product</label>
    <referenceTo>SalesProduct__c</referenceTo>
    <relationshipLabel>Sales Product Rate Plans</relationshipLabel>
    <relationshipName>Sales_Product_Rate_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/SalesProduct__c/SalesProduct__c.object-meta.xml
<CustomObject>
    <description>Products</description>
    <label>Sales Product</label>
    <nameField>
        <label>Sales Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SalesProduct__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <referenceTo>Product_Family__c</referenceTo>
    <relationshipLabel>Sales Products</relationshipLabel>
    <relationshipName>Sales_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/SalesProduct__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <description>Key field to Sales Product to source system</description>
    <externalId>true</externalId>
    <label>SalesProductExternalID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/SalesProductSalesFamily__c/SalesProductSalesFamily__c.object-meta.xml
<CustomObject>
    <description>Junction table between SalesProducts and ProductFamilies</description>
    <label>SalesProductSalesFamily</label>
    <nameField>
        <label>SalesProductSalesFamily Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesProductSalesFamily</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesProductSalesFamily__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Family</label>
    <referenceTo>Product_Family__c</referenceTo>
    <relationshipLabel>SalesProductSalesFamily</relationshipLabel>
    <relationshipName>SalesProductSalesFamily</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/SalesProductSalesFamily__c/fields/Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Product</label>
    <referenceTo>SalesProduct__c</referenceTo>
    <relationshipLabel>SalesProductSalesFamily</relationshipLabel>
    <relationshipName>SalesProductSalesFamily</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SPC_Product__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <externalId>true</externalId>
    <label>SalesProductExternalID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

main/default/classes/Test_CatalogEndpoint.cls
@isTest
public with sharing class Test_CatalogEndpoint extends TestUtils.TestClass {
	
	static testMethod void testEndpoint(){
		Mocks testData = new Mocks();
		test.startTest();
		
		CatalogEndpoint.PricingProductView ppv = new CatalogEndpoint.PricingProductView();
		CatalogEndpoint.SalesProductClliView spcv = new CatalogEndpoint.SalesProductClliView();
		CatalogEndpoint.BuildingAccessTypeView batv = new CatalogEndpoint.BuildingAccessTypeView();
		
		Sales_Product_Rate_Plan__c sprp = new Sales_Product_Rate_Plan__c(Sales_Product__r = new SalesProduct__c(SalesProductExternalID__c = '0', Product_Family__r = new Product_Family__c()));
		SalesProductSalesFamily__c spsf = new SalesProductSalesFamily__c(Product_Family__r=new Product_Family__c());
		Building__c b = new Building__c();
		CatalogEndpoint.SalesProductRatePlanView sprpv = new CatalogEndpoint.SalesProductRatePlanView(sprp, spsf, b);

		CatalogUtils.SPCPricingView spv = new CatalogUtils.SPCPricingView(new spc_pricing__c());
		CatalogUtils.DiscountAuthorityView dal = new CatalogUtils.DiscountAuthorityView(100,true,'Testing');
		CatalogUtils.GetProductFeaturePricing(new List<Integer>{2},10,'PLTDOR13','test',new List<Integer>{247},new List<Integer>{36});
		CatalogUtils.GetRelations(new List<OLI__c>());
		CatalogUtils.getRelationsByGroupByComponentId(new Set<Decimal>());
		CatalogUtils.getRelationsByGroupByProductId(new Set<Decimal>());


		QuoteWrapper.QuoteLineItem qli = new QuoteWrapper.QuoteLineItem();
		QuoteWrapper.getConfigFamilies(testData.lstconfig[0].Id);
		QuoteWrapper.sortListByProductname(new List<QuoteWrapper.ProductFamily>());
	}
	
	static testMethod void testGetAccessBandwidthSalesRatePlanInfo(){
       	CatalogEndpoint.GetAccessBandwidthSalesRatePlanInfo();
	}
	
	static testMethod void testGetActiveSPCProducts(){
		CatalogEndpoint.GetActiveSPCProducts();
	}
	
	static testMethod void testGetBuildingAccessTypeInfo(){
		CatalogEndpoint.GetBuildingAccessTypeInfo();
        
        test.startTest();
        Building__c Building = new Building__c(City__c = 'Toronto', State__c = 'ON', Address__c = '123 Address Street', Country__c = 'US');
        insert Building;
        Access_Technology__c ATech = new Access_Technology__c(Access_Technology_ID__c = 123);
        insert ATech;
        Building_Access_Availability__c BAA = new Building_Access_Availability__c(Building__c = Building.Id, Access_Technology__c = ATech.id);
        insert BAA;
        
        CatalogEndpoint.GetBuildingAccessTypeInfo();
        test.stopTest();
	}
	
	static testMethod void testGetPricingByPricingID(){
       	CatalogEndpoint.GetPricingByPricingID(new List<String>());
	}
	
	static testMethod void testGetPricingforProduct(){
		Mocks testdata = new Mocks();
		
		test.startTest();
        
        Market_Area__c MArea = new Market_Area__c(MarketAreaExternalID__c = '12345');
        insert MArea;
        
		Building__c b = testdata.building;
		b.Building_Type__c = 'ILEC LSO';
		b.LSO_CLLI__C = 'PTLDOR13';
        b.Market_Area__c = MArea.Id;
		update b;
        
        Product_Family__c family = new Product_Family__c(Name = 'Test', Description__c = '12345', ProductFamilyExternalId__c = '12345');
        insert family;
        SalesProduct__c prod = new SalesProduct__c(SalesProductExternalID__c = '147', Product_Family__c = family.Id);
        insert prod;
        Feature_Grouping__c FGroup = new Feature_Grouping__c(FeatureGroupExternalID__c = '12345');
        insert FGroup;
        Sales_Rate_Plan_Description__c PlanDesc = new Sales_Rate_Plan_Description__c(SalesRatePlanDescExternalID__c = '12345', Feature_Grouping__c = FGroup.Id);
        insert PlanDesc;
        Sales_Product_Rate_Plan__c plan = new Sales_Product_Rate_Plan__c(Sales_Product__c = prod.Id, Sales_Rate_Plan_Description__c = PlanDesc.Id,  SalesProductRatePlanExternalID__c = '12345', Bandwidth__c = null);
        insert plan;
        Product_Pricing__c sampleData = new Product_Pricing__c(
            Term__c = null,
            Expiration_Date__c = Datetime.now().addDays(5),
            Market_Area__c = MArea.Id,
            Sales_Product_Rate_Plan__c = plan.Id,
            SalesRatePlanPricingExternalID__c = '147'
        );
        insert sampleData;
        
        System.Assert(!CatalogEndpoint.GetPricingforProduct(new integer[]{147,50},'PTLDOR13',1,10,36).isEmpty());
		System.Assert(CatalogEndpoint.GetPricingforProduct(new integer[]{147,50},'FAKECLLI',1,10,36).isEmpty());
        System.Assert(!CatalogEndpoint.GetPricingforProduct(new integer[]{147},'PTLDOR13',null,null,null).isEmpty());
        
        test.stopTest();
	}
	
	static testMethod void testGetPricingforProductWithAncillaryProducts(){
		Mocks testdata = new Mocks();
		
		test.startTest();
        
        Market_Area__c MArea = new Market_Area__c(MarketAreaExternalID__c = '12345');
        insert MArea;
        
		Building__c b = testdata.building;
		b.Building_Type__c = 'ILEC LSO';
		b.LSO_CLLI__C = 'PTLDOR13';
        b.Market_Area__c = MArea.Id;
		update b;
        
        System.Assert(CatalogEndpoint.GetPricingforProductWithAncillaryProducts(new integer[]{147},'PTLDOR13',1,10,36,false).isEmpty());
        System.Assert(CatalogEndpoint.GetPricingforProductWithAncillaryProducts(new integer[]{147},'PTLDOR13',1,10,36,true).isEmpty());
                      
        Product_Family__c family = new Product_Family__c(Name = 'Test', Description__c = '12345', ProductFamilyExternalId__c = '12345');
        insert family;
        SalesProduct__c prod = new SalesProduct__c(SalesProductExternalID__c = '147', Product_Family__c = family.Id);
        insert prod;
        Feature_Grouping__c FGroup = new Feature_Grouping__c(FeatureGroupExternalID__c = '12345');
        insert FGroup;
        Sales_Rate_Plan_Description__c PlanDesc = new Sales_Rate_Plan_Description__c(SalesRatePlanDescExternalID__c = '12345', Feature_Grouping__c = FGroup.Id);
        insert PlanDesc;
        Sales_Product_Rate_Plan__c plan = new Sales_Product_Rate_Plan__c(Sales_Product__c = prod.Id, Sales_Rate_Plan_Description__c = PlanDesc.Id,  SalesProductRatePlanExternalID__c = '12345', Bandwidth__c = null);
        insert plan;
        Product_Pricing__c sampleData = new Product_Pricing__c(
            Term__c = null,
            Expiration_Date__c = Datetime.now().addDays(5),
            Market_Area__c = MArea.Id,
            Sales_Product_Rate_Plan__c = plan.Id,
            SalesRatePlanPricingExternalID__c = '147'
        );
        insert sampleData;
		               
        System.Assert(CatalogEndpoint.GetPricingforProductWithAncillaryProducts(new integer[]{147},'FAKECLLI',1,10,36,false).isEmpty());
        System.Assert(!CatalogEndpoint.GetPricingforProductWithAncillaryProducts(new integer[]{147},'PTLDOR13',null,null,null,false).isEmpty());
        
        test.stopTest();
	}
	
	static testMethod void testGetProductFamilies(){
       	CatalogEndpoint.GetProductFamilies();
	}
	
	static testMethod void testGetProductFamilyByID(){
        CatalogEndpoint.GetProductFamilyByID(43);
	}
	
	static testMethod void testGetProductFeaturePricing(){
		CatalogEndpoint.GetProductFeaturePricing(new List<Integer>(), 0, '', '', new List<Integer>(), new List<Integer>());
	}
	
	static testMethod void testGetSalesProductClliInfo(){
       	CatalogEndpoint.GetSalesProductClliInfo();
        
        test.startTest();
        Product_Family__c family = new Product_Family__c(Name = 'Test', Description__c = '12345', ProductFamilyExternalId__c = '12345');
        insert family;
        SalesProduct__c SaleProd = new SalesProduct__c(SalesProductExternalID__c = '12345', Product_Family__c = family.Id);
        insert SaleProd;
   		Building__c Building = new Building__c(City__c = 'Toronto', State__c = 'ON', Address__c = '123 Address Street', Country__c = 'US');
        insert Building;
        SPC_Product__c SPCProd = new SPC_Product__c(SalesProductExternalID__c = 12345);
        insert SPCProd;
        Building_Sales_Product__c BSaleProd = new Building_Sales_Product__c(Sales_Product__c = SaleProd.Id, Building__c = Building.Id, SPC_Product__c = SPCProd.Id);
        insert BSaleProd;
        
        CatalogEndpoint.GetSalesProductClliInfo();
        test.stopTest();
	}
	
	static testMethod void testGetSalesProductRatePlans(){
        CatalogEndpoint.AccessTechBandwidthView atbv = new CatalogEndpoint.AccessTechBandwidthView();
        atbv.AccessTechID = 6;
        atbv.Bandwidth = 10;
        
        test.startTest();
        
        Building__c Building = new Building__c(City__c = 'Toronto', State__c = 'ON', Address__c = '123 Address Street', Country__c = 'US', LSO_CLLI__C = 'PTLDOR13', Building_Type__c = 'ILEC LSO');
        insert Building;
        Access_Technology__c ATech = new Access_Technology__c(Access_Technology_ID__c = 123);
        insert ATech;
        Building_Access_Availability__c BAA = new Building_Access_Availability__c(Building__c = Building.Id, Access_Technology__c = ATech.id);
        insert BAA;
        Access_Types__c AType = new Access_Types__c(Access_Technology__c = ATech.Id, Access_Type_ID__c = 1);
        insert AType;
        
       	System.Assert(CatalogEndpoint.GetSalesProductRatePlans(new CatalogEndpoint.AccessTechBandwidthView[]{atbv}, 'PTLDOR13', 43).isEmpty());
		CatalogEndpoint.GetSalesProductRatePlans(new CatalogEndpoint.AccessTechBandwidthView[]{atbv}, '', 43);
        
        AType.Access_Type_ID__c = 7;
        update AType;
        CatalogEndpoint.GetSalesProductRatePlans(new CatalogEndpoint.AccessTechBandwidthView[]{atbv}, 'PTLDOR13', 43);
		AType.Access_Type_ID__c = 13;
        update AType;
        CatalogEndpoint.GetSalesProductRatePlans(new CatalogEndpoint.AccessTechBandwidthView[]{atbv}, 'PTLDOR13', 43);
        
        test.stopTest();
    }		
    
    static testMethod void testPricingProductView(){
        CatalogEndPoint.PricingProductView ppv = new CatalogEndPoint.PricingProductView();
        ppv.AccessTypeID = 6789;
        ppv.Bandwidth = 0.8517;
        ppv.MRR = 3.14159;
        ppv.NRR = 2.7132;
        ppv.ProductID = 1926734114;
        ppv.ProductName = 'NameOfProduct';
        ppv.RatePlanID = 10937892;
        ppv.RatePlanName = 'SomePlanName';
       	System.AssertEquals(ppv.AccessTypeID,6789);
        System.AssertEquals(ppv.Bandwidth,0.8517);
        System.AssertEquals(ppv.MRR,3.14159);
        System.AssertEquals(ppv.NRR,2.7132);
        System.AssertEquals(ppv.ProductID,1926734114);
        System.AssertEquals(ppv.ProductName,'NameOfProduct');
        System.AssertEquals(ppv.RatePlanID,10937892);
        System.AssertEquals(ppv.RatePlanName,'SomePlanName');
    }
    
    static testMethod void testSalesProductClliView(){
        CatalogEndpoint.SalesProductClliView spv = new CatalogEndpoint.SalesProductClliView();
        spv.LSOClli = 'Test';
        spv.SalesProductID = '01IC0000000tlmq';
        spv.BuildingID = '01IC0000000tlmq';
        spv.AccessTypes = new List<Decimal>{0.5,0.987};
        System.AssertEquals(spv.LSOClli,'Test');
        System.AssertEquals(spv.SalesProductID,'01IC0000000tlmq');
        System.AssertEquals(spv.BuildingID,'01IC0000000tlmq');
        System.AssertEquals(spv.AccessTypes, new List<Decimal>{0.5,0.987});
    }
}