objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Toggles whether a location is on hold.</description>
    <inlineHelpText>Toggles whether a location is on hold.</inlineHelpText>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

classes/Test_OpportunityLocationTriggers.cls
@isTest
public with sharing class Test_OpportunityLocationTriggers {
	
    static testMethod void testOpportunityLocationTrigger() {
    	OpportunityLocationTrigger oppLocator = new OpportunityLocationTrigger();
    	test.startTest();
    	
    	Mocks testData = new Mocks();

    	Opportunity_Location__c ol = testData.Location;
    	List<Opportunity_Location__c> ols = new List<Opportunity_Location__c>();
    	ols.add(ol);
    	Map<Id,Opportunity_Location__c> moloc = new Map<Id,Opportunity_Location__c>();

    	for(Opportunity_Location__c loc : ols){    		
    		moloc.put(loc.Id, loc);
    	}
    	Map<Id,Opportunity_Location__c> molocClone = moloc.deepClone();
    	List<Opportunity_Location__c> mol = new List<Opportunity_Location__c>();

		for(Opportunity_Location__c oppLoc : molocClone.values()) {
			oppLoc.On_Hold__c = true;
			mol.add(oppLoc);
		}
		 	
		update mol;
    	//OpportunityLocationTrigger.OpportunityLocationModified(molocClone, moloc, true, true);
    	
    	//OpportunityLocationTrigger.UpdateChangeOpportunity(molocClone);
    	test.stopTest();
    }
}