objects/Integration_Error__c/Integration_Error__c.object-meta.xml
<CustomObject>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Integration_Error__c/fields/ObjectID__c.field-meta.xml
<CustomField>
    <fullName>ObjectID__c</fullName>
    <label>ObjectID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/classes/Schedule_IntegrationErrorsRetry.cls
public without sharing class Schedule_IntegrationErrorsRetry implements Schedulable {
	public void execute(SchedulableContext sc) {
		retryIntegrationErrors();
	}
	
	public static void retryIntegrationErrors(){
		Set<String> ids = new Set<String>();
		for(Integration_Error__c error : [select ObjectID__c from Integration_Error__c limit 2000])
			ids.add(error.ObjectID__c);
		
		if(ids.size() > 0)
			IntegrationUtils.reintegrateObjects(ids);
	}
}