objects/Integration_Error__c/Integration_Error__c.object-meta.xml
<CustomObject>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Integration_Error__c/fields/ObjectID__c.field-meta.xml
<CustomField>
    <fullName>ObjectID__c</fullName>
    <label>ObjectID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Survey__c/fields/Survey_Name__c.field-meta.xml
<CustomField>
    <fullName>Survey_Name__c</fullName>
    <label>Survey Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

main/default/classes/Test_SurveyErrorsController.cls
@isTest
public class Test_SurveyErrorsController { 
	static testMethod void testSurveyErrors(){
		mocks testData = new Mocks();
		Survey__c s = new Survey__c();
		s.Account__c = testData.parentAccount.Id;
		s.Survey_Name__c = 'Test Name';
		insert s;

		Integration_Error__c e = new Integration_Error__c();
		e.ObjectID__c = s.Id;
		insert e;

		test.startTest();
		SurveyErrorsController sec = new SurveyErrorsController();
		sec.resendSurveys();
		sec.errorID = e.Id;
		sec.resendSingle();
		test.stopTest();
	}
}