objects/Integration_Error__c/Integration_Error__c.object-meta.xml
<CustomObject>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Integration_Error__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <description>This is a general purpose field for storing what we were trying to do when integrating when we failed.  Both Action and the related object are taken into account when reading the values here:

Object(Action): Value
---------------------
Account(Update): Comma delimited field names
Contact(Update): N/A
Contact(Delete): ICC Contact ID
Service Location(Insert): Closed Won Opportunity ID (earliest closed date)
Service Location(Update): Comma delimited field names</description>
    <label>Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Integration_Error__c/fields/ObjectID__c.field-meta.xml
<CustomField>
    <fullName>ObjectID__c</fullName>
    <label>ObjectID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/Integration_Error__c/fields/RelatedID__c.field-meta.xml
<CustomField>
    <fullName>RelatedID__c</fullName>
    <label>RelatedID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/classes/SurveyErrorsController.cls
public with sharing class SurveyErrorsController{

	public List<Integration_Error__c> errors {get;set;}
	
	private String surveyIdPrefix = Survey__c.sobjectType.getDescribe().getKeyPrefix() + '%';

	public SurveyErrorsController(){
		getData();
	}
	
	private void getData(){
		errors = new List<Integration_Error__c>();
		for(Integration_Error__c error : [select Id, Name, ObjectID__c, Info__c, Message__c, RelatedID__c, CreatedDate from Integration_Error__c where ObjectID__c like :surveyIdPrefix limit 1000]){
    		errors.add(error);
    	}
	}
	
	public PageReference resendSurveys(){
		CustomerSurveyUtils.resendFailedSurveys(errors);
		getData();
		return null;
	}
	
	public Id errorID {get; set;}
	public PageReference resendSingle(){
		Integration_Error__c oneToSend = null;
		for(Integration_Error__c e : errors){
			if(e.Id == errorID){
				oneToSend = e;
				break;
			}
		}
		if(oneToSend != null)
		CustomerSurveyUtils.resendFailedSurveys(new List<Integration_Error__c>{oneToSend});
		getData();
		return null;
	}
}