main/default/objects/Feature_Duration__c/Feature_Duration__c.object-meta.xml
<CustomObject>
    <label>Feature Duration</label>
    <nameField>
        <label>Feature Duration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feature Durations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Feature_Duration__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Feature_Duration__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <referenceTo>Feature__c</referenceTo>
    <relationshipLabel>Feature Durations</relationshipLabel>
    <relationshipName>Feature_Durations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>LD</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
            <value>
                <fullName>TF</fullName>
            </value>
            <value>
                <fullName>Traditional Voice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Contract Renewal Orders</description>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Provisioning_Product__c/Provisioning_Product__c.object-meta.xml
<CustomObject>
    <label>Provisioning Product</label>
    <nameField>
        <label>Provisioning Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provisioning Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Provisioning_Product__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SPC_Product__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>SPC Products</relationshipLabel>
    <relationshipName>SPC_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SPC_Product__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <externalId>true</externalId>
    <label>SalesProductExternalID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Sub Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

objects/Sub_Order_Feature__c/Sub_Order_Feature__c.object-meta.xml
<CustomObject>
    <label>Sub-Order Feature</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sub-Order Feature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub-Order Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order_Feature__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <referenceTo>Feature__c</referenceTo>
    <relationshipName>SubOrder_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sub_Order_Feature__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Sub-Order Features</relationshipLabel>
    <relationshipName>Sub_Order_Features</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sub_Order_Group__c/Sub_Order_Group__c.object-meta.xml
<CustomObject>
    <label>Sub-Order Group</label>
    <nameField>
        <label>Sub-Order Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Order Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order_Group__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Sub_Order_Group__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Sub_Order_Group__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Sub-Order Groups</relationshipLabel>
    <relationshipName>Sub_Order_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Workstep__c/Workstep__c.object-meta.xml
<CustomObject>
    <label>Workstep</label>
    <nameField>
        <label>Worksteps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Worksteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workstep__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <formula>Workstep_Library__r.External_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Workstep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Workstep__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Workstep__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <formula>Sub_Order__r.SPC_Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SPC Product</label>
    <type>Text</type>
</CustomField>

objects/Workstep__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sub-Order</label>
    <referenceTo>Sub_Order__c</referenceTo>
    <relationshipLabel>Worksteps</relationshipLabel>
    <relationshipName>Worksteps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Workstep_Issue__c/Workstep_Issue__c.object-meta.xml
<CustomObject>
    <label>Workstep Issue</label>
    <nameField>
        <displayFormat>WI-{0000}</displayFormat>
        <label>Workstep Issues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workstep Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Workstep_Issue__c/fields/Sub_Order__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order__c</fullName>
    <formula>HYPERLINK( 
Workstep__r.Sub_Order__r.Id, 
Workstep__r.Sub_Order__r.Name )</formula>
    <label>Sub-Order</label>
    <type>Text</type>
</CustomField>

main/default/objects/Workstep_Issue__c/fields/Workstep__c.field-meta.xml
<CustomField>
    <fullName>Workstep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workstep</label>
    <referenceTo>Workstep__c</referenceTo>
    <relationshipLabel>Workstep Issues</relationshipLabel>
    <relationshipName>Workstep_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/Test_SubOrderTriggers.cls
@isTest
public with sharing class Test_SubOrderTriggers {
    
    static testMethod void testTriggers() {
        Mocks testData = new Mocks();
        Test.startTest();
        
        Opportunity opp = testData.opportunity;
        Order__c ord = new Order__c(Opportunity__c = opp.Id);
        insert ord;
        
        SPC_Product__c spc = new SPC_Product__c(
            SalesProductExternalID__c = -1
            ,Provisioning_Product__c = testData.mpProvProd.get('Standard').Id
        );
        insert spc;
        
        Sub_Order__c so = new Sub_Order__c(
            Service_Location__c = testData.serviceLocation.Id
            ,Order__c = ord.Id
            ,SPC_Product__c = spc.Id
            ,Workplan_Start_Date__c = Date.today()
            ,Provisioning_Product__c = testData.mpProvProd.get('Standard').Id
        );
        insert so;
        
        Feature__c f = new Feature__c(
            External_ID__c = -1
        );
        insert f;
        
        Feature_Duration__c fd = new Feature_Duration__c(
            External_ID__c = -1
            ,Feature__c = f.Id
        );
        insert fd;
        
        Sub_Order_Feature__c sof = new Sub_Order_Feature__c(
            Sub_Order__c = so.Id
            ,Feature__c = f.Id
        );
        insert sof;
        
        Sub_Order_Group__c sog = new Sub_Order_Group__c(
            Sub_Order__c = so.Id
            ,Quantity__c = 10
            ,Product__c = 'The Pickles'
        );
        insert sog;
        
        Workstep__c ws = new Workstep__c (Status__c = 'Open', Order__c = ord.Id, Sub_Order__c = so.Id);		
        insert ws;		
        
        so.Provisioning_Product__c = testData.mpProvProd.get('BO').Id;		
        update so;
        
        test.stopTest();
    }
    
    static testmethod void testhandleProvisioningProductUpdates(){
        Mocks Testdata = new Mocks();
        Test.startTest();
        
        Provisioning_Product__c pp = new Provisioning_Product__c();
        insert pp;
        
        Workstep__c ws = new Workstep__c(Status__c = 'Complete', Order__c = Testdata.order.Id, Sub_Order__c = Testdata.suborder.Id);
        insert ws;
        
        try{
            Testdata.suborder.Provisioning_Product__c = pp.Id;
            update Testdata.suborder;
        }
        catch (Exception e){
            System.assert(e.getMessage().contains('The provisioning product cannot be changed because the current workstep process has been started'));
        }
        Test.stopTest();        
    }
    
    static testmethod void testevaluateSubOrder(){
        Mocks Testdata = new Mocks();
        Test.startTest();  
        
        Workstep_Library__c wsl = new Workstep_Library__c(
            Start_Date_Driving_Fields__c = 'Sub_Order__c.Install_Date__c',
            Anti_Workstep__c = true
        );
        insert wsl;
        
        Access_Types__c aT = new Access_Types__c(Access_Type_ID__c = 1, Access_Technology__c = Testdata.accessTec.Id);
        insert aT;
        
        Workstep__c ws = new Workstep__c(Status__c = 'Blocked', Order__c = Testdata.order.Id, Sub_Order__c = Testdata.suborder.Id, Workstep_Library__c = wsl.Id);
        insert ws;
        
        Workstep_Issue__c wsi = new Workstep_Issue__c(Workstep__c = ws.Id);
        insert wsi;
        
        Testdata.suborder.Install_Date__c = Datetime.Now().addDays(7);
        Testdata.suborder.Status__c = 'Cancelled';
        Testdata.suborder.Access_Types__c = aT.Id;
        update Testdata.suborder;
        
        Test.stopTest();
    }    
}