objects/ICB__c/ICB__c.object-meta.xml
<CustomObject>
    <description>Custom object to better track Individual Case Basis requests</description>
    <label>ICB</label>
    <nameField>
        <displayFormat>ICB Request-{000000}</displayFormat>
        <label>ICB Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICBs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/ICB__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The account that this ICB is associated with</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ICBs</relationshipLabel>
    <relationshipName>ICB_RequestsToAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/ICB__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Field used for reporting for the users who cannot see Administrative reports and therefore cannot see all pending requests.  This field will be set by Field Update in the Approval processes and by a workflow rule.</description>
    <inlineHelpText>System Maintained Field: Displays current status or step in the approval process.</inlineHelpText>
    <label>Approval Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/ICB__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Enter an overall description of why you&#39;re requesting this ICB (2500 characters max)</inlineHelpText>
    <label>Description</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

objects/ICB__c/fields/ICB_Pricing_Reason__c.field-meta.xml
<CustomField>
    <fullName>ICB_Pricing_Reason__c</fullName>
    <description>Reason for Pricing  ICB that AE selects.</description>
    <inlineHelpText>Select a reason for your Pricing ICB (AE Selects)</inlineHelpText>
    <label>ICB Pricing Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ICB_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Competitive Response</fullName>
            </value>
            <value>
                <fullName>CPQ Required Quote</fullName>
            </value>
            <value>
                <fullName>Customer Incentive</fullName>
            </value>
            <value>
                <fullName>ETF Program</fullName>
            </value>
            <value>
                <fullName>Inside Wiring - Integra Provided</fullName>
            </value>
            <value>
                <fullName>Move Request</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other Program</fullName>
            </value>
            <value>
                <fullName>Price Schedule</fullName>
            </value>
            <value>
                <fullName>Renewal Request</fullName>
            </value>
            <value>
                <fullName>Signed Contract</fullName>
            </value>
            <value>
                <fullName>Temporary Service</fullName>
            </value>
            <value>
                <fullName>Usage-Based Internet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ICB__c/fields/ICB_Type__c.field-meta.xml
<CustomField>
    <fullName>ICB_Type__c</fullName>
    <description>First means of dialing in the workflow based on Pricing or Technical ICB needs</description>
    <inlineHelpText>Pick One!</inlineHelpText>
    <label>ICB Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ICB__c/fields/Pricing_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricing Agreement</label>
    <referenceTo>Pricing_Agreement__c</referenceTo>
    <relationshipLabel>ICBs</relationshipLabel>
    <relationshipName>ICBs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/ICB__c/fields/Sales_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Sales_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales Engineer associated to this ICB</description>
    <inlineHelpText>Sales Engineer associated to this ICB</inlineHelpText>
    <label>Sales Engineer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Title</field>
            <operation>contains</operation>
            <value>Sales Engineer</value>
        </filterItems>
        <infoMessage>Type part or all of a name to find a Sales Engineer.  If you don&#39;t see who you are looking for, click on Show all Results and try again.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>ICB_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/ICB__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>System Maintained Status of the ICB</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved-Pending Sale</fullName>
            </value>
            <value>
                <fullName>Approved with Conditions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Pricing_Agreement__c/Pricing_Agreement__c.object-meta.xml
<CustomObject>
    <label>Wholesale Pricing Agreement</label>
    <nameField>
        <label>Pricing Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale Pricing Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pricing_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wholesale Pricing Agreements</relationshipLabel>
    <relationshipName>Pricing_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Pricing_Agreement__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/Test_PricingAgreementTriggers.cls
@isTest
public with sharing class Test_PricingAgreementTriggers {
    
	static testmethod void testTriggers(){
		Mocks testData = new Mocks();
        User u = getStandardUser();  
        Account a = testData.parentAccount;
                
        Test.startTest(); 
        Pricing_Agreement__c pa = new Pricing_Agreement__c(Account__c = a.Id, Approval_Status__c ='Approval Required');
        insert pa;        
        
        ICB__c icb = new ICB__c();
        icb.ICB_Type__c = 'Pricing';
        icb.Description__c = 'This is a test pricing request for unit testing ICB triggers';
        icb.ICB_Pricing_Reason__c = 'Capital Build';
        icb.Account__c = a.Id;
        icb.Pricing_Agreement__c = pa.Id;
        icb.Sales_Engineer__c = u.Id;
        icb.status__c = 'Approved-Pending Sale';
        
        insert icb;
        
        pa.Approval_Status__c ='Approved';
        update pa;

        Test.stopTest();
    }
    
    
    private static User getStandardUser(){
		return [SELECT Title, Id, Username, Name FROM User WHERE IsActive = true AND UserType LIKE:'%Standard%' LIMIT 1];
    }



}