objects/ICB__c/ICB__c.object-meta.xml
<CustomObject>
    <description>Custom object to better track Individual Case Basis requests</description>
    <label>ICB</label>
    <nameField>
        <displayFormat>ICB Request-{000000}</displayFormat>
        <label>ICB Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICBs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/ICB__c/fields/AccountExecutive__c.field-meta.xml
<CustomField>
    <fullName>AccountExecutive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>AE associated to an ICB - possibly the one creating the ICB</description>
    <inlineHelpText>AE associated to an ICB - possibly the one creating the ICB</inlineHelpText>
    <label>Account Executive</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Sales</value>
        </filterItems>
        <infoMessage>Filtered on AEs, search all if needed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>ICB_RequestsToUserForAE</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ICB__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Opportunity object.</description>
    <inlineHelpText>Associate this ICB Request to the Opportunity.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>ICB_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/ICB__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Same picklist field as the Opportunity.  Needed for another dependent picklist.</description>
    <inlineHelpText>Same picklist field as the Opportunity. This field will default based on the product selected on the opportunity.  If you require an ICB for multiple products please create an ICB for each product and select something other than the default as needed.</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ICB_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIP</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>Traditional Voice</fullName>
            </value>
            <value>
                <fullName>Access Service</fullName>
                <isActive>false</isActive>
                <label>Access Service</label>
            </value>
            <value>
                <fullName>Basic Voice Services</fullName>
                <isActive>false</isActive>
                <label>Basic Voice Services</label>
            </value>
            <value>
                <fullName>Broadband Bundle</fullName>
                <isActive>false</isActive>
                <label>Broadband Bundle</label>
            </value>
            <value>
                <fullName>Business Connect Bundles</fullName>
                <isActive>false</isActive>
                <label>Business Connect Bundles</label>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
                <isActive>false</isActive>
                <label>Cloud Connect</label>
            </value>
            <value>
                <fullName>Cloud Firewall Service</fullName>
                <isActive>false</isActive>
                <label>Cloud Firewall Service</label>
            </value>
            <value>
                <fullName>Collaboration &amp; Messaging</fullName>
                <isActive>false</isActive>
                <label>Collaboration &amp; Messaging</label>
            </value>
            <value>
                <fullName>Colocation Services</fullName>
                <isActive>false</isActive>
                <label>Colocation Services</label>
            </value>
            <value>
                <fullName>Conference Now</fullName>
                <isActive>false</isActive>
                <label>Conference Now</label>
            </value>
            <value>
                <fullName>DDoS Mitigation Service</fullName>
                <isActive>false</isActive>
                <label>DDoS Mitigation Service</label>
            </value>
            <value>
                <fullName>DSL/Broadband</fullName>
                <isActive>false</isActive>
                <label>DSL/Broadband</label>
            </value>
            <value>
                <fullName>DSL/Broadband w/Voice</fullName>
                <isActive>false</isActive>
                <label>DSL/Broadband w/Voice</label>
            </value>
            <value>
                <fullName>Dark Fiber</fullName>
                <isActive>false</isActive>
                <label>Dark Fiber</label>
            </value>
            <value>
                <fullName>Dark Fiber (ICB Required)</fullName>
                <isActive>false</isActive>
                <label>Dark Fiber (ICB Required)</label>
            </value>
            <value>
                <fullName>Dedicated DSL/Broadband</fullName>
                <isActive>false</isActive>
                <label>Dedicated DSL/Broadband</label>
            </value>
            <value>
                <fullName>Dedicated HS Internet - Usage-Based</fullName>
                <isActive>false</isActive>
                <label>Dedicated HS Internet - Usage-Based</label>
            </value>
            <value>
                <fullName>Dedicated High-Speed Internet</fullName>
                <isActive>false</isActive>
                <label>Dedicated High-Speed Internet</label>
            </value>
            <value>
                <fullName>Dedicated Internet</fullName>
                <isActive>false</isActive>
                <label>Dedicated Internet</label>
            </value>
            <value>
                <fullName>Dedicated Internet Access</fullName>
                <isActive>false</isActive>
                <label>Dedicated Internet Access</label>
            </value>
            <value>
                <fullName>Dedicated Internet-Usage Based</fullName>
                <isActive>false</isActive>
                <label>Dedicated Internet-Usage Based</label>
            </value>
            <value>
                <fullName>Ethernet Private Line (E-Line)</fullName>
                <isActive>false</isActive>
                <label>Ethernet Private Line (E-Line)</label>
            </value>
            <value>
                <fullName>Ethernet Services E-LAN</fullName>
                <isActive>false</isActive>
                <label>Ethernet Services E-LAN</label>
            </value>
            <value>
                <fullName>Ethernet Services E-LINE</fullName>
                <isActive>false</isActive>
                <label>Ethernet Services E-LINE</label>
            </value>
            <value>
                <fullName>Ethernet Virtual Private Line (E-Line)</fullName>
                <isActive>false</isActive>
                <label>Ethernet Virtual Private Line (E-Line)</label>
            </value>
            <value>
                <fullName>Hosted PBX</fullName>
                <isActive>false</isActive>
                <label>Hosted PBX</label>
            </value>
            <value>
                <fullName>Hosted Voice Services</fullName>
                <isActive>false</isActive>
                <label>Hosted Voice Services</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ICB__c/fields/Product_Manager__c.field-meta.xml
<CustomField>
    <fullName>Product_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product Manager for this ICB based on the Product selected.  Populated by Trigger.</description>
    <inlineHelpText>System Maintained:  Product Manager for this ICB based on the Product selected</inlineHelpText>
    <label>Product Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ICB</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/ICB__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>&quot;Contract Term&quot; value from the related Opportunity</description>
    <inlineHelpText>This is the &quot;Contract Term&quot; value from the related Opportunity</inlineHelpText>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ICBProduct__c/ICBProduct__c.object-meta.xml
<CustomObject>
    <description>Temporary object to store the Product and corresponding Product Manager that is used by the ICB process.  Eventually this object should be eliminated and we should use the Product object after CPQ has undergone some work.</description>
    <label>ICB Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICBProduct</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

main/default/objects/ICBProduct__c/fields/ProductManager__c.field-meta.xml
<CustomField>
    <fullName>ProductManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to User object for the Product Manager for this product.</description>
    <inlineHelpText>Select the Product Manager responsible for this Product.</inlineHelpText>
    <label>Product Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProductProductManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/ICBTriggers.cls
public without sharing class ICBTriggers {  
    
    //pub prop
    public static Map<Id, Opportunity> OpportunityMap {get; set;}
    public static Map<Id, OpportunityTeamMember> MemberMap {get; set;}
    
    //pri prop
    private static Set<Id> idset {get; set;}
    private static Set<string> stringset{get;set;}
    private static final String TEST_VIOLATION_MSG = 'This method can only be called from a test.';
    
    public static void updateFormFields(List<ICB__c> newICBs, Boolean isUpdate){
        
        
        Init(newICBs);

        setProductManager(newICBs); 
        setAccountExecutive(newICBs);
        
        if(!isUpdate){
            setTermValue(newICBs);
        }   
    }
    
    public static void Init(List<ICB__c> icbs){
        
        setRelationMaps(getRelationOpportunityIdSet(icbs));
        
    }
    
    public static void setTermValue(List<ICB__c> icbs){     
        for(ICB__c icb : icbs){
                        
            if(icb.Opportunity__c == null) continue;            
            icb.Term__c = OpportunityMap.get(icb.Opportunity__c).Term__c;
            
        }
    }
    
    public static void setAccountExecutive(List<ICB__c> icbs){
        
        for(ICB__c icb : icbs){
            
            if(icb.Opportunity__c == null) continue;
            icb.AccountExecutive__c = OpportunityMap.get(icb.Opportunity__c).OwnerId;
            
        }
    }
    
        public static void setProductManager(List<ICB__c> icbs){
        
        stringset = new Set<string>();
                
        for(ICB__c icb : icbs){
            if(!String.IsEmpty(icb.Product__c)){
                string v = icb.Product__c;
                stringset.add(v.normalizeSpace());              
            }
        }
        
        Map<string, ICBProduct__c> products = new Map<string, ICBProduct__c>(); 
            
        List<ICBProduct__c> items = [SELECT Id, Name, ProductManager__c FROM ICBProduct__c WHERE IsDeleted != true AND Name IN: stringset];
        
        for(ICBProduct__c item : items){
            products.put(item.Name, item);
        }
        
        for(ICB__c icb : icbs){
            if(products.containsKey(icb.Product__c)){
                icb.Product_Manager__c = products.get(icb.Product__c).ProductManager__c;                
            }
        }       
    }
    
    //private methods
    private static void setRelationMaps(Set<Id> ids){
        
        OpportunityMap = new Map<Id, Opportunity>();
        MemberMap = new Map<Id, OpportunityTeamMember>();
        
        for(Opportunity o : [SELECT Id, Name, OwnerId, Term__c, (SELECT Id, UserId, OpportunityId from OpportunityTeamMembers WHERE TeamMemberRole = 'Sales Engineer') FROM Opportunity WHERE Id IN:ids]){
            OpportunityMap.put(o.Id, o);
            
            for(OpportunityTeamMember m : o.OpportunityTeamMembers){
                MemberMap.put(m.OpportunityId, m);
            }
        }
    }
    

    private static Set<Id> getRelationOpportunityIdSet(List<ICB__c> icbs){
        
        idset = new Set<id>();
        
        //load opportunity id set reference
        for(ICB__c icb : icbs){
            idset.add(icb.Opportunity__c);
        }
        system.debug(idset);
        
        return idset;
    }
    
    //private method test wrappers  
    public static Set<Id> test_getRelationOpportunityIdSet(List<ICB__c> icbs){
        return test.isRunningTest() ? getRelationOpportunityIdSet(icbs) : null;
    }
    
    public static void test_setRelationMaps(Set<Id> ids){
        if(test.isRunningTest())
        	setRelationMaps(ids);
        
    }
}