objects/ICB__c/ICB__c.object-meta.xml
<CustomObject>
    <description>Custom object to better track Individual Case Basis requests</description>
    <label>ICB</label>
    <nameField>
        <displayFormat>ICB Request-{000000}</displayFormat>
        <label>ICB Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICBs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ICB__c/fields/Number_of_Months__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Months__c</fullName>
    <description>Number of months of MRC to be credited</description>
    <inlineHelpText>If Free Month(s) Incentive Credit is selected, enter the number of months to credit.</inlineHelpText>
    <label>Number of Months</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>one (1)</fullName>
            </value>
            <value>
                <fullName>two (2)</fullName>
            </value>
            <value>
                <fullName>three (3)</fullName>
            </value>
            <value>
                <fullName>four (4)</fullName>
            </value>
            <value>
                <fullName>five (5)</fullName>
            </value>
            <value>
                <fullName>six (6)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ICB__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Opportunity object.</description>
    <inlineHelpText>Associate this ICB Request to the Opportunity.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>ICB_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ICB__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Service Location for Off-Net Quoting Request</description>
    <inlineHelpText>Service Location for Off-Net Quoting Request</inlineHelpText>
    <label>Service Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>ICBs (Location)</relationshipLabel>
    <relationshipName>ICBs1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/ICB__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>&quot;Contract Term&quot; value from the related Opportunity</description>
    <inlineHelpText>This is the &quot;Contract Term&quot; value from the related Opportunity</inlineHelpText>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/IncentiveCreditText__c/IncentiveCreditText__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>IncentiveCreditText</label>
</CustomObject>

main/default/objects/IncentiveCreditText__c/fields/Credit_Text__c.field-meta.xml
<CustomField>
    <fullName>Credit_Text__c</fullName>
    <label>Credit Text</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/IncentiveCreditText__c/fields/Number_of_Months__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Months__c</fullName>
    <label>Number of Months</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/IncentiveCreditText__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Toggles whether a location is on hold.</description>
    <inlineHelpText>Toggles whether a location is on hold.</inlineHelpText>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OpportunityLocationConfiguration__c/OpportunityLocationConfiguration__c.object-meta.xml
<CustomObject>
    <description>A configuration for an OpportunityLocation.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityLocationConfiguration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Opportunity_Location__r.Opportunity__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

objects/OpportunityLocationConfiguration__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Solutions</relationshipLabel>
    <relationshipName>OpportunityLocationConfigurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/OpportunityLocationConfiguration__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
                <default>true</default>
                <label>24</label>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>Month to Month</fullName>
            </value>
            <value>
                <fullName>Coterminous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Technical_Information__c/Technical_Information__c.object-meta.xml
<CustomObject>
    <label>Technical Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Technical_Information__c/fields/Current_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Current_Service_Provider__c</fullName>
    <label>Current Service Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Technical_Information__c/fields/Opportunity_Site__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Technical Information</relationshipLabel>
    <relationshipName>Technical_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ProposalGenericController.cls
public with sharing class ProposalGenericController {

    public CompanyInfo clientMainAddress {get;set;}
    public Date currentdate {get;set;}
    public String currentDayOrdinal {get;set;}
    public String currentMonthName {get;set;}
    public String currentDay {get;set;}
    public String currentYear {get;set;}
	public List<OpportunityLocationConfiguration__c> locations { get; set; }
	public String techInfo {get;set;}
	public ICB__C icb {get;Set;}
    public Opportunity currentOpportunity {
	    get{
            return currentOpportunity;
        }   
        set {
            currentdate = Date.Today();
            clientMainAddress = new CompanyInfo(value.Account);
            currentOpportunity = value;
            getLocationsForOpportunity();
	        }     
    }

	public class PDFException extends Exception {}
	
	public IncentiveCreditText__c iCText{
		get{
			System.debug('ICB : ' + icb);
			System.debug('No months: ' + icb.Number_Of_Months__c);
			System.debug('Term: ' + currentOpportunity.term__c);
			for(IncentiveCreditText__c ict  : [Select Credit_Text__c From IncentiveCreditText__c Where Number_of_Months__c = :icb.Number_of_Months__c and Term__c = :currentOpportunity.term__c]){
				return ict;
			}
			
			//return default if we don't find a valid combo
			throw new PDFException('Incentive Credit Addendum Error: Invalid combination of month\'s credit for term length. Please ensure Opportunity "Contract Term" field is set and Incentive Credit on ICB is set to a valid option.');
		}
		
	}
	
	public ProposalGenericController() {
   	 
        DateTime d = datetime.now();
        currentDayOrdinal = ApexUtils.numberToOrdinal(string.valueOf(d.day()));
        currentMonthName = d.format('MMMMM');
        currentDay = d.format('dd');
        currentYear = string.valueOf(d.year());
                   
    }   

    public void getLocationsForOpportunity(){
		locations = new List<OpportunityLocationConfiguration__c>();
        List<OpportunityLocationConfiguration__c> lstLocations = 
            [Select Id, Opportunity_Location__r.Service_Location__r.Location__r.Name
            from OpportunityLocationConfiguration__c 
            where Opportunity_Location__r.Order__r.Opportunity__c=:currentOpportunity.Id AND Opportunity_Location__r.On_Hold__c=false AND Active__c=true ];          
    	for( OpportunityLocationConfiguration__c ol : lstLocations ) {
    		locations.add(ol);
    	}
    	
    	Set<String> TI = new Set<String>();
    	for(Technical_Information__c techInfos : [Select Current_Service_Provider__c From Technical_Information__c  Where Opportunity_Site__r.Order__r.Opportunity__c=:currentOpportunity.Id]){
    		if(techInfos.Current_Service_Provider__c != null){
    			TI.Add(techInfos.Current_Service_Provider__c);
    		}
    	} 
    	
    	if(TI.size() > 0){
    		techInfo = '';
    		for(String tInfo : TI){
				if(tInfo != null)   			
    				techInfo= techInfo + tInfo + '; ' ;    				
    			}
    	}
    	
    }    
    
	
}