objects/ICB__c/ICB__c.object-meta.xml
<CustomObject>
    <description>Custom object to better track Individual Case Basis requests</description>
    <label>ICB</label>
    <nameField>
        <displayFormat>ICB Request-{000000}</displayFormat>
        <label>ICB Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICBs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/ICB__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Field used for reporting for the users who cannot see Administrative reports and therefore cannot see all pending requests.  This field will be set by Field Update in the Approval processes and by a workflow rule.</description>
    <inlineHelpText>System Maintained Field: Displays current status or step in the approval process.</inlineHelpText>
    <label>Approval Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/ICB__c/fields/ICB_Pricing_Reason__c.field-meta.xml
<CustomField>
    <fullName>ICB_Pricing_Reason__c</fullName>
    <description>Reason for Pricing  ICB that AE selects.</description>
    <inlineHelpText>Select a reason for your Pricing ICB (AE Selects)</inlineHelpText>
    <label>ICB Pricing Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ICB_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Competitive Response</fullName>
            </value>
            <value>
                <fullName>CPQ Required Quote</fullName>
            </value>
            <value>
                <fullName>Customer Incentive</fullName>
            </value>
            <value>
                <fullName>ETF Program</fullName>
            </value>
            <value>
                <fullName>Inside Wiring - Integra Provided</fullName>
            </value>
            <value>
                <fullName>Move Request</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other Program</fullName>
            </value>
            <value>
                <fullName>Price Schedule</fullName>
            </value>
            <value>
                <fullName>Renewal Request</fullName>
            </value>
            <value>
                <fullName>Signed Contract</fullName>
            </value>
            <value>
                <fullName>Temporary Service</fullName>
            </value>
            <value>
                <fullName>Usage-Based Internet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ICB__c/fields/ICB_Technical_Reason__c.field-meta.xml
<CustomField>
    <fullName>ICB_Technical_Reason__c</fullName>
    <description>Dependent picklist based on the Product picklist field.</description>
    <inlineHelpText>Required field for all Technical ICBs.  Select the reason you need an ICB in order to sell this product.</inlineHelpText>
    <label>ICB Technical Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&gt; 4G EVC or UNI/NNI Access</fullName>
            </value>
            <value>
                <fullName>2 Fiber Protection</fullName>
            </value>
            <value>
                <fullName>Any Bandwidth &gt;500 Mb</fullName>
            </value>
            <value>
                <fullName>Any Request for Multi-Cast</fullName>
            </value>
            <value>
                <fullName>Auto Mitigation</fullName>
            </value>
            <value>
                <fullName>CALNET 3: Security Standards</fullName>
            </value>
            <value>
                <fullName>CFS over E-LAN</fullName>
            </value>
            <value>
                <fullName>Customer access to Netflow</fullName>
            </value>
            <value>
                <fullName>Customer-Provided Router</fullName>
            </value>
            <value>
                <fullName>Customer requires more than 15 POTS per location or more than 50 POTS across multiple locations.</fullName>
            </value>
            <value>
                <fullName>Data Center Resale</fullName>
            </value>
            <value>
                <fullName>Development Required</fullName>
            </value>
            <value>
                <fullName>EoC &gt; 8-Pair Bonding</fullName>
            </value>
            <value>
                <fullName>EoC Other:  List Reason in Description</fullName>
            </value>
            <value>
                <fullName>EoF Dedicated / SONET-protected Access</fullName>
            </value>
            <value>
                <fullName>EoF Dedicated Access</fullName>
            </value>
            <value>
                <fullName>EoF Non-standard circuit routing / Diverse AR Termination</fullName>
            </value>
            <value>
                <fullName>EoF Other:  List Reason in Description</fullName>
            </value>
            <value>
                <fullName>EoTDM: Ethernet over N x DS3 access</fullName>
            </value>
            <value>
                <fullName>EoTDM Other:  List Reason in Description</fullName>
            </value>
            <value>
                <fullName>Extended Other:  List Reason in Description</fullName>
            </value>
            <value>
                <fullName>International VPN Node</fullName>
            </value>
            <value>
                <fullName>LAG Requirements on EVPL Hubs or E-LAN nodes</fullName>
            </value>
            <value>
                <fullName>Manual Toll-Free Re-Direction Requested</fullName>
            </value>
            <value>
                <fullName>Market Expansion Line Services</fullName>
            </value>
            <value>
                <fullName>More than 20 Active Mitigations per Month</fullName>
            </value>
            <value>
                <fullName>More than 20 Reactive Mitigations</fullName>
            </value>
            <value>
                <fullName>Non-Standard Bandwidth</fullName>
            </value>
            <value>
                <fullName>Non-Standard CFS Configuration</fullName>
            </value>
            <value>
                <fullName>Non-Standard circuit routing/Diverse AR Termination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ICB__c/fields/ICB_Type__c.field-meta.xml
<CustomField>
    <fullName>ICB_Type__c</fullName>
    <description>First means of dialing in the workflow based on Pricing or Technical ICB needs</description>
    <inlineHelpText>Pick One!</inlineHelpText>
    <label>ICB Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ICB__c/fields/Pricing_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricing Agreement</label>
    <referenceTo>Pricing_Agreement__c</referenceTo>
    <relationshipLabel>ICBs</relationshipLabel>
    <relationshipName>ICBs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/ICB__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>System Maintained Status of the ICB</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved-Pending Sale</fullName>
            </value>
            <value>
                <fullName>Approved with Conditions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Pricing_Agreement__c/Pricing_Agreement__c.object-meta.xml
<CustomObject>
    <label>Wholesale Pricing Agreement</label>
    <nameField>
        <label>Pricing Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale Pricing Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Pricing_Agreement__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Pricing_Agreement__c/fields/Contract_Signed_By__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Signed By</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <infoMessage>The name entered in this field should be a Contact from the Account. If you need to select another Contact, click &quot;Show all results&quot;.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Wholesale Pricing Agreements</relationshipLabel>
    <relationshipName>Pricing_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Pricing_Agreement__c/fields/Record_Locked__c.field-meta.xml
<CustomField>
    <fullName>Record_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once Contract Signed Date is entered, this record will be locked</description>
    <label>Record Locked</label>
    <type>Checkbox</type>
</CustomField>

classes/PricingAgreementTriggers.cls
public without sharing class PricingAgreementTriggers {
   private static final Set<String> wonICBStatusSet = new Set<String>{'Approved-Pending Sale'};
   public static void PricingAgreementModified(List<Pricing_Agreement__c> tNew, List<Pricing_Agreement__c> tOld, Boolean isUpdate, Boolean isBefore, Boolean isDelete){
        Map<Id, Pricing_Agreement__c> tOldMap = tOld != null ? new Map<Id, Pricing_Agreement__c>(tOld) : new Map<Id, Pricing_Agreement__c>();

       if(isBefore){
          if(!isDelete){
              checkCanLockRecords(tNew, tOldMap);
          }
       }else{
          if(isUpdate){
             updateRelatedICBStatuses(tNew, tOldMap);
          }
       }
   }
   
   private static void checkCanLockRecords(List<Pricing_Agreement__c> tNew, Map<Id, Pricing_Agreement__c> tOldMap ){
       String userProfile = [select Name from Profile where Id =: UserInfo.getProfileId()].Name;
       for(Pricing_Agreement__c pa: tNew){
           if(pa.Record_Locked__c && userProfile != 'System Administrator'){
               pa.addError('This Wholesale Pricing Agreement record is locked. No change is allowed');
           }
           if(!pa.Record_Locked__c && pa.Contract_Signed_Date__c != null && pa.Contract_Signed_By__c != null){
               pa.Record_Locked__c = true;
           }
       }
   }
   public static void updateRelatedICBStatuses(List<Pricing_Agreement__c> tNew, Map<Id, Pricing_Agreement__c> tOldMap ){
        Set<Id> approvedIDs = new Set<id>();
        for(Pricing_Agreement__c pa: tNew){
            if(pa.Approval_Status__c!= tOldMap.get(pa.Id).Approval_Status__c&& pa.Approval_Status__c != null && pa.Approval_Status__c =='Approved'){
                approvedIDs.add(pa.Id);
            }
        }
        
        //  Removed ICB_Technical_Reason__c because this field is deleted
        if(approvedIDs.size() > 0){
            Map<Id, ICB__c> m = new Map<Id, ICB__c>([select Name, Id, Status__c, Pricing_Agreement__c, ICB_Pricing_Reason__c, ICB_Type__c from ICB__c where Pricing_Agreement__c in: approvedIDs]);
            Map<Id, ICB__c> updates = new Map<Id, ICB__c>();
            
            for(Pricing_Agreement__c pa : tNew){
                if(approvedIDs.contains(pa.id)){
                    for(ICB__c i : updateICBStatus(getICBsByPricingAgreementAndStatus(m, pa.id, wonICBStatusSet), 'Approved'))
                        updates.put(i.id, i);

                }
            }
            
            List<ICB__c> icbs = updates.values();
            if(icbs.size() > 0){
                List<String> errors = new List<String>();
                
                Database.SaveResult[] results = Database.update(icbs, false);
                for(Integer i=0; i<results.size(); i++){
                    Database.SaveResult result = results[i];
                    for(Database.Error error : result.getErrors())
                        errors.add(icbs[i].Id + ': ' + error.message);
                }
                
                if(errors.size() > 0)
                    ApexUtils.sendEmails(new List<Messaging.SingleEmailMessage>{ApexUtils.createEmailMessage(new List<String>{UserInfo.getUserEmail()}, CustomSettingUtils.IntegrationErrorEmailAddresses, 'ICB records failed to save from Pricing Agreement Approval Status change', string.join(errors, '\n'), false, null)});
            }
        }        
   
   }
   
    private static List<ICB__c> getICBsByPricingAgreementAndStatus(Map<Id, ICB__c> icbmap, Id paId, Set<String> statuses){
        List<ICB__c> icblist = new List<ICB__c>();
        for(ICB__c icb : icbmap.values()){
            string strPaid = icb.Pricing_Agreement__c;
            if(strPaid.contains(paId) && statuses.contains(icb.status__c))
                icblist.add(icb);
        }
        return icblist; 
    }
    private static List<ICB__c> updateICBStatus(List<ICB__c> icbs, String newStatus){
        
        for(icb__c icb : icbs){
            icb.Status__c = newStatus;
            
            icb.ICB_Pricing_Reason__c = (string.isEmpty(icb.ICB_Pricing_Reason__c) && icb.ICB_Type__c == 'Pricing') ? 'Other' : icb.ICB_Pricing_Reason__c;
        }
        
        return icbs;
    }    
   
}