main/default/objects/Predecessor__c/Predecessor__c.object-meta.xml
<CustomObject>
    <label>Predecessor</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Predecessor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Predecessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Predecessor__c/fields/Dependent_Workstep__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Workstep__c</fullName>
    <label>Dependent Workstep</label>
    <referenceTo>Workstep__c</referenceTo>
    <relationshipLabel>Predecessors</relationshipLabel>
    <relationshipName>Predecessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Predecessor__c/fields/Predecessor_Workstep__c.field-meta.xml
<CustomField>
    <fullName>Predecessor_Workstep__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Predecessor Workstep</label>
    <referenceTo>Workstep__c</referenceTo>
    <relationshipLabel>Successors</relationshipLabel>
    <relationshipName>Successors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/classes/PredecessorTriggers.cls
public with sharing class PredecessorTriggers {
	
	public static boolean DisableTrigger = false;
	
 	public static void PredecessorModified(List<Predecessor__c> tNew, List<Predecessor__c> tOld, Boolean isUpdate, Boolean isBefore, Boolean isDelete){
		
    	if(DisableTrigger || !ApexUtils.executeTriggerMethods('Predecessor__c', isBefore, isDelete)) return;
		
        if(isBefore){
        	//Nothing to do
        }
        else{
        	Map<Id, Predecessor__c> tOldMap = tOld != null ? new Map<Id, Predecessor__c>(tOld) : new Map<Id, Predecessor__c>();
        	updateWorksteps(tNew, tOldMap, isDelete);
        	
			ApexUtils.afterTriggerComplete('Predecessor__c', isDelete);
    	}
    }
    
    private static void updateWorksteps(List<Predecessor__c> tNew, Map<Id, Predecessor__c> tOldMap, Boolean isDelete) {
		Set<Id> wsIDs = new Set<Id>();
		for (Predecessor__c p : isDelete ? tOldMap.values() : tNew) {
system.debug('pred in predTrigger: ' + p);			
			wsIDs.add(p.Dependent_Workstep__c);			
			wsIDs.add(p.Predecessor_Workstep__c);
		}		
		WorkstepUtils.updateWorkstepSuccessors(wsIDs);
	}
}