objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Building__c/fields/Capital_Project_Building__c.field-meta.xml
<CustomField>
    <fullName>Capital_Project_Building__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify building is part of a Capital Project for SFDC reporting</description>
    <label>Capital Project Building</label>
    <type>Checkbox</type>
</CustomField>

objects/Capital_Project__c/Capital_Project__c.object-meta.xml
<CustomObject>
    <label>Capital Project</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Capital Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Capital_Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Capital Projects</relationshipLabel>
    <relationshipName>Capital_Projects4</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Capital_Project__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Capital Projects</relationshipLabel>
    <relationshipName>Capital_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Capital_Project__c/fields/Request_Title__c.field-meta.xml
<CustomField>
    <fullName>Request_Title__c</fullName>
    <label>Request Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

main/default/objects/Capital_Project_Building__c/Capital_Project_Building__c.object-meta.xml
<CustomObject>
    <label>Capital Project Building</label>
    <nameField>
        <displayFormat>CPB-{000000}</displayFormat>
        <label>Capital Project Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Project Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Capital_Project_Building__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Capital Project Buildings</relationshipLabel>
    <relationshipName>Capital_Project_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Capital_Project_Building__c/fields/Capital_Project__c.field-meta.xml
<CustomField>
    <fullName>Capital_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capital Project</label>
    <referenceTo>Capital_Project__c</referenceTo>
    <relationshipLabel>Capital Project Buildings</relationshipLabel>
    <relationshipName>Capital_Project_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Build Location</description>
    <inlineHelpText>Build Location</inlineHelpText>
    <label>Location</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Order__c/fields/Order_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Create_Date__c</fullName>
    <description>Date Build Order is created</description>
    <inlineHelpText>Date Build Order is created</inlineHelpText>
    <label>Order Create Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/Provisioning_Plan_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Plan_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Provisioning Plan Enabled</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Order__c/recordTypes/Build_Order.recordType-meta.xml
<RecordType>
    <fullName>Build_Order</fullName>
    <active>true</active>
    <label>Build Order</label>
</RecordType>

main/default/objects/Provisioning_Product__c/Provisioning_Product__c.object-meta.xml
<CustomObject>
    <label>Provisioning Product</label>
    <nameField>
        <label>Provisioning Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provisioning Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GlobalActions.cls
global class GlobalActions {
	webService static Id CreateBuildOrder(Id buildingID) {
		return createBuildOrder(buildingID, false);
    }
    
@AuraEnabled
    webService static Id CreateAdditionalBuildOrder(Id orderID, boolean extraOrder) {
        List<Order__c> ord = [select Id, Building__c, Location__c from Order__c where Id =: orderID];
		return createBuildOrder(ord[0].Building__c, true);
    }
	
	private static Id createBuildOrder(Id buildingID, boolean extraOrder){
		Schema.Describesobjectresult r = Order__c.sObjectType.getDescribe();
		Boolean hasAccess = r.isCreateable();
		//fix this to getRecordTypeInfos and loop thru to find build order instead in case Build Order changes...loop using DeveloperName Build_Order
		for(Schema.RecordtypeInfo rti : Order__c.sObjectType.getDescribe().getRecordTypeInfos()) {
			if(rti.getName().equalsIgnoreCase('Build Order')){
				if(!hasAccess || !rti.isAvailable()){
					return null;
				}
				else{
			        List<Order__c> ord = !extraOrder ? [select Id from Order__c where Building__c =: buildingID] : new List<Order__c>();
			        if(extraOrder || ord.size() == 0){
			        	List<Provisioning_Product__c> pp = [select Id from Provisioning_Product__c where Name = 'Standard Build' limit 1];
			        	ord = new List<Order__c>{new Order__c(Building__c = buildingID
								        						,RecordTypeId = rti.getRecordTypeId()
								        						,Location__c = [select Name from Location__c where Building__c = :buildingID limit 1].Name
								        						,Provisioning_Product__c = pp.size() > 0 ? pp[0].Id : null
								        						,Provisioning_Plan_Enabled__c = true
								        						,Order_Create_Date__c = Date.today()
								        						,Workplan_Start_Date__c = Date.today())};
			        	insert ord;
			        }
		        	return ord.size() > 0 ? ord[0].Id : null;
				}
			}
		}
		return null;	
	}
	
	webService static Boolean CurrentUserHasAgreedToChatterTerms(){
		return SecurityUtils.currentUserHasAgreedToChatterTerms();
	}
	
	webService static List<String> GetPicklistValues(String obj, String field){
		List<String> l = new List<String>();
		for(Schema.PicklistEntry pe : SchemaUtils.GetType(obj).getDescribe().fields.getMap().get(field).getDescribe().getPicklistValues()) l.add(pe.getLabel());
		return l;
	}
	
	webService static Id GetSalesFormsContentVersionIDByTitle(String title){
		List<ContentVersion> docs = [Select Id From ContentVersion Where title = :title and (Asset_Type__c = 'Sales Forms and Pricing' or Asset_Type__c = 'Sales Process/Procedure' or Asset_Type__c = 'Process/Procedure') limit 1];
		return (docs.size() > 0) ? docs[0].Id : null;
	}
	
	webService static void CreateLeadFromGeoResultsBusiness(Id grbID){
		AddressUtils.CreateLeadsFromGeoResultsBusinesses(new Map<Id, Id>{ grbID => null });
	}
	
	webservice static Id CreateCustomerBuildFromOpp(Id oppId, string title, string description){
		List<PermissionSetAssignment> pSetAssignments = [select Id from permissionSetAssignment where assigneeId = :UserInfo.getUserId() and permissionSetId = '0PS1A000000TMfY'];
		Id oppOrdRTID = Schema.SObjectType.Order__c.getRecordTypeInfosByName().get('Opportunity Order').getRecordTypeID();
		Map<Id,Id> orderIdByOppId = new Map<Id,Id>();
		for(Order__c ord : [select id, Opportunity__c from order__c where recordTypeId = :oppOrdRTID and opportunity__c = :oppId]){
			orderIdByOppId.put(ord.Opportunity__c, ord.Id);
		}
		if(pSetAssignments.size() > 0){
			Capital_Project__c cproj = new Capital_Project__c();
			cproj.RecordTypeId = Schema.SObjectType.Capital_Project__c.getRecordTypeInfosByName().get('Customer Build').getRecordTypeID();
			cproj.Opportunity__c = oppId;
			cproj.Request_Title__c = title;
			cproj.Description__c = description;
			cproj.Order__c = orderIdByOppId.containsKey(oppId)?orderIdByOppId.get(oppId):null;
			//insert cproj;
			SecurityUtils.BypassProcesser.saveObjects(new List<Capital_Project__c>{cproj}, false);
			return cproj.Id;
		}
		else
			return null;
	}

	webservice static Id CreateNetworkBuildFromBldg(Id bldgId){
		List<PermissionSetAssignment> pSetAssignments = [select Id from permissionSetAssignment where assigneeId = :UserInfo.getUserId() and permissionSetId = '0PS1A0000000YXi'];
		if(pSetAssignments.size() > 0){
			Capital_Project__c cproj = new Capital_Project__c();
			cproj.RecordTypeId = Schema.SObjectType.Capital_Project__c.getRecordTypeInfosByName().get('Network Build').getRecordTypeID();
			SecurityUtils.BypassProcesser.saveObjects(new List<Capital_Project__c>{cproj}, false);
			Capital_Project_Building__c cbldg = new Capital_Project_Building__c();
			if(cproj.Id != null){
				cbldg.Capital_Project__c = cproj.Id;
				cbldg.Building__c = bldgId;
				SecurityUtils.BypassProcesser.saveObjects(new List<Capital_Project_Building__c>{cbldg}, false);
			}
			return cproj.Id;
		}
		else
			return null;
	}

	@InvocableMethod
	public static List<String> CreateCustomerBuildFromFlow(List<Id> oppIds){
		List<Capital_Project__c> cprojs = new List<Capital_Project__c>();
		Id oppOrdRTID = Schema.SObjectType.Order__c.getRecordTypeInfosByName().get('Opportunity Order').getRecordTypeID();
		Map<Id,Id> orderIdByOppId = new Map<Id,Id>();
		for(Order__c ord : [select id, Opportunity__c from order__c where recordTypeId = :oppOrdRTID and opportunity__c in :oppIds]){
			orderIdByOppId.put(ord.Opportunity__c, ord.Id);
		}
		for(Id oppId : oppIds){
			Capital_Project__c cproj = new Capital_Project__c();
			cproj.RecordTypeId = Schema.SObjectType.Capital_Project__c.getRecordTypeInfosByName().get('Customer Build').getRecordTypeID();
			cproj.Opportunity__c = oppId;
			cproj.Order__c = orderIdByOppId.containsKey(oppId)?orderIdByOppId.get(oppId):null;
			cprojs.add(cproj);
		}
		SecurityUtils.BypassProcesser.saveObjects(cprojs, false);
		List<String> retVals = new List<String>();
		for(Capital_Project__c cproj : cprojs) retVals.add(cproj.Id);
		return retVals;
	}
}