objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Address Component: City</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Address Component: Zip</description>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Address Component: State</description>
    <inlineHelpText>Use 2-digit abbreviation for State</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Directory_Listing__c/Directory_Listing__c.object-meta.xml
<CustomObject>
    <label>Directory Listing</label>
    <nameField>
        <displayFormat>DL-{00000}</displayFormat>
        <label>Listing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Directory Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Directory_Listing__c/fields/Listing_Telephone_Number__c.field-meta.xml
<CustomField>
    <fullName>Listing_Telephone_Number__c</fullName>
    <label>Listing Telephone Number</label>
    <type>Phone</type>
</CustomField>

objects/Directory_Listing__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

main/default/classes/CompanyInfo.cls
public with sharing class CompanyInfo {
    
    public string Name { get; set; }
    public string Street { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Zip { get; set; }
    public string CityStateZip { get; set; }
    public string Phone { get; set; }
    public string MobilePhone { get; set; }
    public string Fax { get; set; }
    public string Email { get; set; }
    public string Title { get; set; }
	public String AccountNumber {get;Set;}
	
	// date stuff
	private Date pTodaysDate {get;Set;}
	private Date todaysDate {
		get{
			if(pTodaysDate == null)
				pTodaysDate = Date.today();
			return pTodaysDate;
		}
	}
    
    private void setFromAccount(Account acct, Boolean useBilling) {
    	Name = acct.Name;
        Phone = acct.Phone;
        Fax = acct.Fax;
        Email = null;
        Title = null;
		AccountNumber = acct.AccountNumber;
        
        if (useBilling) {
        	Street = acct.BillingStreet;
        	City = acct.BillingCity;   
        	State = acct.BillingState; 
        	Zip = acct.BillingPostalCode;	
        } else {
        	Street = acct.ShippingStreet;
        	City = acct.ShippingCity;   
        	State = acct.ShippingState; 
        	Zip = acct.ShippingPostalCode;
        }
        
        CityStateZip = formatCityStateZip(City, State, Zip );
    }
    
    public CompanyInfo(Account acct, Boolean useBilling){
        if( acct == null )
            return;
        
         setFromAccount(acct, useBilling);  
    }
    
    public CompanyInfo(Account acct){
        if( acct == null )
            return;
        
        setFromAccount(acct, false); 
    }
        public CompanyInfo(User owner) {
        if( owner == null )
            return;
        
        if( String.IsEmpty(owner.Preferred_First_Name__c) ) {
        	Name = owner.Name;
        }
        else {
        	Name = owner.Preferred_First_Name__c + ' ' + owner.LastName;
        }
        
        Street = Owner.Street;
        City = Owner.City;  
        State = Owner.State;    
        Zip = Owner.PostalCode;
        Phone = Owner.Phone;
        MobilePhone = Owner.MobilePhone;
        Fax = Owner.Fax;
        Email = Owner.Email;
        Title = Owner.Title;
        CityStateZip = formatCityStateZip(City, State, Zip );   
    }
    
    //check for opportunity indirect agent first, otherwise opp.owner
    public CompanyInfo(Opportunity currentOppId, User owner) {
    	Map<Id,string> opps = new Map<id,string>();
    	Map<Id,string> ocrs = new Map<id,string>();

    	for(Opportunity opp : [Select Id, Name From Opportunity Where Id =: currentOppId.Id And Sales_Channel__c =: 'Indirect Sales' Limit 1]){
    		opps.put(opp.id, opp.Name);
    	}
        if(opps.size() > 0){
        	for(OpportunityContactRole ocr : [Select ContactId, Role From OpportunityContactRole Where OpportunityId =: opps.keyset() And OpportunityContactRole.Role =: 'Agent' Limit 1]){
        		ocrs.put(ocr.ContactId, ocr.Role);
        	}	
        	if(ocrs.size() > 0){
	        	Contact con = [Select Title, Account.Name, Phone, MobilePhone, Name, MailingStreet, MailingState, MailingPostalCode, MailingCity, Fax, Email From Contact Where Id =: ocrs.keyset() Limit 1];
	        	//Name = con.Name + ', ' + con.Account.Name;
	        	Name = con.Name;
	        	Street = con.MailingStreet;
		        City = con.MailingCity;  
		        State = con.MailingState;    
		        Zip = con.MailingPostalCode;
		        Phone = con.Phone;
                MobilePhone = con.MobilePhone;
		        Fax = con.Fax;
		        Email = con.Email;
		        Title = con.Title;
		        CityStateZip = formatCityStateZip(City, State, Zip );
        		}
        	else{
        		return;
        	}

        }
        else{
        	return;
        } 
  
    }
    
    public CompanyInfo(Directory_Listing__c listing) {
        if( listing == null )
            return;
        
        Name = listing.Company_Name__c;
        Street = listing.Address__c;
        City = listing.City__c; 
        State = listing.State__c;   
        Zip = listing.Zip__c;
        Phone = listing.Listing_Telephone_Number__c;
        Fax = null;
        Email = null;
        Title = null;
        CityStateZip = formatCityStateZip(City, State, Zip );   
    }
    public CompanyInfo(Building__c listing, String serviceLocName) {
        if( listing == null )
            return;
        
        Name = serviceLocName;
        Street = listing.Address__c;
        City = listing.City__c; 
        State = listing.State__c;   
        Zip = listing.Postal_Code__c;
        Phone = null;
        Fax = null;
        Email = null;
        Title = null;
        CityStateZip = formatCityStateZip(City, State, Zip );   
    }

    public CompanyInfo(Building__c listing, String serviceLocName, String serviceLocSuite) {
        if( listing == null )
            return;
        
        Name = serviceLocName;
        if(!String.IsEmpty(serviceLocSuite)){
        	Street = listing.Address__c + ' ' + serviceLocSuite;
        }
        else{
        	Street = listing.Address__c;
        }
        
        City = listing.City__c; 
        State = listing.State__c;   
        Zip = listing.Postal_Code__c;
        Phone = null;
        Fax = null;
        Email = null;
        Title = null;
        CityStateZip = formatCityStateZip(City, State, Zip );   
    }

    private string formatCityStateZip( string city, string state, string zip) {
        string total = '';
        
        if( !String.IsEmpty(city) ) {
            total += city;
        }
            
        if( !String.IsEmpty(state) ) {
            if( total != '' )
                total += ', ';
                
            total += state;
        }
        
        if( !String.IsEmpty(zip) ) {
            if( total != '' )
                total += ' ';
                
            total += zip;           
        }
        return total;
    }   
}