objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

classes/Test_GlobalActions.cls
@isTest
public with sharing class Test_GlobalActions extends TestUtils.TestClass {
	
    static testMethod void testCreateBuildOrder() {
    	Mocks testData = new Mocks();
		
		Building__c b = testData.building;
		Location__c l = testData.loc;
		
    	test.startTest();
    	
    	system.assert(testData.mpProvProd.get('Standard Build') == null, 'Provisioning Product named "Standard Build" exists to associate to a build order');
    	GlobalActions.CreateBuildOrder(b.Id);
    	
    	test.stopTest();
    }
}