objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Junction__c/Junction__c.object-meta.xml
<CustomObject>
    <description>A generic object to object junction to be manipulated in code only.</description>
    <label>Junction</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Junction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Junction__c/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <label>Source ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Junction__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Junction__c/fields/Target_ID__c.field-meta.xml
<CustomField>
    <fullName>Target_ID__c</fullName>
    <label>Target ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Junction__c/fields/Target_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Type__c</fullName>
    <label>Target Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Order_Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Completion_Status__c</fullName>
    <label>Order Completion Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Scoping</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>In Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Record_Status__c</fullName>
    <label>Record Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Contract Renewal Orders</description>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Provisioning_Product__c/Provisioning_Product__c.object-meta.xml
<CustomObject>
    <label>Provisioning Product</label>
    <nameField>
        <label>Provisioning Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provisioning Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SPC_Product__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>SPC Products</relationshipLabel>
    <relationshipName>SPC_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SPC_Product__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <externalId>true</externalId>
    <label>SalesProductExternalID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Sub Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

main/default/classes/Test_RelatedSubOrders.cls
@isTest
public with sharing class Test_RelatedSubOrders {
    
		static testMethod void testController(){
    	Mocks testData = new Mocks();
    	Test.startTest();
    	
    	Opportunity opp = testData.opportunity;
    	Order__c ord = new Order__c(Opportunity__c = opp.Id);
    	insert ord;
    	
    	SPC_Product__c spc = new SPC_Product__c(
    									SalesProductExternalID__c = -1
    									,Provisioning_Product__c = testData.mpProvProd.get('Standard').Id
    									);
    	insert spc;
    	
    	Sub_Order__c so = new Sub_Order__c(
    									Service_Location__c = testData.serviceLocation.Id
    									,Order__c = ord.Id
    									,SPC_Product__c = spc.Id
    									,Workplan_Start_Date__c = Date.today()
    									);
    	insert so;

    	Apexpages.StandardController sc = new Apexpages.StandardController(so);
    	RelatedSubOrders rso = new RelatedSubOrders(sc);
        rso.returnRelated(so);	
    	rso.Save();
    	rso.SaveManual();
    	rso.Remove();		
		test.stopTest();
	}
    
    static testmethod void testSave(){
        Mocks Testdata = new Mocks();
        ApexPages.StandardController ctrl = new ApexPages.StandardController(Testdata.suborder);
        RelatedSubOrders obj = new RelatedSubOrders(ctrl);
        obj.ModifiedTempIds = JSON.serialize(new Set<String>{Testdata.order.Id});
        
        Test.startTest();
        obj.Save();       
    }
    
    static testmethod void testSaveManual(){
        Mocks Testdata = new Mocks();
        ApexPages.StandardController ctrl = new ApexPages.StandardController(Testdata.suborder);
        RelatedSubOrders obj = new RelatedSubOrders(ctrl);
        
        Order__c order = new Order__c(opportunity__c = Testdata.opportunity.Id);
        order.Order_Completion_Status__c = 'In Progress';
       	order.RecordTypeId = Schema.Sobjecttype.Order__c.getRecordTypeInfosByName().get('Build Order').getRecordTypeId();
        order.building__c = Testdata.building.Id;
        insert order;
        
        obj.AddBldOrder = [Select Id, Name from Order__c Where Id =: order.Id Limit 1][0].Name;
        
        Test.startTest();
        obj.SaveManual();
    }
    
    static testmethod void testRemove(){
        Mocks Testdata = new Mocks();
        ApexPages.StandardController ctrl = new ApexPages.StandardController(Testdata.suborder);
        RelatedSubOrders obj = new RelatedSubOrders(ctrl);
        
        obj.ModifiedTempIds = JSON.serialize(new Set<String>{Testdata.suborder.Id});
        
        Test.startTest();
        obj.Remove();
    }
    
    static testmethod void testOrderWrapper(){
        Mocks Testdata = new Mocks();
        
        Test.startTest();
        RelatedSubOrders.OrderWrapper inst = new RelatedSubOrders.OrderWrapper(Testdata.order, true);
        System.assertEquals(true, inst.isSelected);
    }
    
    static testmethod void testsObjectWrapper(){
        Mocks Testdata = new Mocks();
        
        Test.startTest();
        RelatedSubOrders.sObjectWrapper inst = new RelatedSubOrders.sObjectWrapper(Testdata.location, true);
		System.assertEquals(true, inst.isSelected);
    }
    
    static testmethod void testGettersAndSetters(){
        Mocks Testdata = new Mocks();
   		ApexPages.StandardController ctrl = new ApexPages.StandardController(Testdata.suborder);
        RelatedSubOrders obj = new RelatedSubOrders(ctrl);
        
        System.assertEquals(obj.o = Testdata.order, obj.o);
        System.assertEquals(obj.so = Testdata.suborder, obj.so);
        System.assertEquals(obj.getRelatedWrapperCollection(), (List<RelatedSubOrders.sObjectWrapper>)obj.ritem);
        System.assertEquals(obj.getWrapperCollection(), (List<RelatedSubOrders.sObjectWrapper>)obj.oitem);
        System.assertEquals(JSON.deserialize(obj.ModifiedTempIds, Set<String>.Class), null);
        System.assertEquals(obj.AddBldOrder, null);     
    }
    
    static testmethod void testreturnRelated(){
        Mocks Testdata = new Mocks();
        ApexPages.StandardController ctrl = new ApexPages.StandardController(Testdata.suborder); // SourceIds
        RelatedSubOrders obj = new RelatedSubOrders(ctrl);
        
        Order__c order = new Order__c(opportunity__c = Testdata.opportunity.Id);
        order.building__c = Testdata.building.Id;
        order.Record_Status__c = 'Open';
        insert order; // TargetIds
        
        Junction__c junc = new Junction__c(Source_ID__c = Testdata.suborder.Id, Target_ID__c = order.Id, Source_Type__c = 'Test', Target_Type__c = 'Test');
        insert junc;
        
        Test.startTest();
        obj.returnRelated(Testdata.suborder);
    }
}