objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Building__c/fields/Capital_Project_Building__c.field-meta.xml
<CustomField>
    <fullName>Capital_Project_Building__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify building is part of a Capital Project for SFDC reporting</description>
    <label>Capital Project Building</label>
    <type>Checkbox</type>
</CustomField>

objects/Building_Access_Availability__c/Building_Access_Availability__c.object-meta.xml
<CustomObject>
    <label>Building Access Availability</label>
    <nameField>
        <label>Access Availability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building Access Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Building_Access_Availability__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Building Access Availabilities</relationshipLabel>
    <relationshipName>Access_Availabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Capital_Project_Building__c/Capital_Project_Building__c.object-meta.xml
<CustomObject>
    <label>Capital Project Building</label>
    <nameField>
        <displayFormat>CPB-{000000}</displayFormat>
        <label>Capital Project Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Project Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Capital_Project_Building__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Capital Project Buildings</relationshipLabel>
    <relationshipName>Capital_Project_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Georesults_business__c/Georesults_business__c.object-meta.xml
<CustomObject>
    <description>Contact Details Loaded from third party data providers such as GeoResults.</description>
    <label>GeoResults Business</label>
    <nameField>
        <displayFormat>GB-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Georesults Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Georesults_business__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Georesults Businesses</relationshipLabel>
    <relationshipName>Georesults_Businesses</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/Test_NetworkMap.cls
@isTest
public with sharing class Test_NetworkMap extends TestUtils.TestClass {

    static testMethod void testController() {
		NetworkMap nm = new NetworkMap();
		nm.latitude = 45.5000;
		nm.longitude = -120.000;
		nm.distRange = 1;
		nm.displayAllIlec = false;
		nm.myNearNet = false;
		nm.myOnNet = false;
		nm.displayIlec = true;
		nm.nearNetHigh = false;
		nm.nearNetMed = false;
		nm.nearNetLow = false;
		nm.nearNetUnPrior = false;
		nm.leadRoomSuite = '';
		nm.selectedMaxBAA = 30;
		nm.selectedMinBAA = 5;
		nm.maxBAA = 30;
		nm.MinBAA = 0;
		nm.maxMRREoF = 800;
		nm.minMRREoF = 10;
		nm.selectedMaxMRREoF = 800;
		nm.selectedMinMRREoF = 0;
		string userSalesChannel = nm.UserSalesChannel;
		List<SelectOption> opts = nm.gbFilterListViews;
		List<SelectOption> opts2 = nm.leadFilterListViews;
		List<SelectOption> opts3 = nm.accountFilterListViews;
		NetworkMap.rt_map = new map<Id, Schema.RecordTypeInfo>();
		NetworkMap.BuildOrderData bod = new NetworkMap.BuildOrderData(new Order__c());
		NetworkMap.CapitalProjectData cpd = new NetworkMap.CapitalProjectData(new Capital_Project_Building__c());

		boolean test1 = nm.isDebugProfile;
		string s = nm.wireCenterBuildings;
		nm.GatherBuildingData();
		
		NetworkMap.getTimeZone();
		NetworkMap.WireCenter wc = new NetworkMap.WireCenter('test',new List<building__c>());
		NetworkMap.AcctData ad = new NetworkMap.AcctData(new Account(),true);
		NetworkMap.GRBusData gr = new NetworkMap.GRBusData(new GeoResults_Business__c(CreatedDate = Datetime.now()),1,false);
		NetworkMap.BuildingData bd = new NetworkMap.BuildingData(new Building__c(),new Set<GeoResults_Business__c>(),new Set<Building_Access_Availability__c>(), new Set<Account>(),new Set<Id>(),new Map<String,Integer>(),new Map<Id,GeoResults_Business__c>());
		
		
		
		
		nm.leadstatus = 'test';
		nm.leadsource = 'test';
		nm.leadFirstName = 'Solaire';
		nm.leadLastName = 'of Astora';
		nm.leadGRID = gr.id;
		nm.leadPhone = '5555555555';
		nm.leadCompany = 'Sunlight Knights';
		nm.CreateLead();
		
		nm.oppAccountID = new Account().Id;
		nm.oppAcctName = 'Unending Awesomeness';
		nm.CreateOpportunity();
		
    }
}