objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Serving_LSO__c.field-meta.xml
<CustomField>
    <fullName>Serving_LSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serving LSO</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Invalid serving LSO - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Building__c.Is_Serving_LSO__c</field>
            <operation>equals</operation>
            <value>true</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Buildings (Serving LSO)</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Customer_Detail__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Owned_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Product__c/Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{0000000}</displayFormat>
        <label>Opportunity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Opportunity__r.Account.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

objects/Opportunity_Product__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Primary_Service_Location__r.Location__r.Name</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

objects/Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>Opportunity_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Opportunity_Product__c/fields/Primary_Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Product__c/fields/Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product__c</fullName>
    <label>Sales Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access Service</fullName>
            </value>
            <value>
                <fullName>Basic Voice Services</fullName>
            </value>
            <value>
                <fullName>Broadband/DSL</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Cloud Firewall Service</fullName>
            </value>
            <value>
                <fullName>Collaboration &amp; Messaging</fullName>
            </value>
            <value>
                <fullName>Colocation Services</fullName>
            </value>
            <value>
                <fullName>Conference Now</fullName>
            </value>
            <value>
                <fullName>CPE MRR</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet</fullName>
            </value>
            <value>
                <fullName>DSL and/or Broadband</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LAN</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LINE Host Site</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LINE Remote Site</fullName>
            </value>
            <value>
                <fullName>Failover – Dedicated Internet</fullName>
            </value>
            <value>
                <fullName>Failover – VPN Solutions</fullName>
            </value>
            <value>
                <fullName>Hosted &amp; Managed PBX</fullName>
            </value>
            <value>
                <fullName>Hosted Voice Services</fullName>
            </value>
            <value>
                <fullName>ISDN/PRI</fullName>
            </value>
            <value>
                <fullName>ISP Services</fullName>
            </value>
            <value>
                <fullName>Legacy Voice or Integrated T1</fullName>
            </value>
            <value>
                <fullName>Long Distance</fullName>
            </value>
            <value>
                <fullName>Managed Prime/Pro</fullName>
            </value>
            <value>
                <fullName>Managed UC</fullName>
            </value>
            <value>
                <fullName>NAA</fullName>
            </value>
            <value>
                <fullName>Need A Product</fullName>
            </value>
            <value>
                <fullName>Network Security Suite</fullName>
            </value>
            <value>
                <fullName>Network Solutions</fullName>
            </value>
            <value>
                <fullName>NGN SIP Trunking</fullName>
            </value>
            <value>
                <fullName>Novus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An explicit account lookup that should only be used if the order is not opportunity driven.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account-based Orders</relationshipLabel>
    <relationshipName>Account_Based_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Contract_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed_Date__c</fullName>
    <formula>Opportunity__r.Contract_Signed_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Signed Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Order__c/fields/Customer_Requested_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Due_Date__c</fullName>
    <formula>Opportunity__r.Customer_Requested_Due_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Requested Due Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Build Location</description>
    <inlineHelpText>Build Location</inlineHelpText>
    <label>Location</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Service_Location__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Indirect Channel Agency</value>
        </filterItems>
        <filterItems>
            <field>Account.AgentId__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations (Agency)</relationshipLabel>
    <relationshipName>ServiceLocationToAccountForAgency</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Location__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Service_Location__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Owned_Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ILECOpportunityGeneration.cls
public with sharing class ILECOpportunityGeneration extends TreeViewController {
	
	public Boolean opportunityClosedSuccessfully {get; private set;}
	public Integer MRR {get;set;}
	public Opportunity_Product__c oppProd {get; private set;}
	public Service_Location__c sloc {get; private set;}
	public Opportunity opp {get; private set;}
	public Account account {get; private set;}
	public List<Contact> contacts {get;private set;}
	public List<SelectOption> contactList{
		get{
			List<SelectOption> options = new List<SelectOption>();
			if(contacts.size() > 0){
				for(Contact c : contacts){
					options.add(new SelectOption(c.Id,c.Name));
				}
			}	
			return options;
		}
	}
	public String addressToGeocode {get; private set;}
	public Boolean hasResponsibleParty {get;private set;}
	public Id ResponsiblePartyId {get;set;}
	public Boolean slocCreated {get;private set;}
	
	public ILECOpportunityGeneration(){
		opportunityClosedSuccessfully = false;
		hasResponsibleParty = false;
		
		String accountId = '';
		accountId = ApexPages.currentPage().getParameters().get('accountId');
		if(accountId != '')
		{
			loadAccount();
			
			List<Service_Location__c> slocs = loadServiceLocation(accountId);
			if(slocs.size() > 0){
				sloc = slocs[0];
				slocCreated = true; 
			}
			else{
				slocCreated = false;
				sloc = null;
			}
			
			List<Opportunity> opps = [select Id, Name from Opportunity where AccountId = :accountId and type = 'New Logo' and StageName = 'Identification' and RecordType.DeveloperName = 'ILEC_Manual_Entry' limit 1];
			if(opps.size() > 0) { 
				opp = opps[0];
				List<OpportunityContactRole> oppContacts = [select Id, ContactId
															from OpportunityContactRole 
															where OpportunityId = :opp.Id
																and Role = 'Responsible Party'];
				if(oppContacts.size() > 0)
					hasResponsibleParty = true; 
			}
			else{
				opp = new Opportunity();
				recordtype rt = [select Id from recordtype where sobjecttype = 'opportunity' and developername = 'ILEC_Manual_Entry' limit 1];
				opp.RecordTypeId = rt.Id;
				String oppName = 'New Opportunity for Account: ' + account.Name;
				opp.Name = (oppName.length() > 80)? oppName.substring(0,80) : oppName;
				opp.AccountId = account.id;
				opp.Type = 'New Logo';
				opp.StageName = 'Identification';
				opp.CloseDate = Date.today();				
			}
			
			oppProd = new Opportunity_Product__c();
			contacts = [select Id, Name, Default_Responsible_Party__c from Contact where AccountId = :account.Id order by createdDate];
			for(Contact con : contacts){
				if (ResponsiblePartyId == null){
					ResponsiblePartyId = con.Id;
				}
				if (con.Default_Responsible_Party__c)
				{
					ResponsiblePartyId = con.Id;
					break;
				}
			}
			
			addressToGeocode = account.ShippingStreet
									+ (!string.IsEmpty(account.ShippingCity) ? ', ' + account.ShippingCity : '')
									+ (!string.IsEmpty(account.ShippingState) ? ', ' + account.ShippingState : '')
									+ (!string.IsEmpty(account.ShippingPostalCode) ? ', ' + account.ShippingPostalCode : '');
			
			TreeViewsByDivID = new Map<String, TreeViewImplementation>{'opportunityHierarchy'=>new TreeViewImplementation(account, sLoc, opp)};
		}
		else
		{
			//error
		}
	}
	
	public class TreeViewImplementation extends TreeViewController.TreeViewImplementation{
		public Account account {get; set;}
		public Service_Location__c sLoc {get; set;}
		public Opportunity opp {get; set;}
		
		public TreeViewImplementation(Account account, Service_Location__c sLoc, Opportunity opp){
			this.account = account;
			this.sLoc = sLoc;
			this.opp = opp;
			loadMoreEnabled = false;
		}
		
		public override List<TreeNode> getNodes(){
			TreeNode accountNode = new TreeNode(account.Name, account.Id);
			if(sloc != null){
				accountNode.addChildNode(new TreeNode(sloc.Name, sloc.Id),'[Service Location]');
			}
			if(opp.Id != null){
				TreeNode oppNode = new TreeNode(opp.Name, opp.Id);
				for(Opportunity_Product__c oppProduct : [select Id, Sales_Product__c 
													 	from Opportunity_Product__c 
													 	where Opportunity__c = :opp.Id
														 	and Primary_Service_Location__c = :sloc.Id]){
					oppNode.addChildNode(new TreeNode(oppProduct.Sales_Product__c, oppProduct.Id), '[Products]');									 		
				}
				accountNode.addChildNode(oppNode, '[Opportunity]');
			}
			
			return new List<TreeNode>{accountNode};
		}
	    
		public override Map<String, String> getIconMap(){
			Map<String, String> m = CustomerHierarchyController.mapSObjectIcons();
			m.put('new', '/img/icon/flag16.png');
			return m;
		}
	}
	
	public PageReference AddProduct() {
		if(!CreateLocation()){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error creating service location!'));
			return null;
		}
		if(opp.id == null && opp != null) {
			insert opp;
		}
		if(opp == null || (opp != null && opp.id == null)) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error creating opportunity!'));
			return null;
		}
		oppProd.Opportunity__c = opp.id;
		oppProd.Primary_Service_Location__c = sloc.Id;
		insert oppProd;
		oppProd = new Opportunity_Product__c();
		
		return refresh();
	}
	
	public PageReference Finalize() {
		closeOpp();
		return null;
	}
	
	private Boolean CreateLocation() {
		if(slocCreated) return true;
		
		Boolean buildingCreated = false;
		Boolean slocCreated = false;
		// create service location
		
		integraWS.SFLocationView locView = AddressParser.addressParsed();
        system.debug('KIT locView: ' + locView);
		Building__c tempRootBuilding = null;
		Location__c tempRootLocation = null;
		Service_Location__c tempMatchingServiceLoc = null;
        if(locView != null && locView.Success && !string.IsEmpty(locView.BuildingHash)){
			tempRootBuilding = AddressUtils.CreateBuilding(locView, false);
			tempRootLocation = AddressUtils.CreateLocation(tempRootBuilding, locView, false);
			system.debug('KIT tempRootBuilding: ' + tempRootBuilding);
			system.debug('KIT tempRootLocation: ' + tempRootLocation);
			
			tempMatchingServiceLoc = new Service_Location__c();
			tempMatchingServiceLoc.Name = account.Name;
			tempMatchingServiceLoc.Account__c = account.Id;
			tempMatchingServiceLoc.Phone__c = account.Phone;
			tempMatchingServiceLoc.Owner__c = account.OwnerId;
			tempMatchingServiceLoc.Agency__c = account.Agency__c;
			tempMatchingServiceLoc.Billable__c = account.Billable__c;
			tempMatchingServiceLoc.Customer_Detail__c = account.Customer_Detail__c;
			system.debug('KIT tempMatchingServiceLoc' + tempMatchingServiceLoc);
			
            	// create new location
            	
            if(tempRootBuilding != null){
            	system.debug('KIT upserting tempRootBuilding: ' + tempRootBuilding);
				upsert tempRootBuilding;
				buildingCreated = true;
				if(tempRootLocation != null){
					tempRootLocation.Building__c = tempRootBuilding.Id;
					system.debug('KIT upserting tempRootLocation: ' + tempRootLocation);
					upsert tempRootLocation;
				
					tempMatchingServiceLoc.Location__c = tempRootLocation.Id;
				}
            }
            system.debug('KIT inserting tempMatchingServiceLoc: ' + tempMatchingServiceLoc);
			insert tempMatchingServiceLoc;
		    slocCreated = true;
		    sloc = tempMatchingServiceLoc;
            if(tempRootBuilding.Serving_LSO__c == null){
            	system.debug('KIT Serving_LSO__c is null!');       	
            	// end create new location
                //Task t = !Test.IsRunningTest() ? AddressUtils.CreateTaskForNoServingLSO(tempRootBuilding, locView.LSOCLLI) : new Task();
                //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'A <a href=\'../' + tempMatchingServiceLoc.Id + '\'>service location</a> has been created to match this account but no serving LSO could be determined for this location. A <a href=\'../' + t.Id + '\'>task</a> has been created to correct the building.'));
            }
        }
        return buildingCreated && slocCreated;
        
	}
	
	public static Map<Id, Map<String, Id>> AddressValidationMappingByID { get; set; }
	private void closeOpp(){
		try{
			if(opp!=null && opp.id != null){
				if(!hasResponsibleParty){
					OpportunityContactRole ocr = new OpportunityContactRole();
					ocr.OpportunityId = opp.id;
					ocr.ContactId = ResponsiblePartyId;
					ocr.Role = 'Responsible Party';
					insert ocr;
				}
				
				CustomerDetailUtils.triggerDetailAddressValidation = false;
				CustomerDetailTriggers.ManualAddressValidation = true;
				//opp.StageName = OpportunityUtils.STAGE_CLOSED_WON;
				opp.StageName = OpportunityUtils.STAGE_5;
				opp.Contract_Signed_Date__c = Date.today();
				opp.Customer_Requested_Due_Date__c = Date.today();
				opp.Term__c = '12';
				opp.Bypass_Validation__c = true;
				update opp;
				
				AddressValidationMappingByID = CustomerDetailTriggers.AddressValidationMappingByID;
				
				opportunityClosedSuccessfully = true;
			}
		}
		catch(Exception e){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
			opportunityClosedSuccessfully = false;
		}
	}
	
	public PageReference ValidateAddressesAndRedirectToOppIntegrationPage(){
		List<String> errors = AddressUtils.validateAndSetCustomerDetailAddresses(AddressValidationMappingByID, UserInfo.getSessionId());
		system.debug('CustomerDetail Validation: ' + errors);
		
		PageReference nextPage = Page.CustomerIntegration;
		nextPage.getParameters().put('Id', [select Id from Order__c where Opportunity__r.Id =: opp.Id limit 1].Id);
		nextPage.setRedirect(true);
		return nextPage;
	}
	
	private void loadAccount(){
		String accountId = '';
		accountId = ApexPages.currentPage().getParameters().get('accountId');
		if(accountId != '')
		{
			account = [select Id
							 ,Name
							 ,Phone
							 ,OwnerId
							 ,Agency__c
							 ,Billable__c
							 ,Customer_Detail__c
							 ,ShippingStreet
							 ,ShippingCity
							 ,ShippingState
							 ,ShippingPostalCode 
							 ,ICC_Account_Type__c
					   from Account 
					   where id = :accountId limit 1];
		}
	}
	
	private List<Service_Location__c> loadServiceLocation(string AccountId){
		return [select Id, Name, Customer_Detail__c from Service_Location__c where account__c = :AccountId limit 1];
	}
	
	private PageReference refresh(){
		PageReference nextPage = Page.ILECOpportunityGeneration;
        nextPage.getParameters().put('accountId', account.Id);
        nextPage.setRedirect(true);
        return nextPage;
	}
}