objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Address Component: City</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Address Component: Zip</description>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Address Component: State</description>
    <inlineHelpText>Use 2-digit abbreviation for State</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/CN__c/CN__c.object-meta.xml
<CustomObject>
    <label>CN</label>
    <nameField>
        <label>CN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CN__c/fields/Opportunity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line Item</label>
    <referenceTo>OLI__c</referenceTo>
    <relationshipLabel>CNs</relationshipLabel>
    <relationshipName>CNs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/CN__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>CNs</relationshipLabel>
    <relationshipName>CNs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/DID__c/DID__c.object-meta.xml
<CustomObject>
    <description>To enter multiple non-sequential numbers, you can add them individually (Save and New), or put a comma between them in the TN Range Start/Non Sequential field.</description>
    <label>DID and Virtual TN</label>
    <nameField>
        <displayFormat>DID-{00000}</displayFormat>
        <label>DID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DID&#39;s and Virtual TN&#39;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DID__c/fields/Technical_Information__c.field-meta.xml
<CustomField>
    <fullName>Technical_Information__c</fullName>
    <label>Technical Information</label>
    <referenceTo>Technical_Information__c</referenceTo>
    <relationshipName>DIDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Location__c/fields/Room_Suite__c.field-meta.xml
<CustomField>
    <fullName>Room_Suite__c</fullName>
    <label>Room/Suite</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OLI__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>OpportunityLocationConfiguration__r.Opportunity_Location__r.Opportunity__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Current_LD_Provider__c.field-meta.xml
<CustomField>
    <fullName>Current_LD_Provider__c</fullName>
    <label>Current LD Provider</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Current_Provider_Local__c.field-meta.xml
<CustomField>
    <fullName>Current_Provider_Local__c</fullName>
    <label>Current Provider Local</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Toggles whether a location is on hold.</description>
    <inlineHelpText>Toggles whether a location is on hold.</inlineHelpText>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/OpportunityLocationConfiguration__c/OpportunityLocationConfiguration__c.object-meta.xml
<CustomObject>
    <description>A configuration for an OpportunityLocation.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityLocationConfiguration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Opportunity_Location__r.Opportunity__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

objects/OpportunityLocationConfiguration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Opportunity_Location__r.Opportunity__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

objects/OpportunityLocationConfiguration__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Solutions</relationshipLabel>
    <relationshipName>OpportunityLocationConfigurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An explicit account lookup that should only be used if the order is not opportunity driven.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account-based Orders</relationshipLabel>
    <relationshipName>Account_Based_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Build Location</description>
    <inlineHelpText>Build Location</inlineHelpText>
    <label>Location</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Technical_Information__c/Technical_Information__c.object-meta.xml
<CustomObject>
    <label>Technical Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Technical_Information__c/fields/Current_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Current_Service_Provider__c</fullName>
    <label>Current Service Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Technical_Information__c/fields/DID__c.field-meta.xml
<CustomField>
    <fullName>DID__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DID’s</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Technical_Information__c/fields/Opportunity_Site__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Technical Information</relationshipLabel>
    <relationshipName>Technical_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Technical_Information__c/fields/Toll_Free_Provider__c.field-meta.xml
<CustomField>
    <fullName>Toll_Free_Provider__c</fullName>
    <label>Toll Free Provider</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Technical_Information__c/recordTypes/DID.recordType-meta.xml
<RecordType>
    <fullName>DID</fullName>
    <active>true</active>
    <label>04 – DID’s and Virtual TN&#39;s</label>
</RecordType>

main/default/objects/Technical_Information__c/recordTypes/Features_Schedule.recordType-meta.xml
<RecordType>
    <fullName>Features_Schedule</fullName>
    <active>true</active>
    <label>02 – Features Schedule</label>
</RecordType>

objects/Technical_Information__c/recordTypes/Other_Technical_Notes.recordType-meta.xml
<RecordType>
    <fullName>Other_Technical_Notes</fullName>
    <active>true</active>
    <label>01 - Customer Profile</label>
</RecordType>

main/default/objects/Technical_Information__c/recordTypes/Toll_Free_Services.recordType-meta.xml
<RecordType>
    <fullName>Toll_Free_Services</fullName>
    <active>true</active>
    <label>05 – Toll Free Services</label>
</RecordType>

objects/Toll_Free_Number__c/Toll_Free_Number__c.object-meta.xml
<CustomObject>
    <label>Toll Free Number</label>
    <nameField>
        <displayFormat>TF-{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toll Free Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Toll_Free_Number__c/fields/Technical_Information__c.field-meta.xml
<CustomField>
    <fullName>Technical_Information__c</fullName>
    <label>Technical Information</label>
    <referenceTo>Technical_Information__c</referenceTo>
    <relationshipLabel>Toll Free Numbers</relationshipLabel>
    <relationshipName>Toll_Free_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Toll_Free_Number__c/fields/Toll_Free_Number__c.field-meta.xml
<CustomField>
    <fullName>Toll_Free_Number__c</fullName>
    <label>Toll-Free Number</label>
    <type>Phone</type>
</CustomField>

main/default/classes/ProposalLOAController.cls
public with sharing class ProposalLOAController {   
 
 Map<Id, Service_Location__c> serviceLocations = new Map<Id, Service_Location__c>();
   
	public Boolean doRender {get;Set;}
	
    public class LocationWrapper {
		public String localProvider {get;set;}
		public String ldProvider {get;Set;}
		public String tollFreeProvider {get;set;}
        public List<Toll_Free_Number__c> tollFreeNumbers {get;set;}
        public List<DID__c> didNumbers {get;set;}
        public Boolean didRange {get;set;}
        public CompanyInfo locationAddress { get; set; }
        public Opportunity_Location__c rawLocation {get;set;}
		
        public Boolean hasTollFree {get;set;}
        public Boolean hasVoice {get;set;}
        public Boolean hasIntrastate {get;set;}
        public Boolean hasInterstate {get;set;}
		public Boolean hasTollFreeTech {Get;Set;}
		public Boolean hasCNs {get;Set;}
		public Boolean hasVirtualTN {get;Set;}
		
        
        public LocationWrapper(Opportunity_Location__c loc, Map<Id, Service_Location__c> srvloc, Map<Id, Building__c> buildings) {    	
        	localProvider = loc.Current_Provider_Local__c;
			ldProvider = loc.Current_LD_Provider__c;
        	tollFreeProvider = '';
            rawLocation = loc;
            tollFreeNumbers = new List<Toll_Free_Number__c>();
            didNumbers = new List<DID__c>();
            didRange = false;
            //locationAddress = new CompanyInfo(loc.Service_Location__r.Account__r); 
            String serviceLocName = '';
            String serviceLocId = '';           
            String serviceLocSuite = '';
            Service_Location__c sName = srvloc.get(Loc.Service_Location__c);
    		serviceLocName = sName.Name;
    		serviceLocId = sName.Location__r.Building__r.Id;
   			serviceLocSuite = loc.Service_Location__r.Location__r.Room_Suite__c;
       		Building__c bldg = buildings.get(serviceLocId);
            locationAddress = new CompanyInfo(bldg, serviceLocName, serviceLocSuite);    
            
            hasTollFree = false;
            hasVoice = false;
            hasIntrastate = false;
            hasInterstate = false;
			hasCNs = false;
			hasVirtualTN = false;
        }
		
		public Boolean CanDisplay(){
			return ((hasVoice && hasCNs)||
			       (hasVirtualTN && didNumbers.size()>0)||
			       (hasTollFree && tollFreeNumbers.size() > 0)||
			       (hasIntrastate && (hasCNs || didNumbers.size()>0))||
			       (hasInterstate && (hasCNs || didNumbers.size()>0)));
		}
    }

    public List<LocationWrapper> locations { get; set; }
	public List<LocationWrapper> displayLocations {
		get{
			List<LocationWrapper> locs = new List<LocationWrapper>();
			for(LocationWrapper rapper : locations){
				if(rapper.CanDisplay()){
					locs.add(rapper);
				}
			}
			return locs;
		}
	}
    public CompanyInfo clientMainAddress {get;set;}
    
    public Opportunity currentOpportunity {
        get{
            return currentOpportunity;
        }
        set{
            currentOpportunity = value;
            clientMainAddress = new CompanyInfo(currentOpportunity.Account);        
            getOpportunityLocationInfo();
        }
    }
    
    public Map<Id, Service_Location__c> getRelatedServiceLocations(List<Opportunity_Location__c> locations){
    	Set<Id> ids = new Set<Id>();
    	for(Opportunity_Location__c optloc : locations){
    		ids.Add(optloc.Service_Location__c);
    	}
    	 
    	return new Map<Id, Service_Location__c>([SELECT Name, Location__r.Building__r.Id FROM Service_Location__c WHERE Id IN:ids]);
    }
    
     public Map<Id, Building__c> getRelatedBuildings(List<Service_Location__c> locations){
    	Set<Id> ids = new Set<Id>();
    	for(Service_Location__c srvloc : locations){
    		ids.Add(srvloc.Location__r.Building__r.Id);
    	}
    	 
    	return new Map<Id, Building__c>([SELECT Address__c, City__c, State__c, Postal_Code__c FROM Building__c WHERE Id IN:ids]);
    }

    public void getOpportunityLocationInfo(){
        this.doRender = false;
        // don't want to use a map, since want an ordered list
        List<Opportunity_Location__c> rawLocations =  
            [Select Id, Service_Location__r.Location__r.Room_Suite__c, Name, Current_Provider_Local__c, Current_LD_Provider__c,
            Service_Location__r.Account__r.Name, Service_Location__r.Account__r.ShippingState, Service_Location__r.Account__r.ShippingCity, 
            Service_Location__r.Account__r.ShippingStreet, Service_Location__r.Account__r.ShippingPostalCode, 
            Service_Location__r.Account__r.Phone, Service_Location__r.Account__r.Fax,  
            Service_Location__r.Account__r.Local_Service_Provider__c,
            (Select Name From CNs__r ORDER BY Name) 
            From Opportunity_Location__c
            where Order__r.Opportunity__c = :currentOpportunity.Id AND On_Hold__c=false
            ORDER BY Service_Location__r.Account__r.Account_Depth__c, Service_Location__r.Account__r.Name];            
            Map<Id, Service_Location__c> srvloc = getRelatedServiceLocations(rawLocations);
            Map<Id, Building__c> srvlocbuilds = getRelatedBuildings(srvloc.values());
        
	        locations = new List<LocationWrapper>();
	        Set<Id> locIds = new Set<Id>();	        
	        
	        for(Opportunity_Location__c ol : rawLocations){    	
	            locations.add( new LocationWrapper(ol, srvloc, srvlocbuilds));
	            locIds.add(ol.Id);
	        }
        
        Map<Id, RecordType> rtTI = new Map<Id, RecordType>([select		Id, 
        									DeveloperName
		        				   from 	RecordType 
		        				   where 	SObjectType = 'Technical_Information__c'
		        				   and 		(DeveloperName = 'Toll_Free_Services' 
		        				   			or DeveloperName = 'Other_Technical_Notes'
		        				   			or DeveloperName = 'DID'
											or DeveloperName = 'Features_Schedule')]);
        
        
        // need to restrict by record type also
        List<Technical_Information__c> lstTechInfo = 
            [Select Id, 
            		Opportunity_Site__c, 
            		Toll_Free_Provider__c,
            		Current_Service_Provider__c,
					CurrentProvider__c,
					CurrentProviderLD__c,
            		RecordTypeId,
            		(Select Type__c, X8XX_555_5555_Number__c, Ring_to_Number__c, Restrictions__c, X800_Service_Area__c From Toll_Free_Numbers__r ORDER BY X8XX_555_5555_Number__c), 
           			(Select Start__c, End__c From DIDs__r ORDER By Start__c)
            From 	Technical_Information__c
            WHERE 	Opportunity_Site__c in :locIds
            and	  	RecordTypeId in :rtTI.keySet()];
        
        for( Technical_Information__c t : lstTechInfo ) {
            LocationWrapper loc = findLoc(t.Opportunity_Site__c);
            //System.debug('loc Name: ' + loc.rawLocation.Name + ' : L: ' + t.currentProvider__c + ' : LD: ' + t.CurrentProviderLD__c);
			//loc.localProvider = (!string.isEmpty(loc.localProvider) || string.isEmpty(t.CurrentProvider__c)) ? loc.localProvider : t.CurrentProvider__c;
			//loc.ldProvider = (!string.isEmpty(loc.ldProvider) || t.CurrentProviderLD__c == null)? loc.ldProvider : t.CurrentProviderLD__c;
            
			String rtName = rtTI.get(t.RecordTypeId).DeveloperName;
            
            if (rtName == 'Toll_Free_Services') {
            	
            	loc.tollFreeProvider = (t.Toll_Free_Provider__c == null) ? '' : t.Toll_Free_Provider__c;
            
            	if( t.Toll_Free_Numbers__r.size() > 0 ) {
	                for(Toll_Free_Number__c tfn : t.Toll_Free_Numbers__r){
						if(tfn.Type__c == 'Existing Toll-Free Number')
							loc.tollFreeNumbers.add(tfn);
					}
					loc.hasTollFreeTech = true;					
	            }
	            
            } else if (rtName == 'Other_Technical_Notes') {
            	loc.localProvider = string.isEmpty(t.Current_Service_Provider__c) ? loc.localProvider : t.Current_Service_Provider__c;
            	
            } else if (rtName == 'DID') {
            	
	            if( t.DIDs__r.size() > 0 ) {
	                loc.didNumbers.addAll(t.DIDs__r); 
	                if(t.DIDs__r.size() > 1) {
	            		loc.didRange = true;
	            	}
				}
	        }
        }
        
        
        //Get the Inter/Intra/Voice/Toll info
        List<OLI__c> lstOLIs = [Select Id,
        							   OLI__c.OpportunityLocationConfiguration__r.Opportunity_Location__c,
        							   OLI__c.PP_Voice_Line__c,
        							   OLI__c.PP_Toll_Free__c,
        							   OLI__c.PP_LD_Interstate__c,
        							   OLI__c.PP_LD_Intrastate__c,
									   OLI__c.PP_DID_Virtual_TN__c,
									   (select Name from CNs__r)
        					    from   OLI__c
        					    where  OLI__c.OpportunityLocationConfiguration__r.Active__c=true
        					    and    OLI__c.OpportunityLocationConfiguration__r.Opportunity_Location__c in :locIds];   
       
       	for (OLI__c oli : lstOLIs) {
       		LocationWrapper loc = findLoc(oli.OpportunityLocationConfiguration__r.Opportunity_Location__c);
            
			if(!loc.hasCNs && oli.CNs__r != null){ //marked as not, keep trying.  marked as true, we're done.
				for(CN__c cn : oli.CNs__r){
					if(!cn.Name.startsWithIgnoreCase('tn')){
						loc.hasCNs = true;
						break;
					}
				}
			}
		}
		for(OLI__c oli : lstOLIs){
			LocationWrapper loc = findLoc(oli.OpportunityLocationConfiguration__r.Opportunity_Location__c);
			
			loc.hasVoice = (oli.PP_Voice_Line__c || (oli.PP_DID_Virtual_TN__c && (loc.didNumbers.size()>0 || loc.hasCNs)) || loc.hasVoice); //If it's already true, don't set it to false
			loc.hasVirtualTN = (oli.PP_DID_Virtual_TN__c || loc.hasVirtualTN); //If it's already true, don't set it to fase
         	loc.hasTollFree = ((oli.PP_Toll_Free__c && loc.tollFreeNumbers.size() > 0) || loc.hasTollFree); //If it's already true, don't set it to false
         	loc.hasInterstate = (oli.PP_LD_Interstate__c || (loc.hasInterstate && (loc.didNumbers.size()>0 || loc.hasCNs))); //If it's already true, don't set it to false
         	loc.hasIntrastate = (oli.PP_LD_Intrastate__c || (loc.hasIntrastate && (loc.didNumbers.size()>0 || loc.hasCNs))); //If it's already true, don't set it to false
			
			this.doRender |= loc.CanDisplay();
       	}     
    }

    public LocationWrapper findLoc(Id locId) {
        for( LocationWrapper lw : locations ) {
            if( lw.rawLocation.Id == locId)
                return lw;              
        }
        return null;
    }
}