objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>New - Newly entered and awaiting verification
Validated - Validated against duplicates and assigned a CLLI Code
Build Approved - Optional, Capital Allocated
Pending Build - Optional, ESO Initiated
Active - Ready to provide services</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Build Approved</fullName>
            </value>
            <value>
                <fullName>Pending Build</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Profiled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Junction__c/Junction__c.object-meta.xml
<CustomObject>
    <description>A generic object to object junction to be manipulated in code only.</description>
    <label>Junction</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Junction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Junction__c/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <label>Source ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Junction__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Junction__c/fields/Target_ID__c.field-meta.xml
<CustomField>
    <fullName>Target_ID__c</fullName>
    <label>Target ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Junction__c/fields/Target_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Type__c</fullName>
    <label>Target Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Order_Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Completion_Status__c</fullName>
    <label>Order Completion Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Scoping</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>In Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Contract Renewal Orders</description>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Stage of the sales process you are currently working</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Working</fullName>
            </value>
            <value>
                <fullName>Sales Complete</fullName>
            </value>
            <value>
                <fullName>Indirect - Sales Complete</fullName>
            </value>
            <value>
                <fullName>Completed to Billing/Billing Only</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Referred to SE</fullName>
            </value>
            <value>
                <fullName>SSS Held</fullName>
            </value>
            <value>
                <fullName>SE Received</fullName>
            </value>
            <value>
                <fullName>SE Held</fullName>
            </value>
            <value>
                <fullName>SE Complete</fullName>
            </value>
            <value>
                <fullName>SSS SE Received</fullName>
            </value>
            <value>
                <fullName>Order to Pending</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Records Updated Only/No Order</fullName>
            </value>
            <value>
                <fullName>Returned to Account Specialists - Wholesale</fullName>
            </value>
            <value>
                <fullName>Order Accepted</fullName>
            </value>
            <value>
                <fullName>SSS Reviewing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Provisioning_Product__c/Provisioning_Product__c.object-meta.xml
<CustomObject>
    <label>Provisioning Product</label>
    <nameField>
        <label>Provisioning Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provisioning Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SPC_Product__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>SPC Products</relationshipLabel>
    <relationshipName>SPC_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SPC_Product__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <externalId>true</externalId>
    <label>SalesProductExternalID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Sub Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending Sales</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
            </value>
            <value>
                <fullName>Pending DM</fullName>
            </value>
            <value>
                <fullName>Waiting for Telco</fullName>
            </value>
            <value>
                <fullName>Waiting for Translations</fullName>
            </value>
            <value>
                <fullName>Waiting for Circuit Design</fullName>
            </value>
            <value>
                <fullName>Waiting For - Facilities: ILEC</fullName>
            </value>
            <value>
                <fullName>Waiting For - Task/Stage Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

classes/Test_RelatedOrdersSubOrders.cls
@isTest
public with sharing class Test_RelatedOrdersSubOrders {
	static testMethod void testController(){
        Mocks testData = new Mocks();
    	test.startTest();
    	
    	Order__c o = testData.order;
    	Apexpages.StandardController sc = new Apexpages.StandardController(o);
    	RelatedOrdersSubOrders roso = new RelatedOrdersSubOrders(sc);
    	
    	roso.DetermineRelationOfOrderOrSub(o);
    	
    	List<Order__c> lOrd = new List<Order__c>();
    	
    	lOrd.add(testData.order);
    	
    	roso.RelatedOrder(lOrd);
    	    	    	
    	roso.Save();
    	
    	roso.SaveManual();
    	
    	roso.Remove();				
		
		Order__c ord = testData.order;
		SPC_Product__c spc = new SPC_Product__c(
    									SalesProductExternalID__c = -1
    									,Provisioning_Product__c = testData.mpProvProd.get('Standard').Id
    									);
    	insert spc;
		Sub_Order__c so = new Sub_Order__c(
    									Service_Location__c = testData.serviceLocation.Id
    									,Order__c = ord.Id
    									,SPC_Product__c = spc.Id
    									,Workplan_Start_Date__c = Date.today()
    									);
    	insert so;
    	
    	Apexpages.StandardController sosc = new Apexpages.StandardController(o);
    	RelatedOrdersSubOrders rso = new RelatedOrdersSubOrders(sosc);
    	
    	List<Sub_Order__c> subOrd = new List<Sub_Order__c>();
    	
    	subOrd.add(so);
    	
    	rso.RelatedSubOrders(subOrd);
    	    	    	
    	rso.Save();
    	
    	rso.SaveManual();
    	
    	rso.Remove();
    	
    	test.stopTest();
	}
    
    static testmethod void testSave(){
        Mocks Testdata = new Mocks();
        ApexPages.StandardController ctrl = new ApexPages.StandardController(Testdata.order);
        RelatedOrdersSubOrders obj = new RelatedORdersSubOrders(ctrl);
        obj.ModifiedTempIds = JSON.serialize(new Set<String>{Testdata.suborder.Id});
        
        Test.startTest();
        obj.Save();       
    }
    
    static testmethod void testSaveManual(){
        Mocks Testdata = new Mocks();
        ApexPages.StandardController ctrl = new ApexPages.StandardController(Testdata.order);
        RelatedOrdersSubOrders obj = new RelatedOrdersSubOrders(ctrl);
        
        Sub_Order__c suborder = new Sub_Order__c(Order__c = Testdata.order.Id);
        suborder.Status__c = 'In Progress';
        insert suborder;
        
        obj.AddSubOrder = [Select Id, Name from Sub_Order__c Where Id =: suborder.Id Limit 1][0].Name;
        
        Test.startTest();
        obj.SaveManual();
        
        Junction__c junc = new Junction__c(Source_ID__c = Testdata.order.Id, Target_ID__c = suborder.Id, Source_Type__c = 'Test', Target_Type__c = 'Test');
        insert junc;
        
        obj.SaveManual();
    }
    
    static testmethod void testRemove(){
        Mocks Testdata = new Mocks();
        ApexPages.StandardController ctrl = new ApexPages.StandardController(Testdata.order);
        RelatedOrdersSubOrders obj = new RelatedOrdersSubOrders(ctrl);
        
        obj.ModifiedTempIds = JSON.serialize(new Set<String>{Testdata.suborder.Id, Testdata.order.Id});
        Junction__c junc = new Junction__c(Source_ID__c = Testdata.order.Id, Target_ID__c = Testdata.suborder.Id, Source_Type__c = 'Test', Target_Type__c = 'Test');
        insert junc;
        
        Test.startTest();
        obj.Remove();
    }
    
    static testmethod void testOrderWrapper(){
        Mocks Testdata = new Mocks();
        
        Test.startTest();
        RelatedOrdersSubOrders.OrderWrapper inst = new RelatedOrdersSubOrders.OrderWrapper(Testdata.order, true);
        System.assertEquals(true, inst.isSelected);
    }
    
    static testmethod void testSubOrderWrapper(){
        Mocks Testdata = new Mocks();
        
        Test.startTest();
        RelatedOrdersSubOrders.SubOrderWrapper inst = new RelatedOrdersSubOrders.SubOrderWrapper(Testdata.suborder, true);
        System.assertEquals(true, inst.isSelected);
    }
    
    static testmethod void testsObjectWrapper(){
        Mocks Testdata = new Mocks();
        
        Test.startTest();
        RelatedOrdersSubOrders.sObjectWrapper inst = new RelatedOrdersSubOrders.sObjectWrapper(Testdata.suborder, true);
		System.assertEquals(true, inst.isSelected);
    }
    
    static testmethod void testRelatedSubOrders(){
        Mocks Testdata = new Mocks();
        ApexPages.StandardController ctrl = new ApexPages.StandardController(Testdata.order);
        RelatedOrdersSubOrders obj = new RelatedOrdersSubOrders(ctrl);
        // source = order // target = suborder
        
        Junction__c junc = new Junction__c(Source_ID__c = Testdata.order.Id, Target_ID__c = Testdata.suborder.Id, Source_Type__c = 'Test', Target_Type__c = 'Test');
        insert junc;
        
        Test.startTest();
        obj.RelatedSubOrders(new List<Sub_Order__c>{Testdata.suborder});        
    }
    
    static testmethod void testRelatedOrder(){
        Mocks Testdata = new Mocks();
        ApexPages.StandardController ctrl = new ApexPages.StandardController(Testdata.order);
        RelatedOrdersSubOrders obj = new RelatedOrdersSubOrders(ctrl);
        // source = suborder // target = order
        
        Junction__c junc = new Junction__c(Source_ID__c = Testdata.suborder.Id, Target_ID__c = Testdata.order.Id, Source_Type__c = 'Test', Target_Type__c = 'Test');
        insert junc;
        
        Test.startTest();
        obj.RelatedOrder(new List<Order__c>{Testdata.order});        
    }
    
    static testmethod void testDetermineRelationOfOrderOrSub(){
        Mocks Testdata = new Mocks();
        
        Order__c order = new Order__c(opportunity__c = Testdata.opportunity.Id);
        order.Order_Completion_Status__c = 'In Progress';
       	order.RecordTypeId = Schema.Sobjecttype.Order__c.getRecordTypeInfosByName().get('Build Order').getRecordTypeId();
        order.building__c = Testdata.building.Id;
        insert order;
        
		Test.startTest();
        ApexPages.StandardController ctrl = new ApexPages.StandardController(order);
        RelatedOrdersSubOrders obj = new RelatedOrdersSubOrders(ctrl);
    }
    
    static testmethod void testGettersAndSetters(){
        Mocks Testdata = new Mocks();
   		ApexPages.StandardController ctrl = new ApexPages.StandardController(Testdata.order);
        RelatedOrdersSubOrders obj = new RelatedOrdersSubOrders(ctrl);
        
        System.assertEquals(obj.o = Testdata.order, obj.o);
        System.assertEquals(obj.getRelatedWrapperCollection(), (List<RelatedOrdersSubOrders.sObjectWrapper>)obj.ritem);
        System.assertEquals(obj.getWrapperCollection(), (List<RelatedOrdersSubOrders.sObjectWrapper>)obj.oitem);
        System.assertEquals(JSON.deserialize(obj.ModifiedTempIds, Set<String>.Class), null);
        System.assertEquals(obj.AddSubOrder, null);     
    }
}