objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Address Component: City</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Address Component: Zip</description>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Address Component: State</description>
    <inlineHelpText>Use 2-digit abbreviation for State</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Directory_Listing__c/Directory_Listing__c.object-meta.xml
<CustomObject>
    <label>Directory Listing</label>
    <nameField>
        <displayFormat>DL-{00000}</displayFormat>
        <label>Listing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Directory Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Directory_Listing__c/fields/Technical_Information__c.field-meta.xml
<CustomField>
    <fullName>Technical_Information__c</fullName>
    <label>Directory Listing</label>
    <referenceTo>Technical_Information__c</referenceTo>
    <relationshipLabel>Directory Listings</relationshipLabel>
    <relationshipName>Directory_Listings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/ICB__c/ICB__c.object-meta.xml
<CustomObject>
    <description>Custom object to better track Individual Case Basis requests</description>
    <label>ICB</label>
    <nameField>
        <displayFormat>ICB Request-{000000}</displayFormat>
        <label>ICB Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICBs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ICB__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Service Location for Off-Net Quoting Request</description>
    <inlineHelpText>Service Location for Off-Net Quoting Request</inlineHelpText>
    <label>Service Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>ICBs (Location)</relationshipLabel>
    <relationshipName>ICBs1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/ICB__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>&quot;Contract Term&quot; value from the related Opportunity</description>
    <inlineHelpText>This is the &quot;Contract Term&quot; value from the related Opportunity</inlineHelpText>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Location__c/fields/Room_Suite__c.field-meta.xml
<CustomField>
    <fullName>Room_Suite__c</fullName>
    <label>Room/Suite</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OLI__c/fields/MRC_Total__c.field-meta.xml
<CustomField>
    <fullName>MRC_Total__c</fullName>
    <formula>Qty__c  * (MRC__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MRC Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/OLI__c/fields/OpportunityLocationConfiguration__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLocationConfiguration__c</fullName>
    <label>OpportunityLocationConfiguration</label>
    <referenceTo>OpportunityLocationConfiguration__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/MRC_Total__c.field-meta.xml
<CustomField>
    <fullName>MRC_Total__c</fullName>
    <label>MRC Total</label>
    <summarizedField>OpportunityLocationConfiguration__c.MRC_Total__c</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLocationConfiguration__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLocationConfiguration__c.Opportunity_Location__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OpportunityLocationConfiguration__c/OpportunityLocationConfiguration__c.object-meta.xml
<CustomObject>
    <description>A configuration for an OpportunityLocation.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OpportunityLocationConfiguration__c/fields/Display_on_Solution__c.field-meta.xml
<CustomField>
    <fullName>Display_on_Solution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display on Solution</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/OpportunityLocationConfiguration__c/fields/MRC_Total__c.field-meta.xml
<CustomField>
    <fullName>MRC_Total__c</fullName>
    <label>MRC Total</label>
    <summarizedField>OLI__c.MRC_Total__c</summarizedField>
    <summaryForeignKey>OLI__c.OpportunityLocationConfiguration__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/OpportunityLocationConfiguration__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Solutions</relationshipLabel>
    <relationshipName>OpportunityLocationConfigurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/OpportunityLocationConfiguration__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
                <default>true</default>
                <label>24</label>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>Month to Month</fullName>
            </value>
            <value>
                <fullName>Coterminous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Build Location</description>
    <inlineHelpText>Build Location</inlineHelpText>
    <label>Location</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Technical_Information__c/Technical_Information__c.object-meta.xml
<CustomObject>
    <label>Technical Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Technical_Information__c/fields/Opportunity_Site__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Technical Information</relationshipLabel>
    <relationshipName>Technical_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Technical_Information__c/recordTypes/DID.recordType-meta.xml
<RecordType>
    <fullName>DID</fullName>
    <active>true</active>
    <label>04 – DID’s and Virtual TN&#39;s</label>
</RecordType>

main/default/classes/Test_Proposal.cls
@isTest
public with sharing class Test_Proposal extends TestUtils.TestClass {
	
    static testMethod void testGenericController() {
        Mocks testData = new Mocks();
        
        ProposalGenericController ctr = new ProposalGenericController();
        ctr.currentOpportunity = testData.opportunity;
        //loopThroughAddress(ctr.integraDecisionMaker);
        loopThroughAddress(ctr.clientMainAddress);
        
        List<User> lstUsers = [SELECT Id, Name, FirstName, LastName, Preferred_First_Name__c, Street, City, State, PostalCode, Phone, MobilePhone, Fax, Email, Title from User limit 1];
        
        CompanyInfo address = new CompanyInfo(lstUsers[0]);
    }
    
    static void loopThroughAddress(CompanyInfo address) {
        String temp = address.Name;
        temp = address.Street;
        temp = address.City;
        temp = address.CityStateZip;
        temp = address.Email;
        temp = address.Phone;
        temp = address.State;
        temp = address.Title;
        temp = address.Zip;     
    }

    static testMethod void testLOA() {
        Mocks testData = new Mocks();
		
		Opportunity opp = testData.opportunity;
		Opportunity_Location__c loc = testData.location;
		List<OLI__c> olis = testData.lstLineItems;
		
		RecordType rt = [select Id from RecordType where SObjectType = 'Technical_Information__c' and DeveloperName = 'DID'];
		List<Technical_Information__c> tis = new List<Technical_Information__c>{
																	        	new Technical_Information__c(Opportunity_Site__c = loc.Id, RecordTypeId = rt.Id)
																	        	,new Technical_Information__c(Opportunity_Site__c = loc.Id, RecordTypeId = rt.Id)
																			};
		insert tis;
		
		test.startTest();
        
        ProposalLOAController ctr = new ProposalLOAController();
        ctr.currentOpportunity = opp;
    }

    static testMethod void testDirectoryForm() {
        Mocks testData = new Mocks();
        
        ProposalDirectoryForm ctr = new ProposalDirectoryForm();
        ctr.currentOpportunity = testData.opportunity;
    } 
    
    static testMethod void testServiceAgreement() {
        Mocks testData = new Mocks();
		
		Order__c ord = testData.Order;
		Opportunity opp = testData.opportunity;
		List<OLI__c> olis = testData.lstLineItems;
		
		test.startTest();
		
        ProposalServiceAgreementController ctr = new ProposalServiceAgreementController();
        ctr.currentOpportunity = opp;
		
		ProposalServiceAgreementController.Location l = new ProposalServiceAgreementController.Location();
    }

    static testMethod void testQuote() {
        Mocks testData = new Mocks();
		
		List<OpportunityLocationConfiguration__c> sols = testData.lstconfig;
		List<OLI__c> olis = testData.lstLineItems;
		Opportunity_Location__c oppLoc = testData.location;
		oppLoc = [select Id, MRC_Total__c
						,Service_Location__r.Name, Service_Location__r.Location__r.Room_Suite__c
						,Service_Location__r.Location__r.Building__r.Id, Service_Location__r.Location__r.Building__r.Address__c, Service_Location__r.Location__r.Building__r.City__c
							,Service_Location__r.Location__r.Building__r.State__c, Service_Location__r.Location__r.Building__r.Postal_Code__c
						,(select Id, Term__c, Display_on_Solution__c, Name from OpportunityLocationConfigurations__r) from Opportunity_Location__c where Id =: oppLoc.Id];
		test.startTest();
        
        ProposalQuoteController ctr = new ProposalQuoteController();
		ctr.oppLocs = new Map<Id, Opportunity_Location__c>{ oppLoc.Id => oppLoc };
		ctr.OppLocOLIs = olis;
        ctr.currentOpportunityLocationId = oppLoc.Id;
		
        system.debug(ctr.comparisonTotal);
        system.debug(ctr.currentOpportunityLocationId);
        system.debug(ctr.lstProducts);
        system.debug(ctr.MonthlySavingsAmount);
        system.debug(ctr.MonthlyPercentSavingsAmount);
        system.debug(ctr.AnnualSavingsAmount);
    }
    
    
    static testMethod void testProposalGeneratePDFController() {
        Mocks testData = new Mocks();
		
		Opportunity opp = testData.opportunity;
		Contact c = testData.parentAccountContact;
		
		test.startTest();
		
    	PageReference pageReference = Page.ProposalGeneratePDF;
        pageReference.getParameters().put('recipient', c.Id);
        Test.setCurrentPage(pageReference);

        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(opp);
        ProposalGeneratePDFController ctr = new ProposalGeneratePDFController(sc);
		
		//Pull the page elements
		system.debug('ErateWCLTPageBreak: ' + ctr.ErateWCLTPageBreak);
		system.debug('ErateSAPageBreak: ' + ctr.ErateSAPageBreak);
		system.debug('LTPageBreak: ' + ctr.LTPageBreak);
		system.debug('ESPageBreak: ' + ctr.ESPageBreak);
		system.debug('QTPageBreak: ' + ctr.QTPageBreak);
		system.debug('CCPageBreak: ' + ctr.CCPageBreak);
		system.debug('SAPageBreak: ' + ctr.SAPageBreak);
		system.debug('LOAPageBreak: ' + ctr.LOAPageBreak);
		system.debug('DFPageBreak: ' + ctr.DFPageBreak);
		system.debug('FormMSA: ' + ctr.FormMSA);
		system.debug('FormMSACollaboration: ' + ctr.FormMSACollaboration);
		system.debug('FormMSAColocation: ' + ctr.FormMSAColocation);
		system.debug('FormMSADDos: ' + ctr.FormMSADDos);
		system.debug('FormMSADEthernetServices: ' + ctr.FormMSADEthernetServices);
		system.debug('FormMSAHSISPageBreak: ' + ctr.FormMSAHSISPageBreak);
		system.debug('FormMSA_HVS: ' + ctr.FormMSA_HVS);
		system.debug('FormMSAUCCloudVoicePageBreak: ' + ctr.FormMSAUCCloudVoicePageBreak);
		system.debug('FormMSAVPNPageBreak: ' + ctr.FormMSAVPNPageBreak);
		system.debug('FormWaveLengthPageBreak: ' + ctr.FormWaveLengthPageBreak);
		system.debug('FormMSAWirelessBackupAddendum: ' + ctr.FormMSAWirelessBackupAddendum);
		system.debug('FormMSAMonthToMonthRenewal: ' + ctr.FormMSAMonthToMonthRenewal);
		system.debug('FormInsideWirePageBreak: ' + ctr.FormInsideWirePageBreak);
		system.debug('Form911PageBreak: ' + ctr.Form911PageBreak);
		system.debug('FormSummaryOfWork: ' + ctr.FormSummaryOfWork);
		system.debug('FormPaperlessPageBreak: ' + ctr.FormPaperlessPageBreak);
		system.debug('ROLOAPageBreak: ' + ctr.ROLOAPageBreak);
		system.debug('FormETFCreditPageBreak: ' + ctr.FormETFCreditPageBreak);
		system.debug('FormIncentiveMRCPageBreak: ' + ctr.FormIncentiveMRCPageBreak);
		system.debug('FormIncentiveAmountPageBreak: ' + ctr.FormIncentiveAmountPageBreak);
		system.debug('FormSatGuaranteePageBreak: ' + ctr.FormSatGuaranteePageBreak);
		system.debug('FormMovePageBreak: ' + ctr.FormMovePageBreak);
		system.debug('FormBusinessDownturnSRPageBreak: ' + ctr.FormBusinessDownturnSRPageBreak);
		system.debug('FormBusinessDownturnLDPageBreak: ' + ctr.FormBusinessDownturnLDPageBreak);
		system.debug('FormCFSCB: ' + ctr.FormCFSCB);
		system.debug('FormCFSServiceSLA: ' + ctr.FormCFSServiceSLA);
		system.debug('LOACPNIPageBreak: ' + ctr.LOACPNIPageBreak);
		system.debug('FormPartnerPageBreak: ' + ctr.FormPartnerPageBreak);
		system.debug('FormITServicesPageBreak: ' + ctr.FormITServicesPageBreak);
		
		//Now load a doc
        pageReference.getParameters().put('document', string.valueOf(GlobalUtilities.DOCGENBIT_QUOTE));
        ctr = new ProposalGeneratePDFController(sc);
		
		ProposalGeneratePDFController.OppLocOLIView v = new ProposalGeneratePDFController.OppLocOLIView(null, null);
    }
    
    static testMethod void testProposalGenericController() {
        Mocks testData = new Mocks();
        PageReference pageReference = Page.ProposalGeneratePDF;
        pageReference.getParameters().put('recipient', testData.parentAccountContact.Id);
        pageReference.getParameters().put('id', testData.opportunity.Id);
        Test.setCurrentPage(pageReference);
        
        ProposalGenericController ctr = new ProposalGenericController();        
    }

    static testMethod void testGeneratePDF() {
        Mocks testData = new Mocks();
		
		Opportunity opp = testData.opportunity;
		
		SPC_Product__c p = new SPC_Product__c(SalesProductExternalID__c = 185, Expiration__c = null, Hide_In_Wizard__c = false);
		insert p;
		
		OLI__c oli = new OLI__c(MRC__c = 123, OpportunityLocationConfiguration__c=testData.lstconfig[0].Id,  Qty__c=3, SPC_Sales_Product__c = p.Id);
		insert oli;
		
		Contact c = testData.parentAccountContact;
		OpportunityContactRole ocr = new OpportunityContactRole(ContactId = c.Id, OpportunityId = opp.Id, Role = 'Some Jerk');
		insert ocr;
		
		PDF_Mapping__c pdf = new PDF_Mapping__c(Name = 'Peetie F', Selected_PDFS__c = 'TheLunchCodes.pdf', SPC_Product__c = p.Id);
		insert pdf;
		
		ICB__c icb = new ICB__c(ICB_Type__c = 'AiShiBi', ICB_Pricing_Reason__c = 'Ballin', Sales_Engineer__c = testData.user.Id, Opportunity__c = opp.Id);
		insert icb;
		
		test.startTest();
        
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(opp);
		OpptyGeneratePDFController ctr = new OpptyGeneratePDFController(sc);
		ctr.currentOppty = opp;
        ctr.fileContents = Blob.valueOf('test');
        ctr.fileContentsUpload = Blob.valueOf('test');
        ctr.pageBytes = Blob.valueOf('test');
        ctr.selectedDocType = 'test';
        ctr.ShowDisplayButton = false;
        ctr.oTypeName = 'test';
        ctr.JSONSelectedProps = JSON.serialize(new List<String>{'1', '2'});
		ctr.selectedAction = 'Store';
		ctr.cv.Title = 'Content';
		ctr.cv.Description = 'Description';
		OpptyGeneratePDFController.storeDocURL = URL.getSalesforceBaseUrl().toExternalForm() + '/home/home.jsp';
		//ctr.bytes = Blob.valueOf('Don\'t let the bed bugs');
		
        system.debug(ctr.potentialRecipients);
        system.debug(ctr.recipients);
        system.debug(ctr.selectedContactRecipent);
        system.debug(ctr.documentActions);
		system.debug(ctr.indirectSections);
        system.debug(ctr.proposalSections);
        system.debug(ctr.contractSections);
        system.debug(ctr.otherSections);
        //ctr.getPageBytes();
        ctr.generate();
        ctr.generateNextPageUrl();
        
        ctr.selectedContactRecipent = null;
        ctr.generate();
		ctr.createProposalElements();
        //ctr.getObjectProperties();
   	}
            
    static testMethod void testGeneratePDFStore() {
        Mocks testData = new Mocks();
        
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(testData.opportunity);
		System.debug(testData.order);
		
        OpptyGeneratePDFController ctr = new OpptyGeneratePDFController(sc);
		ctr.JSONSelectedProps = JSON.serialize(new List<String>());
        ctr.selectedProposalSections.add(ctr.proposalSections[0].getValue() );
        ctr.selectedProposalSections.add(ctr.proposalSections[1].getValue() );
        ctr.selectedProposalSections.add(ctr.proposalSections[2].getValue() );
        ctr.generateNextPageUrl();

        ctr.selectedAction = 'Store';
        ctr.generate();     
    }
	
	static testMethod void testCompanyInfo(){
        Mocks testData = new Mocks();
		
		Account a = testData.parentAccount;
		Opportunity opp = testData.opportunity;
		User u = testData.user;
		
		Building__c b = testData.building;
		Location__c loc = testData.loc;
		Service_Location__c sLoc = testData.serviceLocation;
		
		Directory_Listing__c dl = new Directory_Listing__c();
		
		test.startTest();
		
		CompanyInfo ci = new CompanyInfo(a, true);
		ci = new CompanyInfo(a, false);
		
		ci = new CompanyInfo(opp, u);
		
		ci = new CompanyInfo(b, sLoc.Name);
		ci = new CompanyInfo(b, sLoc.Name, loc.Room_Suite__c);
		
		ci = new CompanyInfo(dl);
	}
	
	static testMethod void testPDFMapping(){
		test.startTest();
		
		PDFMapping m = new PDFMapping();
		system.assert(m.AvailablePDFS.size() > 0, 'No available PDFs found');
		system.assert(m.existingMappings.size() == 0, 'Existing custom PDF mappings encountered');
		m.NewMapping();
		m.SaveData();
		m.SelectedID = m.SelectedPDF.Id;
		m.GatherData();
		m.DeleteSelected();
	}
}