objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Building_CLLI__c.field-meta.xml
<CustomField>
    <fullName>Building_CLLI__c</fullName>
    <label>Building CLLI</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/Building_Hash__c.field-meta.xml
<CustomField>
    <fullName>Building_Hash__c</fullName>
    <externalId>true</externalId>
    <label>Building Hash</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Building__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <label>Building Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meet Point</fullName>
            </value>
            <value>
                <fullName>Commercial Building</fullName>
            </value>
            <value>
                <fullName>ILEC LSO</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Collocated</fullName>
            </value>
            <value>
                <fullName>ILEC Remote Switch</fullName>
            </value>
            <value>
                <fullName>Wireless MSC</fullName>
            </value>
            <value>
                <fullName>Wireless Tower</fullName>
            </value>
            <value>
                <fullName>Integra Hut/Shelter</fullName>
            </value>
            <value>
                <fullName>Pending Build</fullName>
            </value>
            <value>
                <fullName>Carrier POP</fullName>
            </value>
            <value>
                <fullName>Data Center</fullName>
            </value>
            <value>
                <fullName>Integra Switch/Hub</fullName>
            </value>
            <value>
                <fullName>Carrier Hotel</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Off Footprint</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Extended Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Address Component: City</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

objects/Building__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

objects/Building__c/fields/Net_Classification__c.field-meta.xml
<CustomField>
    <fullName>Net_Classification__c</fullName>
    <label>Net Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eNNI</fullName>
            </value>
            <value>
                <fullName>ILEC</fullName>
            </value>
            <value>
                <fullName>Near-net</fullName>
            </value>
            <value>
                <fullName>Off-net</fullName>
            </value>
            <value>
                <fullName>On-net</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Building__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Address Component: Zip</description>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Serving_LSO__c.field-meta.xml
<CustomField>
    <fullName>Serving_LSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serving LSO</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Invalid serving LSO - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Building__c.Is_Serving_LSO__c</field>
            <operation>equals</operation>
            <value>true</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Buildings (Serving LSO)</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Building__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Address Component: State</description>
    <inlineHelpText>Use 2-digit abbreviation for State</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>New - Newly entered and awaiting verification
Validated - Validated against duplicates and assigned a CLLI Code
Build Approved - Optional, Capital Allocated
Pending Build - Optional, ESO Initiated
Active - Ready to provide services</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Build Approved</fullName>
            </value>
            <value>
                <fullName>Pending Build</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Profiled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Building_Access_Availability__c/Building_Access_Availability__c.object-meta.xml
<CustomObject>
    <label>Building Access Availability</label>
    <nameField>
        <label>Access Availability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building Access Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Building_Access_Availability__c/fields/Access_Technology_Name__c.field-meta.xml
<CustomField>
    <fullName>Access_Technology_Name__c</fullName>
    <formula>Access_Technology__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Access Technology Name</label>
    <type>Text</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Building Access Availabilities</relationshipLabel>
    <relationshipName>Access_Availabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Maximum_Bandwidth__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Bandwidth__c</fullName>
    <label>Maximum Bandwidth (Mbps)</label>
    <precision>7</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

objects/Building_Access_Availability__c/fields/Minimum_Required_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Required_Revenue__c</fullName>
    <label>Minimum Required Revenue</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Net_Classification__c.field-meta.xml
<CustomField>
    <fullName>Net_Classification__c</fullName>
    <formula>Text(Building__r.Net_Classification__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Classification</label>
    <type>Text</type>
</CustomField>

objects/Building_Access_Availability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <color>#78C953</color>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Auto-Augment</fullName>
                <color>#F3D904</color>
                <label>Auto-Augment</label>
            </value>
            <value>
                <fullName>ICB</fullName>
                <color>#FF0000</color>
                <label>ICB</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Near-net Profiled</fullName>
                <color>#FFFF66</color>
                <label>Near-net Profiled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Georesults_business__c/Georesults_business__c.object-meta.xml
<CustomObject>
    <description>Contact Details Loaded from third party data providers such as GeoResults.</description>
    <label>GeoResults Business</label>
    <nameField>
        <displayFormat>GB-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Georesults Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Georesults_business__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Street address where this business is located, generally including the street number and street name.</description>
    <inlineHelpText>Street address where this business is located, generally including the street number and street name.</inlineHelpText>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

objects/Georesults_business__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Georesults Businesses</relationshipLabel>
    <relationshipName>Georesults_Businesses</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Georesults_business__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Name of the city, town, township, or municipality where this business is located.</description>
    <inlineHelpText>Name of the city, town, township, or municipality where this business is located.</inlineHelpText>
    <label>City</label>
    <type>TextArea</type>
</CustomField>

objects/Georesults_business__c/fields/CleanBusiness__c.field-meta.xml
<CustomField>
    <fullName>CleanBusiness__c</fullName>
    <description>Name of this business after it has been cleansed of extra characters such as inc. and the.</description>
    <label>Cleaned Business Name</label>
    <type>TextArea</type>
</CustomField>

objects/Georesults_business__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Complete name of the primary contact at this business location.</description>
    <inlineHelpText>Complete name of the primary contact at this business location.</inlineHelpText>
    <label>Contact Name</label>
    <type>TextArea</type>
</CustomField>

objects/Georesults_business__c/fields/GeoId__c.field-meta.xml
<CustomField>
    <fullName>GeoId__c</fullName>
    <description>Unique identification number for this business assigned by GeoResults.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identification number for this business assigned by GeoResults.</inlineHelpText>
    <label>GeoId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/Georesults_business__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location relating to the Unit value in the GeoResults Business Record</description>
    <inlineHelpText>Look-up the Location object this record is related to.</inlineHelpText>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Georesults Businesses</relationshipLabel>
    <relationshipName>Georesults_Businesses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Georesults_business__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Standard 2-letter US Postal Service abbreviation for the state where this business is located.</description>
    <inlineHelpText>Standard 2-letter US Postal Service abbreviation for the state where this business is located.</inlineHelpText>
    <label>State</label>
    <type>TextArea</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Location__c/fields/Room_Suite__c.field-meta.xml
<CustomField>
    <fullName>Room_Suite__c</fullName>
    <label>Room/Suite</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/classes/BuildingMergeController.cls
public with sharing class BuildingMergeController implements TestUtils.ITestableClass{

	public Building__c mergeFrom {get;Set;}
	public Building__c mergeTo {get;Set;}
	public string buildingID {get;Set;}
	public string mergeType {get;Set;}
	
	public BuildingMergeController(){
		mergeFrom = new Building__c();
		mergeTo = new Building__c();
	}

	public PageReference GetBuildingData(){
		Building__c b = getBuilding(buildingID);
		if(mergeType == 'from')
			mergeFrom = b;
		else
			mergeTo = b;
		return null;
	}
	
	private Building__c getBuilding(string bldgID){
		return [Select Id,Name,Building_Hash__c,Address__c,City__c,State__c,Postal_Code__c,Building_Type__c,Net_classification__c,building_clli__c,latitude__c,longitude__c
						,(Select Id,Name,Access_Technology_Name__c,Maximum_Bandwidth__c,Minimum_Required_Revenue__c,Status__c From Access_Availabilities__r)
						,(Select Id,Name,CleanBusiness__c,Contact__c,GeoID__c From Georesults_Businesses__r)
						,(Select Id,Name,Building_Hash__c,Address__c,City__c,State__c,Postal_Code__c,Building_Type__c,Net_classification__c,building_clli__c From Buildings__r)
						,(Select Id,Name,Room_Suite__c from Locations__r)	
						From Building__c where Id = :bldgID];
	}
	
	public PageReference mergeObjs(){
		Boolean failed = false;
		
		try{
			Schema.DescribeSObjectResult d = Schema.getGlobalDescribe().get('Building__c').getDescribe();
			
			//Chunk them together by object type so they can be saved together
			Map<String, Map<Id, sObject>> childObjs = new Map<String, Map<Id, sObject>>();
			for(Schema.ChildRelationship cr : d.getChildRelationships()){
				DescribeFieldResult fDesc = cr.getField().getDescribe();
				Schema.DescribeSObjectResult child = cr.getChildSObject().getDescribe();
				if(fDesc.isUpdateable() && child.isQueryable() && child.isUpdateable()){
					String f = fDesc.getName();
					String childObjName = child.getName();
					Map<Id, sObject> m = childObjs.get(childObjName) != null ? childObjs.get(childObjName) : new Map<Id, sObject>();
					for(sObject o : Database.query('select Id from ' + childObjName + ' where ' + f + ' = \'' + mergeFrom.id + '\'')){
						sObject obj = m.get(o.Id) != null ? m.get(o.Id) : o;
						o.put(f, mergeTo.id);
						m.put(o.id, obj);
					}
					
					if(m.size() > 0) childObjs.put(childObjName, m);
				}
			}
			//Callout to update master addressid
			integraWSEndpointMediator.Endpoint.UpdateMasterAddressIDByBuildingHash(mergeFrom.Building_Hash__c,mergeTo.Building_Hash__c,UserInfo.getSessionId(), CustomSettingUtils.SFDCCallbackEndpoint);
			
			for(String childObjName : childObjs.keyset())
				update childObjs.get(childObjName).values();
			
			update mergeTo;
			delete mergeFrom;
			
			
		}
		catch(Exception e){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
			failed = true;
		}
		
		return !failed ? new PageReference('/' + mergeTo.id) : null;
	}
	
	/* TestUtils.ITestableClass methods */
    public TestUtils.TestClass getTestClass(){ return new Test_BuildingMerge(); }
}