objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Serving_LSO__c.field-meta.xml
<CustomField>
    <fullName>Serving_LSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serving LSO</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Invalid serving LSO - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Building__c.Is_Serving_LSO__c</field>
            <operation>equals</operation>
            <value>true</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Buildings (Serving LSO)</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Building_Sales_Product__c/Building_Sales_Product__c.object-meta.xml
<CustomObject>
    <label>Building Sales Product</label>
    <nameField>
        <label>Building Sales Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building Sales Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Building_Sales_Product__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Building Sales Products</relationshipLabel>
    <relationshipName>Building_Sales_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Building_Sales_Product__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Building Sales Products</relationshipLabel>
    <relationshipName>Building_Sales_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BuildingSalesProducts.cls
public with sharing class BuildingSalesProducts {
	public List<Building_Sales_Product__c> bsps {get;set;}

	public BuildingSalesProducts(ApexPages.StandardController stdController){
		ApexPages.Standardcontroller sc = stdController;
        sc.addFields(new List<String>{'serving_lso__r.id'});
		Building__c b = (Building__c)sc.getRecord();
		
		bsps = GetBuildingSalesProducts(b);
	}
	
	public List<Building_Sales_Product__c> GetBuildingSalesProducts(Building__c b){
		if(b.Serving_LSO__c != null)
			return [Select Id,SPC_Product__r.Name, Name From Building_Sales_Product__c Where Building__c = :b.serving_lso__r.id and SPC_Product__r.name != null Order by SPC_Product__r.Name];
		else
			return new List<Building_Sales_Product__c>();
	}
}