objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Address Component: City</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Address Component: Zip</description>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Address Component: State</description>
    <inlineHelpText>Use 2-digit abbreviation for State</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/classes/Test_RecordSelector.cls
@isTest
public with sharing class Test_RecordSelector extends TestUtils.TestClass {
	
	static testMethod void testRecordSelector() {
		Mocks testData = new Mocks();
		
		PageReference pageReference = ApexPages.currentPage();
		pageReference.getParameters().put('sObjectType', 'building__c');
		pageReference.getParameters().put('fields', 'Id,Address__c,City__c,State__c,Postal_Code__c,Name');
		//pageReference.getParameters().put('useRecentRecords', 'true');
		
		RecordSelectorController rsc = new RecordSelectorController();
		
		rsc.multiSelect = false;
		rsc.useRecent = true;
		rsc.filter = 'test';
		rsc.sObjType = 'Building__c';
		rsc.objFields = 'Id,Name';
		rsc.customWhere = 'Locked__c = false';
		System.debug(rsc.sObjType);
		System.debug(rsc.objFields);
		rsc.refreshDataTable(true);
		
		rsc.Reset();
		rsc.ToggleViewMode();
		rsc.GatherSelection();
		
		rsc.PageUpdated('test');
		rsc.SortChanged('test');
		sObjectType t = testdata.building.getSObjectType();
		RecordSelectorController.Config c = new RecordSelectorController.Config(t,false);
		RecordSelectorController.sObjectConfig sc = new RecordSelectorController.sObjectConfig(testData.building.Id);
	}
}