objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Disconnect_Line_Item__c/Disconnect_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Turn Down</label>
    <nameField>
        <displayFormat>DLI-{00000}</displayFormat>
        <label>DLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Turn Downs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Disconnect_Line_Item__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipName>Disconnect_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OLI__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if( OpportunityLocationConfiguration__r.Active__c , 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/OLI__c/fields/MRC__c.field-meta.xml
<CustomField>
    <fullName>MRC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MRC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/OLI__c/fields/MRC_Total__c.field-meta.xml
<CustomField>
    <fullName>MRC_Total__c</fullName>
    <formula>Qty__c  * (MRC__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MRC Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/OLI__c/fields/OpportunityLocationConfiguration__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLocationConfiguration__c</fullName>
    <label>OpportunityLocationConfiguration</label>
    <referenceTo>OpportunityLocationConfiguration__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/OLI__c/fields/PP_LD_Interstate__c.field-meta.xml
<CustomField>
    <fullName>PP_LD_Interstate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PP_LD_Interstate</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/OLI__c/fields/PP_LD_Intrastate__c.field-meta.xml
<CustomField>
    <fullName>PP_LD_Intrastate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PP_LD_Intrastate</label>
    <type>Checkbox</type>
</CustomField>

objects/OLI__c/fields/PP_Product_Pricing_Name__c.field-meta.xml
<CustomField>
    <fullName>PP_Product_Pricing_Name__c</fullName>
    <label>PP_Product_Pricing_Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OLI__c/fields/Price_Id__c.field-meta.xml
<CustomField>
    <fullName>Price_Id__c</fullName>
    <description>Price Id From  IntegraWs</description>
    <label>Price Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/OLI__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Qty</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/OLI__c/fields/SPC_Component__c.field-meta.xml
<CustomField>
    <fullName>SPC_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SPC Component</label>
    <referenceTo>SPC_Component__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/MRC_Total__c.field-meta.xml
<CustomField>
    <fullName>MRC_Total__c</fullName>
    <label>MRC Total</label>
    <summarizedField>OpportunityLocationConfiguration__c.MRC_Total__c</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLocationConfiguration__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLocationConfiguration__c.Opportunity_Location__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OpportunityLocationConfiguration__c/OpportunityLocationConfiguration__c.object-meta.xml
<CustomObject>
    <description>A configuration for an OpportunityLocation.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OpportunityLocationConfiguration__c/fields/Display_on_Solution__c.field-meta.xml
<CustomField>
    <fullName>Display_on_Solution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display on Solution</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/OpportunityLocationConfiguration__c/fields/MRC_Total__c.field-meta.xml
<CustomField>
    <fullName>MRC_Total__c</fullName>
    <label>MRC Total</label>
    <summarizedField>OLI__c.MRC_Total__c</summarizedField>
    <summaryForeignKey>OLI__c.OpportunityLocationConfiguration__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/OpportunityLocationConfiguration__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Solutions</relationshipLabel>
    <relationshipName>OpportunityLocationConfigurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/OpportunityLocationConfiguration__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
                <default>true</default>
                <label>24</label>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>Month to Month</fullName>
            </value>
            <value>
                <fullName>Coterminous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Oppty_Cost_Comparison__c/Oppty_Cost_Comparison__c.object-meta.xml
<CustomObject>
    <label>Oppty Cost Comparison</label>
    <nameField>
        <displayFormat>OCC-{00000}</displayFormat>
        <label>Oppty Cost Comparison Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oppty Cost Comparisons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Oppty_Cost_Comparison__c/fields/MRC__c.field-meta.xml
<CustomField>
    <fullName>MRC__c</fullName>
    <label>MRC</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Oppty_Cost_Comparison__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Oppty Cost Comparisons</relationshipLabel>
    <relationshipName>Oppty_Cost_Comparisons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/SPC_Component__c/SPC_Component__c.object-meta.xml
<CustomObject>
    <label>SPC Component</label>
    <nameField>
        <label>SPC Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/SPC_Component__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>The friendly display name of the component</description>
    <label>Display Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/SPC_Pricing__c/SPC_Pricing__c.object-meta.xml
<CustomObject>
    <label>SPC Pricing</label>
    <nameField>
        <displayFormat>SPCPrice-{0000}</displayFormat>
        <label>SPC Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPC Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/SPC_Pricing__c/fields/Price_ID__c.field-meta.xml
<CustomField>
    <fullName>Price_ID__c</fullName>
    <description>This is the unique identifier created for each pricing row.</description>
    <externalId>true</externalId>
    <label>Price ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/Pricing_Name__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Name__c</fullName>
    <description>Use this to append/overwrite the description of the pricing row</description>
    <label>Pricing Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/SPC_Pricing__c/fields/SPC_Component__c.field-meta.xml
<CustomField>
    <fullName>SPC_Component__c</fullName>
    <label>SPC Component</label>
    <referenceTo>SPC_Component__c</referenceTo>
    <relationshipLabel>SPC Pricing</relationshipLabel>
    <relationshipName>SPC_Pricing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

classes/ProposalQuoteController.cls
public with sharing class ProposalQuoteController {
    
    public Opportunity currentOpportunity {get; set;}

    public Opportunity_Location__c opptyLoc { get;set; }
    public String term {get; set;} 
    public Boolean display {get; set;}
    public String solution {get; set;}
    public List<QuoteWrapper.Product> lstProducts {get;set;} 
	public Map<String,List<QuoteWrapper.Product>> mapProducts {get;set;}
    //public List<QuoteWrapper.QuoteLineItem> lstLongDistanceProducts {get;set;}   
    public CompanyInfo locationAddress {get;set;}
    public Boolean hasLongDistance {get;set;}
    public String ignoreFamilySortx {get;set;}
    
    public Decimal comparisonTotal { get; set; }
    public Decimal MonthlySavingsAmount { get; set; }
    public Decimal MonthlyPercentSavingsAmount { get; set; }
    public Decimal AnnualSavingsAmount { get; set; }            
    
    public Boolean showPercentageBox {get;set;}
    public map<id,opportunity_location__c> oppLocs {
    	get{
    		return oppLocs;
    	}
    	set{
    		oppLocs = new Map<Id,Opportunity_location__c>();
    		oppLocs = value;
    	}
    }
	
	//Setter hack
    public Map<Id, OLI__c> OppLocOLIsMap {
		get{ return OppLocOLIs != null ? new Map<Id, OLI__c>(OppLocOLIs) : null; }
		set{ if(value != null) OppLocOLIs = ((Map<Id, OLI__c>)value).values(); }
	}
    
    public List<OLI__c> OppLocOLIs {get;set;}
    
    public string currentOpportunityLocationId {
        get{
            return currentOpportunityLocationId;
        }
        set{
            currentOpportunityLocationId = value;
            //lstLongDistanceProducts= new List<QuoteWrapper.QuoteLineItem>();
           if(oppLocs!= null){
            opptyLoc = oppLocs.get(value);
			term = opptyLoc.OpportunityLocationConfigurations__r[0].Term__c;
			display = opptyLoc.OpportunityLocationConfigurations__r[0].Display_on_Solution__c;
			solution = opptyLoc.OpportunityLocationConfigurations__r[0].Name;
			
            Building__c b = opptyLoc.Service_Location__r.Location__r.Building__r;
            locationAddress = new CompanyInfo(b,opptyLoc.Service_Location__r.Name, opptyLoc.Service_Location__r.Location__r.Room_Suite__c);

			   

            if( (opptyLoc.OpportunityLocationConfigurations__r != null) && (opptyLoc.OpportunityLocationConfigurations__r.size() > 0) ) {
            	List<OLI__c> currentOLIs = new List<OLI__c>();
				Map<string,SPC_Pricing__c> mapPricingNamePrices = new map<String,SPC_Pricing__c>();
				List<String> currentPriceIds = new List<String>();
				for(OLI__c oli :OppLocOLIs){ 
					currentPriceIds.add(oli.Price_ID__c);
				}
				
				For(SPC_Pricing__c prices : CatalogUtils.GetPricingByPricingID(currentPriceIds)){
					if(prices.Pricing_Name__c != null || (prices.SPC_Component__c != null && prices.SPC_Component__r.Display_Name__c != null))
						mapPricingNamePrices.put(prices.Price_ID__c,prices);
				}
								
            	for(OLI__c oli :OppLocOLIs){ 
					if(mapPricingNamePrices.containskey(oli.Price_id__c)){
						SPC_Pricing__c priceNamePrice = mapPricingNamePrices.get(oli.Price_id__c);
						if(priceNamePrice.SPC_Component__c != null && priceNamePrice.SPC_Component__r.Display_Name__c != null)
							oli.PP_Product_Pricing_Name__c = priceNamePrice.SPC_Component__r.Display_Name__c;
						else
							oli.PP_Product_Pricing_Name__c = oli.PP_Product_Pricing_Name__c.replace(' - ' + priceNamePrice.Pricing_Name__c, '').replace('-' + priceNamePrice.Pricing_Name__c, '');
					}
					
            		if((oli.OpportunityLocationConfiguration__r.Opportunity_Location__c == currentOpportunityLocationId) && oli.OpportunityLocationConfiguration__r.Active__c == true){
            			currentOLIs.add(oli);
            		}
            	}
            	
				lstProducts = QuoteWrapper.getConfigProductsFromOLIs(currentOlis);
				mapProducts = new Map<String,List<QuoteWrapper.Product>>();
			    for (QuoteWrapper.Product prod : lstProducts) {
					for(string groupname : prod.linesMap.keyset()){
						string groupNameVal = groupname == '' ? prod.Name : groupname;
						if(mapProducts.containskey(groupNameVal)){
							mapProducts.get(groupNameVal).add(prod);
						}
						else{
							mapProducts.put(groupNameVal,new List<QuoteWrapper.Product>{prod});
						}
					}
				}
            }
            
            hasLongDistance = false;
            /*for (QuoteWrapper.Product prod : lstProducts) {
            	
            	for (QuoteWrapper.QuoteLineItem line : prod.lines) {
	            	if (line.rawOLI.PP_LD_Interstate__c || line.rawOLI.PP_LD_Intrastate__c) {
	            		hasLongDistance = true;
	            		
	            		lstLongDistanceProducts.add(line);
	            	}
            	}
            }*/
            
            
            //Once you added all the products, remove from the main list those that were added to the LD list
            /*for (QuoteWrapper.QuoteLineItem ldLine : lstLongDistanceProducts) {
            	Integer posProd = 0;
            	
            	for (QuoteWrapper.Product prod : lstProducts) {
            		Integer posLine = 0;
            		
	            	for (QuoteWrapper.QuoteLineItem line : prod.lines) {
	            		if (line.rawOLI.Id == ldline.rawOLI.id) {
	            			prod.lines.remove(posLine);
	            			break;
	            		}
	            		posLine += 1;
	            	}
	            	
	            	if (prod.lines.size() == 0) {
	            		lstProducts.remove(posProd);
	            		break;
	            	}
	            	
	            	posProd += 1;
            	}
            }*/
            
            comparisonTotal = 0;
            if( opptyLoc.Oppty_Cost_Comparisons__r != null ) {
                for( Oppty_Cost_Comparison__c occ : opptyLoc.Oppty_Cost_Comparisons__r ) {
                    comparisonTotal += occ.MRC__c * occ.Qty__c;
                }
            }
            
            if( opptyLoc.Disconnect_Line_Items__r != null ) {
                for( Disconnect_Line_Item__c occ : opptyLoc.Disconnect_Line_Items__r ) {
                    if( occ.MRC__c != null )
                        comparisonTotal += occ.MRC__c;
                }
            }

            MonthlySavingsAmount = Math.abs(comparisonTotal - opptyLoc.MRC_Total__c);
            AnnualSavingsAmount = MonthlySavingsAmount * 12;

            if( comparisonTotal == 0 )
                MonthlyPercentSavingsAmount = 0;
            else
                MonthlyPercentSavingsAmount = MonthlySavingsAmount / comparisonTotal * 100;
                
            showPercentageBox =  (MonthlySavingsAmount <= comparisonTotal);         
           }
        }
    }
}