objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <label>Building Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meet Point</fullName>
            </value>
            <value>
                <fullName>Commercial Building</fullName>
            </value>
            <value>
                <fullName>ILEC LSO</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Collocated</fullName>
            </value>
            <value>
                <fullName>ILEC Remote Switch</fullName>
            </value>
            <value>
                <fullName>Wireless MSC</fullName>
            </value>
            <value>
                <fullName>Wireless Tower</fullName>
            </value>
            <value>
                <fullName>Integra Hut/Shelter</fullName>
            </value>
            <value>
                <fullName>Pending Build</fullName>
            </value>
            <value>
                <fullName>Carrier POP</fullName>
            </value>
            <value>
                <fullName>Data Center</fullName>
            </value>
            <value>
                <fullName>Integra Switch/Hub</fullName>
            </value>
            <value>
                <fullName>Carrier Hotel</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Off Footprint</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Extended Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Address Component: City</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

objects/Building__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Building__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Area</label>
    <referenceTo>Market_Area__c</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings_del</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Building__c/fields/Net_Classification__c.field-meta.xml
<CustomField>
    <fullName>Net_Classification__c</fullName>
    <label>Net Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eNNI</fullName>
            </value>
            <value>
                <fullName>ILEC</fullName>
            </value>
            <value>
                <fullName>Near-net</fullName>
            </value>
            <value>
                <fullName>Off-net</fullName>
            </value>
            <value>
                <fullName>On-net</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Building__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Address Component: Zip</description>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Address Component: State</description>
    <inlineHelpText>Use 2-digit abbreviation for State</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>New - Newly entered and awaiting verification
Validated - Validated against duplicates and assigned a CLLI Code
Build Approved - Optional, Capital Allocated
Pending Build - Optional, ESO Initiated
Active - Ready to provide services</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Build Approved</fullName>
            </value>
            <value>
                <fullName>Pending Build</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Profiled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Market_Area__c/Market_Area__c.object-meta.xml
<CustomObject>
    <label>Market Area</label>
    <nameField>
        <label>Market Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Market_Area__c/fields/ICCMarketAreaID__c.field-meta.xml
<CustomField>
    <fullName>ICCMarketAreaID__c</fullName>
    <label>ICCMarketAreaID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Market_Area__c/fields/MarketAreaExternalID__c.field-meta.xml
<CustomField>
    <fullName>MarketAreaExternalID__c</fullName>
    <externalId>true</externalId>
    <label>MarketAreaExternalID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Opportunity_Product__c/Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{0000000}</displayFormat>
        <label>Opportunity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Product__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Primary_Service_Location__r.Location__r.Name</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

objects/Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>Opportunity_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Opportunity_Product__c/recordTypes/Manual_Entry.recordType-meta.xml
<RecordType>
    <fullName>Manual_Entry</fullName>
    <active>true</active>
    <description>Configured manually instead of through CPQ</description>
    <label>Manual Entry</label>
</RecordType>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <formula>text(Building__r.Building_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Building Type</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/Contract_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed_Date__c</fullName>
    <formula>Opportunity__r.Contract_Signed_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Signed Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/Credit_Check_Approval__c.field-meta.xml
<CustomField>
    <fullName>Credit_Check_Approval__c</fullName>
    <description>A credit check must be performed on all new logo and any existing logo increasing credit limit over conditional amount.</description>
    <inlineHelpText>A credit check must be performed on all new logo and any existing logo increasing credit limit over conditional amount.</inlineHelpText>
    <label>Credit Check Approval</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Approved</fullName>
            </value>
            <value>
                <fullName>Credit Approved pending condition</fullName>
            </value>
            <value>
                <fullName>Credit Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/Credit_Commitment_Met__c.field-meta.xml
<CustomField>
    <fullName>Credit_Commitment_Met__c</fullName>
    <description>The date the credit hold reason code was satisfied and credit approval complete.</description>
    <inlineHelpText>The date the credit hold reason code was satisfied and credit approval complete.</inlineHelpText>
    <label>Credit Commitment Met</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Order__c/fields/Customer_Requested_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Due_Date__c</fullName>
    <formula>Opportunity__r.Customer_Requested_Due_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Requested Due Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <description>Used by email template to distinguish CA orders from US</description>
    <formula>IF(Opportunity__r.Account.Customer_Detail__c != null, Opportunity__r.Account.Customer_Detail__r.Market_Area__r.Name,
  IF( Opportunity__r.Account.BillingCountry == &quot;CA&quot;, &quot;National&quot;,&quot;Not National&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Area</label>
    <type>Text</type>
</CustomField>

main/default/objects/Order__c/fields/Order_Pending_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Pending_Date__c</fullName>
    <description>Date the order status moved to pending</description>
    <label>Order Pending Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Stage of the sales process you are currently working</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Working</fullName>
            </value>
            <value>
                <fullName>Sales Complete</fullName>
            </value>
            <value>
                <fullName>Indirect - Sales Complete</fullName>
            </value>
            <value>
                <fullName>Completed to Billing/Billing Only</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Referred to SE</fullName>
            </value>
            <value>
                <fullName>SSS Held</fullName>
            </value>
            <value>
                <fullName>SE Received</fullName>
            </value>
            <value>
                <fullName>SE Held</fullName>
            </value>
            <value>
                <fullName>SE Complete</fullName>
            </value>
            <value>
                <fullName>SSS SE Received</fullName>
            </value>
            <value>
                <fullName>Order to Pending</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Records Updated Only/No Order</fullName>
            </value>
            <value>
                <fullName>Returned to Account Specialists - Wholesale</fullName>
            </value>
            <value>
                <fullName>Order Accepted</fullName>
            </value>
            <value>
                <fullName>SSS Reviewing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Location__c/fields/Net_Classification__c.field-meta.xml
<CustomField>
    <fullName>Net_Classification__c</fullName>
    <formula>TEXT(Location__r.Building__r.Net_Classification__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Classification</label>
    <type>Text</type>
</CustomField>

classes/Test_SalesCompReportController.cls
@isTest
public with sharing class Test_SalesCompReportController extends TestUtils.TestClass {
    private static List<User> users = null;    
    
    private static void getTestData(){
        users = getUserList();
        
        Account acct =  new Account(Name = 'parent1'
                                    ,ShippingCountry = 'US'
                                    ,ShippingState = 'OR'
                                    ,ShippingCity = 'Portland'
                                    ,ShippingPostalCode = '97124'
                                    ,ShippingStreet = '1234 Test'
                                    ,Phone = '800-123-1234'
                                    ,Industry = 'Z - Unclassified'
                                    , OwnerId = users[0].Id);
        insert acct;
        Contact ct = new Contact(LastName='test', email='test@test.com', AccountId=acct.Id, Title = 'test', Phone = '5555555555');
        insert ct;
        Id typeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Retail').getRecordTypeId();
            
        Opportunity oppt = new Opportunity(OwnerId = users[0].Id
            ,RecordTypeId = typeid
            ,AccountId = acct.Id
            ,LeadSource = 'Jigsaw'
            ,Term__c = '36'
            ,Name = 'Acme Explosives 2'
            ,CloseDate = date.today().addDays(10)
            ,Amount = 243.39
            ,Split_Owner_1__c = users[0].Id
            ,Split_Owner_2__c = users[1].Id
            ,Split_Percent_1__c = 20
            ,Split_Percent_2__c = 80
            ,ForecastCategoryName = 'Pipeline'   
            ,StageName = 'Stage 4 - Contract Signed / Won'
            ,Customer_Requested_Due_Date__c = date.today().addDays(-2)
            ,Contract_Signed_Date__c = date.today().addDays(-1)
            ,Proposal_Meeting_Held_Date__c = date.today().addDays(-1)
            ,Initial_Appointment_Held_Date__c =date.today().addDays(-5)
            ,Initial_Appointment_Set_Date__c = date.today().addDays(-5)
            ,Proposal_Meeting_Set_Date__c = date.today().addDays(-2)
            ,LOA_Signed_By__c =   ct.Id
            ,Opportunity_Product__c = 'test product');
        insert oppt; 

        List<Order__c> orders  = [Select Id, Opportunity__c from Order__c where Opportunity__c  =:oppt.Id];
        Order__c tO = orders[0]!= null?orders[0]:new Order__c(Opportunity__c = oppt.Id);
        tO.Credit_Check_Approval__c = 'Credit Approved';
        tO.Credit_Commitment_Met__c = Date.today();        
        to.Order_Pending_Date__c = Date.today().addDays(-1);
        to.Status__c = 'Order Accepted';
        if(orders[0]!=null){
            update tO;
        }else{
            insert tO;
        }

        Market_Area__c marketArea = new Market_Area__c(Name='asdf', MarketAreaExternalId__c='qwer1234', ICCMarketAreaID__c=1);
		insert marketArea;
        Building__c building = new Building__c(Address__c = '1234 fake st'
        									,City__c = 'Coolsville'
                                            ,Country__c = 'US'
        									,State__c = 'OR'
        									,Postal_Code__c = '12345'
        									,Market_Area__c = marketArea.Id
											,Latitude__c = 45.5000
											,Longitude__c = -120.000
											,Net_Classification__c = 'On-net'
											,Building_Type__c = 'Commercial Building');
    	insert building;
        Location__c loc  = new Location__c(Building__c = building.Id);
    	insert loc;
        Service_Location__c sLoc = new Service_Location__c(Account__c = acct.Id, Name = 'Test Loc', Location__c = loc.Id);
		insert sLoc;

		RecordType oppProdManual = [select Id from RecordType where sObjectType='Opportunity_Product__c' and DeveloperName='Manual_Entry'];
	 	Opportunity_Product__c oppProd = new Opportunity_Product__c(Opportunity__c=oppt.Id, Primary_Service_Location__c=sLoc.Id, Sales_Product__c='Some Product', RecordTypeId=oppProdManual.Id,  Active__c = true);
		insert oppProd;        
    }
    static List<User> getUserList(){    
        List<User> users = ([SELECT IsActive, Name, Id FROM User WHERE IsActive = true and  profile.Name = 'Sales' limit 2]);
        
        return (users.size() > 0) ? users : null;    
    }    
    
    static testmethod void testGenerateReport(){
        getTestData();
        Test.startTest();      

        SalesCompReportController  scrc = new SalesCompReportController();        
        scrc.startDate = Date.toDay().addDays(-2);
        scrc.endDate = Date.toDay().addDays(3);
        scrc.generateReport();
        
        Test.stopTest();        
    }
    
    static testmethod void testGenerateReportForSplit(){
        getTestData();
        Test.startTest();       

        SalesCompReportController  scrc = new SalesCompReportController();
        scrc.startDate = Date.toDay().addDays(-2);
        scrc.endDate = Date.toDay().addDays(3);
        scrc.generateReportForSplit();
        
        Test.stopTest();        
    }
}