objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Order__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Modify</fullName>
            </value>
            <value>
                <fullName>Move</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/Build_Category__c.field-meta.xml
<CustomField>
    <fullName>Build_Category__c</fullName>
    <description>Customer or Network request</description>
    <inlineHelpText>Customer or Network request</inlineHelpText>
    <label>Build Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/ESO_Classification__c.field-meta.xml
<CustomField>
    <fullName>ESO_Classification__c</fullName>
    <label>ESO Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Class I</fullName>
            </value>
            <value>
                <fullName>Class II</fullName>
            </value>
            <value>
                <fullName>Class III</fullName>
            </value>
            <value>
                <fullName>Class IV</fullName>
            </value>
            <value>
                <fullName>Class V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/ESO_Number__c.field-meta.xml
<CustomField>
    <fullName>ESO_Number__c</fullName>
    <label>ESO Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Order__c/fields/Field_Owner__c.field-meta.xml
<CustomField>
    <fullName>Field_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/iCert_Number__c.field-meta.xml
<CustomField>
    <fullName>iCert_Number__c</fullName>
    <label>iCert Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Build Location</description>
    <inlineHelpText>Build Location</inlineHelpText>
    <label>Location</label>
    <type>TextArea</type>
</CustomField>

objects/Order__c/fields/Order_Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Completion_Status__c</fullName>
    <label>Order Completion Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Scoping</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>In Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/Order_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Create_Date__c</fullName>
    <description>Date Build Order is created</description>
    <inlineHelpText>Date Build Order is created</inlineHelpText>
    <label>Order Create Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/OSP_Required__c.field-meta.xml
<CustomField>
    <fullName>OSP_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OSP Required</label>
    <type>Checkbox</type>
</CustomField>

objects/Order__c/fields/Provisioning_Plan_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Plan_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Provisioning Plan Enabled</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Order__c/fields/Provisioning_Product__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provisioning Product</label>
    <referenceTo>Provisioning_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Order__c/fields/Third_Party__c.field-meta.xml
<CustomField>
    <fullName>Third_Party__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Third Party</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Provisioning_Product__c/Provisioning_Product__c.object-meta.xml
<CustomObject>
    <label>Provisioning Product</label>
    <nameField>
        <label>Provisioning Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provisioning Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/classes/DecommOrderQuestions.cls
public with sharing class DecommOrderQuestions {
	public Order__c dummyOrder { get; set; }
	public String bldgId;
	public Id rt;
		
	public DecommOrderQuestions() {
		bldgId = Apexpages.currentPage().getParameters().get('id');
		dummyOrder = new Order__c();
		dummyOrder.OwnerId = UserInfo.getUserId();
		dummyOrder.Action__c = 'Remove';
		dummyOrder.ESO_Number__c = '';
		dummyOrder.Building__c = bldgId;
		dummyOrder.Order_Completion_Status__c = 'In Progress';
		dummyOrder.Build_Category__c = 'Network';			
	}
	
	public PageReference Save() {
		return SaveAction();
	}
	
	public PageReference Cancel() {
		PageReference pr = new PageReference('/' + bldgId);
        pr.setRedirect(true);

		return pr;
	}
	
	public PageReference QuickSave() {
		return SaveAction();		
	}
	
	public PageReference SaveAction() {
		try {
			List<String> errors = new List<String>();
			
			if (string.IsEmpty(dummyOrder.Project_Name__c))
				errors.add('Project Name: You must enter a value');
			if (dummyOrder.ESO_Classification__c == null)
				errors.add('ESO Classification: You must select a value');
			if (string.IsEmpty(dummyOrder.Scope__c))
				errors.add('Comments: You must enter a value');

			if (errors.size() > 0) {
				system.debug('errors: ' + errors);
				for(String error : errors)
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, error));
				return null;
			}			
		} 
		catch (DMLException e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,e.getMessage()));
			return null;
		}
		Order__c decom = new Order__c();
		Schema.Describesobjectresult r = Order__c.sObjectType.getDescribe();
		Boolean hasAccess = r.isCreateable();
		
		for(Schema.RecordtypeInfo rti : Order__c.sObjectType.getDescribe().getRecordTypeInfos()) {						
			if(rti.getName().equalsIgnoreCase('Decomm Order')){
				rt = rti.getRecordTypeId();
				if(!hasAccess || !rti.isAvailable()){
					return null;
				}
			}
		}
		try{
					decom.Project_Name__c = dummyOrder.Project_Name__c;
					decom.OwnerId = dummyOrder.OwnerId;
					decom.ESO_Classification__c = dummyOrder.ESO_Classification__c;
					decom.Action__c = dummyOrder.Action__c;
					decom.ESO_Number__c = dummyOrder.ESO_Number__c;
					decom.Building__c = dummyOrder.Building__c;					
					decom.Order_Completion_Status__c = dummyOrder.Order_Completion_Status__c;
					decom.Field_Owner__c = dummyOrder.Field_Owner__c;
					decom.Build_Category__c = dummyOrder.Build_Category__c;
					decom.iCert_Number__c = dummyOrder.iCert_Number__c;
					decom.Third_Party__c = dummyOrder.Third_Party__c;
					decom.OSP_Required__c = dummyOrder.OSP_Required__c;
					decom.Scope__c = dummyOrder.Scope__c;
					decom.RecordTypeId = rt;					
					List<Location__c> locName = [select Name from Location__c where Building__c = :bldgId limit 1];				
					decom.Location__c = locName.size() == 0 ? Null : locName[0].Name;					
					decom.Order_Create_Date__c = Date.today();
					decom.Workplan_Start_Date__c = Date.today();
					decom.Provisioning_Plan_Enabled__c = true;
					if(decom.OSP_Required__c){
						List<Provisioning_Product__c> pp = [select Id from Provisioning_Product__c where Name = 'Standard Build Decommission' limit 1];
						decom.Provisioning_Product__c = pp.size() > 0 ? pp[0].Id : null;
					}
					else{
						List<Provisioning_Product__c> pp = [select Id from Provisioning_Product__c where Name = 'Build Decommission - no OSP' limit 1];
						decom.Provisioning_Product__c = pp.size() > 0 ? pp[0].Id : null;
					}											
				insert decom;
		}
		catch(Exception e){			
			return null;
		}
		
		PageReference pr = new PageReference('/' + decom.Id);
        pr.setRedirect(true);
        
		return pr;
	}	
}