objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>New - Newly entered and awaiting verification
Validated - Validated against duplicates and assigned a CLLI Code
Build Approved - Optional, Capital Allocated
Pending Build - Optional, ESO Initiated
Active - Ready to provide services</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Build Approved</fullName>
            </value>
            <value>
                <fullName>Pending Build</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Profiled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <formula>IF(NOT(ISBLANK(Opportunity__r.Account.Id)), Opportunity__r.Account.Name, Account__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AccountName</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/ESO_Number__c.field-meta.xml
<CustomField>
    <fullName>ESO_Number__c</fullName>
    <label>ESO Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Order__c/fields/iCert_Number__c.field-meta.xml
<CustomField>
    <fullName>iCert_Number__c</fullName>
    <label>iCert Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Build Location</description>
    <inlineHelpText>Build Location</inlineHelpText>
    <label>Location</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Order__c/fields/Projected_Network_Ready_Date__c.field-meta.xml
<CustomField>
    <fullName>Projected_Network_Ready_Date__c</fullName>
    <label>Projected Network Ready Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Order__c/fields/Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Record_Status__c</fullName>
    <label>Record Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/Site_Survey_Date__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey_Date__c</fullName>
    <label>Site Survey Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Contract Renewal Orders</description>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Stage of the sales process you are currently working</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Working</fullName>
            </value>
            <value>
                <fullName>Sales Complete</fullName>
            </value>
            <value>
                <fullName>Indirect - Sales Complete</fullName>
            </value>
            <value>
                <fullName>Completed to Billing/Billing Only</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Referred to SE</fullName>
            </value>
            <value>
                <fullName>SSS Held</fullName>
            </value>
            <value>
                <fullName>SE Received</fullName>
            </value>
            <value>
                <fullName>SE Held</fullName>
            </value>
            <value>
                <fullName>SE Complete</fullName>
            </value>
            <value>
                <fullName>SSS SE Received</fullName>
            </value>
            <value>
                <fullName>Order to Pending</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Records Updated Only/No Order</fullName>
            </value>
            <value>
                <fullName>Returned to Account Specialists - Wholesale</fullName>
            </value>
            <value>
                <fullName>Order Accepted</fullName>
            </value>
            <value>
                <fullName>SSS Reviewing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order__c/fields/Customer_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Date__c</fullName>
    <label>Customer Requested Date</label>
    <type>DateTime</type>
</CustomField>

objects/Sub_Order__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Service_Location__r.Location__r.Name</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending Sales</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
            </value>
            <value>
                <fullName>Pending DM</fullName>
            </value>
            <value>
                <fullName>Waiting for Telco</fullName>
            </value>
            <value>
                <fullName>Waiting for Translations</fullName>
            </value>
            <value>
                <fullName>Waiting for Circuit Design</fullName>
            </value>
            <value>
                <fullName>Waiting For - Facilities: ILEC</fullName>
            </value>
            <value>
                <fullName>Waiting For - Task/Stage Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sub_Order__c/fields/Sub_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Sub_Order_Number__c</fullName>
    <formula>Order__r.Name &amp; &quot;-&quot; &amp; TEXT(Sub_Sequence__c)</formula>
    <label>Sub-Order Number</label>
    <type>Text</type>
</CustomField>

classes/RelatedOrdersSubOrders.cls
public with sharing class RelatedOrdersSubOrders{
	public String error {get; private set;}
	public Order__c ord {get; set;}
	
	public List<Order__c> oList {get; set;}
	public List<Order__c> rList {get; set;}
	public List<OrderWrapper> ritem {get; set;}
	public List<OrderWrapper> oitem {get; set;}
	public List<Sub_Order__c> aList {get; set;}
	public List<Sub_Order__c> relList {get; set;}
	public List<SubOrderWrapper> relitem {get; set;}
	public List<SubOrderWrapper> aitem {get; set;}
	public Sub_Order__c subOrder {get; set;}
	public Order__c o {get; set;}
	public ApexPages.StandardController controller;
	
	public List<Order__c> tList {get; set;}
	public List<Sub_Order__c> soList {get; set;}
	public Boolean isSubOrder {get; set;}
	
	public List<sObjectWrapper> getRelatedWrapperCollection() {
		return (List<sObjectWrapper>)ritem;
	}
	public List<sObjectWrapper> getWrapperCollection() {
		return (List<sObjectWrapper>)oitem;
	}
	
	private Set<String> SetOfModifiedTempIds;
	public String ModifiedTempIds{
		get { return JSON.serialize(SetOfModifiedTempIds); }
		Set { SetOfModifiedTempIds = (Set<String>)JSON.deserialize(value, Set<String>.class); }
	}
	
	private String ManualSubOrder;
	public String AddSubOrder{
		get { return ManualSubOrder; }
		Set { ManualSubOrder = value; }
	}
	
	public class OrderWrapper extends sObjectWrapper {
		public Order__c sub { get; set; }
		public Boolean isSelected { get; set; }
		
		public OrderWrapper(Order__c sub, Boolean isSelected) {		
			this.sub = sub;
			sObj = (sObject)sub;
			this.isSelected = isSelected;
		}
	}
	
	public class SubOrderWrapper extends sObjectWrapper {
		public Sub_Order__c sub { get; set; }
		public Boolean isSelected { get; set; }
		
		public SubOrderWrapper(Sub_Order__c sub, Boolean isSelected) {		
			this.sub = sub;
			sObj = (sObject)sub;
			this.isSelected = isSelected;
		}
	}

	public virtual class sObjectWrapper {
		public boolean isSelected { get; set; }
		public sObject sObj {get; set;}
		
		public sObjectWrapper(){}
		public sObjectWrapper(sObject sObj, Boolean isSelected){
			this.sObj = sObj;
			this.isSelected = isSelected;
		}
		
		public virtual List<sObjectWrapper> getSubWrapperLists(){ return new List<sObjectWrapper>(); }
	}
	
	public Schema.sObjectType sObjType { get; set; }
	

    public RelatedOrdersSubOrders(ApexPages.StandardController controller) { 
    	subOrder = new Sub_Order__c();   	
    	ord = (Order__c)controller.getRecord();
		DetermineRelationOfOrderOrSub(ord);
	}
	
	public void DetermineRelationOfOrderOrSub(Order__c ord){ 
		//If the user is on a Build Order page, show possible related SO's. 
		//If the user is on an Oppty Order page, show possible related Build Orders 	
		tList = new List<Order__c>();
		soList = new List<Sub_Order__c>();
		isSubOrder = false;
    	Id rtBuildOrderId = Schema.Sobjecttype.Order__c.getRecordTypeInfosByName().get('Build Order').getRecordTypeId();
    	List<Id> bldg = new List<Id>();
		
		for(Order__c oOrder :[SELECT Id, Building__c, Name FROM Order__c WHERE Id =: ord.Id]){			
			if(oOrder.Building__c != null)		
    			bldg.add(oOrder.Building__c);
    	}
 	
    	if(rtBuildOrderId == ord.RecordTypeId && bldg.size() > 0){    		    		     		
    		//Get suborders by location->building for possible relation BO that user is currently viewing.
    		isSubOrder = true;
    		soList = [Select Sub_Order_Number__c, Status__c, Order__r.AccountName__c, Service_Location__c, SPC_Product__r.Name, 
    		Customer_Requested_Date__c, Name, Location__c, Id, Service_Location__r.Location__r.Building__r.Id, 
    		Order__r.Id,  Order__c
    		From Sub_Order__c WHERE Order__r.RecordTypeId != :rtBuildOrderId AND Service_Location__r.Location__r.Building__r.Id =: bldg];
    	}
    	else if(rtBuildOrderId != ord.RecordTypeId){
    		//Get build orders related to OpptyOrder  
    		Set<Id> rSo = getSOSetForMO(ord.Id);
    		tList = [Select Record_Status__c, iCert_Number__c, Site_Survey_Date__c, Projected_Network_Ready_Date__c, ESO_Number__c, Name, Location__c, Id, Building__c		
    		From Order__c WHERE RecordTypeId = :rtBuildOrderId AND Building__c =: rSo];
    	}
    	else{
    		error = 'There is no building associated with this Order and thus no related orders/suborders can be identified';
    	}
	
	//must add junction table Manual relationships
		if (isSubOrder == false)
			RelatedOrder(tList);
		else if (isSubOrder == true)
			RelatedSubOrders(soList);    	
	}
	
	public void RelatedOrder(List<Order__c> tList){
		ritem = new List<OrderWrapper>();
		oitem = new List<OrderWrapper>();
		Map<Id, Order__c> mapSO = new Map<Id, Order__c>();
		Set<String> sRelated = new Set<String>();
		List<String> rManual = new List<String>();
		Set<Id> sourceIds = new Set<Id>();
		Set<Id> targetIds = new Set<Id>();
		
		for(Order__c so : tList){
			mapSO.put(so.Id, so);
    	}
		
		//Get related suborders from Junction Class
		List<Sub_Order__c> so = [Select Id From Sub_Order__c Where Order__c =: ord.Id];
		for(Sub_Order__c sub : so){
			sourceIds.add(sub.Id);
		}

		for(Order__c lOrd : tList){
			targetIds.add(lOrd.Id);
		}

		List<JunctionUtils.Junction> junc = JunctionUtils.GetSOrTBasedJunctions(sourceIDs, targetIDs);
		if(junc.size() > 0){
			for(JunctionUtils.Junction j : junc){						
				sRelated.add(String.valueOf(j.Target.Id));
			}
		}

		oList = new List<Order__c>();
		rList = new List<Order__c>();	
		if(sRelated.size() == 0){			
			oList.addAll(tList);			
		}		
		else{			
			for(String soid : sRelated){							
				Order__c sOrder = mapSO.get(soid);
			
				if(sOrder != null){
					mapSO.remove(soid);				
					rList.add(sOrder);
				}
				else{
					rManual.add(soid);
				}		
			}
			oList.addAll(mapSO.values());
		}	
		for(Order__c os : [Select Record_Status__c, iCert_Number__c, Site_Survey_Date__c, Projected_Network_Ready_Date__c, ESO_Number__c, Name, Location__c, Id, Building__c		
    		From Order__c WHERE Id =: rManual]){
    			rList.add(os);
    		}	

		for(Order__c rSO : rList != null ? rList : new List<Order__c>()){
    		boolean selected = true;
    		OrderWrapper sow = new OrderWrapper(rSO, selected);  		    		
    		ritem.add(sow);    		
		}
		for(Order__c oSO : oList != null ? oList : new List<Order__c>()){
    		boolean selected = false;
    		OrderWrapper sop = new OrderWrapper(oSO, selected);
    		oitem.add(sop);     		
		}
	}
	
	private Set<Id> getSOSetForMO(Id ordId){
		Set<Id> rSo = new Set<Id>();
		List<Sub_Order__c> so = [Select Service_Location__r.Location__r.Building__r.Id From Sub_Order__c Where Order__c =: ordId];
		for(Sub_Order__c sub : so){
			rSo.add(sub.Service_Location__r.Location__r.Building__r.Id);
		}
		return rSo;
	}
	public void RelatedSubOrders(List<Sub_Order__c> tList){				
		relitem = new List<SubOrderWrapper>();
		aitem = new List<SubOrderWrapper>();
		Map<String, Sub_Order__c> mapSO = new Map<String, Sub_Order__c>();
		Set<String> sRelated = new Set<String>();
		List<String> rManual = new List<String>();
		Set<Id> sourceIds = new Set<Id>();
		Set<Id> targetIds = new Set<Id>();
		
		for(Sub_Order__c so : tList){
			mapSO.put(so.Id, so);
    	}
		
		//Get related suborders
		sourceIds.add(ord.Id);
		for(Sub_Order__c lOrd : tList){
			targetIds.add(lOrd.Id);
		}

		List<JunctionUtils.Junction> junc = JunctionUtils.GetSOrTBasedJunctions(sourceIDs, targetIDs);

		if(junc.size() > 0){
			for(JunctionUtils.Junction j : junc){						
				sRelated.add(String.valueOf(j.Target.Id));
			}
		}
			
		aList = new List<Sub_Order__c>();
		relList = new List<Sub_Order__c>();	
		if(sRelated.size() == 0){			
			aList.addAll(tList);			
		}
		else{
			for(String soid : sRelated){						
				Sub_Order__c sOrder = mapSO.get(soid);
				
				if(sOrder != null){
					mapSO.remove(soid);					
					relList.add(sOrder);
				}
				else{
					rManual.add(soid);
				}	
			}
			aList.addAll(mapSO.values());
		}
		for(Sub_Order__c so : [Select Sub_Order_Number__c, Status__c, Order__r.AccountName__c, Service_Location__c, SPC_Product__r.Name, 
    		Customer_Requested_Date__c, Name, Location__c, Id, Service_Location__r.Location__r.Building__r.Id, 
    		Order__r.Id,  Order__c
    		From Sub_Order__c WHERE Id =: rManual]){
    			relList.add(so);
    		}					

		for(Sub_Order__c rSO : relList != null ? relList : new List<Sub_Order__c>()){
    		boolean selected = true;
    		SubOrderWrapper sow = new SubOrderWrapper(rSO, selected);
   		  		    		
    		relitem.add(sow);    		
		}
		for(Sub_Order__c oSO : aList != null ? aList : new List<Sub_Order__c>()){
    		boolean selected = false;
    		SubOrderWrapper sop = new SubOrderWrapper(oSO, selected);
    		aitem.add(sop);     		
		}		
	}
	
	public PageReference Save(){
		List<JunctionUtils.Junction> junc = new List<JunctionUtils.Junction>();
		if(SetOfModifiedTempIds != null){
			for(Sub_Order__c soc : [SELECT Id FROM Sub_Order__c WHERE Id IN : SetOfModifiedTempIds]){	
				Schema.SObjectType sOt = SchemaUtils.GetSObjectTypeByID(ord.Id);
				Schema.SObjectType tOt = SchemaUtils.GetSObjectTypeByID(soc.Id);

				if(sOt != null && tOt != null){
					junc.add(new JunctionUtils.Junction(sOt.newSObject(ord.Id), tOt.newSObject(soc.Id), null));
					junc.add(new JunctionUtils.Junction(tOt.newSObject(soc.Id), sOt.newSObject(ord.Id), null));
				}
			}							

		}			

		//update otherSideRelated;	
		List<Database.UpsertResult> jUpsertResults = JunctionUtils.SaveJunctions(junc);		
			
		PageReference nextPage = Page.RelatedOrdersSubOrders;
		nextPage.getParameters().put('Id', ord.Id);
		nextPage.setRedirect(true);
		return nextPage;
	}
	
	public PageReference SaveManual(){
		Set<Id> sourceIds = new Set<Id>();
		Set<Id> targetIds = new Set<Id>();
		Sub_Order__c sOrder = new Sub_Order__c();
		List<JunctionUtils.Junction> junc = new List<JunctionUtils.Junction>();
		sOrder = null;
		for(Sub_Order__c b : [Select  Id
    		From Sub_Order__c WHERE Name =: ManualSubOrder AND Status__c IN ('In Progress', 'New')]){			
			sOrder = b;
		}
			
		if(sOrder == null){
			ApexPages.Message noSubOrder = new ApexPages.Message(ApexPages.Severity.Error, 'Error: The SubOrder Name you entered is either not a Sub Order or not In Progress.');
			ApexPages.addMessage(noSubOrder);
			return null;
		}
		else{	
			sourceIds.add(ord.Id);
		    targetIds.add(sOrder.Id);		
			List<JunctionUtils.Junction> juncs = JunctionUtils.GetJunctions(sourceIds, targetIds);

			if(juncs.size() == 0){
				Schema.SObjectType sOt = SchemaUtils.GetSObjectTypeByID(ord.Id);
				Schema.SObjectType tOt = SchemaUtils.GetSObjectTypeByID(sOrder.Id);						
				juncs.add(new JunctionUtils.Junction(sOt.newSObject(ord.Id), tOt.newSObject(sOrder.Id), null));
				juncs.add(new JunctionUtils.Junction(tOt.newSObject(sOrder.Id), sOt.newSObject(ord.Id), null));	
									
				List<Database.UpsertResult> jUpsertResults = JunctionUtils.SaveJunctions(juncs);	
			}
			else{
				ApexPages.Message dupSubOrder = new ApexPages.Message(ApexPages.Severity.Error, 'Error: The SubOrder Name you entered is already related to this Build Order.');
				ApexPages.addMessage(dupSubOrder);
				return null;
			}
		}
		PageReference nextPage = Page.RelatedOrdersSubOrders;
		nextPage.getParameters().put('Id', ord.Id);
		nextPage.setRedirect(true);
		return nextPage;
	}
	
	public PageReference Remove(){
		Set<Id> sourceIds = new Set<Id>();
		Set<Id> targetIds = new Set<Id>();

		sourceIds.add(ord.Id);
		targetIds.add(ord.Id);
		
		if(SetOfModifiedTempIds != null){
			for(String tId : SetOfModifiedTempIds){
				sourceIds.add(tId);
				targetIds.add(tId);
			}
			List<JunctionUtils.Junction> junc = JunctionUtils.GetJunctions(sourceIDs, targetIDs);	
			List<Database.DeleteResult> jUpsertResults = JunctionUtils.DeleteJunctions(junc);						
		}

			PageReference nextPage = Page.RelatedOrdersSubOrders;
			nextPage.getParameters().put('Id', ord.Id);
			nextPage.setRedirect(true);
			return nextPage;    
		 
	}
}