objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Building__c/fields/MSAG_Address_Format__c.field-meta.xml
<CustomField>
    <fullName>MSAG_Address_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MSAG Address Format</label>
    <referenceTo>Building_Address_Format__c</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>MSAG_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Building__c/fields/Tax_Main_Address_Format__c.field-meta.xml
<CustomField>
    <fullName>Tax_Main_Address_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Main Address Format</label>
    <referenceTo>Building_Address_Format__c</referenceTo>
    <relationshipLabel>Buildings (Tax Main Address Format)</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Building_Address_Format__c/Building_Address_Format__c.object-meta.xml
<CustomObject>
    <label>Building Address Format</label>
    <nameField>
        <displayFormat>Address Format {0000000000}</displayFormat>
        <label>Building Address Format Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Building Address Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Customer_Contact__c/Customer_Contact__c.object-meta.xml
<CustomObject>
    <label>Customer Contact</label>
    <nameField>
        <displayFormat>Customer Contact {0000000000}</displayFormat>
        <label>Customer Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>After Hours</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Contact</fullName>
            </value>
            <value>
                <fullName>Authorized User</fullName>
            </value>
            <value>
                <fullName>AutoDialer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>BTS Contact</fullName>
            </value>
            <value>
                <fullName>CPNI Contact</fullName>
            </value>
            <value>
                <fullName>Customer Data</fullName>
            </value>
            <value>
                <fullName>Customer Voice</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Local Contact</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Network Notification Email</fullName>
            </value>
            <value>
                <fullName>Network Notification Primary</fullName>
            </value>
            <value>
                <fullName>Network Notification SMS</fullName>
            </value>
            <value>
                <fullName>Open View Contact</fullName>
            </value>
            <value>
                <fullName>Payweb Email</fullName>
            </value>
            <value>
                <fullName>Responsible Party</fullName>
            </value>
            <value>
                <fullName>SMP Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Contact</fullName>
            </value>
            <value>
                <fullName>Vendor Data</fullName>
            </value>
            <value>
                <fullName>Vendor Voice</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Contact__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Contacts</relationshipLabel>
    <relationshipName>Customer_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Customer_Detail__c/fields/Billing_Main_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_City__c</fullName>
    <label>Billing Main City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Country__c</fullName>
    <label>Billing Main Country</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Postal_Code__c</fullName>
    <label>Billing Main Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Billing_Main_Room_Suite__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Room_Suite__c</fullName>
    <label>Billing Main Room/Suite</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_State__c</fullName>
    <label>Billing Main State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Billing_Main_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Street__c</fullName>
    <label>Billing Main Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Collection_Code__c.field-meta.xml
<CustomField>
    <fullName>Collection_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Code</label>
    <referenceTo>Customer_Setting__c</referenceTo>
    <relationshipLabel>Customer Details</relationshipLabel>
    <relationshipName>Collection_Code_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Detail__c/fields/Customer_Main_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Main_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subscriber Address Type &#39;Customer Main&#39;</description>
    <label>Customer Main Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Customer Details (Customer Main Address)</relationshipLabel>
    <relationshipName>Customer_Main_Address_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Detail__c/fields/Disputed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Disputed_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Disputed Amount is updated by the icollect system.</description>
    <inlineHelpText>Disputed Amount is updated by the icollect system.</inlineHelpText>
    <label>Disputed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Customer_Detail__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pre-Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Past_Due__c.field-meta.xml
<CustomField>
    <fullName>Past_Due__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies if the the record is past due.</description>
    <inlineHelpText>Identifies if the the record is past due.</inlineHelpText>
    <label>Past Due</label>
    <type>Checkbox</type>
</CustomField>

objects/Customer_Setting__c/Customer_Setting__c.object-meta.xml
<CustomObject>
    <label>Customer Setting</label>
    <nameField>
        <label>Customer Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Setting__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Settings</relationshipLabel>
    <relationshipName>Customer_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Setting__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <label>External ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Setting__c/recordTypes/Bill_Cycle_Schedule.recordType-meta.xml
<RecordType>
    <fullName>Bill_Cycle_Schedule</fullName>
    <active>true</active>
    <label>Bill Cycle Schedule</label>
</RecordType>

main/default/objects/Customer_Setting__c/recordTypes/Collection_Code.recordType-meta.xml
<RecordType>
    <fullName>Collection_Code</fullName>
    <active>true</active>
    <label>Collection Code</label>
</RecordType>

objects/Customer_Setting__c/recordTypes/Market_Type.recordType-meta.xml
<RecordType>
    <fullName>Market_Type</fullName>
    <active>true</active>
    <label>Market Type</label>
</RecordType>

objects/Customer_Setting__c/recordTypes/Subscriber_Setting.recordType-meta.xml
<RecordType>
    <fullName>Subscriber_Setting</fullName>
    <active>true</active>
    <label>Subscriber Setting</label>
</RecordType>

main/default/objects/Customer_Setting__c/recordTypes/Tax_Information.recordType-meta.xml
<RecordType>
    <fullName>Tax_Information</fullName>
    <active>true</active>
    <label>Tax Information</label>
</RecordType>

main/default/objects/Customer_Setting_Reference__c/Customer_Setting_Reference__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to populate ref table driven dropdowns to configure customer setting objects.</description>
    <label>Customer Setting Reference</label>
</CustomObject>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Service_Location__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/classes/Test_CustomerDetailExtensionController.cls
@isTest(SeeAllData=true)
public with sharing class Test_CustomerDetailExtensionController extends TestUtils.TestClass {
	
 	static testMethod void testControllerCoverage() {
        Mocks testData = new Mocks();
    	
    	Customer_Detail__c cd = test_setupTestData(testData.loc.Id, testData.parentAccount, testData.serviceLocation);
		cd.Disputed_Amount__c = 1.0;	//Let it hit the reset to zero code
		
		Building_Address_Format__c baf = new Building_Address_Format__c();
		insert baf;
		
		Building__c b = testData.building;
		b.MSAG_Address_Format__c = baf.Id;
		b.Tax_Main_Address_Format__c = baf.Id;
		update b;
		
    	Map<String, Id> rts = new Map<String, Id>();
    	for(RecordType rt : [select DeveloperName, Id from RecordType where DeveloperName in ('Collection_Code')])
    		rts.put(rt.DeveloperName, rt.Id);
		
		List<Customer_Setting__c> csList = new List<Customer_Setting__c>{
								    		new Customer_Setting__c(RecordTypeId=rts.get('Collection_Code'), External_ID__c='1', Value__c='1')
								    	};
		insert csList;
    	
    	//Hit integration trigger code
    	cd.Past_Due__c = true;
    	update cd;
		
    	test.startTest();
    	
    	//CustomerDetailExtensionController.AddressFormat format = new CustomerDetailExtensionController.AddressFormat(new CustomerDetailExtensionController.LocationAddress('addr name', testData.loc, null, 'addr'), new Building_Address_Format__c());
    	
        PageReference pageReference = Page.CustomerDetailExtensionController;
        Test.setCurrentPage(pageReference);
        
		Apexpages.StandardController sc = new Apexpages.StandardController(cd);
    	CustomerDetailExtensionController ec = new CustomerDetailExtensionController(sc);
    	ec.marketAreaUpdated();
    	ec.marketTypeUpdated();
		
		ec.customerDetail.Collection_Code__c = csList[0].Id;
    	ec.doSave();
    	
        pageReference.getParameters().put('streetNumber', '1234');
        pageReference.getParameters().put('street', 'fake');
        pageReference.getParameters().put('suite', '1');
        pageReference.getParameters().put('city', 'Coolsville');
        //MNK Added Aug 2017
        pageReference.getParameters().put('country', 'US');
        pageReference.getParameters().put('state', 'OR');
        pageReference.getParameters().put('postalCode', '54321');
        pageReference.getParameters().put('latitude', '111');
        pageReference.getParameters().put('longitude', '-111');
        pageReference.getParameters().put('success', 'true');
    	
    	pageReference.getParameters().put('addressIDs', 'Billing_Main,Customer_Main_Address__c');
    	pageReference.getParameters().put('locationID', cd.Customer_Main_Address__c);
		ec.validateAddress();
		for(CustomerDetailExtensionController.LocationAddress address : ec.addresses){
			address.canUpdateToValidatedAddress = true;
			address.RoomSuite = 'Something else';
		}
    	ec.updateAddressesFromValidatedAddress();
    	//pageReference.getParameters().put('addressIDs', 'Billing_Main');
    	ec.updateAddresses();
    	
        pageReference.getParameters().put('linkID', string.valueOf(testData.grandChildAccount.Id));
    	ec.linkToObject();
    	Service_Location__c newLoc = new Service_Location__c(Name='NewLoc', Location__c = testData.loc.Id, Account__c = testData.grandChildAccount.Id);
    	insert newLoc;
        pageReference.getParameters().put('linkID', string.valueOf(newLoc.Id));
    	ec.linkToObject();
		
        pageReference.getParameters().put('formatId', 'Customer_Main_Address__c');
        pageReference.getParameters().put('houseNumber', '123');
        pageReference.getParameters().put('street', 'jam st');
        pageReference.getParameters().put('city', 'slamsville');
		
		//Set the building address format explicitly
		/*for(CustomerDetailExtensionController.LocationAddress address : ec.addresses){
			if(address.id == 'Customer_Main_Address__c'){
				ec.addressFormats.add(new CustomerDetailExtensionController.AddressFormat(address, baf));
			}
		}
		
		ec.updateAddressFormat();
		System.debug(ec.getTestClass());*/
    	
    	test.stopTest();
    }
	
 	static testMethod void testContacts() {
        System.Debug('testContacts');
        Mocks testData = new Mocks();
    	test.startTest();
    	
    	Customer_Detail__c cd = test_setupTestData(testData.loc.Id, null, null);
    	
    	List<Customer_Contact__c> ccs = new List<Customer_Contact__c>{
    										new Customer_Contact__c(Contact__c=testData.parentAccountContact.Id, Customer_Detail__c=cd.Id, Contact_Type__c=ICCWrapper.ResonsiblePartyContactType, Email__c='fake@fakeadress.com')
    										,new Customer_Contact__c(Contact__c=testData.parentAccountContact.Id, Customer_Detail__c=cd.Id, Contact_Type__c='Authorized Agent', Email__c='fake@fakeadress.com')
    									};
    	insert ccs;
    	
        PageReference pageReference = Page.CustomerDetailExtensionController;
        Test.setCurrentPage(pageReference);
        System.debug('cd :'+cd);
		Apexpages.StandardController sc = new Apexpages.StandardController(cd);
    	CustomerDetailExtensionController ec = new CustomerDetailExtensionController(sc);
    	ec.updateResponsibleParty();
    	ec.selectedContact = string.valueOf(testData.parentAccountContact.Id);
    	ec.selectedContactTypes = new List<String>{'Roommate'};
    	ec.createNewCustomerContact();
    	
        pageReference.getParameters().put('roleIDs', string.valueOf(ccs[0].Id) + ',' + string.valueOf(ccs[1].Id));
    	ec.removeRoles();
    	
    	test.stopTest();
    }
	
	static testMethod void testSubSettings(){
        System.Debug('testSubSettings');
        Mocks testData = new Mocks();
    	
    	Customer_Detail__c cd = test_setupTestData(testData.loc.Id, null, null);
		Customer_Detail__c cd2 = (Customer_Detail__c)ApexUtils.deepCopyFields(Customer_Detail__c.getsObjectType(), cd, new Customer_Detail__c(), new Set<String>{'ICC_Subscriber_ID__c'});
		insert cd2;
    	
    	Map<String, Id> rts = new Map<String, Id>();
    	for(RecordType rt : [select DeveloperName, Id from RecordType where DeveloperName in ('Bill_Cycle_Schedule', 'Market_Type')])
    		rts.put(rt.DeveloperName, rt.Id);
		insert new List<Customer_Setting__c>{
								    		new Customer_Setting__c(RecordTypeId=rts.get('Bill_Cycle_Schedule'), External_ID__c='1', Value__c='1')
								    		,new Customer_Setting__c(RecordTypeId=rts.get('Market_Type'), External_ID__c='1')
								    	};
		
		insert new List<Customer_Setting_Reference__c>{new Customer_Setting_Reference__c(Name='Ref1', Category__c='SubscriberSetting', Description__c='SubSetting', ID__c='1', Flags__c='1,1,1')
														,new Customer_Setting_Reference__c(Name='Ref2', Category__c='SubscriberTaxInfo', Description__c='SubTaxInfo', ID__c='2')};
		
    	test.startTest();
		
        PageReference pageReference = Page.CustomerDetailExtensionController;
        Test.setCurrentPage(pageReference);
        
		Apexpages.StandardController sc = new Apexpages.StandardController(cd);
    	CustomerDetailExtensionController ec = new CustomerDetailExtensionController(sc);
    	
    	ec.selectedSubSetting = '1';
    	ec.createNewSubscriberSetting();
    	Customer_Setting__c subSetting = [select Id from Customer_Setting__c where Customer_Detail__c =: cd.Id and RecordType.DeveloperName = 'Subscriber_Setting'];
		subSetting.External_ID__c = '-1';
		update subSetting;
    	
    	ec.selectedSubTax = '1';
    	ec.createNewSubscriberTax();
    	Customer_Setting__c taxInfo = [select Id from Customer_Setting__c where Customer_Detail__c =: cd.Id and RecordType.DeveloperName = 'Tax_Information'];
		taxInfo.External_ID__c = '-1';
		update taxInfo;
		
		//Reload the controller so the external IDs get loaded
		ec = new CustomerDetailExtensionController(sc);
		
        pageReference.getParameters().put('settingIDs', string.valueOf(subSetting.Id));
    	ec.updateSubscriberSettings();
		
        pageReference.getParameters().put('settingIDs', string.valueOf(subSetting.Id));
    	ec.deleteSubscriberSettings();
		
        pageReference.getParameters().put('settingIDs', string.valueOf(taxInfo.Id));
    	ec.updateSubscriberTaxInformation();
		
		pageReference.getParameters().put('copyTaxInfoIDs', string.valueOf(taxInfo.Id));
		pageReference.getParameters().put('copyToIDs', string.valueOf(cd2.Id));
		ec.copyTaxExemptions();
		
    	test.stopTest();
	}
	
	private static Customer_Detail__c test_setupTestData(Id locationId, Account a, Service_Location__c sLoc){
    	Customer_Detail__c cd = new Customer_Detail__c(ICC_Subscriber_ID__c='-9999'
														,Billable__c = true
    													,Customer_Main_Address__c=locationId
    													,Billing_Main_City__c='abcd'
                                                        ,Billing_Main_Country__c = 'US'
    													,Billing_Main_State__c='OR'
    													,Billing_Main_Street__c='1234'
    													,Billing_Main_Postal_Code__c='00000'
    													,Billing_Main_Room_Suite__c='1'
														,Integration_Status__c = 'Active');
    	insert cd;
    	
    	if(a != null){
	    	a.Customer_Detail__c = cd.Id;
	    	a.Phone = null;
	    	upsert a;
    	}
    	if(sLoc != null){
	    	sLoc.Customer_Detail__c = cd.Id;
	    	sLoc.Phone__c = null;
	    	update sLoc;
    	}
    	
    	return ((List<Customer_Detail__c>)ApexUtils.retrieveFullObjects(Customer_Detail__c.getsObjectType(), 'Id = \'' + cd.Id + '\''))[0];
	}
}