objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <label>Building Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meet Point</fullName>
            </value>
            <value>
                <fullName>Commercial Building</fullName>
            </value>
            <value>
                <fullName>ILEC LSO</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Collocated</fullName>
            </value>
            <value>
                <fullName>ILEC Remote Switch</fullName>
            </value>
            <value>
                <fullName>Wireless MSC</fullName>
            </value>
            <value>
                <fullName>Wireless Tower</fullName>
            </value>
            <value>
                <fullName>Integra Hut/Shelter</fullName>
            </value>
            <value>
                <fullName>Pending Build</fullName>
            </value>
            <value>
                <fullName>Carrier POP</fullName>
            </value>
            <value>
                <fullName>Data Center</fullName>
            </value>
            <value>
                <fullName>Integra Switch/Hub</fullName>
            </value>
            <value>
                <fullName>Carrier Hotel</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Off Footprint</fullName>
            </value>
            <value>
                <fullName>ILEC LSO: Extended Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Address Component: City</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/In_Market__c.field-meta.xml
<CustomField>
    <fullName>In_Market__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to define if LSO (and mapped buildings) reside within Integra Footprint or outside. Used to evaluate on footprint/off footprint definition.</description>
    <label>In Market</label>
    <type>Checkbox</type>
</CustomField>

objects/Building__c/fields/Net_Classification__c.field-meta.xml
<CustomField>
    <fullName>Net_Classification__c</fullName>
    <label>Net Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eNNI</fullName>
            </value>
            <value>
                <fullName>ILEC</fullName>
            </value>
            <value>
                <fullName>Near-net</fullName>
            </value>
            <value>
                <fullName>Off-net</fullName>
            </value>
            <value>
                <fullName>On-net</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Building__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Address Component: Zip</description>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Building__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Address Component: State</description>
    <inlineHelpText>Use 2-digit abbreviation for State</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Building__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>New - Newly entered and awaiting verification
Validated - Validated against duplicates and assigned a CLLI Code
Build Approved - Optional, Capital Allocated
Pending Build - Optional, ESO Initiated
Active - Ready to provide services</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Build Approved</fullName>
            </value>
            <value>
                <fullName>Pending Build</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Profiled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Building_Access_Availability__c/Building_Access_Availability__c.object-meta.xml
<CustomObject>
    <label>Building Access Availability</label>
    <nameField>
        <label>Access Availability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building Access Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Building_Access_Availability__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Building Access Availabilities</relationshipLabel>
    <relationshipName>Access_Availabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Building_Access_Availability__c/fields/Net_Classification__c.field-meta.xml
<CustomField>
    <fullName>Net_Classification__c</fullName>
    <formula>Text(Building__r.Net_Classification__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Classification</label>
    <type>Text</type>
</CustomField>

objects/Building_Access_Availability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <color>#78C953</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <color>#78C953</color>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Auto-Augment</fullName>
                <color>#F3D904</color>
                <label>Auto-Augment</label>
            </value>
            <value>
                <fullName>ICB</fullName>
                <color>#FF0000</color>
                <label>ICB</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Near-net Profiled</fullName>
                <color>#FFFF66</color>
                <label>Near-net Profiled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Customer_Detail__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pre-Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Service_Location__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>IF(ISBLANK(Account__r.Customer_Detail__c)
	,IF(ISBLANK(Parent_Service_Location__c)
		,&#39;&#39;
		,IF(ISBLANK(Parent_Service_Location__r.Parent_Service_Location__c)
			,&#39;&#39;
			,&#39;ERROR&#39;
		)
	)
	,IF(ISBLANK(Parent_Service_Location__c)
		,IF(Account__r.Customer_Detail__c = Customer_Detail__c, &#39;1&#39;, &#39;2&#39;)
		,IF(Account__r.Customer_Detail__c = Parent_Service_Location__r.Customer_Detail__c
			,&#39;2&#39;
			,IF(OR(ISBLANK(Parent_Service_Location__r.Parent_Service_Location__r.Parent_Service_Location__c), Account__r.Customer_Detail__c = Parent_Service_Location__r.Parent_Service_Location__r.Customer_Detail__c)
				,&#39;3&#39;
				,&#39;ERROR&#39;)
		)
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <type>Text</type>
</CustomField>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Service_Location__c/fields/Net_Classification__c.field-meta.xml
<CustomField>
    <fullName>Net_Classification__c</fullName>
    <formula>TEXT(Location__r.Building__r.Net_Classification__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Classification</label>
    <type>Text</type>
</CustomField>

objects/Service_Location__c/fields/Owner_Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Owner_Sales_Channel__c</fullName>
    <formula>TEXT(Owner__r.Sales_Channel__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Sales Channel</label>
    <type>Text</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Parent_Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Parent_Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Service Location</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__r.ICC_Subscriber_ID__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__r.ICC_Account_Number__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ServiceLocationSummaryController.cls
public with sharing class ServiceLocationSummaryController implements TestUtils.ITestableClass {

	public Account act {get;private Set;}
	public Date d {get;private Set;}
	
	public List<Service_Location__c> ServiceLocs {get; private Set;}
	public Map<Id, List<Building_Access_Availability__c>> BaaListByBuildingId {get; private Set;}
	public Map<Id, Set<Service_Location__c>> ServLocMap  {get; private Set;}
	public Map<Id, Building__c> buildingsMap  {get; private Set;}
	
	public ServiceLocationSummaryController(){
		d = Date.today();
		String accountID = ApexPages.currentPage().getParameters().get('accountId');
		
		if(act == null)
			act = [select Id, OwnerId, Name, Customer_Detail__c from Account where Id = :accountId];
		List<Service_Location__c> sLocs = [select Id
											,Account__c
											,Name
											,ICC_Subscriber_ID__c
											,Parent_Service_Location__c
											,Parent_Service_Location__r.Name
											,Level__c
											,Billable__c
                                           	,Owner_Sales_Channel__c
		    								,Customer_Detail__c
											,Customer_Detail__r.Integration_Status__c
											,Location__r.Building__c
											,Location__r.Building__r.Address__c
											,Location__r.Building__r.State__c
											,Location__r.Building__r.City__c
											,Location__r.Building__r.In_Market__c
											,Location__r.Building__r.Status__c
											,Location__r.Building__r.Net_Classification__c
											,Location__r.Building__r.Building_Type__c
											,Location__r.Building__r.Postal_Code__c
											,Location__r.Building__r.Serving_LSO__r.In_Market__c
											,Location__r.Building__r.Is_Serving_LSO__c
											,Location__r.Building__r.Building_CLLI__c
											
											,Location__r.Building__r.Serving_LSO__r.ID
											,Location__r.Building__r.Serving_LSO__r.Address__c
											,Location__r.Building__r.Serving_LSO__r.State__c
											,Location__r.Building__r.Serving_LSO__r.City__c
											,Location__r.Building__r.Serving_LSO__r.Postal_Code__c
											,Location__r.Building__r.Serving_LSO__r.Building_CLLI__c
											,Location__r.Building__r.Serving_LSO__r.Building_Alias__c
											
											from Service_Location__c where Account__c = :accountID];
		Set<Service_Location__c> sLocsToShow = new Set<Service_Location__c>();
		List<Service_Location__c> servLocs = new List<Service_Location__c>();
		Set<Id> possibleParentSlocIds = new Set<Id>();
		Set<Id> buildingIDs = new Set<Id>();
		Set<Building__c> buildingsSet = new Set<Building__c>();
		ServLocMap = new Map<Id, Set<Service_Location__c>>();
		BuildingsMap = new Map<Id,Building__c>();
		BaaListByBuildingId = new Map<Id, List<Building_Access_Availability__c>>();
		Set<Service_Location__c> tempSvcLocs;
		
		Integer startSize = -1;
		while(startSize != sLocsToShow.size()){
			startSize = sLocsToShow.size();
			
			for(Service_Location__c sLoc : sLocs){
				if(sLoc.Account__c == accountID){
					sLocsToShow.add(sloc);
					buildingIDs.add(sloc.location__r.Building__c);
					possibleParentSlocIds.add(sLoc.Id);
				}
				if(sLoc.Parent_Service_Location__c != null && possibleParentSlocIds.contains(sLoc.Parent_Service_Location__c)){
					sLocsToShow.add(sLoc);
					
					buildingsSet.add(sloc.location__r.Building__r);
				}
				
				tempSvcLocs = ServLocMap.get(sloc.location__r.Building__c);
				if (tempSvcLocs == null){
					tempSvcLocs = new Set<Service_Location__c>();
				}
				tempSvcLocs.add(sloc);
				ServLocMap.put(sloc.location__r.Building__c, tempSvcLocs);				
				Buildingsmap.put(sloc.location__r.building__r.id,sloc.location__r.building__r);
			}
		}

		for(Id bid : ServLocMap.keySet()){
			if(ServLocMap.get(bid) != null){
				for(Service_Location__c sLoc : ServLocMap.get(bid)){
					BaaListByBuildingId.put(sLoc.Location__r.building__c, new List<Building_Access_Availability__c>());
				}
			}
		}
		
		for(Building_Access_Availability__c baa : [select Id, Building__c, Access_Technology_Name__c, Carrier__c, Maximum_Bandwidth__c, Minimum_Bandwidth__c, Minimum_Required_Revenue__c, Wholesale_Hurdle__c, Status__c from building_Access_Availability__c where building__c in :buildingIDs]){
			List<Building_Access_Availability__c> baaList = null;
			if(BaaListByBuildingId.get(baa.building__c) != null)
				baaList = BaaListByBuildingId.get(baa.building__c);
			else
				baaList = new List<Building_Access_Availability__c>();			
			baaList.add(baa);			
			BaaListByBuildingId.put(baa.Building__c, baaList);
		}		
		ServiceLocs = new List<Service_Location__c>();
		ServiceLocs.addAll(sLocsToShow);		
	}
	
	/* TestUtils.ITestableClass methods */
	public TestUtils.TestClass getTestClass(){ return new Test_ServiceLocationSummaryController(); }
}