objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <description>Catalogue of buildings and building data</description>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Location__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Building this location belongs to.</description>
    <inlineHelpText>Building this location belongs to.</inlineHelpText>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Location__c/fields/Room_Suite__c.field-meta.xml
<CustomField>
    <fullName>Room_Suite__c</fullName>
    <label>Room/Suite</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/classes/BuildingAccounts.cls
public class BuildingAccounts implements TestUtils.ITestableClass {
	public List<Service_Location__c> bsl {get;set;}

	public BuildingAccounts(ApexPages.StandardController stdController){
		ApexPages.Standardcontroller sc = stdController;
		if(!Test.isRunningTest()){
        sc.addFields(new List<String>{'id'});
		Building__c b = (Building__c)sc.getRecord();
		
		bsl = GetBuildingAccount(b);
		}
	}
	
	public List<Service_Location__c> GetBuildingAccount(Building__c b){

			//return [Select Account__r.Id, Account__r.Name, Account__r.Type, Account__r.Owner.Name, Id, Name, Location__r.Id, Location__r.Name, Account__r.Account_Sales_Channel__c From Service_Location__c Where Location__r.Building__c = :b.id Order by Location__r.Room_Suite__c];
			return [Select Account__r.Id, Account__r.Name, Account__r.Type, Account__r.Owner.Name, Id, Name, Location__r.Id, Location__r.Name From Service_Location__c Where Location__r.Building__c = :b.id Order by Location__r.Room_Suite__c];
	}
	
	/* TestUtils.ITestableClass methods */
	public TestUtils.TestClass getTestClass(){ return new Test_BuildingAccounts(); }
}