objects/Customer_At_Risk__c/Customer_At_Risk__c.object-meta.xml
<CustomObject>
    <description>Information why a customer is at risk</description>
    <label>Customer At Risk</label>
    <nameField>
        <displayFormat>At Risk {0000}</displayFormat>
        <label>Customer At Risk Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer At Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Customer_At_Risk__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>lookup field to the account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers At Risk</relationshipLabel>
    <relationshipName>Customers_At_Risk</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Customer_At_Risk__c/fields/Actions_Taken_to_Resolve__c.field-meta.xml
<CustomField>
    <fullName>Actions_Taken_to_Resolve__c</fullName>
    <description>Detail steps to take to resolution</description>
    <inlineHelpText>Please enter all steps taken and to be taken to get resolution of issues.</inlineHelpText>
    <label>Actions Taken to Resolve</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Customer_At_Risk__c/fields/At_Risk_Detail__c.field-meta.xml
<CustomField>
    <fullName>At_Risk_Detail__c</fullName>
    <description>notes for why at risk</description>
    <inlineHelpText>Enter a summary note as to why this customer is at risk; what the action plan is to resolve, including due dates, as well as who this has been escalated to.</inlineHelpText>
    <label>Reason At Risk Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Customer_At_Risk__c/fields/Contract_End_Date_for_Majorit_of_MRR__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date_for_Majorit_of_MRR__c</fullName>
    <label>Contract End Date for Majority of MRR?</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

main/default/objects/Customer_At_Risk__c/fields/MRR_at_Risk__c.field-meta.xml
<CustomField>
    <fullName>MRR_at_Risk__c</fullName>
    <description>mrr billed</description>
    <label>MRR at Risk</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Customer_At_Risk__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Picklist - Product</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Family__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Dedicated Internet</fullName>
            </value>
            <value>
                <fullName>VPN/MPLS</fullName>
            </value>
            <value>
                <fullName>Ethernet Services</fullName>
            </value>
            <value>
                <fullName>Wavelength</fullName>
            </value>
            <value>
                <fullName>Private Line</fullName>
            </value>
            <value>
                <fullName>VPLS</fullName>
            </value>
            <value>
                <fullName>Dark Fiber</fullName>
            </value>
            <value>
                <fullName>Basic Voice</fullName>
            </value>
            <value>
                <fullName>Long Distance</fullName>
            </value>
            <value>
                <fullName>Toll Free</fullName>
            </value>
            <value>
                <fullName>ISDN/PRI</fullName>
            </value>
            <value>
                <fullName>Managed PBX</fullName>
            </value>
            <value>
                <fullName>Hosted Voice</fullName>
            </value>
            <value>
                <fullName>Hosted PBX</fullName>
            </value>
            <value>
                <fullName>SIP Solutions/NGN SIP Trunking</fullName>
            </value>
            <value>
                <fullName>UC (UCCV &amp; MiCloud)</fullName>
                <label>UC (UCCV &amp; MiCloud &amp; HCS)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Customer_At_Risk__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>Picklist - Product Family</description>
    <label>Primary Product Family At Risk</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cloud Voice (SIP &amp; UC)</fullName>
            </value>
            <value>
                <fullName>Data Services</fullName>
            </value>
            <value>
                <fullName>Legacy Hosted/Managed Services</fullName>
            </value>
            <value>
                <fullName>Legacy Voice Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Customer_At_Risk__c/fields/Reason_At_Risk__c.field-meta.xml
<CustomField>
    <fullName>Reason_At_Risk__c</fullName>
    <description>Reason why at risk</description>
    <label>Reason At Risk</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Decision</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Delivery Issues</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Repair Issues</fullName>
            </value>
            <value>
                <fullName>Sales Misrepresentation</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_At_Risk__c/fields/Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level__c</fullName>
    <description>Risk Level</description>
    <label>Risk Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Intends to Disconnect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_At_Risk__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to service location</description>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Customer At Risk</relationshipLabel>
    <relationshipName>Customer_At_Risk</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_At_Risk__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>status of at risk customer</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Partial Disconnect</fullName>
            </value>
            <value>
                <fullName>Full Account Disconnect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_At_Risk__c/fields/Total_Account_MRC__c.field-meta.xml
<CustomField>
    <fullName>Total_Account_MRC__c</fullName>
    <description>Total billed revenue</description>
    <label>DNU_Total Account MRR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Product_Family__c/Product_Family__c.object-meta.xml
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/Test_CustomerAtRiskTriggers.cls
@isTest
public with sharing class Test_CustomerAtRiskTriggers extends TestUtils.TestClass {
    static testMethod void testCustomerAtRisk(){
        Mocks testData = new Mocks();
        
        Customer_At_Risk__c car = new Customer_At_Risk__c();
        car.Actions_Taken_to_Resolve__c = 'testing';
        car.Reason_At_Risk__c = 'Billing';
        car.Account__c = testData.parentAccount.id;
        car.Status__c = 'Open';
        car.Risk_Level__c = 'Low';
        car.At_Risk_Detail__c = 'Test';
        car.Total_Account_MRC__c = 1;
        car.MRR_at_Risk__c = 1;
        car.Product_Family__c = 'Data Services';
        car.Product__c = 'VPN Solutions';
        car.Service_Location__c = testData.serviceLocation.id;
        car.Contract_End_Date_for_Majorit_of_MRR__c = Date.today();
        insert car;
    }
}