main/default/objects/Pricing_Agreement__c/Pricing_Agreement__c.object-meta.xml
<CustomObject>
    <label>Wholesale Pricing Agreement</label>
    <nameField>
        <label>Pricing Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale Pricing Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pricing_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wholesale Pricing Agreements</relationshipLabel>
    <relationshipName>Pricing_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Pricing_Agreement__c/fields/Contract_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term__c</fullName>
    <description>in Months</description>
    <label>Contract Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/PricingAgreementPDFDisplayController.cls
public with sharing class PricingAgreementPDFDisplayController {
    public transient ApexPages.Component comp {get; private Set;}
    public String paId {get;set;}
    
    public PricingAgreementPDFDisplayController(){
        comp = new Component.Apex.OutputPanel();
       	paId = ApexPages.currentPage().getParameters().get('pricingAgreementId');   
        Pricing_Agreement__c pa = [SELECT Id, Name, Account__c, Account__r.Name, Contract_Term__c FROM Pricing_Agreement__c WHERE Id=:paId]; 
        Component.Apex.OutputPanel op = new Component.Apex.OutputPanel(layout='block');
        op.childComponents.add(new Component.c.PDF_PricingAgreement(currentPA = pa));
        //ApexPages.Component c = 
        comp.childComponents.add(op);
    }

}