main/default/objects/Pricing_Agreement__c/Pricing_Agreement__c.object-meta.xml
<CustomObject>
    <label>Wholesale Pricing Agreement</label>
    <nameField>
        <label>Pricing Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesale Pricing Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pricing_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Wholesale Pricing Agreements</relationshipLabel>
    <relationshipName>Pricing_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Pricing_Agreement__c/fields/Contract_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term__c</fullName>
    <description>in Months</description>
    <label>Contract Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Pricing_Agreement_Product__c/Pricing_Agreement_Product__c.object-meta.xml
<CustomObject>
    <label>Pricing Agreement Product</label>
    <nameField>
        <displayFormat>PAD-{00000000}</displayFormat>
        <label>Pricing Agreement Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Agreement Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pricing_Agreement_Product__c/fields/MRC_1__c.field-meta.xml
<CustomField>
    <fullName>MRC_1__c</fullName>
    <label>MRC 1year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Pricing_Agreement_Product__c/fields/MRC_2__c.field-meta.xml
<CustomField>
    <fullName>MRC_2__c</fullName>
    <label>MRC 2year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Pricing_Agreement_Product__c/fields/MRC_3__c.field-meta.xml
<CustomField>
    <fullName>MRC_3__c</fullName>
    <label>MRC 3year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Pricing_Agreement_Product__c/fields/NRC_1__c.field-meta.xml
<CustomField>
    <fullName>NRC_1__c</fullName>
    <label>NRC 1year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Pricing_Agreement_Product__c/fields/NRC_2__c.field-meta.xml
<CustomField>
    <fullName>NRC_2__c</fullName>
    <label>NRC 2year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Pricing_Agreement_Product__c/fields/NRC_3__c.field-meta.xml
<CustomField>
    <fullName>NRC_3__c</fullName>
    <label>NRC 3year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Pricing_Agreement_Product__c/fields/Pricing_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Agreement__c</fullName>
    <label>Wholesale Pricing Agreement</label>
    <referenceTo>Pricing_Agreement__c</referenceTo>
    <relationshipLabel>Pricing Agreement Products</relationshipLabel>
    <relationshipName>Pricing_Agreement_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Pricing_Agreement_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dedicated Internet EoTDM 1.5 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoTDM 3 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoTDM 4.5 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoTDM 6 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoTDM 7.5 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoTDM 9 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoTDM 10.5 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoTDM 12 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoC 5 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoC 10 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoC 15 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoC 20 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoC 30 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoC 40 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoC 45 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoC 50 Mbps</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet EoC 60 Mbps</fullName>
            </value>
            <value>
                <fullName>Voice T1 ISDN/PRI (Loop &amp; Trunks)</fullName>
            </value>
            <value>
                <fullName>EEL Surcharge</fullName>
            </value>
            <value>
                <fullName>SIP Business Line</fullName>
            </value>
            <value>
                <fullName>SIP  ISDN PRI Channel</fullName>
            </value>
            <value>
                <fullName>Native SIP Trunking Sessions</fullName>
            </value>
            <value>
                <fullName>IAD - Intergrated Access Devise</fullName>
            </value>
            <value>
                <fullName>DID Numbers</fullName>
            </value>
            <value>
                <fullName>Remote Location Service</fullName>
            </value>
            <value>
                <fullName>Market Expansion DID Service</fullName>
            </value>
            <value>
                <fullName>Feature Package Plus</fullName>
            </value>
            <value>
                <fullName>Caller ID Name &amp; Number</fullName>
            </value>
            <value>
                <fullName>LD and Feature Package 2,000</fullName>
            </value>
            <value>
                <fullName>LD and Feature Package 5,000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/ProposalPricingAgreementController.cls
public with sharing class ProposalPricingAgreementController {
    public String CustomerName {get;set;}
    public String ContractTerm {get;set;}
    public String contactName {get;set;}
    //public List<Pricing_Agreement_Product__c > PricingAgreementProducts {get;set;}
    public List<PricingAgreementProductWrapper > PricingAgreementProductWrappers {get;set;}
    
    public Pricing_Agreement__c currentPricingAgreement {
        get{
            return currentPricingAgreement;
        }
        set{
            boolean color = true;
            currentPricingAgreement = value;
            CustomerName = currentPricingAgreement.Account__r.Name;
            ContractTerm = currentPricingAgreement.Contract_Term__c;
            //PricingAgreementProducts = [SELECT Product__c, MRC_1__c, MRC_2__c, MRC_3__c, NRC_1__c, NRC_2__c, NRC_3__c FROM Pricing_Agreement_Product__c WHERE Pricing_Agreement__c = :currentPricingAgreement.Id order by Product__c];
            PricingAgreementProductWrappers = new List<PricingAgreementProductWrapper>();
            for(Pricing_Agreement_Product__c p : [SELECT Product__c, MRC_1__c, MRC_2__c, MRC_3__c, NRC_1__c, NRC_2__c, NRC_3__c FROM Pricing_Agreement_Product__c WHERE Pricing_Agreement__c = :currentPricingAgreement.Id order by Product__c]){
                PricingAgreementProductWrapper pap = new PricingAgreementProductWrapper(p, color);  
                PricingAgreementProductWrappers.add(pap);
                color = !color;
            }
        }
    }

    public class PricingAgreementProductWrapper {
        public boolean Color {get;set;}
        public string Product {get;set;}
        public decimal MRC1 {get;set;}
        public decimal MRC2 {get;set;}
        public decimal MRC3 {get;set;}
        public decimal NRC1 {get;set;}
        public decimal NRC2 {get;set;}
        public decimal NRC3 {get;set;}
        
        public PricingAgreementProductWrapper(Pricing_Agreement_Product__c pap, boolean b){
            Color = b;
            Product = pap.Product__c;
            MRC1 = pap.MRC_1__c;
            MRC2 = pap.MRC_2__c;
            MRC3 = pap.MRC_3__c;
            NRC1 = pap.NRC_1__c;
            NRC2 = pap.NRC_2__c;
            NRC3 = pap.NRC_3__c;
        }
    }
}