main/default/objects/Market_Area__c/Market_Area__c.object-meta.xml
<CustomObject>
    <label>Market Area</label>
    <nameField>
        <label>Market Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Market_Area__c/fields/MarketAreaExternalID__c.field-meta.xml
<CustomField>
    <fullName>MarketAreaExternalID__c</fullName>
    <externalId>true</externalId>
    <label>MarketAreaExternalID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <description>Used by email template to distinguish CA orders from US</description>
    <formula>IF(Opportunity__r.Account.Customer_Detail__c != null, Opportunity__r.Account.Customer_Detail__r.Market_Area__r.Name,
  IF( Opportunity__r.Account.BillingCountry == &quot;CA&quot;, &quot;National&quot;,&quot;Not National&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Area</label>
    <type>Text</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_ILECOppGeneration.cls
@isTest
public with sharing class Test_ILECOppGeneration extends TestUtils.TestClass {
	
	static testMethod void testILECOppGeneration(){
		Mocks testData = new Mocks();
        Account a = testData.parentAccount;
		a.ShippingStreet = '1201 ne lloyd blvd';
		a.ShippingCity = 'portland';
		a.ShippingState = 'OR';
		a.ShippingPostalCode = '97232';
		update a;
		        
		Opportunity opp = testData.opportunity;
		opp.type = 'New Logo';
		opp.StageName = 'Identification';
		opp.RecordTypeId = '0121A000000QeQ9QAK';
		update opp;
		Service_Location__c sLoc = testData.serviceLocation;
		
		Order__c o = testData.order;

		Contact cont = new Contact();
		cont.AccountId = a.Id;
		cont.FirstName = 'test';
		cont.LastName = 'guy';
		cont.Email = 'test@test.com';
		insert cont;
        test.startTest();
		
		PageReference pageReference = Page.ILECOpportunityGeneration;
		pageReference.getParameters().put('accountId', a.Id);
		
		pageReference.getParameters().put('streetNumber', '1201');
		pageReference.getParameters().put('street', 'NE LLOYD BLVD');
		pageReference.getParameters().put('city', 'Portland');
		pageReference.getParameters().put('state', 'OR');
		pageReference.getParameters().put('postalCode', '97232');
		pageReference.getParameters().put('latitude', '45.5296809');
		pageReference.getParameters().put('longitude', '-122.6532694');
		
		Test.setCurrentPage(pageReference);        
		ILECOpportunityGeneration con = new ILECOpportunityGeneration();
		con.ResponsiblePartyId = cont.Id;
		List<SelectOption> ctslst = con.contactList;
		//con.CreateLocation();
		con.AddProduct();
		con.Finalize();
		con.ValidateAddressesAndRedirectToOppIntegrationPage();
		Integer MRR = con.MRR;
		
		ILECOpportunityGeneration.TreeViewImplementation tv = new ILECOpportunityGeneration.TreeViewImplementation(a, testData.serviceLocation, opp);
		tv.getNodes();
		tv.getIconMap();
		
		/*opp.Type = 'New Logo';
		opp.StageName = OpportunityUtils.STAGE_QUALIFIED;
		update opp;
		Service_Location__c sloc = testData.serviceLocation;
		con = new ILECOpportunityGeneration();*/
		
		
		test.stopTest();
	}
    
    static testmethod void testCreateLocation(){
        Test.startTest();
        Mocks TestData = new Mocks();
        ApexPages.currentPage().getParameters().put('streetNumber', '1201');
		ApexPages.currentPage().getParameters().put('street', 'NE LLOYD BLVD');
		ApexPages.currentPage().getParameters().put('city', 'Portland');
		ApexPages.currentPage().getParameters().put('state', 'OR');
		ApexPages.currentPage().getParameters().put('postalCode', '97232');
		ApexPages.currentPage().getParameters().put('latitude', '45.5296809');
		ApexPages.currentPage().getParameters().put('longitude', '-122.6532694');
        ApexPages.currentPage().getParameters().put('country', 'CA');
        ApexPages.currentPage().getParameters().put('accountId', TestData.parentAccount.Id);
        Market_Area__c MArea = new Market_Area__c(MarketAreaExternalID__c = '12345', Name = 'National');
        insert MArea;
        
        ILECOpportunityGeneration instance = new ILECOpportunityGeneration();
        System.AssertNotEquals(instance.AddProduct(), null);         
        Test.stopTest();
    }
}