main/default/objects/Market_Area__c/Market_Area__c.object-meta.xml
<CustomObject>
    <label>Market Area</label>
    <nameField>
        <label>Market Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Market_Area__c/fields/MarketAreaExternalID__c.field-meta.xml
<CustomField>
    <fullName>MarketAreaExternalID__c</fullName>
    <externalId>true</externalId>
    <label>MarketAreaExternalID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OLI__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>OpportunityLocationConfiguration__r.Opportunity_Location__r.Opportunity__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

objects/OLI__c/fields/OpportunityLocationConfiguration__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLocationConfiguration__c</fullName>
    <label>OpportunityLocationConfiguration</label>
    <referenceTo>OpportunityLocationConfiguration__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/OLI__c/fields/Product_Family_Product__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Product__c</fullName>
    <label>Product Family Product</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/OpportunityLocationConfiguration__c/OpportunityLocationConfiguration__c.object-meta.xml
<CustomObject>
    <description>A configuration for an OpportunityLocation.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityLocationConfiguration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>Opportunity_Location__r.Opportunity__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

objects/OpportunityLocationConfiguration__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Solutions</relationshipLabel>
    <relationshipName>OpportunityLocationConfigurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <description>Used by email template to distinguish CA orders from US</description>
    <formula>IF(Opportunity__r.Account.Customer_Detail__c != null, Opportunity__r.Account.Customer_Detail__r.Market_Area__r.Name,
  IF( Opportunity__r.Account.BillingCountry == &quot;CA&quot;, &quot;National&quot;,&quot;Not National&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Area</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>LD</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
            <value>
                <fullName>TF</fullName>
            </value>
            <value>
                <fullName>Traditional Voice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Contract Renewal Orders</description>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product_Family__c/Product_Family__c.object-meta.xml
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SPC_Product__c/fields/SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>SalesProductExternalID__c</fullName>
    <externalId>true</externalId>
    <label>SalesProductExternalID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Technical_Information__c/Technical_Information__c.object-meta.xml
<CustomObject>
    <label>Technical Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Technical_Information__c/fields/Opportunity_Site__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Technical Information</relationshipLabel>
    <relationshipName>Technical_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Technical_Information__c/recordTypes/Features_Schedule.recordType-meta.xml
<RecordType>
    <fullName>Features_Schedule</fullName>
    <active>true</active>
    <label>02 – Features Schedule</label>
</RecordType>

classes/Test_ManageLocationConfigurations.cls
@isTest
public with sharing class Test_ManageLocationConfigurations extends TestUtils.TestClass {
	
    static testMethod void testController() {
        // create test data
        Market_Area__c marketArea = new Market_Area__c(Name='asdf', MarketAreaExternalId__c='qwer1234');
        insert marketArea;
        Account grandparentAccount = new Account(Name = 'Grandparent', ShippingCountry='US', ShippingState = 'OR', ShippingCity = 'Portland', ShippingPostalCode = '97124', ShippingStreet = '1234 Test', Phone = '800-123-1234' );
        insert grandparentAccount;
        Account parentAccount = new Account(Name = 'Parent', ParentId = grandparentAccount.Id, ShippingCountry='US', ShippingState = 'OR', ShippingCity = 'Portland', ShippingPostalCode = '97124', ShippingStreet = '1234 Test' );
        insert parentAccount;
        Account childAccount = new Account(Name = 'Child', ParentId = parentAccount.Id, ShippingCountry='US', ShippingState = 'OR', ShippingCity = 'Portland', ShippingPostalCode = '97124', ShippingStreet = '1234 Test' );
        insert childAccount;
        Opportunity opportunity = new Opportunity(RecordTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Retail').getRecordTypeID() ,Name = 'Test Opp',  Product_Family__c = 'Data Services', Product__c = 'Elan', Type= 'New Logo', Oppty_Sub_Type__c='New Logo',StageName = OpportunityUtils.STAGE_QUALIFIED, CloseDate = Date.today().addDays(30), AccountId = grandparentAccount.Id);
        insert opportunity;
        Order__c ord = new Order__c(Opportunity__c = opportunity.Id);
        insert ord;
        Opportunity_Location__c opportunityLocations = new Opportunity_Location__c(Name = 'Parent', Opportunity__c = opportunity.id, Order__c = ord.Id);
        insert opportunityLocations;
        
        RecordType rtTechInfo = [select Id from RecordType WHERE SobjectType = 'Technical_Information__c' and DeveloperName != 'Features_Schedule' limit 1];
        
        Technical_Information__c technicalInfos = new Technical_Information__c(Name = '02-Features_Schedule', Opportunity_Site__c = opportunityLocations.Id, RecordTypeId = rtTechInfo.Id);
        //create our page reference
        PageReference pageReference = Page.ManageLocationConfigurations;
        pageReference.getParameters().put('opportunityId', opportunity.Id);
        Test.setCurrentPage(pageReference);
        
        // create our controller 
        ManageLocationConfigurationsController manageLocationConfigurationsController = new ManageLocationConfigurationsController();
        
        // workflow accessor only tests
        manageLocationConfigurationsController.gotoManageLocationProducts();
        manageLocationConfigurationsController.gotoGeneratePDF();
        
        manageLocationConfigurationsController.TechInfoRecordTypeId_gotoTechInfo = rtTechInfo.Id;
        manageLocationConfigurationsController.gotoTechInfo();
    }
    
    static testmethod void testgotoTechInfoDocument(){
        Test.startTest();
        Mocks TestData = new Mocks();
        ApexPages.currentPage().getParameters().put('opportunityId', TestData.opportunity.Id);
        manageLocationConfigurationsController controller = new manageLocationCOnfigurationsController();
        System.assertEquals(controller.gotoTechInfoDocument(), null);       
        Test.stopTest();
    }
    
    static testmethod void testsetUpProductFamily(){
        Test.startTest();
        // Data Setup
        Mocks TestData = new Mocks();
        ApexPages.currentPage().getParameters().put('opportunityId', TestData.opportunity.Id);
        Opportunity_Location__c loc = TestData.location;
        OpportunityLocationConfiguration__c sol = TestData.lstconfig[0];
        OLI__c LineItem = TestData.lstLineItems[0];
        SPC_Product__c SPCProd = new SPC_Product__c(name = TestData.lstLineItems[0].Product_Family_Product__c, SalesProductExternalID__c = 123);
        insert SPCProd;
        
        // Let contructor call setUpProductFamily
        manageLocationConfigurationsController controller = new manageLocationCOnfigurationsController();
        // Call some other functions to run them with data
		controller.LocationId_gotoTechInfo = TestData.location.Id;
        controller.gotoTechInfo();
        controller.gotoOpportunity();
        
        // Cover variables in wrapTI
        manageLocationConfigurationsController.wrapTI inst = new manageLocationConfigurationsController.wrapTI(new Technical_Information__c(), 'display');
        inst.documentName = 'DocName';
        inst.overrideDisplayName = 'overRideName';
        Test.stopTest();
    }

}