main/default/objects/Dynamic_SOQL_Criteria__c/Dynamic_SOQL_Criteria__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Dynamic SOQL Criteria</label>
</CustomObject>

objects/Dynamic_SOQL_Criteria__c/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <label>sObject</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Dynamic_SOQL_Criteria__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/ICB__c/ICB__c.object-meta.xml
<CustomObject>
    <description>Custom object to better track Individual Case Basis requests</description>
    <label>ICB</label>
    <nameField>
        <displayFormat>ICB Request-{000000}</displayFormat>
        <label>ICB Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICBs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Integra_Contract__c/Integra_Contract__c.object-meta.xml
<CustomObject>
    <label>Integra Contract</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>Integra Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integra Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OLI__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if( OpportunityLocationConfiguration__r.Active__c , 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/OLI__c/fields/OpportunityLocationConfiguration__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLocationConfiguration__c</fullName>
    <label>OpportunityLocationConfiguration</label>
    <referenceTo>OpportunityLocationConfiguration__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityLocationConfiguration__c/OpportunityLocationConfiguration__c.object-meta.xml
<CustomObject>
    <description>A configuration for an OpportunityLocation.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityLocationConfiguration__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Solutions</relationshipLabel>
    <relationshipName>OpportunityLocationConfigurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Oppty_Cost_Comparison__c/Oppty_Cost_Comparison__c.object-meta.xml
<CustomObject>
    <label>Oppty Cost Comparison</label>
    <nameField>
        <displayFormat>OCC-{00000}</displayFormat>
        <label>Oppty Cost Comparison Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oppty Cost Comparisons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Oppty_Cost_Comparison__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Oppty Cost Comparisons</relationshipLabel>
    <relationshipName>Oppty_Cost_Comparisons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Ref_PDF_Element__c/Ref_PDF_Element__c.object-meta.xml
<CustomObject>
    <description>Configuration of an available PDF element.</description>
    <label>Ref PDF Element</label>
    <nameField>
        <label>Ref PDF Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ref PDF Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Ref_PDF_Element__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>only active components are displayed for selection</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Ref_PDF_Element__c/fields/Display_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Display_Criteria__c</fullName>
    <label>Display Criteria</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Ref_PDF_Element__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <description>name to be displayed on the page for the user</description>
    <label>Document Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Ref_PDF_Element__c/fields/Hide_When_Invalid__c.field-meta.xml
<CustomField>
    <fullName>Hide_When_Invalid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide When Invalid</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Ref_PDF_Element__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proposal Sections</fullName>
            </value>
            <value>
                <fullName>Contract Sections</fullName>
            </value>
            <value>
                <fullName>Other Sections</fullName>
            </value>
            <value>
                <fullName>Indirect Sections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Technical_Information__c/Technical_Information__c.object-meta.xml
<CustomObject>
    <label>Technical Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/classes/Test_OpportunityPDF.cls
@isTest
public with sharing class Test_OpportunityPDF extends TestUtils.TestClass {
	
	private static String BLOBCONTENTS = 'ALL\'S RIGHT WITH THE WORLD.';
	
	static testMethod void testGeneratePage() {
		Mocks testData = new Mocks();
		
		Opportunity opp = testData.opportunity;
		
		Contact c = testData.parentAccountContact;
		
		String section1 = Ref_PDF_Element__c.Section__c.getDescribe().getPicklistValues()[0].getLabel();
		String section2 = Ref_PDF_Element__c.Section__c.getDescribe().getPicklistValues()[1].getLabel();
		List<Ref_PDF_Element__c> rpes =  new List<Ref_PDF_Element__c>{
												new Ref_PDF_Element__c(Active__c = true, Document_Name__c = 'MSA', Name = 'MSA', Display_Criteria__c = '1', Section__c = section1)
												,new Ref_PDF_Element__c(Active__c = true, Document_Name__c = 'MSNay', Name = 'MSNay', Display_Criteria__c = '1 AND 2 AND 3 AND 4 AND 5 AND 6 AND 7 AND 8', Hide_When_Invalid__c = true, Section__c = section2)
											};
		insert rpes;
		
		List<Dynamic_SOQL_Criteria__c> soql = new List<Dynamic_SOQL_Criteria__c>{
													new Dynamic_SOQL_Criteria__c(Name = 'Opportunity-Exists', sObject__c = 'Opportunity', Unique_ID__c = 1)
													,new Dynamic_SOQL_Criteria__c(Name = 'OLI-Exists', sObject__c = 'OLI__c', Unique_ID__c = 2)
													,new Dynamic_SOQL_Criteria__c(Name = 'OCC-Exists', sObject__c = 'Oppty_Cost_Comparison__c', Unique_ID__c = 3)
													,new Dynamic_SOQL_Criteria__c(Name = 'ICB-Exists', sObject__c = 'ICB__c', Unique_ID__c = 4)
													,new Dynamic_SOQL_Criteria__c(Name = 'IC-Exists', sObject__c = 'Integra_Contract__c', Unique_ID__c = 5)
													,new Dynamic_SOQL_Criteria__c(Name = 'OppLoc-Exists', sObject__c = 'Opportunity_Location__c', Unique_ID__c = 6)
													,new Dynamic_SOQL_Criteria__c(Name = 'OLC-Exists', sObject__c = 'OpportunityLocationConfiguration__c', Unique_ID__c = 7)
													,new Dynamic_SOQL_Criteria__c(Name = 'TI-Exists', sObject__c = 'Technical_Information__c', Unique_ID__c = 8)
												};
		insert soql;
		
		Test.startTest();
		
        PageReference pageReference = Page.OpportunityPDFGeneration;
        Test.setCurrentPage(pageReference);
		
        pageReference.getParameters().put('oppId', opp.Id);
		
		OpportunityPDFController opc = new OpportunityPDFController();
		
        pageReference.getParameters().put('contactID', c.Id);
		opc.selectContact();
		
		System.assert(opc.selectableElements.size() == 1 && opc.selectableElements.containsKey(section1), 'Expected section "' + section1 + '" and not "' + section2 + '" in selectable elements map');
		opc.selectableElements.get(section1)[0].Selected = true;
		
		opc.getPDF();
		String pdfContents = EncodingUtil.base64Decode(opc.pdfString).toString();
		System.assert(pdfContents == BLOBCONTENTS, 'Error retrieving test PDF content. Expected "' + BLOBCONTENTS + '" but received "' + pdfContents + '"');
		
		opc.savePDF();
		
		Test.stopTest();
	}
	
	static testMethod void testDisplayPage() {
		Mocks testData = new Mocks();
		
		Opportunity opp = testData.opportunity;
		
		Contact c = testData.parentAccountContact;
		
		String section1 = Ref_PDF_Element__c.Section__c.getDescribe().getPicklistValues()[0].getLabel();
		List<Ref_PDF_Element__c> rpes =  new List<Ref_PDF_Element__c>{
												new Ref_PDF_Element__c(Active__c = true, Document_Name__c = 'PartnerOrderProfile', Name = 'PartnerOrderProfile', Display_Criteria__c = '1', Section__c = section1)
											};
		insert rpes;
		
		Test.startTest();
		
        PageReference pageReference = Page.OpportunityPDFDisplay;
        Test.setCurrentPage(pageReference);
		
        pageReference.getParameters().put('oppId', opp.Id);
        pageReference.getParameters().put('contId', c.Id);
        pageReference.getParameters().put('pdfComps', rpes[0].Id);
		
		OpportunityPDFDisplayController opdc = new OpportunityPDFDisplayController();
		
		//System.debug(opdc.salesChannel);
		System.debug(opdc.brandingURL);
		System.debug(opdc.businessDownturn);
		System.debug(opdc.currentOpptyLocs);
		System.debug(opdc.iCText);
		System.debug(opdc.techInfo);
		System.debug(opdc.oppLocOLIs);
		System.debug(opdc.oppLocMap);
		
		Test.stopTest();
	}
	
	public static Blob getTestPDFResults(){
		return Blob.valueOf(BLOBCONTENTS);
	}
}