main/default/objects/Directory_Listing__c/Directory_Listing__c.object-meta.xml
<CustomObject>
    <label>Directory Listing</label>
    <nameField>
        <displayFormat>DL-{00000}</displayFormat>
        <label>Listing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Directory Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Directory_Listing__c/fields/Listing_Telephone_Number__c.field-meta.xml
<CustomField>
    <fullName>Listing_Telephone_Number__c</fullName>
    <label>Listing Telephone Number</label>
    <type>Phone</type>
</CustomField>

objects/Directory_Listing__c/fields/Main_Listing__c.field-meta.xml
<CustomField>
    <fullName>Main_Listing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Main Listing</label>
    <type>Checkbox</type>
</CustomField>

objects/Directory_Listing__c/fields/Technical_Information__c.field-meta.xml
<CustomField>
    <fullName>Technical_Information__c</fullName>
    <label>Directory Listing</label>
    <referenceTo>Technical_Information__c</referenceTo>
    <relationshipLabel>Directory Listings</relationshipLabel>
    <relationshipName>Directory_Listings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Directory_Listing__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional Listing</fullName>
            </value>
            <value>
                <fullName>Alternate Call</fullName>
            </value>
            <value>
                <fullName>Cross Reference</fullName>
            </value>
            <value>
                <fullName>Foreign Listing</fullName>
            </value>
            <value>
                <fullName>Information Listing/Extra Line</fullName>
            </value>
            <value>
                <fullName>National Toll Free Directory</fullName>
            </value>
            <value>
                <fullName>Nonlisted</fullName>
            </value>
            <value>
                <fullName>Nonpublished</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Complimentary Listing</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Directory_Listing__c/fields/Which_Directory__c.field-meta.xml
<CustomField>
    <fullName>Which_Directory__c</fullName>
    <label>Which Directory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABERDEEN</fullName>
            </value>
            <value>
                <fullName>ALAMOSA</fullName>
            </value>
            <value>
                <fullName>ALBANY</fullName>
            </value>
            <value>
                <fullName>ALBERT LEA</fullName>
            </value>
            <value>
                <fullName>ALLIANCE/CHADRON</fullName>
            </value>
            <value>
                <fullName>APACHE JUNCTION &amp; E MESA</fullName>
            </value>
            <value>
                <fullName>ARVADA/BROOMFIELD/WESTMINSTER</fullName>
            </value>
            <value>
                <fullName>ASPEN/GLENWOOD SPRINGS</fullName>
            </value>
            <value>
                <fullName>AURORA/MONTBELLO/DIA</fullName>
            </value>
            <value>
                <fullName>BAINBRIDGE ISLAND</fullName>
            </value>
            <value>
                <fullName>BAKER CITY</fullName>
            </value>
            <value>
                <fullName>BARNUM</fullName>
            </value>
            <value>
                <fullName>BELLINGHAM</fullName>
            </value>
            <value>
                <fullName>BEMIDJI</fullName>
            </value>
            <value>
                <fullName>BIG HORN BASIN</fullName>
            </value>
            <value>
                <fullName>BISMARCK</fullName>
            </value>
            <value>
                <fullName>BLACKFOOT</fullName>
            </value>
            <value>
                <fullName>BOISE</fullName>
            </value>
            <value>
                <fullName>BOULDER</fullName>
            </value>
            <value>
                <fullName>BRAINERD</fullName>
            </value>
            <value>
                <fullName>BRIGHAM CITY</fullName>
            </value>
            <value>
                <fullName>BRIGHTON</fullName>
            </value>
            <value>
                <fullName>BUFFALO</fullName>
            </value>
            <value>
                <fullName>CACHE VALLEY</fullName>
            </value>
            <value>
                <fullName>CAMAS-WASHOUGAL</fullName>
            </value>
            <value>
                <fullName>CANON CITY</fullName>
            </value>
            <value>
                <fullName>CASA GRANDE</fullName>
            </value>
            <value>
                <fullName>CASTLE ROCK/PARKER</fullName>
            </value>
            <value>
                <fullName>CENTRAL &amp; DOWNTOWN DENVER</fullName>
            </value>
            <value>
                <fullName>CENTRAL OREGON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Directory_Listing__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Toggles whether a location is on hold.</description>
    <inlineHelpText>Toggles whether a location is on hold.</inlineHelpText>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An explicit account lookup that should only be used if the order is not opportunity driven.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account-based Orders</relationshipLabel>
    <relationshipName>Account_Based_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Technical_Information__c/Technical_Information__c.object-meta.xml
<CustomObject>
    <label>Technical Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Technical_Information__c/fields/Directory_Listing__c.field-meta.xml
<CustomField>
    <fullName>Directory_Listing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Directory Listing</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Technical_Information__c/fields/Opportunity_Site__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipLabel>Technical Information</relationshipLabel>
    <relationshipName>Technical_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Technical_Information__c/fields/Service_Limits__c.field-meta.xml
<CustomField>
    <fullName>Service_Limits__c</fullName>
    <label>Service Exceptions</label>
    <type>TextArea</type>
</CustomField>

objects/Technical_Information__c/fields/SummaryOfWork__c.field-meta.xml
<CustomField>
    <fullName>SummaryOfWork__c</fullName>
    <label>Summary Of Work</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Technical_Information__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NEW Toll Free Number</fullName>
            </value>
            <value>
                <fullName>EXISTING Toll Free Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/ProposalDirectoryForm.cls
public with sharing class ProposalDirectoryForm {
    
    private final Opportunity_Location__c oppLocation;
    public CompanyInfo clientMainAddress {get;set;}
    public CompanyInfo clientBillingAddress {get;set;}
    
    
    public class DirectoryListing {
        public Directory_Listing__c rawListing {get;set;}
        public CompanyInfo listingAddress {get;set;}
        
        public DirectoryListing(Directory_Listing__c dl) {
            rawListing = dl;
            listingAddress = new CompanyInfo(dl);
        }
    }


    public List<DirectoryListing> listings {get;set;}
    
    //public List<Technical_Information__c> techInfo {get;set;} 
      public Technical_Information__c  techInfo {get;set;}
      public String summarywork {get;set;}
      public String servicelimit {get;set;}
      
        
    public Opportunity currentOpportunity {
        get{
            return currentOpportunity;
        }
        set{
            currentOpportunity = value;
            clientMainAddress = new CompanyInfo(currentOpportunity.Account);
try{
            techInfo = [Select SummaryOfWork__c, Service_Limits__c From Technical_Information__c  Where Opportunity_Site__r.Order__r.Opportunity__c=:currentOpportunity.Id And (SummaryOfWork__c != null Or Service_Limits__c != null)];
			if((! String.IsEmpty(techInfo.SummaryOfWork__c)) || (! String.IsEmpty(techInfo.Service_Limits__c))) {
				summarywork = techInfo.SummaryOfWork__c;
				servicelimit = techInfo.Service_Limits__c;
			}else {
				summarywork = 'No Info Entered';
				servicelimit = 'No Info Entered';
			}
			
}catch(exception e) 
{
ApexUtils.messageDisplay(e.getMessage());
}
            if (! String.IsEmpty(currentOpportunity.Account.BillingStreet)) {
            	clientBillingAddress = new CompanyInfo(currentOpportunity.Account, true);
            } else {
            	clientBillingAddress = new CompanyInfo(currentOpportunity.Account);
            }            
            
            getOpportunityInfo();
        }
    }

    public void getOpportunityInfo(){
        
        List<Directory_Listing__c> rawListings =
            [Select Company_Name__c, Address__c, City__c, State__c, Zip__c, Listing_Telephone_Number__c, Type__c, Which_Directory__c, Main_Listing__c
            From Directory_Listing__c 
            where Technical_Information__r.Opportunity_Site__r.On_Hold__c=false AND Technical_Information__r.Opportunity_Site__r.Order__r.Opportunity__c=:currentOpportunity.Id
            ORDER BY Technical_Information__r.Opportunity_Site__r.Account__r.Account_Depth__c,  Technical_Information__r.Opportunity_Site__r.Account__r.Name];
            
        listings = new List<DirectoryListing>();
        for( Directory_Listing__c dl : rawListings ) {
            listings.add(new DirectoryListing(dl));
        }   

		//List<Technical_Information__c> techInfos = ApexUtils.retrieveFullObjects(Technical_Information__c.sObjectType, 'Opportunity_Site__c=\'' + currentOpportunity.Id +'\'');        

    }       
}