main/default/objects/Approval_Matrix__c/Approval_Matrix__c.object-meta.xml
<CustomObject>
    <description>[Perficient, Scott Roose, 03/11/2019]  This object was created as part of the project to move the .NET app iApproval into Salesforce.</description>
    <label>Approval Matrix</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Approval Matrix Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Approval_Matrix__c/fields/Credit_Approval_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Approval_Limit__c</fullName>
    <label>Credit Approval Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Approval_Matrix__c/fields/iCert_Max__c.field-meta.xml
<CustomField>
    <fullName>iCert_Max__c</fullName>
    <label>iCert Max</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Approval_Matrix__c/fields/Refund_Approval_Limit__c.field-meta.xml
<CustomField>
    <fullName>Refund_Approval_Limit__c</fullName>
    <label>Refund Approval Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Approval_Matrix__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>User ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/DOA_Mapping__c/DOA_Mapping__c.object-meta.xml
<CustomObject>
    <description>[Perficient, Scott Roose, 03/12/2019] This object was created as part of the project to move the .NET app iApproval into Salesforce.</description>
    <label>DOA Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>DOA Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOA Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DOA_Mapping__c/fields/CapEx_Limit__c.field-meta.xml
<CustomField>
    <fullName>CapEx_Limit__c</fullName>
    <label>CapEx Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/DOA_Mapping__c/fields/Credits_Refunds_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credits_Refunds_Limit__c</fullName>
    <label>Credits / Refunds Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/DOA_Mapping__c/fields/General_Limit__c.field-meta.xml
<CustomField>
    <fullName>General_Limit__c</fullName>
    <label>General Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/DOA_Mapping__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

classes/TestClassFactory.cls
/***********************************************************************************************************
* Name       : TestClassFactory
* Purpose    : This class will act as a reference class for all test class
************************************************************************************************************
* Author                 | Version    | Created Date    | Description
************************************************************************************************************
* Sathya                  | 1.0        | 25/03/2019      | Initial version
***********************************************************************************************************/

@isTest
public class TestClassFactory {
    public static List<User> userDetails(Id userProfile, Integer totalUser) {
        List<User> result = new List<User>();
        for(Integer i=0;i<totalUser;i++)
        {
            User user=new User();
            user.Alias = 'ydhfta'; 
            user.Email=i+'testingAll@pertitesnt.com';
            user.EmailEncodingKey='UTF-8';
            user.LastName='test30'+i;
            user.LanguageLocaleKey='en_US'; 
            user.LocaleSidKey='en_US'; 
            user.ProfileId = userProfile; 
            user.Title='Perficient11'+i;
            user.TimeZoneSidKey='America/Los_Angeles';
            user.UserName='test30@testperficient.com'+i;
            user.IsActive = true;
            user.Excludes_From_Batch_Processing__c=False;
            user.Ready_For_DOA_Processing__c=True;
            result.add(user);
        }
        return result;
    } 
       public static User userDetails1(Id userProfile) {
        User result = new User(Alias = 'ydhfta',Email='testingAll@pertitesnt.com',EmailEncodingKey='UTF-8',LastName='testing33',
                               LanguageLocaleKey='en_US',LocaleSidKey='en_US',ProfileId = userProfile,Title='TitleNotMatched',
                               TimeZoneSidKey='America/Los_Angeles',UserName='test30@testperficient.com');
        return result;
       }
    public static Approval_Matrix__c approvalMatrix(Id newUser) {
        
        Approval_Matrix__c result=new Approval_Matrix__c(
            Credit_Approval_Limit__c = 41,
            Refund_Approval_Limit__c = 23,
            iCert_Max__c = 23,
            User_ID__c = newUser);
        return result;
    }
    
    public static ContentVersion contentFile() {
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');
        ContentVersion result=new ContentVersion(
            title = 'test content trigger',      
            PathOnClient ='test',           
            VersionData =beforeblob);
        return result;
    }
    public static ContentDocumentLink contentDoc(Id approvalMat, Id ContentDocId) {
        ContentDocumentLink result=new ContentDocumentLink(
            LinkedEntityId=approvalMat,
            ShareType= 'I',
            ContentDocumentId=ContentDocId,
            Visibility = 'AllUsers');
        return result;
    }
    public static DOA_Mapping__c newDOA() {
        DOA_Mapping__c result=new DOA_Mapping__c(
            Job_Title__c='Perficient110',
            General_Limit__c=39,
            Credits_Refunds_Limit__c=39,
            CapEx_Limit__c=39);
        return result;
    }
    public static DOA_Mapping__c newDOA1() {
        DOA_Mapping__c result=new DOA_Mapping__c(
            Job_Title__c='NotMatched',
            General_Limit__c=39,
            Credits_Refunds_Limit__c=39,
            CapEx_Limit__c=39);
        return result;
    }
}