main/default/objects/Approval_Matrix__c/Approval_Matrix__c.object-meta.xml
<CustomObject>
    <description>[Perficient, Scott Roose, 03/11/2019]  This object was created as part of the project to move the .NET app iApproval into Salesforce.</description>
    <label>Approval Matrix</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Approval Matrix Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Approval_Matrix__c/fields/Credit_Approval_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Approval_Limit__c</fullName>
    <label>Credit Approval Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Approval_Matrix__c/fields/iCert_Max__c.field-meta.xml
<CustomField>
    <fullName>iCert_Max__c</fullName>
    <label>iCert Max</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Approval_Matrix__c/fields/Refund_Approval_Limit__c.field-meta.xml
<CustomField>
    <fullName>Refund_Approval_Limit__c</fullName>
    <label>Refund Approval Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

classes/ACR_ApprovalMatrixTriggerHelperTest.cls
/***********************************************************************************************************
* Name       : ACR_ApprovalMatrixTriggerHelperTest
* Purpose    : Test class for ACR_ApprovalMatrixTriggerHelper
************************************************************************************************************
* Author                 | Version    | Created Date    | Description
************************************************************************************************************
* Sathya                  | 1.0        | 24/03/2019      | Initial version
***********************************************************************************************************/

@isTest
public class ACR_ApprovalMatrixTriggerHelperTest {
    @isTest
    static void attachmentErrorSysAdminTest(){
        //Fetching Profile Id
        String profileName='\'System Administrator\'';
        ACR_DomainLayer.QueryEditor prof = new ACR_DomainLayer.QueryEditor('Profile','WHERE Name='+profileName,'SELECT','Id ');
        List<Profile> profileId=(List<Profile>) prof.ResultSet; 
        Id profId=profileId[0].Id;
        //Inserting Users
        Integer totalUsers=10;
        List<User> newUser = TestClassFactory.userDetails(profId,totalUsers);
        insert newUser; 
        Test.StartTest();
        for(User user: newUser){
            System.runAs(user){
                //Inserting a record in Approval Matrix
                Approval_Matrix__c approvalMat = TestClassFactory.approvalMatrix(user.id); 
                insert approvalMat;
                ContentVersion contentFiles = TestClassFactory.contentFile();    
                insert contentFiles;         
                String contentId='\''+contentFiles.Id+'\'' ;
                ACR_DomainLayer.QueryEditor contentVer = new ACR_DomainLayer.QueryEditor('ContentDocument','','SELECT','Id, Title, LatestPublishedVersionId ');
                List<ContentDocument> ContentDoc=(List<ContentDocument>) contentVer.ResultSet; 
                ContentDocumentLink contentDocs = TestClassFactory.contentDoc(approvalMat.Id,ContentDoc[0].Id);
                insert contentDocs;
                
                //Updating a field in Approval Matrix
                approvalMat.iCert_Max__c = 26;
                try{
                    update approvalMat; 
                    System.assertEquals(41,approvalMat.Credit_Approval_Limit__c);
                    System.assertEquals(23,approvalMat.Refund_Approval_Limit__c);
                    System.assertEquals(26,approvalMat.iCert_Max__c);
                }
                Catch(exception error){
                    System.Assert(error.getMessage().contains('Please add the attachment!'),error.getMessage());
                }
            }    
        }
        Test.StopTest();
    }
    @isTest   
    static void attachmentErrorStandardUserTest(){
        //Fetching Profile Id
        String profileName='\'Standard User\'';
        ACR_DomainLayer.QueryEditor prof = new ACR_DomainLayer.QueryEditor('Profile','WHERE Name='+profileName,'SELECT','Id ');
        List<Profile> profileId=(List<Profile>) prof.ResultSet; 
        Id profId=profileId[0].Id;
        //Inserting Users
        Integer totalUsers=10;
        List<User> newUser = TestClassFactory.userDetails(profId,totalUsers);
        insert newUser; 
        Test.StartTest();
        for(User user: newUser){
            System.runAs(user){
                //Inserting a record in Approval Matrix
                Approval_Matrix__c approvalMat = TestClassFactory.approvalMatrix(user.id); 
                insert approvalMat;
                //Updating a field in Approval Matrix
                approvalMat.iCert_Max__c = 26;
                try{
                    update approvalMat;
                    System.assertEquals(41,approvalMat.Credit_Approval_Limit__c);
                    System.assertEquals(23,approvalMat.Refund_Approval_Limit__c);
                    System.assertEquals(26,approvalMat.iCert_Max__c);
                }
                Catch(exception error){
                    System.Assert(error.getMessage().contains('Please add the attachment'),error.getMessage());
                } 
            }    
        }
        Test.StopTest();
    }
}