objects/Account_Scheduled_Task__c/Account_Scheduled_Task__c.object-meta.xml
<CustomObject>
    <label>Account Scheduled Task</label>
    <nameField>
        <displayFormat>Scheduled Task-{000000}</displayFormat>
        <label>Account Scheduled Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Scheduled Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_Scheduled_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Scheduled Tasks</relationshipLabel>
    <relationshipName>Account_Scheduled_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Account_Scheduled_Task__c/fields/Automation_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Automation_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automation Enabled</label>
    <type>Checkbox</type>
</CustomField>

objects/Account_Scheduled_Task__c/fields/Current_Activity_Required__c.field-meta.xml
<CustomField>
    <fullName>Current_Activity_Required__c</fullName>
    <description>Next Activity Required = (if previous Proactive Type &amp; Case Origin = Account Review Visit or Account Review Virtual the next Activity to display needs to = Contact. If previous Proactive Type &amp; Case Origin = Call In, Call Out or Email the next Activity to display needs to = Account Review).</description>
    <inlineHelpText>Next Activity Required = (if previous Proactive Type &amp; Case Origin = Account Review Visit or Account Review Virtual the next Activity to display needs to = Contact. If previous Proactive Type &amp; Case Origin = Call In, Call Out or Email the next Activity</inlineHelpText>
    <label>Next Activity Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Account Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Account_Scheduled_Task__c/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Excludes from all Processes</description>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

objects/Account_Scheduled_Task__c/fields/Last_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_Run__c</fullName>
    <description>Previous Activity Run Date - Last date this activity was completed.</description>
    <label>Previous Activity Run Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Account_Scheduled_Task__c/fields/Next_Run__c.field-meta.xml
<CustomField>
    <fullName>Next_Run__c</fullName>
    <description>Next Activity Run Date - Date set for the next automation process to run.</description>
    <inlineHelpText>Next Activity Run Date</inlineHelpText>
    <label>Next Activity Run Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Account_Scheduled_Task__c/fields/Occurrence_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Frequency__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Occurrence Frequency</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Account_Scheduled_Task__c/fields/Previous_Proactive_Activity__c.field-meta.xml
<CustomField>
    <fullName>Previous_Proactive_Activity__c</fullName>
    <description>Account Review Visit or Account Review Virtual the next Activity to display needs to = Contact. If previous Proactive Type &amp; Case Origin = Call In, Call Out or Email the next Activity to display needs to = Account Review).</description>
    <inlineHelpText>Account Review Visit or Account Review Virtual the next Activity to display needs to = Contact. If previous Proactive Type &amp; Case Origin = Call In, Call Out or Email the next Activity to display needs to = Account Review).</inlineHelpText>
    <label>Previous Proactive Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Review</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/Schedule_AccountScheduledTaskProcess.cls
public without sharing class Schedule_AccountScheduledTaskProcess implements Schedulable {
    public void execute(SchedulableContext sc) {
		//check and see if it's a holiday.  we aren't going to process on holidays
		if(!ApexUtils.isHoliday()){
        	processTasks();
		}
    }
	
	private static Map<String, Case> templateCasesMap;
	private static Map<String, Case> TemplateCasesByType{
		get{
			if(templateCasesMap == null){				
				templateCasesMap = new Map<String, Case>();
				String q = 'Select ' + SchemaUtils.RetrieveFullObjectFields(Case.sObjectType) + ', RecordType.DeveloperName From Case Where is_Template__c = true';
				for(Case c : (List<Case>)Database.query(q)){
					String activityName = c.RecordType.DeveloperName == 'Proactive_Review_Visit_Virtual' ? 'Account Review' : 'Contact';
					templateCasesMap.put(activityName, c);
				}
			}
			return templateCasesMap;
		}
		Set;
	}
		
	public static Case GetCaseForTemplate(Account_Scheduled_Task__c ast){
		Case c = new Case();
		//use previous because we should have updated this already.
		Case template = TemplateCasesByType.get(ast.Previous_Proactive_Activity__c);
		if(template != null) ApexUtils.deepCopyFields(c.getSobjectType(), template, c, null);
		c.Is_Template__c = false;
		return c;
	}
    
    public static void processTasks(){
		List<Case> newCases = new List<Case>();
		List<Case> casesToClose = new List<Case>();
		List<Account_Scheduled_Task__c> asts = [select Id, (Select Id, Status, Reason, IsClosed, Commit_Date__c from Cases__r ORDER BY CreatedDate DESC)
														//,Account__c, Account__r.Account_Sales_Channel__c, Account__r.MRR__c, Current_Activity_Required__c, Next_Run__c, Previous_Proactive_Activity__c
														,Account__c, Account__r.Customer_Detail__r.Care_Organization__c, Account__r.MRR__c, Current_Activity_Required__c, Next_Run__c, Previous_Proactive_Activity__c														
														,Occurrence_Frequency__c
													from Account_Scheduled_Task__c where Automation_Enabled__c = true and Disabled__c = false and Next_Run__c <= TODAY limit 10000];
		
		Map<Id, Id> actIdToACId = new Map<Id,Id>();
		for(Account_Scheduled_Task__c ast : asts){
			actIdToACId.put(ast.Account__c, null);
		}
		for(AccountTeamMember atm : [select UserId, AccountId from AccountTeamMember where AccountId in :actIdToACId.keyset() and TeamMemberRole = 'Account Consultant']){
			actIdToACId.put(atm.AccountId, atm.UserID);
		}
		//need these to have their workflows run before creating cases.
		List<Account_Scheduled_Task__c> actionableCaseTasks = new List<Account_Scheduled_Task__c>();
		Set<Id> actionableIds = new Set<Id>();
		for(Account_Scheduled_Task__c ast : asts){
			if(actIdToACId.get(ast.Account__c) != null){
				Boolean incomplete = false;
				if(ast.Cases__r != null && ast.Cases__r.size() > 0 && !ast.Cases__r[0].IsClosed && ast.Cases__r[0].Commit_Date__c <= Date.today()){
					Case c = ast.Cases__r[0];
					c.Status = 'Incomplete';
					casesToClose.add(c);
					incomplete = true;
				}
				
				ast.Last_Run__c = ast.Next_Run__c;//Date.today();
				ast.Previous_Proactive_Activity__c = ast.Current_Activity_Required__c;

                String careOrgName =  ast.Account__r.Customer_Detail__r.Care_Organization__c!=null?CustomerDetailUtils.getCareOrgById(ast.Account__r.Customer_Detail__r.Care_Organization__c).Name:null;
				AccountScheduledTaskUtils.updateASTFromABSandMRR(ast, careOrgName, ast.Account__r.MRR__c);
				//AccountScheduledTaskUtils.updateASTFromABSandMRR(ast, ast.Account__r.Account_Sales_Channel__c, ast.Account__r.MRR__c);				
				if(incomplete){
					string current = ast.Current_Activity_Required__c;
					ast.Current_Activity_Required__c = ast.Previous_Proactive_Activity__c;
					ast.Previous_Proactive_Activity__c = current;
				}
				actionableCaseTasks.add(ast);
				actionableIds.add(ast.Id);
			}
		}
		Database.SaveResult[] sResults = Database.update(actionableCaseTasks,false);
		actionableCaseTasks = [select Id
										,Account__c, Current_Activity_Required__c, Next_Run__c, Previous_Proactive_Activity__c
									from Account_Scheduled_Task__c where Id in :actionableIds];
		
		for(Account_Scheduled_Task__c ast : actionableCaseTasks){
			//create new case.
			Id di = actIdToACId.get(ast.Account__c);
			if(di == null) continue;
			Case c = GetCaseForTemplate(ast);
			c.OwnerId = actIdToACId.get(ast.Account__c);
			c.Commit_Date__c = ast.Next_Run__c;
			c.AccountId = ast.Account__c;
			c.Account_Scheduled_Task__c = ast.Id;
			newCases.add(c);
			
		}
		insert newCases;
		update casesToClose;
		string errMsg = '';
		for(integer i = 0; i < sResults.size(); ++i){
			Database.SaveResult sr = sResults[i];
			Account_Scheduled_Task__c ast = actionableCaseTasks[i];
			if(!sr.isSuccess()){
				errMsg += string.isEmpty(errMsg)? '' : '\n';
				errMsg += 'Error updating AST: ' + ast.Id + ' - Errors: ';
				for(Database.Error err : sr.getErrors()){
					errMsg += err.getStatusCode() + ': ' + err.getMessage();
				}
			}
		}
		if(!string.isEmpty(errMsg)){
			Messaging.SingleEmailMessage msg = ApexUtils.createEmailMessage(ApexUtils.ITAdminId, new List<String>(), 'Account Scheduled Task Process Exception', errMsg, false, '');
			ApexUtils.sendEmails(new List<Messaging.SingleEmailMessage>{msg});
		}
	}
	
	
}