objects/Account_Scheduled_Task__c/Account_Scheduled_Task__c.object-meta.xml
<CustomObject>
    <label>Account Scheduled Task</label>
    <nameField>
        <displayFormat>Scheduled Task-{000000}</displayFormat>
        <label>Account Scheduled Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Scheduled Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_Scheduled_Task__c/fields/Occurrence_Category__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Category__c</fullName>
    <label>Occurrence Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
                <default>true</default>
                <label>Month</label>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/MRR__c.field-meta.xml
<CustomField>
    <fullName>MRR__c</fullName>
    <label>MRR</label>
    <summarizedField>Service__c.MRR__c</summarizedField>
    <summaryFilterItems>
        <field>Service__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Inactive</value>
    </summaryFilterItems>
    <summaryForeignKey>Service__c.Customer_Detail__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

main/default/objects/Proactive_Case_Occurrence_Setting__c/Proactive_Case_Occurrence_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>configuration settings for Account Scheduled Tasks controlling Proactive Cases</description>
    <label>Proactive Case Occurrence Settings</label>
</CustomObject>

objects/Proactive_Case_Occurrence_Setting__c/fields/Account_Business_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Business_Segment__c</fullName>
    <inlineHelpText>Account Business Segment this rule applies to.</inlineHelpText>
    <label>Account Business Segment</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Proactive_Case_Occurrence_Setting__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <inlineHelpText>every X &#39;Category&#39;</inlineHelpText>
    <label>Frequency</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Proactive_Case_Occurrence_Setting__c/fields/Minimum_MRR__c.field-meta.xml
<CustomField>
    <fullName>Minimum_MRR__c</fullName>
    <inlineHelpText>minimum mrr to active this rule.</inlineHelpText>
    <label>Minimum MRR</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Proactive_Case_Occurrence_Setting__c/fields/Occurrence_Category__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Category__c</fullName>
    <inlineHelpText>Month, Week, Year</inlineHelpText>
    <label>Occurrence Category</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Proactive_Case_Occurrence_Setting__c/fields/Occurrence_Day_Offset__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Day_Offset__c</fullName>
    <description>no use for category = &#39;Year&#39;
when category = &#39;Month&#39; Last = last day of the month</description>
    <inlineHelpText>1st, 2nd, 3rd, 4th, Last</inlineHelpText>
    <label>Occurrence Day Offset</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

main/default/objects/Proactive_Case_Occurrence_Setting__c/fields/Rotating_Proactive_Type__c.field-meta.xml
<CustomField>
    <fullName>Rotating_Proactive_Type__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>enables rotation of proactive case types.</inlineHelpText>
    <label>Rotating Proactive Type</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Proactive_Case_Occurrence_Setting__c/fields/Starting_Activity__c.field-meta.xml
<CustomField>
    <fullName>Starting_Activity__c</fullName>
    <inlineHelpText>Account Review, Contact</inlineHelpText>
    <label>Starting Activity</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

classes/Test_AccountScheduledTaskUtils.cls
@isTest
public with sharing class Test_AccountScheduledTaskUtils extends TestUtils.TestClass { 
    static testMethod void testUtils(){
        Mocks testData = new Mocks();
        
        Proactive_Case_Occurrence_Setting__c s1 = new Proactive_Case_Occurrence_Setting__c();
        s1.Account_Business_Segment__c = 'Electric Lightwave Premier';
        s1.Frequency__c = 1;
        s1.Minimum_MRR__c = 0;		
        s1.Name = 'ELPLT2.5k';
        s1.Occurrence_Category__c = 'Year';
        s1.Rotating_Proactive_Type__c = false;
        s1.Starting_Activity__c = 'Account Review';
        Proactive_Case_Occurrence_Setting__c s2 = new Proactive_Case_Occurrence_Setting__c();
        s2.Account_Business_Segment__c = 'Default';
        s2.Frequency__c = 6;
        s2.Minimum_MRR__c = 0;
        s2.Name = 'DefaultLT4k';
        s2.Occurrence_Category__c = 'Month';
        s2.Occurrence_Day_Offset__c = 'Last';
        s2.Rotating_Proactive_Type__c = true;
        s2.Starting_Activity__c = 'Account Review';
        insert new List<Proactive_Case_Occurrence_Setting__c>{s1,s2};
        Account a = testData.parentAccount;
        //a.Account_Sales_Channel__c = 'Electric Lightwave Premier';

        Test.startTest();
        AccountScheduledTaskUtils.getSettingForABSAndMRR('Electric Lightwave Premier', 1000);
        AccountScheduledTaskUtils.getSettingForABSAndMRR('Integra Business', 1000);
        AccountScheduledTaskUtils.getASTNextRunDateForQuarter();
        AccountScheduledTaskUtils.getASTNextRunDateForBiAnnual();
        AccountScheduledTaskUtils.getASTNextRunDateForYear();
		system.debug(a.Customer_Detail__c + ': ' + a.MRR__c);
        //Account_Scheduled_Task__c ast = AccountScheduledTaskUtils.createASTForAccount(a.id, a.Account_Sales_Channel__c, 100.0);
        Account_Scheduled_Task__c ast = AccountScheduledTaskUtils.createASTForAccount(a.id, null, 100.0);
        ast = AccountScheduledTaskUtils.createASTForAccount(a.id, 'Integra Business', a.MRR__c);
        AccountScheduledTaskUtils.updateASTFromABSandMRR(ast, 'Electric Lightwave Business', a.MRR__c);
        Test.stopTest();
    }
}