objects/Account_Scheduled_Task__c/Account_Scheduled_Task__c.object-meta.xml
<CustomObject>
    <label>Account Scheduled Task</label>
    <nameField>
        <displayFormat>Scheduled Task-{000000}</displayFormat>
        <label>Account Scheduled Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Scheduled Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_Scheduled_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Scheduled Tasks</relationshipLabel>
    <relationshipName>Account_Scheduled_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Account_Scheduled_Task__c/fields/Automation_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Automation_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automation Enabled</label>
    <type>Checkbox</type>
</CustomField>

objects/Account_Scheduled_Task__c/fields/Current_Activity_Required__c.field-meta.xml
<CustomField>
    <fullName>Current_Activity_Required__c</fullName>
    <description>Next Activity Required = (if previous Proactive Type &amp; Case Origin = Account Review Visit or Account Review Virtual the next Activity to display needs to = Contact. If previous Proactive Type &amp; Case Origin = Call In, Call Out or Email the next Activity to display needs to = Account Review).</description>
    <inlineHelpText>Next Activity Required = (if previous Proactive Type &amp; Case Origin = Account Review Visit or Account Review Virtual the next Activity to display needs to = Contact. If previous Proactive Type &amp; Case Origin = Call In, Call Out or Email the next Activity</inlineHelpText>
    <label>Next Activity Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Account Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Account_Scheduled_Task__c/fields/Next_Run__c.field-meta.xml
<CustomField>
    <fullName>Next_Run__c</fullName>
    <description>Next Activity Run Date - Date set for the next automation process to run.</description>
    <inlineHelpText>Next Activity Run Date</inlineHelpText>
    <label>Next Activity Run Date</label>
    <type>Date</type>
</CustomField>

objects/Account_Scheduled_Task__c/fields/Occurrence_Category__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Category__c</fullName>
    <label>Occurrence Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
                <default>true</default>
                <label>Month</label>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Account_Scheduled_Task__c/fields/Occurrence_Day_of_the_Week_Offset__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Day_of_the_Week_Offset__c</fullName>
    <label>Occurrence Day of the Week Offset</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Occurrence_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st</fullName>
            </value>
            <value>
                <fullName>2nd</fullName>
            </value>
            <value>
                <fullName>3rd</fullName>
            </value>
            <value>
                <fullName>4th</fullName>
            </value>
            <value>
                <fullName>Last</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Account_Scheduled_Task__c/fields/Occurrence_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Frequency__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Occurrence Frequency</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Account_Scheduled_Task__c/fields/Previous_Proactive_Activity__c.field-meta.xml
<CustomField>
    <fullName>Previous_Proactive_Activity__c</fullName>
    <description>Account Review Visit or Account Review Virtual the next Activity to display needs to = Contact. If previous Proactive Type &amp; Case Origin = Call In, Call Out or Email the next Activity to display needs to = Account Review).</description>
    <inlineHelpText>Account Review Visit or Account Review Virtual the next Activity to display needs to = Contact. If previous Proactive Type &amp; Case Origin = Call In, Call Out or Email the next Activity to display needs to = Account Review).</inlineHelpText>
    <label>Previous Proactive Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Review</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Account_Scheduled_Task__c/fields/Skip_Workflow_Field_Updates__c.field-meta.xml
<CustomField>
    <fullName>Skip_Workflow_Field_Updates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Workflow Field Updates</label>
    <type>Checkbox</type>
</CustomField>

objects/Account_Scheduled_Task__c/fields/Starting_On__c.field-meta.xml
<CustomField>
    <fullName>Starting_On__c</fullName>
    <description>The start date for the activity.  Activity start date and fields from set for occurrence will set the next run date calculations.</description>
    <label>Activity Starting On Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

main/default/objects/Proactive_Case_Occurrence_Setting__c/Proactive_Case_Occurrence_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>configuration settings for Account Scheduled Tasks controlling Proactive Cases</description>
    <label>Proactive Case Occurrence Settings</label>
</CustomObject>

objects/Proactive_Case_Occurrence_Setting__c/fields/Account_Business_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Business_Segment__c</fullName>
    <inlineHelpText>Account Business Segment this rule applies to.</inlineHelpText>
    <label>Account Business Segment</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Proactive_Case_Occurrence_Setting__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <inlineHelpText>every X &#39;Category&#39;</inlineHelpText>
    <label>Frequency</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Proactive_Case_Occurrence_Setting__c/fields/Maximum_MRR__c.field-meta.xml
<CustomField>
    <fullName>Maximum_MRR__c</fullName>
    <label>Maximum MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Proactive_Case_Occurrence_Setting__c/fields/Minimum_MRR__c.field-meta.xml
<CustomField>
    <fullName>Minimum_MRR__c</fullName>
    <inlineHelpText>minimum mrr to active this rule.</inlineHelpText>
    <label>Minimum MRR</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Proactive_Case_Occurrence_Setting__c/fields/Occurrence_Category__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Category__c</fullName>
    <inlineHelpText>Month, Week, Year</inlineHelpText>
    <label>Occurrence Category</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Proactive_Case_Occurrence_Setting__c/fields/Occurrence_Day_Offset__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Day_Offset__c</fullName>
    <description>no use for category = &#39;Year&#39;
when category = &#39;Month&#39; Last = last day of the month</description>
    <inlineHelpText>1st, 2nd, 3rd, 4th, Last</inlineHelpText>
    <label>Occurrence Day Offset</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

main/default/objects/Proactive_Case_Occurrence_Setting__c/fields/Rotating_Proactive_Type__c.field-meta.xml
<CustomField>
    <fullName>Rotating_Proactive_Type__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>enables rotation of proactive case types.</inlineHelpText>
    <label>Rotating Proactive Type</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Proactive_Case_Occurrence_Setting__c/fields/Starting_Activity__c.field-meta.xml
<CustomField>
    <fullName>Starting_Activity__c</fullName>
    <inlineHelpText>Account Review, Contact</inlineHelpText>
    <label>Starting Activity</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

classes/AccountScheduledTaskUtils.cls
public with sharing class AccountScheduledTaskUtils implements TestUtils.ITestableClass{ 
	
	
	public static Date getASTNextRunDateForQuarter(){
		return getASTNextRun(3.0d);
	}
	public static Date getASTNextRunDateForBiAnnual(){
		return getASTNextRun(6.0d);
	}
	private static Date getASTNextRun(double threeOrSix){
		Map<Integer, Integer> moToLastDay = new Map<Integer, Integer>{3=>31,6=>30,9=>30,12=>31};
		
		Integer curMonth = Date.today().Month();
		Integer runMonth = integer.valueOf((math.ceil((curMonth+1.0)/threeOrSix)*threeOrSix) - (math.floor(curMonth/12.0)*12));
		Integer runDay = moToLastDay.get(runMonth);
		Integer runYear = Date.today().Year();
		runYear = runMonth < curMonth? runYear + 1 : runYear;
		return Date.newInstance(runYear, runMonth, runDay);
	}
	public static Date getASTNextRunDateForYear(){
		Integer curMonth = Date.Today().Month();
		Integer runMonth = 12;
		Integer runDay = 31;
		Integer runYear = Date.Today().Year() + 1;		
		if(curMonth < 12) --runYear;
		return Date.newInstance(runYear, runMonth, runDay);
	}
	public static Account_Scheduled_Task__c createASTForAccount(id aId, string abs, decimal mrr){
		Account_Scheduled_Task__c ast = new Account_Scheduled_Task__c();
		ast.Account__c = aId;
		ast.Starting_on__c = Date.today();
		ast.Automation_Enabled__c = true;
		updateASTFromABSandMRR(ast, abs, mrr);
		return ast;
	}
	public static void updateASTFromABSandMRR(Account_Scheduled_Task__c ast, string abs, decimal mrr){
		Proactive_Case_Occurrence_Setting__c setToUse = getSettingForABSAndMRR(abs,mrr);
		system.debug('setting: ' + setToUse);
		system.debug('current activity: ' + ast.Previous_Proactive_Activity__c);
		if(setToUse == null) return;

		ast.Current_Activity_Required__c = ast.Previous_Proactive_Activity__c == setToUse.Starting_Activity__c && setToUse.Rotating_Proactive_Type__c ? (setToUse.Starting_Activity__c == 'Contact'? 'Account Review' : 'Contact') : setToUse.Starting_Activity__c;
		ast.Occurrence_Category__c = setToUse.Occurrence_Category__c;
		ast.Occurrence_Day_of_the_Week_Offset__c = setToUse.Occurrence_Day_Offset__c;					
		ast.Occurrence_Frequency__c = setToUse.Frequency__c;
		ast.Next_Run__c = (ast.Occurrence_Frequency__c == 1? getASTNextRunDateForYear() : (ast.Occurrence_Frequency__c == 3? getASTNextRunDateForQuarter() : getASTNextRunDateForBiAnnual()));
		ast.Skip_Workflow_Field_Updates__c = true;
	}
	private static List<Proactive_Case_Occurrence_Setting__c> sSettings;
	public static Proactive_Case_Occurrence_Setting__c getSettingForABSAndMRR(string abs, decimal mrr){
		Proactive_Case_Occurrence_Setting__c setting = null;
		if(sSettings == null) sSettings = [select Account_Business_Segment__c, Frequency__c, Minimum_MRR__c, Maximum_MRR__c, Occurrence_Category__c, Occurrence_Day_Offset__c, Rotating_Proactive_Type__c, Starting_Activity__c from Proactive_Case_Occurrence_Setting__c];
		for(Proactive_Case_Occurrence_Setting__c pcos : sSettings){
			if(pcos.Minimum_MRR__c <= mrr && (pcos.Maximum_MRR__c > mrr || pcos.Maximum_MRR__c == null) && (pcos.Account_Business_Segment__c == abs || pcos.Account_Business_Segment__c == 'Default')) {
				setting = pcos;
				if(pcos.Account_Business_Segment__c == abs) break;
			}
		}
		return setting;
	}

	public TestUtils.TestClass getTestClass(){ return new Test_AccountScheduledTaskUtils(); }
}