objects/OpportunityLocationConfiguration__c/OpportunityLocationConfiguration__c.object-meta.xml
<CustomObject>
    <description>A configuration for an OpportunityLocation.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OpportunityLocationConfiguration__c/fields/MRC_Total__c.field-meta.xml
<CustomField>
    <fullName>MRC_Total__c</fullName>
    <label>MRC Total</label>
    <summarizedField>OLI__c.MRC_Total__c</summarizedField>
    <summaryForeignKey>OLI__c.OpportunityLocationConfiguration__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

main/default/objects/OpportunityLocationConfiguration__c/fields/NRC_Total__c.field-meta.xml
<CustomField>
    <fullName>NRC_Total__c</fullName>
    <label>NRC Total</label>
    <summarizedField>OLI__c.NRC_Total__c</summarizedField>
    <summaryForeignKey>OLI__c.OpportunityLocationConfiguration__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

main/default/objects/OpportunityLocationConfiguration__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
                <default>true</default>
                <label>24</label>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>Month to Month</fullName>
            </value>
            <value>
                <fullName>Coterminous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Order__c/fields/Data_Missing_Codes__c.field-meta.xml
<CustomField>
    <fullName>Data_Missing_Codes__c</fullName>
    <label>Data Missing Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CSR Not Available/Bill Copy Required</fullName>
            </value>
            <value>
                <fullName>Discrepancy - Pricing</fullName>
            </value>
            <value>
                <fullName>Discrepancy - Product</fullName>
            </value>
            <value>
                <fullName>iCert not validated</fullName>
            </value>
            <value>
                <fullName>Incomplete Customer Profile Sheet</fullName>
            </value>
            <value>
                <fullName>LOA/CSR mismatch</fullName>
            </value>
            <value>
                <fullName>LOA Missing/Incomplete</fullName>
            </value>
            <value>
                <fullName>Missing/Incomplete Addendums</fullName>
            </value>
            <value>
                <fullName>Missing/Incomplete Feature schedule</fullName>
            </value>
            <value>
                <fullName>Missing/Incomplete Forms - Other</fullName>
            </value>
            <value>
                <fullName>Missing Turndown Paperwork</fullName>
            </value>
            <value>
                <fullName>Missing Service Location(s)</fullName>
            </value>
            <value>
                <fullName>Order Packet not Submitted</fullName>
            </value>
            <value>
                <fullName>Other – Notes Required</fullName>
            </value>
            <value>
                <fullName>Product(s) not available</fullName>
            </value>
            <value>
                <fullName>WHLSL Order Clarification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/Data_Missing_Comments__c.field-meta.xml
<CustomField>
    <fullName>Data_Missing_Comments__c</fullName>
    <label>Data Missing Comments</label>
    <type>TextArea</type>
</CustomField>

objects/Order__c/fields/Opportunity_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Support Specialist</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Title</field>
            <operation>startsWith</operation>
            <value>Sales Support Specialist</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>startsWith</operation>
            <value>Agent Project Coordinator</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Coordinator_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/fields/Order_Pending_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Pending_Date__c</fullName>
    <description>Date the order status moved to pending</description>
    <label>Order Pending Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Stage of the sales process you are currently working</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Working</fullName>
            </value>
            <value>
                <fullName>Sales Complete</fullName>
            </value>
            <value>
                <fullName>Indirect - Sales Complete</fullName>
            </value>
            <value>
                <fullName>Completed to Billing/Billing Only</fullName>
            </value>
            <value>
                <fullName>Returned to Sales</fullName>
            </value>
            <value>
                <fullName>Referred to SE</fullName>
            </value>
            <value>
                <fullName>SSS Held</fullName>
            </value>
            <value>
                <fullName>SE Received</fullName>
            </value>
            <value>
                <fullName>SE Held</fullName>
            </value>
            <value>
                <fullName>SE Complete</fullName>
            </value>
            <value>
                <fullName>SSS SE Received</fullName>
            </value>
            <value>
                <fullName>Order to Pending</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Records Updated Only/No Order</fullName>
            </value>
            <value>
                <fullName>Returned to Account Specialists - Wholesale</fullName>
            </value>
            <value>
                <fullName>Order Accepted</fullName>
            </value>
            <value>
                <fullName>SSS Reviewing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Order Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ASC Held</fullName>
            </value>
            <value>
                <fullName>MSAG Validation</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Product Build</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Customer Under Contract</fullName>
            </value>
            <value>
                <fullName>Can Not Provide Product(s) Sold</fullName>
            </value>
            <value>
                <fullName>Changed Mind</fullName>
            </value>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>DG Clarification</fullName>
            </value>
            <value>
                <fullName>Sales Support Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/lgt_DataFactory.cls
/*
* @Author: Mahad Zaryab
* @Created Date: 
* @Modified Date: 
* Version     JIRA                  Author                        Comments
* 1.0         SEAL-2831             Mahad Zaryab                  Initial Comments  
*/

public with sharing class lgt_DataFactory {
    @AuraEnabled (Cacheable=true)
    public static List<Order__c> getOrderNumber(String opportunityId) {
        List<Order__c> orders = [SELECT Id,Name,Opportunity_Coordinator__c,Status__c,
                                Status_Reason__c,Data_Missing_Codes__c,Data_Missing_Comments__c,
                                Order_Pending_Date__c FROM Order__c WHERE Id=:opportunityId];

        return orders;
    }

    @AuraEnabled(Cacheable=true)
    public static OpportunityLocationConfiguration__c[] getSolutionTableData(String opportunityId) {
        OpportunityLocationConfiguration__c[] solutions = [SELECT Name, Term__C, Active__c, MRC_Total__C,  NRC_Total__c FROM OpportunityLocationConfiguration__c 
                                                            WHERE Id =:opportunityId];

        // Add Approval Status Logic 
        
        return solutions;
    }

    // @AuraEnabled(Cacheable=true)
    // public static Opportunity getAccountId(String opportunityId) {
    //     Opportunity opportunity = [SELECT Account.Id FROM Opportunity where Id=:opportunityId LIMIT 1];

    //     return opportunity;
    // }

    // @AuraEnabled(Cacheable=true)
    // public static Account getAccountId() {
    //     Account account = [SELECT Id FROM Account where Id='001n000000Wdag9AAB'];

    //     return account;
    // }

    @AuraEnabled (Cacheable=true)
    public static List<OpportunityTeamMember> getOpportunityTeamMembers(String opportunityId) {
        List<OpportunityTeamMember> teamMembers = [SELECT Id, User.Name, TeamMemberRole FROM OpportunityTeamMember
                                                WHERE OpportunityId = :opportunityId];
        
        return teamMembers;
    }
}