main/default/objects/LanguageTranslation__c/LanguageTranslation__c.object-meta.xml
<CustomObject>
    <description>Object to be used for Language Translation</description>
    <label>LanguageTranslation</label>
    <nameField>
        <label>Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LanguageTranslations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LanguageTranslation__c/fields/French_Text__c.field-meta.xml
<CustomField>
    <fullName>French_Text__c</fullName>
    <description>French Translation</description>
    <label>French Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/LanguageTranslation__c/fields/Original_Text__c.field-meta.xml
<CustomField>
    <fullName>Original_Text__c</fullName>
    <description>Hold the text to be translated</description>
    <label>Original Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/OLI__c/OLI__c.object-meta.xml
<CustomObject>
    <description>Line item details for an opportunity</description>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000}</displayFormat>
        <label>OLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OLI__c/fields/DQ__c.field-meta.xml
<CustomField>
    <fullName>DQ__c</fullName>
    <description>System field.  Do not use in page layouts.</description>
    <label>DQ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/OLI__c/fields/DQ_FR__c.field-meta.xml
<CustomField>
    <fullName>DQ_FR__c</fullName>
    <label>DQ_FR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/OLI__c/fields/MRC__c.field-meta.xml
<CustomField>
    <fullName>MRC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MRC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/OLI__c/fields/MRC_Total__c.field-meta.xml
<CustomField>
    <fullName>MRC_Total__c</fullName>
    <formula>Qty__c  * (MRC__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MRC Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/OLI__c/fields/OpportunityLocationConfiguration__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLocationConfiguration__c</fullName>
    <label>OpportunityLocationConfiguration</label>
    <referenceTo>OpportunityLocationConfiguration__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/OLI__c/fields/Parent_Opportunity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Opportunity_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity Line Item</label>
    <referenceTo>OLI__c</referenceTo>
    <relationshipLabel>Dependent Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/OLI__c/fields/PP_Feature_Grouping_Sort__c.field-meta.xml
<CustomField>
    <fullName>PP_Feature_Grouping_Sort__c</fullName>
    <label>PP_Feature_Grouping_Sort</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/OLI__c/fields/PP_Package_Feature__c.field-meta.xml
<CustomField>
    <fullName>PP_Package_Feature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PP_Package_Feature</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/OLI__c/fields/PP_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>PP_Product_Family__c</fullName>
    <label>PP_Product_Family</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OLI__c/fields/PP_Product_Family_Sort__c.field-meta.xml
<CustomField>
    <fullName>PP_Product_Family_Sort__c</fullName>
    <label>PP_Product_Family_Sort</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/OLI__c/fields/PP_Product_Pricing_Name__c.field-meta.xml
<CustomField>
    <fullName>PP_Product_Pricing_Name__c</fullName>
    <label>PP_Product_Pricing_Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OLI__c/fields/PP_Product_Pricing_Name_FR__c.field-meta.xml
<CustomField>
    <fullName>PP_Product_Pricing_Name_FR__c</fullName>
    <label>PP_Product_Pricing_Name_FR</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/OLI__c/fields/PP_Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>PP_Sales_Product__c</fullName>
    <label>PP_Sales_Product</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OLI__c/fields/PP_Sales_Product_Sort__c.field-meta.xml
<CustomField>
    <fullName>PP_Sales_Product_Sort__c</fullName>
    <label>PP_Sales_Product_Sort</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/OLI__c/fields/PP_Sales_Rate_Plan_Description_Sort__c.field-meta.xml
<CustomField>
    <fullName>PP_Sales_Rate_Plan_Description_Sort__c</fullName>
    <label>PP_Sales_Rate_Plan_Description_Sort</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/OLI__c/fields/PP_SalesProductExternalID__c.field-meta.xml
<CustomField>
    <fullName>PP_SalesProductExternalID__c</fullName>
    <label>PP_ SalesProductExternalID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/OLI__c/fields/PP_SalesRatePlanPricingExternalID__c.field-meta.xml
<CustomField>
    <fullName>PP_SalesRatePlanPricingExternalID__c</fullName>
    <label>PP_SalesRatePlanPricingExternalID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/OLI__c/fields/Product_Family_Product__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Product__c</fullName>
    <label>Product Family Product</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OLI__c/fields/Product_Pricing_Display_French_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Pricing_Display_French_Name__c</fullName>
    <description>System field</description>
    <label>Product Pricing Display French Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/OLI__c/fields/Product_Pricing_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Pricing_Display_Name__c</fullName>
    <description>System field for displaying PP_Product_Pricing_Name__c on PDFs</description>
    <label>Product Pricing Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/OLI__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Qty</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/OLI__c/fields/SPC_Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Sales_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SPC Sales Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/OpportunityLocationConfiguration__c/OpportunityLocationConfiguration__c.object-meta.xml
<CustomObject>
    <description>A configuration for an OpportunityLocation.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/OpportunityLocationConfiguration__c/fields/MRC_Total__c.field-meta.xml
<CustomField>
    <fullName>MRC_Total__c</fullName>
    <label>MRC Total</label>
    <summarizedField>OLI__c.MRC_Total__c</summarizedField>
    <summaryForeignKey>OLI__c.OpportunityLocationConfiguration__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

main/default/objects/RemoveSuffixes__c/RemoveSuffixes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Remove Suffixes</label>
</CustomObject>

objects/RemoveSuffixes__c/fields/NewSuffix__c.field-meta.xml
<CustomField>
    <fullName>NewSuffix__c</fullName>
    <label>NewSuffix</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QuoteWrapper.cls
public with sharing class QuoteWrapper {
    public static List<LanguageTranslation__c> lang = [Select Original_Text__c, French_Text__c from LanguageTranslation__c];
    
    public class QuoteLineItem {
        
        public QuoteLineItem(OLI__c oli) {
            rawOLI = oli;           
            printDescription = cleanDescriptionSuffix(oli.PP_Product_Pricing_Name__c);
            oli.Product_Pricing_Display_French_Name__c = getFrenchText(oli.Product_Pricing_Display_Name__c);
            //oli.PP_Product_Pricing_Name_FR__c = getFrenchText(oli.PP_Product_Pricing_Name__c);
            //System.debug('PP_Product_Pricing_Name_c: ' + oli.PP_Product_Pricing_Name__c + ', FR:' + oli.PP_Product_Pricing_Name_FR__c);
            //System.debug('DQ_C: ' + oli.DQ__c + ', FR: ' + oli.DQ_FR__c);
            //System.debug('PP_Product_Pricing_Name_c: ' + oli.Product_Pricing_Display_Name__c + ', FR:' + oli.Product_Pricing_Display_French_Name__c);
        }
        
        public QuoteLineItem() {
          rawOLI = new OLI__c();
          rawOLI.Qty__c = 0;
          printDescription = '';
        }
    
      private String cleanDescriptionSuffix(String originalString) {
          String cleanString = originalString;
          
          for(String suffix : RemoveSuffixes__c.getAll().keySet()) {
              if (originalString.endsWith(suffix)) {
                  String replaceWith = RemoveSuffixes__c.getAll().get(suffix).NewSuffix__c;
                  replaceWith = (replaceWith == null) ? '' : replaceWith;
                  cleanString = originalString.replace(suffix, replaceWith);
                  break;
              }
          }
      
          return cleanString;
      }
        
        public OLI__c rawOLI {get;set;}
        public String printDescription {get;set;} 
        public List<SelectOption> groupselectOption{get;set;}
        public String selectedgroup{get;set;}
    }

    public class Product {
        public string Name {get;set;}
        public string FrenchName {get;set;}
        public string ProductId {get;set;}
        public string SFDCId {get;set;}
        public string externalID{get;set;}
        public String productFamilyId{get;set;}
        public String Salesproduct{get;set;}  
        public String salesproductgroup{get;set;}
        public List<QuoteLineItem> lines {get;set;}
    	public Map<string,List<QuoteLineItem>> linesMap {get;set;}
        public Set<String> lstoftagname{get;set;}
        public Decimal total {get;set;}
        public boolean validatePickVal{get;set;}
        public Decimal NRCTotal {get;Set;}
        public Product() {
          lines = new List<QuoteLineItem>();
        }
        
        public Product(string in_name, string externalId, string internalId) {
        	Name = in_name;
          	ProductId = externalId;
          	SFDCId = internalId;
          	lines = new List<QuoteLineItem>();
      		linesMap = new Map<string,List<QuoteLineItem>>();
          	total = 0;
      		NRCTotal = 0;
        }
    }
    
    public class ProductFamily {
      public string Name {get;set;}
      public string SFDCId {get;set;}
      public List<Product> products {get;set;}
      public List<SPC_Product__c> spcproducts{get;set;}
      public Decimal total {get;set;}
      
      public ProductFamily(string in_Name, Id in_Id ) {
        Name = in_Name;
        SFDCId = in_Id;
        products = new List<Product>();
        total = 0;
      }
    }
    
    public static String getFrenchText(String text){
        String frenchText = text;
        for (LanguageTranslation__c obj : lang){
            if (obj.Original_Text__c == text){
            	frenchText = obj.French_Text__c;
                break;
            }	    
        }
        return frenchText;
    }
    
    public static List<Product> getConfigProductsWithLineItems(Id configId, Boolean sortForPrint, Boolean ignoreFamilySort,  List<OLI__c> oppyLineItems){
        List<Product> lstProducts = new List<Product>();
        if(oppyLineItems != null){
          Product currentProduct = null;
          for( OLI__C oli : oppyLineItems ) {
              if  (oli.Product_Family_Product__c != null)  {
                  if( (currentProduct == null) || (!currentProduct.Name.equals(oli.Product_Family_Product__c))) {
                  		currentProduct = new Product(oli.Product_Family_Product__c, oli.PP_SalesProductExternalID__c, oli.SPC_Sales_Product__c);
            			currentProduct.FrenchName = getFrenchText(oli.Product_Family_Product__c);
                      	lstProducts.add(currentProduct);
                  }
          QuoteLineItem qli = new QuoteLineItem(oli);
          currentProduct.lines.add(qli);
          string oliGroupName = oli.Group_Name__c == null ? oli.Product_Family_Product__c : oli.Group_Name__c;
          if(currentProduct.linesMap.containskey(oliGroupName)){
            List<QuoteLineItem> qlis = currentProduct.linesMap.get(oliGroupName);
            qlis.add(qli);
            currentProduct.linesMap.put(oliGroupName,qlis);
          }
          else{
            currentProduct.linesMap.put(oliGroupName,new List<QuoteLineItem>{qli});
          }
                  currentProduct.total += oli.MRC_Total__c;
              }
          }
        }
        
        return lstProducts;
    }
    
    public static List<Product> getConfigProductsFromOLIs(List<OLI__c> oppyLineItems){
        List<Product> lstProducts = new List<Product>();
        Product currentProduct = null;
    Map<id,Product> currentProductMap = new Map<id,Product>();

        for( OLI__C oli : oppyLineItems ) {
            if  (oli.PP_Sales_Product__c != null)  {
                if( !currentProductMap.containsKey(oli.SPC_Sales_Product__c)) {
          			system.debug('create new current prod: ' + oli.PP_Sales_Product__c + ' ' +  oli.PP_SalesProductExternalID__c + ' ' +  oli.SPC_Sales_Product__c);
                    currentProduct = new Product(oli.PP_Sales_Product__c, oli.PP_SalesProductExternalID__c, oli.SPC_Sales_Product__c);
          			currentProduct.FrenchName = getFrenchText(oli.Product_Family_Product__c);
                    currentProductMap.put(oli.SPC_Sales_Product__c,currentProduct);
          			lstProducts.add(currentProduct);
                }
        		else
          			currentProduct = currentProductMap.get(oli.SPC_Sales_Product__c);
                
        		QuoteLineItem qli = new QuoteLineItem(oli);
                currentProduct.lines.add(qli);
        		string oliGroupName = oli.Group_Name__c == null ? oli.PP_Sales_Product__c : oli.Group_Name__c;
                if(currentProduct.linesMap.containskey(oliGroupName)){
                  	List<QuoteLineItem> qlis = currentProduct.linesMap.get(oliGroupName);
                  	qlis.add(qli);
                  	currentProduct.linesMap.put(oliGroupName,qlis);
                }
                else{
                  	currentProduct.linesMap.put(oliGroupName,new List<QuoteLineItem>{qli});
                }
          
                currentProduct.total += oli.MRC_Total__c;
            }
        }
    
        return lstProducts;
    }
    
    public static List<ProductFamily> getConfigFamilies(Id configId){
      
    List<OLI__c> oppyLineItems = getOLIs(configId, false, false);
        
        List<ProductFamily> lstFamilies = new List<ProductFamily>();
        
        ProductFamily currentFamily = null;
        for( OLI__C oli : oppyLineItems ) {
    
            if  (oli.PP_Product_Family__c != null)  {
                if( (currentFamily == null) || (!currentFamily.Name.equals(oli.PP_Product_Family__c))) {
                  currentFamily = new ProductFamily(oli.PP_Product_Family__c, oli.id);
                  lstFamilies.add(currentFamily);
                }
        
              if  (oli.PP_Sales_Product__c != null)  {
                  if( (currentFamily.products.isEmpty()) || (!currentFamily.products[currentFamily.products.size()-1].Name.equals(oli.PP_Sales_Product__c))) {
                      Product currentProduct = new Product(oli.PP_Sales_Product__c, oli.PP_SalesProductExternalID__c, oli.id);
                      
                      currentFamily.Products.add(currentProduct);
                  }
                  currentFamily.Products[currentFamily.Products.size()-1].lines.add(new QuoteLineItem(oli)); 
                  currentFamily.Products[currentFamily.Products.size()-1].total += oli.MRC_Total__c;
                  currentFamily.total += oli.MRC_Total__c;
              }
            }
        }
      
      return lstFamilies;
    }
  
  private static List<OLI__c> getOLIs(Id configId, Boolean sortForPrint, Boolean ignoreFamilySort) {
    return ApexUtils.retrieveObjectsFromFieldSets(OLI__c.getsObjectType()
                                  ,new List<Set<String>>
                                  {
                                    SchemaUtils.RetrieveFullObjectFieldSet(OLI__c.getsObjectType())
                                    ,new Set<String> { 'Parent_Opportunity_Line_Item__r.PP_SalesRatePlanPricingExternalID__c' }
                                  }
                                  ,'OpportunityLocationConfiguration__c=\'' + configId + '\' AND (PP_Package_Feature__c = false OR PP_Package_Feature__c = null)'
                                  ,sortForPrint
                                ? (!ignoreFamilySort ? 'PP_Product_Family_Sort__c,  PP_Sales_Product_Sort__c, ' : '') + 'MRC__c DESC, Qty__c DESC'
                                : 'PP_Product_Family_Sort__c,  PP_Sales_Product_Sort__c,  PP_Feature_Grouping_Sort__c, PP_Sales_Rate_Plan_Description_Sort__c');
  }
  
  public static List<ProductFamily> sortListByProductName(List<ProductFamily> unsortedList) {
    
    Map<String, ProductFamily> productNameToProductFamily = new Map<String, ProductFamily>();
    for(ProductFamily QPF : unsortedList)
      productNameToProductFamily.put(QPF.name,QPF);
    
    List<String> productNamelst = new List<String>(productNameToProductFamily.keyset());
    productNamelst.sort();
    
    List<ProductFamily> sortedList = new List<ProductFamily>();
    for(String s : productNamelst)
      sortedList.add(productNameToProductFamily.get(s));
    
    return sortedList;
  }
}