main/default/objects/Junction__c/Junction__c.object-meta.xml
<CustomObject>
    <description>A generic object to object junction to be manipulated in code only.</description>
    <label>Junction</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Junction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Junction__c/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <label>Source ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Junction__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Junction__c/fields/Target_ID__c.field-meta.xml
<CustomField>
    <fullName>Target_ID__c</fullName>
    <label>Target ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Junction__c/fields/Target_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Type__c</fullName>
    <label>Target Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/JunctionUtils.cls
public without sharing class JunctionUtils{

	public class Junction{
		public sObject Source { get; private set; }
		public sObject Target { get; private set; }
		public Id JunctionID { get; set; }
		
		public Junction(){ }
		
		public Junction(sObject source, sObject target, Id id){
			this.Source = source;
			this.Target = target;
			JunctionID = id;
		}
		
		public void SetSource(SObject source){
			this.Source = source;
		}
		
		public void SetSource(Id id){
			SetSource(SchemaUtils.GetSObjectTypeByID(id).newSObject(id));
		}
		
		public void SetTarget(SObject target){
			this.Target = target;
		}
		
		public void SetTarget(Id id){
			SetTarget(SchemaUtils.GetSObjectTypeByID(id).newSObject(id));
		}
	}
	
	public static List<Junction> GetJunctions(Set<Id> validSourceIDs, Set<Id> validTargetIDs){
		List<Junction> l = new List<Junction>();
		for(Junction__c j : [select Id, Source_ID__c, Target_ID__c from Junction__c where Source_ID__c in: validSourceIDs and Target_ID__c in: validTargetIDs]){
			Schema.SObjectType sOt = SchemaUtils.GetSObjectTypeByID(j.Source_ID__c);
			Schema.SObjectType tOt = SchemaUtils.GetSObjectTypeByID(j.Target_ID__c);
			if(sOt != null && tOt != null){
				l.add(new Junction(sOt.newSObject(j.Source_ID__c), tOt.newSObject(j.Target_ID__c), j.Id));
			}
		}
		return l;
	}
	
	public static List<Junction> GetSOrTBasedJunctions(Set<Id> validSourceIDs, Set<Id> validTargetIDs){
		List<Junction> l = new List<Junction>();
		List<String> types = new List<String>();
		types.add('Sub_Order__c');
		types.add('Order__c');
		for(Junction__c j : [select Id, Source_ID__c, Target_ID__c from Junction__c where (Source_ID__c in: validSourceIDs and Target_ID__c in: validTargetIDs) or (Source_ID__c in: validSourceIDs and Target_Type__c in: types)]){
			Schema.SObjectType sOt = SchemaUtils.GetSObjectTypeByID(j.Source_ID__c);
			Schema.SObjectType tOt = SchemaUtils.GetSObjectTypeByID(j.Target_ID__c);
			if(sOt != null && tOt != null){
				l.add(new Junction(sOt.newSObject(j.Source_ID__c), tOt.newSObject(j.Target_ID__c), j.Id));
			}
		}
		return l;
	}
	
	public static List<Database.UpsertResult> SaveJunctions(List<Junction> jList){
		List<Junction__c> l = convert(jList);
		
		List<Database.UpsertResult> rList = Database.Upsert(l, true);
		for(Integer i=0; i<rList.size(); i++)
			jList[i].JunctionID = rList[i].Id;
		return rList;
	}
	
	public static List<Database.DeleteResult> DeleteJunctions(List<Junction> jList){
		List<Junction__c> l = convert(jList);
		return Database.Delete(l, true);
	}
	
	private static List<Junction__c> convert(List<Junction> jList){
		List<Junction__c> l = new List<Junction__c>();
		for(Junction j : jList){
			Junction__c oj = new Junction__c(Source_ID__c = j.Source.Id, Target_ID__c = j.Target.Id, Source_Type__c = SchemaUtils.GetSObjectNameByID(j.Source.Id), Target_Type__c = SchemaUtils.GetSObjectNameByID(j.Target.Id));
			if(j.JunctionID != null) oj.Id = j.JunctionID;
			l.add(oj);
		}
		return l;
	}
}