main/default/objects/AccountReference__c/AccountReference__c.object-meta.xml
<CustomObject>
    <description>Redundant &quot;ghost&quot; object that has just a few fields that inherit their values from the account like account name, address, owner and sales channel</description>
    <label>Account Reference</label>
    <nameField>
        <label>Account Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/AccountReference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account this record is associated with.</description>
    <inlineHelpText>Account this record is associated with.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>All_Accounts_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/Government_Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Government_Contract_Type__c</fullName>
    <label>Government Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CALNET3</fullName>
            </value>
            <value>
                <fullName>GSA R8 LSA 2</fullName>
            </value>
            <value>
                <fullName>GSA R8 LSA 2 (+Disaster Purchasing Program)</fullName>
            </value>
            <value>
                <fullName>IT Schedule 70</fullName>
            </value>
            <value>
                <fullName>IT Schedule 70 (+Disaster Purchasing Program)</fullName>
            </value>
            <value>
                <fullName>MiCTA</fullName>
            </value>
            <value>
                <fullName>State of AZ</fullName>
            </value>
            <value>
                <fullName>State of Idaho</fullName>
            </value>
            <value>
                <fullName>State of Oregon</fullName>
            </value>
            <value>
                <fullName>State of Utah MA110</fullName>
            </value>
            <value>
                <fullName>State of WA K1677</fullName>
            </value>
            <value>
                <fullName>State of WA T12-PCH-739</fullName>
            </value>
            <value>
                <fullName>St of MN Backbone 55583</fullName>
            </value>
            <value>
                <fullName>St of MN PRI 66842</fullName>
            </value>
            <value>
                <fullName>Univ of MN PRI 66842</fullName>
            </value>
            <value>
                <fullName>UW-IT Ethernet Services</fullName>
            </value>
            <value>
                <fullName>GOO MGS: OSS_00411380</fullName>
            </value>
            <value>
                <fullName>Canada: Legal Aid</fullName>
            </value>
            <value>
                <fullName>OACCAC</fullName>
            </value>
            <value>
                <fullName>WSIB</fullName>
            </value>
            <value>
                <fullName>Canada Federal Govt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Government_Segment__c.field-meta.xml
<CustomField>
    <fullName>Government_Segment__c</fullName>
    <label>Government Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Province</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Integration_Error__c/Integration_Error__c.object-meta.xml
<CustomObject>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Integration_Error__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Integration_Error__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <description>This is a general purpose field for storing what we were trying to do when integrating when we failed.  Both Action and the related object are taken into account when reading the values here:

Object(Action): Value
---------------------
Account(Update): Comma delimited field names
Contact(Update): N/A
Contact(Delete): ICC Contact ID
Service Location(Insert): Closed Won Opportunity ID (earliest closed date)
Service Location(Update): Comma delimited field names</description>
    <label>Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Integration_Error__c/fields/ObjectID__c.field-meta.xml
<CustomField>
    <fullName>ObjectID__c</fullName>
    <label>ObjectID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Service_Location__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

main/default/classes/Test_AccountTriggers.cls
@isTest
public with sharing class Test_AccountTriggers extends TestUtils.TestClass {
    
    static testMethod void TestAccountReferenceObject(){
        
        Mocks testdata = new Mocks();
        
        List<Account> accts = testdata.getAccountList(1);
        
        test.startTest();
        
        AccountTriggers.createAccountReferenceObject(accts);
        
        List<AccountReference__c> refList = ([SELECT Id, Name, Account__c  FROM AccountReference__c WHERE Account__c IN: accts]);
        
        system.assertEquals(1, refList.size());
		
        delete accts;
		
		refList = ([SELECT Id, Name, Account__c  FROM AccountReference__c WHERE Account__c IN: accts]);
        
        system.assertEquals(0, refList.size());
        
        test.stopTest();
    }
    
    static testMethod void TestSetPreviousUserField(){
        
        Mocks testdata = new Mocks();       
        List<Account> accts = testdata.getAccountList(20);
        
        upsert accts;
        
        User u = [SELECT Title, Id, Username, Name FROM User WHERE IsActive = true AND UserType LIKE:'%Standard%' LIMIT 1];
        
        for(Account a : accts){         
            a.OwnerId = u.Id;
        }
        
        List<Database.Saveresult> results;
         
        try{
        
            results = Database.update(accts, false);
        
        }catch(DmlException e){
            
            for(Database.SaveResult result : results){
                    if(!result.isSuccess())
                        system.debug(result.getErrors()[0]);
            }
            
            
            for (Integer i = 0; i < results.size(); i++) {
           
                if (results[i].isSuccess()) {
                    System.debug('Successfully created ID: ' + results[i].getId());
                } else {
                
                System.debug('Error: could not create sobject for array element ' + i + '.');
                System.debug('   The error reported was: ' + results[i].getErrors()[0].getMessage() + '\n');
                }
            }
        }
    }
    
    static testMethod void TestAccountUpdateIntegration(){
    	Mocks mocks = new Mocks();
    	
        List<Customer_Detail__c> cd = new List<Customer_Detail__c>{new Customer_Detail__c(ICC_Subscriber_ID__c = '-1')
																,new Customer_Detail__c(ICC_Subscriber_ID__c = '-2')};
        insert cd;
		
    	Account a = mocks.parentAccount;
		integraWSEndpointMediator.simulateIntegrationException = true;
    	a.Phone = '(555) 555-1234';
    	//a.OwnerId = mocks.user.Id;
        a.Customer_Detail__c = cd[0].Id;
        a.Billable__c = false;
    	update a;
        
		Service_Location__c sLoc = mocks.serviceLocation;
		sLoc.Customer_Detail__c = cd[1].Id;
		update sLoc;
    	
        test.startTest();
    	
		a.Name = a.Name + '1';
    	a.Billable__c = true;
    	a.Phone = '(555) 555-4321';
		a.Government_Contract_Type__c = 'CALNET3';
		a.Government_Segment__c = 'Federal';
		a.Industry = 'Education';
    	update a;
    	
    	//This won't actually create the IntegrationError object so let's make it
    	Integration_Error__c error = new Integration_Error__c(ObjectID__c = a.Id, Action__c = 'Update', Info__c = 'Phone,Owner');
    	insert error;
    	
    	IntegrationUtils.reintegrateObjects(new Set<String>{a.Id});
    	
    	test.stopTest();
    }

}