main/default/objects/AccountReference__c/AccountReference__c.object-meta.xml
<CustomObject>
    <description>Redundant &quot;ghost&quot; object that has just a few fields that inherit their values from the account like account name, address, owner and sales channel</description>
    <label>Account Reference</label>
    <nameField>
        <label>Account Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/AccountReference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account this record is associated with.</description>
    <inlineHelpText>Account this record is associated with.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>All_Accounts_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Team_Sell_Request__c/Team_Sell_Request__c.object-meta.xml
<CustomObject>
    <description>Record to be used for information to request a teal sell - approval process</description>
    <label>Team Sell Request</label>
    <nameField>
        <displayFormat>Team Sell Request {0000}</displayFormat>
        <label>Team Sell Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Sell Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Sell_Request__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>Related to Account Reference - Account Name</description>
    <label>Account Name</label>
    <referenceTo>AccountReference__c</referenceTo>
    <relationshipLabel>Team Sell Requests</relationshipLabel>
    <relationshipName>Team_Sell_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Team_Sell_Request__c/fields/Partner_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Name__c</fullName>
    <description>Enter the name of the Partner</description>
    <inlineHelpText>Enter the name of the Partner</inlineHelpText>
    <label>Partner Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Team_Sell_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>approval status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/TeamSellRequestTriggers.cls
public without sharing class TeamSellRequestTriggers {
	public static void TeamSellRequestModified(List<Team_Sell_Request__c> tNew, List<Team_Sell_Request__c> tOld, Boolean isBefore, Boolean isUpdate,  Boolean isDelete){
        if (!isBefore){
            if (!isDelete){
				if (isUpdate){
                    List<Id> accountIDs = new List<Id>();
                    List<String> partners = new List<String>();
                    
                    for (Team_Sell_Request__c tsr : tNew){
                        accountIDs.add(tsr.Account_Name__c);
                        partners.add(tsr.Partner_Name__c);
                    }
                    
                    List<AccountTeamMember> accTMs = new List<AccountTeamMember>();
                    Map<Id, Team_Sell_Request__c> tOldMap = tOld != null ? new Map<Id, Team_Sell_Request__c>(tOld) : new Map<Id, Team_Sell_Request__c>();
                    Map<Id, AccountReference__c> arMap = new Map<Id, AccountReference__c>([SELECT Id, Account__c FROM AccountReference__c WHERE Id in :accountIDs]);
                    Map<String, Id> userMap = new Map<String, Id>();
                    
                    for (User u : [SELECT Id, Name FROM User WHERE IsActive = true AND Name in :partners]){
                    	userMap.put(u.Name.toLowerCase(), u.Id);	    
                    }
                    
                    for (Team_Sell_Request__c tsr : tNew){
                        Team_Sell_Request__c oldTSR = tOldMap.get(tsr.Id);
                        if ((oldTSR.Status__c != 'Approved' && tsr.Status__c == 'Approved') && userMap.containsKey(tsr.Partner_Name__c.toLowerCase())){
                        	AccountTeamMember accTM = new AccountTeamMember();
                            AccountReference__c ar = arMap.get(tsr.Account_Name__c);
                            accTM.AccountId = ar.Account__c;
                            //accTM.AccountId = [SELECT Account__c FROM AccountReference__c WHERE Id =: tsr.Account_Name__c].Account__c;
                            accTM.TeamMemberRole = 'Team Member';
                            accTM.AccountAccessLevel = 'Edit';
                            accTM.UserId = userMap.get(tsr.Partner_Name__c.toLowerCase());
                            //accTM.UserId = tsr.Partner__c;
                            accTMs.add(accTM);
                        }
                    }
                    insert accTMs;
            	}                
            }            
        }
    }
}