main/default/objects/AccountReference__c/AccountReference__c.object-meta.xml
<CustomObject>
    <description>Redundant &quot;ghost&quot; object that has just a few fields that inherit their values from the account like account name, address, owner and sales channel</description>
    <label>Account Reference</label>
    <nameField>
        <label>Account Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/AccountReference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account this record is associated with.</description>
    <inlineHelpText>Account this record is associated with.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>All_Accounts_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Team_Sell_Request__c/Team_Sell_Request__c.object-meta.xml
<CustomObject>
    <description>Record to be used for information to request a teal sell - approval process</description>
    <label>Team Sell Request</label>
    <nameField>
        <displayFormat>Team Sell Request {0000}</displayFormat>
        <label>Team Sell Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Sell Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Sell_Request__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>Related to Account Reference - Account Name</description>
    <label>Account Name</label>
    <referenceTo>AccountReference__c</referenceTo>
    <relationshipLabel>Team Sell Requests</relationshipLabel>
    <relationshipName>Team_Sell_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Team_Sell_Request__c/fields/Allstream_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Allstream_Relationship__c</fullName>
    <description>What relationship does Allstream have, if any</description>
    <inlineHelpText>What relationship does Allstream have, if any</inlineHelpText>
    <label>Allstream Relationship</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

main/default/objects/Team_Sell_Request__c/fields/Approval_Request_Notes__c.field-meta.xml
<CustomField>
    <fullName>Approval_Request_Notes__c</fullName>
    <description>Notes to why requested team sell</description>
    <label>Approval Request Notes</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

objects/Team_Sell_Request__c/fields/Opportunity_Discovery_Party__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Discovery_Party__c</fullName>
    <description>Who discovered the opportunity (Requestor or Partner)</description>
    <inlineHelpText>Who discovered the opportunity (Requestor or Partner)</inlineHelpText>
    <label>Opportunity Discovery Party</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Requestor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Team_Sell_Request__c/fields/Partner_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Name__c</fullName>
    <description>Enter the name of the Partner</description>
    <inlineHelpText>Enter the name of the Partner</inlineHelpText>
    <label>Partner Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Team_Sell_Request__c/fields/Partner_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Partner_Relationship__c</fullName>
    <description>What relationship does Partner have</description>
    <inlineHelpText>What relationship does Partner have</inlineHelpText>
    <label>Partner Relationship</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

main/default/objects/Team_Sell_Request__c/fields/Projected_New_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Projected_New_Revenue__c</fullName>
    <description>Projected new revenue from opportunity</description>
    <inlineHelpText>Projected new revenue from opportunity</inlineHelpText>
    <label>Projected New Revenue</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Team_Sell_Request__c/fields/Proposed_services__c.field-meta.xml
<CustomField>
    <fullName>Proposed_services__c</fullName>
    <description>Proposed services</description>
    <inlineHelpText>You can select multiple services</inlineHelpText>
    <label>Proposed services</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Access Service</fullName>
            </value>
            <value>
                <fullName>Basic Voice Services</fullName>
            </value>
            <value>
                <fullName>Broadband/DSL</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Cloud Firewall Service</fullName>
            </value>
            <value>
                <fullName>Collaboration &amp; Messaging</fullName>
            </value>
            <value>
                <fullName>Colocation Services</fullName>
            </value>
            <value>
                <fullName>Conference Now</fullName>
            </value>
            <value>
                <fullName>CPE MRR</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet</fullName>
            </value>
            <value>
                <fullName>DSL and/or Broadband</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LAN</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LINE Host Site</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LINE Remote Site</fullName>
            </value>
            <value>
                <fullName>Failover – Dedicated Internet</fullName>
            </value>
            <value>
                <fullName>Failover – VPN Solutions</fullName>
            </value>
            <value>
                <fullName>Hosted &amp; Managed PBX</fullName>
            </value>
            <value>
                <fullName>Hosted Voice Services</fullName>
            </value>
            <value>
                <fullName>ISDN/PRI</fullName>
            </value>
            <value>
                <fullName>ISP Services</fullName>
            </value>
            <value>
                <fullName>Legacy Voice or Integrated T1</fullName>
            </value>
            <value>
                <fullName>Long Distance</fullName>
            </value>
            <value>
                <fullName>Managed Prime/Pro</fullName>
            </value>
            <value>
                <fullName>Managed UC</fullName>
            </value>
            <value>
                <fullName>Network Security Suite</fullName>
            </value>
            <value>
                <fullName>Network Solutions</fullName>
            </value>
            <value>
                <fullName>NGN SIP Trunking</fullName>
            </value>
            <value>
                <fullName>Novus</fullName>
            </value>
            <value>
                <fullName>PBX Services MAC</fullName>
            </value>
            <value>
                <fullName>PBX Services New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Team_Sell_Request__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person requesting the approval</description>
    <inlineHelpText>Enter the name of the person requesting approval</inlineHelpText>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Sell_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Team_Sell_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>approval status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/Test_TeamSellRequest.cls
@isTest
global class Test_TeamSellRequest {
    public static testMethod void testTeamSellRequestModified() {
        Mocks testData = new Mocks();
        User u = testData.user;
        AccountReference__c accRef = new AccountReference__c(Account__c=testData.parentAccount.Id);
        insert accRef;
        
    	Team_Sell_Request__c tsr = new Team_Sell_Request__c();
        tsr.Account_Name__c = accRef.Id;
        tsr.Allstream_Relationship__c = 'test';
        tsr.Partner_Relationship__c = 'test';
        tsr.Approval_Request_Notes__c = 'test note';
        tsr.Opportunity_Discovery_Party__c = 'Partner';
        tsr.Partner_Name__c = 'Test Engineer';
        tsr.Projected_New_Revenue__c = 100;
        tsr.Proposed_services__c = 'Access Service';
        tsr.Requestor__c = u.Id;
        tsr.Status__c = 'New';
        insert tsr;
        
        test.startTest();
        tsr.Status__c = 'Approved';
        update tsr;
        test.stopTest();
    }
    
    public static testMethod void testTeamSellRequestControllerExtension(){
        Mocks testData = new Mocks();
        User u = testData.user;
        AccountReference__c accRef = new AccountReference__c(Account__c=testData.parentAccount.Id);
        insert accRef;
        
    	Team_Sell_Request__c tsr = new Team_Sell_Request__c();
        tsr.Account_Name__c = accRef.Id;
        tsr.Allstream_Relationship__c = 'test';
        tsr.Partner_Relationship__c = 'test';
        tsr.Approval_Request_Notes__c = 'test note';
        tsr.Opportunity_Discovery_Party__c = 'Partner';
        tsr.Partner_Name__c = 'Test Engineer';
        tsr.Projected_New_Revenue__c = 100;
        tsr.Proposed_services__c = 'Access Service';
        tsr.Status__c = 'New';
        insert tsr;
        
        PageReference pageRef = Page.TeamSellRequestEdit;
		Test.setCurrentPage(pageRef);
		pageRef.getParameters().put('Id', String.valueOf(tsr.Id));
		ApexPages.StandardController sc = new ApexPages.StandardController(tsr);
		TeamSellRequestControllerExtension testAccPlan = new TeamSellRequestControllerExtension(sc);
    }
    
}