main/default/objects/Disconnect_Line_Item__c/Disconnect_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Turn Down</label>
    <nameField>
        <displayFormat>DLI-{00000}</displayFormat>
        <label>DLI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Turn Downs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Disconnect_Line_Item__c/fields/EPCProductDescription__c.field-meta.xml
<CustomField>
    <fullName>EPCProductDescription__c</fullName>
    <label>EPC Product Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Disconnect_Line_Item__c/fields/Opportunity_Location__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Location__c</fullName>
    <label>Opportunity Location</label>
    <referenceTo>Opportunity_Location__c</referenceTo>
    <relationshipName>Disconnect_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Opportunity_Location__c/Opportunity_Location__c.object-meta.xml
<CustomObject>
    <description>Locations on an opportunity</description>
    <label>Opportunity Location</label>
    <nameField>
        <label>Opportunity Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Opportunity_Location__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Toggles whether a location is on hold.</description>
    <inlineHelpText>Toggles whether a location is on hold.</inlineHelpText>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Opportunity_Location__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Opportunity Locations</relationshipLabel>
    <relationshipName>Opportunity_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Product__c/Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{0000000}</displayFormat>
        <label>Opportunity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Product__c/fields/MRC__c.field-meta.xml
<CustomField>
    <fullName>MRC__c</fullName>
    <label>MRC</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>Opportunity_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Opportunity_Product__c/fields/Primary_Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Opportunity_Product__c/fields/Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product__c</fullName>
    <label>Sales Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access Service</fullName>
            </value>
            <value>
                <fullName>Basic Voice Services</fullName>
            </value>
            <value>
                <fullName>Broadband/DSL</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Cloud Firewall Service</fullName>
            </value>
            <value>
                <fullName>Collaboration &amp; Messaging</fullName>
            </value>
            <value>
                <fullName>Colocation Services</fullName>
            </value>
            <value>
                <fullName>Conference Now</fullName>
            </value>
            <value>
                <fullName>CPE MRR</fullName>
            </value>
            <value>
                <fullName>Dedicated Internet</fullName>
            </value>
            <value>
                <fullName>DSL and/or Broadband</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LAN</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LINE Host Site</fullName>
            </value>
            <value>
                <fullName>Ethernet Services - E-LINE Remote Site</fullName>
            </value>
            <value>
                <fullName>Failover – Dedicated Internet</fullName>
            </value>
            <value>
                <fullName>Failover – VPN Solutions</fullName>
            </value>
            <value>
                <fullName>Hosted &amp; Managed PBX</fullName>
            </value>
            <value>
                <fullName>Hosted Voice Services</fullName>
            </value>
            <value>
                <fullName>ISDN/PRI</fullName>
            </value>
            <value>
                <fullName>ISP Services</fullName>
            </value>
            <value>
                <fullName>Legacy Voice or Integrated T1</fullName>
            </value>
            <value>
                <fullName>Long Distance</fullName>
            </value>
            <value>
                <fullName>Managed Prime/Pro</fullName>
            </value>
            <value>
                <fullName>Managed UC</fullName>
            </value>
            <value>
                <fullName>NAA</fullName>
            </value>
            <value>
                <fullName>Need A Product</fullName>
            </value>
            <value>
                <fullName>Network Security Suite</fullName>
            </value>
            <value>
                <fullName>Network Solutions</fullName>
            </value>
            <value>
                <fullName>NGN SIP Trunking</fullName>
            </value>
            <value>
                <fullName>Novus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Opportunity_Product__c/fields/SE_Upsell__c.field-meta.xml
<CustomField>
    <fullName>SE_Upsell__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this product is the result of a Sales Engineer upsell, box will be checked.</description>
    <inlineHelpText>Check the box if the addition of this product is the result of a Sales Engineer Upsell.</inlineHelpText>
    <label>SE Upsell?</label>
    <type>Checkbox</type>
</CustomField>

objects/Opportunity_Product__c/recordTypes/Turndown.recordType-meta.xml
<RecordType>
    <fullName>Turndown</fullName>
    <active>true</active>
    <description>Disconnect (Turndown) Products</description>
    <label>Turndown/Writedown</label>
</RecordType>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/classes/OpportunityLocationTrigger.cls
public with sharing class OpportunityLocationTrigger {
	
	public static void OpportunityLocationModified(Map<Id,Opportunity_Location__c> tNew, Map<Id,Opportunity_Location__c> tOld, Boolean isUpdate, Boolean isBefore){
		
		if(!ApexUtils.executeTriggerMethods('Opportunity_Location__c', isBefore, false)) return;
		
		if(!isBefore){
			if(isUpdate){
				updateChangeOpportunity(tNew);
			}
			
			ApexUtils.afterTriggerComplete('Opportunity_Location__c', false);
		}
	}
	
	private static RecordType turndownRecordType = null;
	private static void updateChangeOpportunity(Map<Id, Opportunity_Location__c> newSol){
		
		Map<Id,Id> oppsLocs = new Map<Id,Id>();
		for(Opportunity_Location__c oLocs : [Select Id, Opportunity__c From Opportunity_Location__c Where id in :newSol.keyset()]){
			oppsLocs.put(oLocs.Opportunity__c ,oLocs.Id);
		}

		Map<Id, Opportunity> oppsMap = new Map<Id, Opportunity>([Select id, RecordType.Name from Opportunity Where id in :oppsLocs.keySet() and RecordType.Id in: OpportunityUtils.ChangeRecordTypes]);

		
		 //Determine turndown recordtype on opportunity_product__c
		if(turndownRecordType == null){
			turndownRecordType = [Select id From  RecordType  Where Name = 'Turndown/Writedown' and SobjectType = 'Opportunity_Product__c' Limit 1];
		}
		
		//Because user can undo turndowns, we 1st need to clear out any turndown opp products that may have previously been created for this opp.
		List<Opportunity_Product__c> delprds = [Select Id, Name, Sales_Product__c From Opportunity_Product__c WHERE Opportunity__c in : oppsMap.keyset() AND RecordType.Id = : turndownRecordType.Id];
		if(delprds.size() > 0) delete delprds;
		
		List<Opportunity_Product__c> oprds = new List<Opportunity_Product__c>();
		for(Disconnect_Line_Item__c dprds : [select Id
													,Name
													,EPCProductDescription__c
													,MRC__c
													,Opportunity_Location__r.On_Hold__c
													,Opportunity_Location__r.Opportunity__c
													,Opportunity_Location__r.Service_Location__c
													from Disconnect_Line_Item__c
													where Opportunity_Location__r.Opportunity__c in :oppsMap.keyset()]){
														
			Opportunity_Location__c opLoc = dprds.Opportunity_Location__r;
			
			Opportunity_Product__c op = new Opportunity_Product__c();
			op.Active__c = opLoc.On_Hold__c == true ? false : true;
			op.MRC__c = - dprds.MRC__c;
			op.Opportunity__c = opLoc.Opportunity__c;
			op.Primary_Service_Location__c = opLoc.Service_Location__c;
			op.RecordTypeId = turndownRecordType.Id;
			op.SE_Upsell__c = false;
			op.Sales_Product__c = dprds.EPCProductDescription__c;
			oprds.add(op);
		}
		
		if(oprds.size() > 0) insert oprds;
	}
}