main/default/objects/Chatter_Auto_Follow__c/Chatter_Auto_Follow__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Chatter Auto-Follow</label>
</CustomObject>

main/default/objects/Chatter_Auto_Follow__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Chatter_Auto_Follow__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/classes/Test_Chatter.cls
@isTest
public with sharing class Test_Chatter{

	static testMethod void testAutoFollow() {
		Mocks testData = new Mocks();
		
		User u = testData.user;
		
		Chatter_Auto_Follow__c caf = new Chatter_Auto_Follow__c(Criteria__c=null, Group__c='Test', Name='Test');
		insert caf;
		
    	Test.startTest();
		
		update u;
	}
	
	static testMethod void testChatterTermsOfUse(){
		ChatterTermsOfUseController ctrl = new ChatterTermsOfUseController();
		ctrl.Agree();
	}
}