main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Order__c/fields/Customer_Requested_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Due_Date__c</fullName>
    <formula>Opportunity__r.Customer_Requested_Due_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Requested Due Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>IF(ISBLANK(Account__c), Opportunity__r.Account.Customer_Detail__r.ICC_Subscriber_ID__c, Account__r.Customer_Detail__r.ICC_Subscriber_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

main/default/objects/Order__c/recordTypes/Opportunity_Order.recordType-meta.xml
<RecordType>
    <fullName>Opportunity_Order</fullName>
    <active>true</active>
    <label>Opportunity Order</label>
</RecordType>

classes/lgt_DataFactory_Test.cls
@isTest
public with sharing class lgt_DataFactory_Test{
    static testMethod void test_getOrderNumber(){
        Customer_Detail__c cd = new Customer_Detail__c(ICC_Subscriber_ID__c='12345');
        insert cd;
        Account  a = new Account(Name = 'testAccount'
                                 ,ShippingCountry = 'US'
                                 ,Customer_Detail__c = cd.Id
                                 ,ShippingStreet = '1234 Someplace ST'
                                 ,ShippingCity = 'Nowhere'
                                 ,ShippingState = 'WA'
                                 ,ShippingPostalCode = '54321'
                                 ,Phone = '800-123-1234'
                                 ,Industry = 'Z - Unclassified');
        insert a;
        
        RecordType rt = [select Id from RecordType where SobjectType = 'Opportunity' and Name = 'Retail'];
        Opportunity opp = new Opportunity(AccountId = a.Id
                                          ,Name = 'Test Opp'
                                          ,RecordTypeId = rt.Id
                                          ,StageName = OpportunityUtils.STAGE_QUALIFIED
                                          ,Type = 'Existing'
                                          ,Oppty_Sub_Type__c='Renewal'
                                          ,CloseDate = Date.today().addDays(30)
                                          ,Customer_Requested_Due_Date__c = Date.today());
        insert opp;
        
        rt = [select Id from RecordType where SobjectType = 'Order__c' and DeveloperName = 'Opportunity_Order'];
        Order__c ord = new Order__c(Opportunity__c = opp.Id, RecordTypeId = rt.Id);
        insert ord;
        
        test.startTest();
        List<Order__c> orders = lgt_DataFactory.getOrderNumber(ord.id);
        System.assertNotEquals(orders[0].Name, null);
        test.stopTest();
        
    }
}