main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Refund_Credit__c/Refund_Credit__c.object-meta.xml
<CustomObject>
    <description>This object is used for processing Refunds &amp; Credits for Customers.</description>
    <label>Refund/Credit</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Refund/Credit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refund/Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Refund_Credit__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Refund/Credits</relationshipLabel>
    <relationshipName>Refund_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ACR_Utils_Test.cls
/***********************************************************************************************************
* Name       : ACR_Utils_Test
* Purpose    : Test class for ACR_Utils
************************************************************************************************************
* Author                 | Version    | Created Date    | Description
************************************************************************************************************
* Rahul Sekar            | 1.0        | April 30, 2019      | Initial version
***********************************************************************************************************/

@isTest
public class ACR_Utils_Test {
    /*
     * 	Conditions not satisfied Approve button access function returns false
     */
    @isTest
    private static void runAsUser(){
        Account ac = TestClassFactory.newAccount();
        Customer_Detail__c custDet = TestClassFactory.customerDetails(ac.id);       
        Refund_Credit__c rc = TestClassFactory.refundCredit(custDet.id);
        Test.startTest();        
            Boolean br = ACR_Utils.determineApproveButtonAccess(rc.id, ACR_ConstantDeclarations.RECORD_TYPE_REFUND , '');
            System.assertEquals(false, br);
        Test.stopTest();
    }
    /*
     *  Conditions satisfied Approve button access function returns true
     */
    @isTest
    private static void runAsSysAdmin(){
        String profileName='\'System Administrator\'';
        ACR_DomainLayer.QueryEditor prof = new ACR_DomainLayer.QueryEditor('Profile','WHERE Name='+profileName,'SELECT','Id ');
        List<Profile> profileId=(List<Profile>) prof.ResultSet; 
        User us = TestClassFactory.userDetails1(profileId[0].id);
        insert us;
        Account ac = TestClassFactory.newAccount();
        Customer_Detail__c custDet = TestClassFactory.customerDetails(ac.id);
        Refund_Credit__c rc = TestClassFactory.refundCredit1(custDet.id,us);
        Test.startTest();
        System.runAs(us){
            Boolean br = ACR_Utils.determineApproveButtonAccess(rc.id, ACR_ConstantDeclarations.RECORD_TYPE_REFUND , '');
            System.assertEquals(true, br);
        }
        Test.stopTest();
    }
}