main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Customer_Detail__c/fields/Acquired_Company_Biller__c.field-meta.xml
<CustomField>
    <fullName>Acquired_Company_Biller__c</fullName>
    <description>Acquired Company or Biller from legacy system or billing system moving forward</description>
    <inlineHelpText>Acquired Company or Biller from legacy system or billing system moving forward</inlineHelpText>
    <label>Acquired Company or Biller</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ASAP</fullName>
            </value>
            <value>
                <fullName>IBIS</fullName>
            </value>
            <value>
                <fullName>ICMS</fullName>
            </value>
            <value>
                <fullName>Optic Access</fullName>
            </value>
            <value>
                <fullName>ProTel</fullName>
            </value>
            <value>
                <fullName>WCI</fullName>
            </value>
            <value>
                <fullName>Phoenix</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_City__c</fullName>
    <label>Billing Main City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Country__c</fullName>
    <label>Billing Main Country</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Postal_Code__c</fullName>
    <label>Billing Main Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Billing_Main_Room_Suite__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Room_Suite__c</fullName>
    <label>Billing Main Room/Suite</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_State__c</fullName>
    <label>Billing Main State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Billing_Main_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Street__c</fullName>
    <label>Billing Main Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/BPID__c.field-meta.xml
<CustomField>
    <fullName>BPID__c</fullName>
    <description>Business Party ID</description>
    <inlineHelpText>Business Party ID</inlineHelpText>
    <label>BPID</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Customer_Main_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Main_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subscriber Address Type &#39;Customer Main&#39;</description>
    <label>Customer Main Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Customer Details (Customer Main Address)</relationshipLabel>
    <relationshipName>Customer_Main_Address_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Customer_Detail__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pre-Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Legacy_ID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_ID__c</fullName>
    <inlineHelpText>Customer Account Number from legacy billing system</inlineHelpText>
    <label>Legacy ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Area</label>
    <referenceTo>Market_Area__c</referenceTo>
    <relationshipLabel>Customer Details</relationshipLabel>
    <relationshipName>Customer_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Detail__c/fields/Parent_Customer__c.field-meta.xml
<CustomField>
    <fullName>Parent_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Customer</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Child Customers</relationshipLabel>
    <relationshipName>Child_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Market_Area__c/Market_Area__c.object-meta.xml
<CustomObject>
    <label>Market Area</label>
    <nameField>
        <label>Market Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Service_Location__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

objects/Service_Location__c/fields/Legacy_ID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_ID__c</fullName>
    <description>Legacy ID from the Customer Detail of the Service Location</description>
    <formula>IF(ISBLANK(Customer_Detail__r.Legacy_ID__c)|| ISNULL(Customer_Detail__r.Legacy_ID__c),Customer_Detail__r.Parent_Customer__r.Legacy_ID__c,Customer_Detail__r.Legacy_ID__c)</formula>
    <inlineHelpText>Legacy ID from the Customer Detail of the Service Location</inlineHelpText>
    <label>Legacy ID</label>
    <type>Text</type>
</CustomField>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

classes/Test_GlobysTransactionController.cls
@isTest
public with sharing class Test_GlobysTransactionController {

	
    public static final id MARKET_AREA_NATIONAL = 'a0JC000000ESX5W';
    //public static final id MARKET_AREA_NATIONAL = 'a0Jm0000006odFsEAI';

    static testMethod void testChangeLegacyIDChildCustomerDetail() {
        Mocks testData = new Mocks();
         
        
        
        Customer_Detail__c cdParent = test_setupTestData('Parent', testData.loc.Id, testData.parentAccount, testData.serviceLocation, false);
        cdParent.Market_Area__c = MARKET_AREA_NATIONAL;
        cdParent.BPID__c = '12345';
        cdParent.ICC_Subscriber_ID__c = '9999991234';
        cdParent.Integration_Status__c = 'Active';
        upsert cdParent;
        
        Service_Location__c childServiceLocation = new Service_Location__c(Account__c = testData.parentAccount.Id, Name = 'Child Test Loc', Location__c = testData.loc.Id);
		insert childServiceLocation;
 		test.startTest();
        Customer_Detail__c cdChild = test_setupTestData('Child', testData.loc.Id, testData.parentAccount, childServiceLocation, true);
        cdChild.Acquired_Company_Biller__c = 'IBIS';
        cdChild.Legacy_ID__c = '00000123145';
        cdChild.Parent_Customer__c = cdParent.id;
        cdChild.Market_Area__c = MARKET_AREA_NATIONAL;
        cdChild.ICC_Subscriber_ID__c = '9999991235';
        cdChild.Integration_Status__c = 'Active';
        upsert cdChild;

        cdChild.Legacy_ID__c = '00000123146';
        update cdChild;
 
        test.stopTest();
 	}  
 
    static testMethod void testChangeBillerChildCustomerDetail() {
        Mocks testData = new Mocks();
         
        
        
        Customer_Detail__c cdParent = test_setupTestData('Parent', testData.loc.Id, testData.parentAccount, testData.serviceLocation, false);
        cdParent.Market_Area__c = MARKET_AREA_NATIONAL;
        cdParent.BPID__c = '12345';
        cdParent.ICC_Subscriber_ID__c = '9999991234';
        cdParent.Integration_Status__c = 'Active';
        upsert cdParent;
        
        Service_Location__c childServiceLocation = new Service_Location__c(Account__c = testData.parentAccount.Id, Name = 'Test Loc', Location__c = testData.loc.Id);
		insert childServiceLocation;
 		test.startTest();
        Customer_Detail__c cdChild = test_setupTestData('Child', testData.loc.Id, testData.parentAccount, childServiceLocation, true);
        cdChild.Acquired_Company_Biller__c = 'IBIS';
        cdChild.Legacy_ID__c = '00000123145';
        cdChild.Parent_Customer__c = cdParent.id;
        cdChild.Market_Area__c = MARKET_AREA_NATIONAL;
        cdChild.ICC_Subscriber_ID__c = '9999991235';
        cdChild.Integration_Status__c = 'Active';
        upsert cdChild;
 
        cdChild.Acquired_Company_Biller__c = 'ICMS';
        update cdChild;
 
        test.stopTest();
 	}     
    
     static testMethod void testClearChildCustomerDetail() {
        Mocks testData = new Mocks();
                
        Customer_Detail__c cdParent = test_setupTestData('Parent', testData.loc.Id, testData.parentAccount, testData.serviceLocation, false);
        cdParent.Market_Area__c = MARKET_AREA_NATIONAL;
        cdParent.BPID__c = '12345';
        cdParent.ICC_Subscriber_ID__c = '9999991234';
        cdParent.Integration_Status__c = 'Active';
        upsert cdParent;
        
        Service_Location__c childServiceLocation = new Service_Location__c(Account__c = testData.parentAccount.Id, Name = 'Test Loc', Location__c = testData.loc.Id);
		insert childServiceLocation;
 		
        test.startTest();
        Customer_Detail__c cdChild = test_setupTestData('Child', testData.loc.Id, testData.parentAccount, childServiceLocation, true);
        cdChild.Acquired_Company_Biller__c = 'IBIS';
        cdChild.Legacy_ID__c = '00000123145';
        cdChild.Parent_Customer__c = cdParent.id;
        cdChild.Market_Area__c = MARKET_AREA_NATIONAL;
        cdChild.ICC_Subscriber_ID__c = '9999991235';
        cdChild.Integration_Status__c = 'Active';
        upsert cdChild;
 
        cdChild.Legacy_ID__c = '';
        update cdChild;
 
        test.stopTest();
 	}  
    
    
    static testMethod void testChangeParentCustomerDetail() {
        Mocks testData = new Mocks();
         
        
        
        Customer_Detail__c cdParent = test_setupTestData('Parent', testData.loc.Id, testData.parentAccount, testData.serviceLocation, false);
        cdParent.Market_Area__c = MARKET_AREA_NATIONAL;
        cdParent.BPID__c = '12345';
        cdParent.ICC_Subscriber_ID__c = '9999991234';
        cdParent.Integration_Status__c = 'Active';
        upsert cdParent;
        
        Service_Location__c childServiceLocation = new Service_Location__c(Account__c = testData.parentAccount.Id, Name = 'Test Loc', Location__c = testData.loc.Id);
		insert childServiceLocation;
 		test.startTest();
        Customer_Detail__c cdChild = test_setupTestData('Child', testData.loc.Id, testData.parentAccount, childServiceLocation, true);
        cdChild.Acquired_Company_Biller__c = 'IBIS';
        cdChild.Legacy_ID__c = '00000123145';
        cdChild.Parent_Customer__c = cdParent.id;
        cdChild.Market_Area__c = MARKET_AREA_NATIONAL;
        cdChild.ICC_Subscriber_ID__c = '9999991235';
        cdChild.Integration_Status__c = 'Active';
        upsert cdChild;
 
        cdParent.BPID__c = '12346';
        update cdParent;
        
        test.stopTest();
	}      
 
    static testMethod void testClearParentCustomerDetail() {
        Mocks testData = new Mocks();
         
        

        testData.serviceLocation.Billable__c = false;
        update testData.serviceLocation;
        
        Customer_Detail__c cdParent = test_setupTestData('Parent', testData.loc.Id, testData.parentAccount, testData.serviceLocation, false);
        cdParent.Market_Area__c = MARKET_AREA_NATIONAL;
        cdParent.BPID__c = '12345';
        cdParent.ICC_Subscriber_ID__c = '9999991234';
        cdParent.Integration_Status__c = 'Active';
        cdParent.Billable__c = false;
        upsert cdParent;
        
        Service_Location__c childServiceLocation = new Service_Location__c(Account__c = testData.parentAccount.Id, Name = 'Child', Location__c = testData.loc.Id, Billable__c = true);
		insert childServiceLocation;
 		test.startTest();
        Customer_Detail__c cdChild = test_setupTestData('Child', testData.loc.Id, testData.parentAccount, childServiceLocation, true);
        cdChild.Acquired_Company_Biller__c = 'IBIS';
        cdChild.Legacy_ID__c = '00000123145';
        cdChild.Parent_Customer__c = cdParent.id;
        cdChild.Market_Area__c = MARKET_AREA_NATIONAL;
        cdChild.ICC_Subscriber_ID__c = '9999991235';
        cdChild.Integration_Status__c = 'Active';
        upsert cdChild;
   
        cdParent.BPID__c = null;
        update cdParent;
      
        test.stopTest();
	}      
    
    private static Customer_Detail__c test_setupTestData(String cdName, Id locationId, Account a, Service_Location__c sLoc, Boolean billable){

        Customer_Detail__c cd = new Customer_Detail__c(Name = cdName
                                                       	,Billable__c = billable
    													,Customer_Main_Address__c=locationId
    													,Billing_Main_City__c='Toronto'
                                                        ,Billing_Main_Country__c = 'CA'
    													,Billing_Main_State__c='ON'
    													,Billing_Main_Street__c='200 Wellington ST @'
    													,Billing_Main_Postal_Code__c='M5V 3G2'
    													,Billing_Main_Room_Suite__c='1');
    	insert cd;
    	
    	if(a != null && cdName == 'Parent'){
	    	a.Customer_Detail__c = cd.Id;
	    	a.Phone = null;
	    	upsert a;
    	}
    	if(sLoc != null){
            sLoc.Billable__c = billable;
	    	sLoc.Customer_Detail__c = cd.Id;
	    	sLoc.Phone__c = null;
	    	update sLoc;
    	}
    	
    	return ((List<Customer_Detail__c>)ApexUtils.retrieveFullObjects(Customer_Detail__c.getsObjectType(), 'Id = \'' + cd.Id + '\''))[0];
	}
    

}