main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Customer_Detail__c/fields/Acquired_Company_Biller__c.field-meta.xml
<CustomField>
    <fullName>Acquired_Company_Biller__c</fullName>
    <description>Acquired Company or Biller from legacy system or billing system moving forward</description>
    <inlineHelpText>Acquired Company or Biller from legacy system or billing system moving forward</inlineHelpText>
    <label>Acquired Company or Biller</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ASAP</fullName>
            </value>
            <value>
                <fullName>IBIS</fullName>
            </value>
            <value>
                <fullName>ICMS</fullName>
            </value>
            <value>
                <fullName>Optic Access</fullName>
            </value>
            <value>
                <fullName>ProTel</fullName>
            </value>
            <value>
                <fullName>WCI</fullName>
            </value>
            <value>
                <fullName>Phoenix</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_City__c</fullName>
    <label>Billing Main City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Country__c</fullName>
    <label>Billing Main Country</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Name__c</fullName>
    <label>Billing Main Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Postal_Code__c</fullName>
    <label>Billing Main Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Billing_Main_Room_Suite__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Room_Suite__c</fullName>
    <label>Billing Main Room/Suite</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_State__c</fullName>
    <label>Billing Main State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Billing_Main_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Street__c</fullName>
    <label>Billing Main Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Customer_Reference__c.field-meta.xml
<CustomField>
    <fullName>Customer_Reference__c</fullName>
    <description>Used for Phoenix Interface. This is for the  customer reference information that is placed on the invoice</description>
    <label>Customer Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Customer_Detail__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pre-Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Customer_Detail__c/fields/Invoice_PLL__c.field-meta.xml
<CustomField>
    <fullName>Invoice_PLL__c</fullName>
    <description>Invoice preference for Phoenix</description>
    <label>Invoice PLL Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online PDF</fullName>
                <default>true</default>
                <label>Online PDF</label>
            </value>
            <value>
                <fullName>Online PDF + Paper</fullName>
            </value>
            <value>
                <fullName>Online PDF + Paper Pull</fullName>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
            <value>
                <fullName>G</fullName>
                <isActive>false</isActive>
                <label>G</label>
            </value>
            <value>
                <fullName>N</fullName>
                <isActive>false</isActive>
                <label>N</label>
            </value>
            <value>
                <fullName>Non-revenue</fullName>
                <isActive>false</isActive>
                <label>Non-revenue</label>
            </value>
            <value>
                <fullName>S</fullName>
                <isActive>false</isActive>
                <label>S</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Y</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <description>Preferred customer language</description>
    <inlineHelpText>Preferred customer language</inlineHelpText>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Legacy_ID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_ID__c</fullName>
    <inlineHelpText>Customer Account Number from legacy billing system</inlineHelpText>
    <label>Legacy ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Area</label>
    <referenceTo>Market_Area__c</referenceTo>
    <relationshipLabel>Customer Details</relationshipLabel>
    <relationshipName>Customer_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Market_Area__c/Market_Area__c.object-meta.xml
<CustomObject>
    <label>Market Area</label>
    <nameField>
        <label>Market Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Market_Area__c/fields/MarketAreaExternalID__c.field-meta.xml
<CustomField>
    <fullName>MarketAreaExternalID__c</fullName>
    <externalId>true</externalId>
    <label>MarketAreaExternalID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Phoenix_Account_Transaction__c/Phoenix_Account_Transaction__c.object-meta.xml
<CustomObject>
    <description>Trigger table for SFDC to Phoenix Account Creation</description>
    <label>Phoenix Account Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>Phoenix Account Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phoenix Account Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Phoenix_Account_Transaction__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Create, Update, Delete</description>
    <label>Action</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Phoenix_Account_Transaction__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Phoenix Account Transactions</relationshipLabel>
    <relationshipName>Phoenix_Account_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Phoenix_Account_Transaction__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Phoenix_Account_Transaction__c/fields/In_Queue__c.field-meta.xml
<CustomField>
    <fullName>In_Queue__c</fullName>
    <description>Y or N</description>
    <label>In Queue</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

main/default/objects/Phoenix_Account_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Pending, Sent, Completed, Error, Requeued</description>
    <label>Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/classes/Test_PhoenixTransactionController.cls
@isTest
public class Test_PhoenixTransactionController {
    
    static testMethod void testNewCreateTransaction() {
        Mocks testData = new Mocks(); 
        //Market_Area__c ma = new Market_Area__c();
        //ma.Name = 'National';
        //ma.MarketAreaExternalID__c = '36';
        //insert ma;
                
        Phoenix_Account_Transaction__c pat = new Phoenix_Account_Transaction__c();
        pat.Customer_Detail__c = testData.customerDetail.Id;
        pat.In_Queue__c = 'Y';
        pat.Status__c = 'In Queue';
        pat.Action__c = 'Create';
        insert pat;
        test.startTest();
        Customer_Detail__c cdChild = new Customer_Detail__c(Name = 'Test CD'
                                                        ,Billing_Main_City__c='Toronto'
                                                        ,Billing_Main_Country__c = 'CA'
                                                        ,Billing_Main_State__c='ON'
                                                        ,Billing_Main_Street__c='200 Wellington ST @'
                                                        ,Billing_Main_Postal_Code__c='M5V 3G2'
                                                        ,Billing_Main_Room_Suite__c='1');
        cdChild.Acquired_Company_Biller__c = 'IBIS';
        cdChild.Legacy_ID__c = '00000123145';
        cdChild.Language_Preference__c = 'English';
        cdChild.Invoice_PLL__c = 'Online PDF';
        cdChild.Customer_Reference__c = '';
        cdChild.Billable__c = true;
        cdChild.Market_Area__c = [SELECT ID FROM Market_Area__c where Name='National'].Id;
        cdChild.Integration_Status__c = 'Active';
        insert cdChild;
        
        cdChild.ICC_Subscriber_ID__c = '9999991235';
        cdChild.Legacy_ID__c = '00000123146';
        update cdChild;
 
        test.stopTest();
    }  
    
    static testMethod void testNewUpdateTransaction() {
        Mocks testData = new Mocks(); 
        //Market_Area__c ma = new Market_Area__c();
        //ma.Name = 'National';
        //ma.MarketAreaExternalID__c = '36';
        //insert ma;

        
        Customer_Detail__c cdChild = new Customer_Detail__c(Name = 'Test CD'
                                                        ,Billing_Main_City__c='Toronto'
                                                        ,Billing_Main_Country__c = 'CA'
                                                        ,Billing_Main_State__c='ON'
                                                        ,Billing_Main_Street__c='200 Wellington ST @'
                                                        ,Billing_Main_Postal_Code__c='M5V 3G2'
                                                        ,Billing_Main_Room_Suite__c='1');
        cdChild.Acquired_Company_Biller__c = 'IBIS';
        cdChild.Legacy_ID__c = '00000123145';
        cdChild.Language_Preference__c = 'English';
        cdChild.Invoice_PLL__c = 'Online PDF';
        cdChild.Customer_Reference__c = '';
        cdChild.Billable__c = true;
        cdChild.Market_Area__c = [SELECT ID FROM Market_Area__c where Name='National'].Id;
        cdChild.ICC_Subscriber_ID__c = '9999991235';
        cdChild.Integration_Status__c = 'Active';
        insert cdChild;
        Phoenix_Account_Transaction__c pat = new Phoenix_Account_Transaction__c();
        pat.Customer_Detail__c = cdChild.Id;
        pat.In_Queue__c = 'N';
        pat.Status__c = 'Success';
        pat.Action__c = 'Create';
        insert pat;
        
        test.startTest();
        cdChild.Legacy_ID__c = '00000123146';
        cdChild.Language_Preference__c = 'French';
        cdChild.Invoice_PLL__c = 'Online PDF + Paper';
        cdChild.Customer_Reference__c = 'Test';
        cdChild.Billing_Main_City__c='Markham';
        cdChild.Billing_Main_Country__c = 'US';
        cdChild.Billing_Main_State__c='AB';
        cdChild.Billing_Main_Street__c='100 Wellington ST';
        cdChild.Billing_Main_Postal_Code__c='N5V 3G2';
        cdChild.Billing_Main_Room_Suite__c='100';
        cdChild.Billing_Main_Name__c = 'Hello';
        cdChild.CurrencyIsoCode = 'USD';
        update cdChild;
 
        test.stopTest();
    }  
    
    static testMethod void testNewCreateTransactionAfterInitialCreateFailed() {
        Mocks testData = new Mocks(); 
        //Market_Area__c ma = new Market_Area__c();
        //ma.Name = 'National';
        //ma.MarketAreaExternalID__c = '36';
        //insert ma;
		
        
        Customer_Detail__c cdChild = new Customer_Detail__c(Name = 'Test CD'
                                                        ,Billing_Main_City__c='Toronto'
                                                        ,Billing_Main_Country__c = 'CA'
                                                        ,Billing_Main_State__c='ON'
                                                        ,Billing_Main_Street__c='200 Wellington ST @'
                                                        ,Billing_Main_Postal_Code__c='M5V 3G2'
                                                        ,Billing_Main_Room_Suite__c='1');
        cdChild.Acquired_Company_Biller__c = 'IBIS';
        cdChild.Legacy_ID__c = '00000123145';
        cdChild.Language_Preference__c = 'English';
        cdChild.Invoice_PLL__c = 'Online PDF';
        cdChild.Customer_Reference__c = '';
        cdChild.Billable__c = true;
        cdChild.Market_Area__c = [SELECT ID FROM Market_Area__c where Name='National'].Id;
        cdChild.ICC_Subscriber_ID__c = '9999991235';
        cdChild.Integration_Status__c = 'Active';
        insert cdChild;
        Phoenix_Account_Transaction__c pat = new Phoenix_Account_Transaction__c();
        pat.Customer_Detail__c = cdChild.Id;
        pat.In_Queue__c = 'N';
        pat.Status__c = 'Failed';
        pat.Action__c = 'Create';
        insert pat;
        
        test.startTest();
        cdChild.Legacy_ID__c = '00000123146';
        cdChild.Language_Preference__c = 'French';
        cdChild.Invoice_PLL__c = 'Online PDF + Paper';
        cdChild.Customer_Reference__c = 'Test';
        cdChild.Billing_Main_City__c='Markham';
        cdChild.Billing_Main_Country__c = 'US';
        cdChild.Billing_Main_State__c='AB';
        cdChild.Billing_Main_Street__c='100 Wellington ST';
        cdChild.Billing_Main_Postal_Code__c='N5V 3G2';
        cdChild.Billing_Main_Room_Suite__c='100';
        cdChild.Billing_Main_Name__c = 'Hello';
        cdChild.CurrencyIsoCode = 'USD';
        update cdChild;
 
        test.stopTest();
    }  
   

}