main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Customer_Detail__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pre-Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

classes/Test_IntegrationEndpoint.cls
@isTest
public with sharing class Test_IntegrationEndpoint extends TestUtils.TestClass {

    static testMethod void testUpdateSubscribers() {
		// create test data
        Mocks testData = new Mocks();
    	
    	Customer_Detail__c cd = new Customer_Detail__c(ICC_Subscriber_ID__c='-9999', Integration_Status__c='Active');
    	insert cd;
    	
		Account a = testData.parentAccount;
		a.Customer_Detail__c = cd.Id;
		update a;
		
		Service_Location__c sLoc = new Service_Location__c(Account__c = a.Id, Name = 'Test Loc', Customer_Detail__c=cd.Id, Location__c = testData.loc.Id);
		insert sLoc; 
		
		test.startTest();
		
    	IntegrationEndpoint.SubscriberUpdate u = new IntegrationEndpoint.SubscriberUpdate();
    	u.SubscriberID = '-9999';
    	u.Status = 'Inactive';
    	IntegrationEndpoint.UpdateSubscribers(new List<IntegrationEndpoint.SubscriberUpdate>{u});
    }
	
	static testMethod void testGetOrderReindexingOpportunitiesBySubscriberID(){
		// create test data
        Mocks testData = new Mocks();
    	
    	Customer_Detail__c cd = new Customer_Detail__c(ICC_Subscriber_ID__c='-9999', Integration_Status__c='Active');
    	insert cd;
    	
		Account a = testData.parentAccount;
		a.Customer_Detail__c = cd.Id;
		update a;
		
		Service_Location__c sLoc = new Service_Location__c(Account__c = a.Id, Name = 'Test Loc', Customer_Detail__c=cd.Id, Location__c = testData.loc.Id);
		insert sLoc; 
		
		test.startTest();
		
    	IntegrationEndpoint.GetOrderReindexingOpportunitiesBySubscriberID(new List<String>{'-9999'});
	}
	
	static testMethod void testGetServingBuildings(){
		IntegrationEndpoint.GetServingBuildings();
	}
}