main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Legacy_ID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_ID__c</fullName>
    <inlineHelpText>Customer Account Number from legacy billing system</inlineHelpText>
    <label>Legacy ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <description>To leverage account security on this object, we set the parent account of this object to the root of the hierarchy associated with it OR a system account if it is detached.</description>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Customer Details</relationshipLabel>
    <relationshipName>Child_Customer_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An explicit account lookup that should only be used if the order is not opportunity driven.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account-based Orders</relationshipLabel>
    <relationshipName>Account_Based_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Contract_Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Cancel_Date__c</fullName>
    <label>Contract Cancel Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Order__c/fields/Contract_Cancel_Reason__c.field-meta.xml
<CustomField>
    <fullName>Contract_Cancel_Reason__c</fullName>
    <label>Contract Cancel Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Consolidation/Downsize</fullName>
            </value>
            <value>
                <fullName>Competitive Loss</fullName>
            </value>
            <value>
                <fullName>Contract Renewals</fullName>
            </value>
            <value>
                <fullName>Feature Change</fullName>
            </value>
            <value>
                <fullName>Internal Clean Up</fullName>
            </value>
            <value>
                <fullName>Moves</fullName>
            </value>
            <value>
                <fullName>Non Payment</fullName>
            </value>
            <value>
                <fullName>Service Conversions</fullName>
            </value>
            <value>
                <fullName>Service Downgrades</fullName>
            </value>
            <value>
                <fullName>Temporary Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/Contract_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_ID__c</fullName>
    <label>Contract ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Actual Install</fullName>
            </value>
            <value>
                <fullName>Actual Churn</fullName>
            </value>
            <value>
                <fullName>Anticipated Install</fullName>
            </value>
            <value>
                <fullName>Anticipated Churn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>IF(ISBLANK(Account__c), Opportunity__r.Account.Customer_Detail__r.ICC_Subscriber_ID__c, Account__r.Customer_Detail__r.ICC_Subscriber_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

main/default/objects/Order__c/fields/New_Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>New_Contract_End_Date__c</fullName>
    <description>For Contract Renewal Orders</description>
    <label>New Contract End Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/New_Contract_MRC__c.field-meta.xml
<CustomField>
    <fullName>New_Contract_MRC__c</fullName>
    <label>New Contract MRC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Order__c/fields/New_Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>New_Contract_Start_Date__c</fullName>
    <description>For Contract Renewal Orders</description>
    <label>New Contract Start Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Order__c/fields/Old_Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Old_Contract_End_Date__c</fullName>
    <description>For Contract Renewal Orders</description>
    <label>Old Contract End Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/Old_Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Old_Contract_Start_Date__c</fullName>
    <label>Old Contract Start Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/Order_Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Completion_Status__c</fullName>
    <label>Order Completion Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Scoping</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>In Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/Order_ID_for_Install_Contract__c.field-meta.xml
<CustomField>
    <fullName>Order_ID_for_Install_Contract__c</fullName>
    <description>For Contract Renewal reporting</description>
    <label>Order ID for Install Contract</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/Original_Contract_MRC__c.field-meta.xml
<CustomField>
    <fullName>Original_Contract_MRC__c</fullName>
    <description>For Contract Renewal Orders</description>
    <label>Original Contract MRC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Order__c/fields/SPC_Product__c.field-meta.xml
<CustomField>
    <fullName>SPC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Contract Renewal Orders</description>
    <label>SPC Product</label>
    <referenceTo>SPC_Product__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order__c/recordTypes/Contract_Renewal.recordType-meta.xml
<RecordType>
    <fullName>Contract_Renewal</fullName>
    <active>true</active>
    <label>Contract Renewal</label>
</RecordType>

objects/SPC_Product__c/SPC_Product__c.object-meta.xml
<CustomObject>
    <label>SPC Product</label>
    <nameField>
        <label>SPC Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ImportDataFromCSVController.cls
public with sharing class ImportDataFromCSVController {
    public Blob csvFileBody{get;set;}
    public String[] orderDataLines {get;set;}
    public List <Order__c> lstOrders {get;set;}
    public Map<String, Order__c> mapOrders{get; set;}
    public boolean readSuccess {get;set;}
    public List<SelectOption> currencies {get; set;}
    public String selectedCurrency {get; set;}    
    public String selectedFileType {get; set;}    
    public Integer numOfRenewal {get; set;}  

    Order__c ordObj;
    String orderDataAsString;
    String fieldValue;
    Integer fieldNumber;
    Map < String, Integer > fieldNumberMap = new Map < String, Integer > ();
    Map<String, String> columnMap = new Map<String, String>{'CUSTNO'=>'Account__c', 'CONTRACT'=>'Contract_ID__c'
                                                            ,'CTR_START'=>'Old_Contract_Start_Date__c' ,'CTR_END'=>'Old_Contract_End_Date__c'
                                                            ,'CTR_PRICE'=>'Original_Contract_MRC__c','NEXT_START'=>'New_Contract_Start_Date__c'
                                                             ,'NEXT_END'=>'New_Contract_End_Date__c','NEXT_PRICE'=>'New_Contract_MRC__c'};

    Map<String, String> churnColumnMap = new Map<String, String>{'CUSTNO'=>'Account__c', 'CONTRACT'=>'Contract_ID__c'
                                                            ,'CURRENTSTARTDATE'=>'Old_Contract_Start_Date__c' ,'CURRENTENDDATE'=>'Old_Contract_End_Date__c'
                                                            ,'MRR'=>'Original_Contract_MRC__c','CURRENTCANCELDATE'=>'Contract_Cancel_Date__c'
                                                             ,'CANCELLATIONDESCRIPTION' =>'Contract_Cancel_Reason__c'};

    Map<String, String> installColumnMap = new Map<String, String>{'CUSTNBR'=>'Account__c', 'CONTRACT'=>'Contract_ID__c', 'ORDER'=>'Order_ID_for_Install_Contract__c'
                                                            ,'CTR_START'=>'New_Contract_Start_Date__c' ,'CTR_END'=>'New_Contract_End_Date__c'
                                                            ,'MRR'=>'New_Contract_MRC__c' };
                                                                 
    List<String> dateFields = new List<String>{'Old_Contract_Start_Date__c','Old_Contract_End_Date__c','New_Contract_Start_Date__c','New_Contract_End_Date__c','Contract_Cancel_Date__c'};   
    List<String> currencyFields = new List<String>{'Original_Contract_MRC__c','New_Contract_MRC__c'};   
    public ImportDataFromCSVController() {
        readSuccess = FALSE;
        orderDataLines = new String[] {};
        lstOrders = new List <Order__c> ();
        mapOrders = new Map<String, Order__c>();
        numOfRenewal=0;
        currencies = new List<SelectOption>();
        List<CurrencyType> currencyTypes = [select ISOCode, ConversionRate, DecimalPlaces from CurrencyType where IsActive=TRUE];
        for (CurrencyType ct : [select ISOCode, ConversionRate, DecimalPlaces from CurrencyType where IsActive=TRUE]) {
            currencies.add(new SelectOption(ct.ISOCode, ct.ISOCode));
        }
    }
    public PageReference  readFromFile(){
        try{
            orderDataAsString = csvFileBody.toString();
            readCSVFile();            
        }
        catch(exception e){
            readSuccess = FALSE;
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR,'Error reading CSV file :'+e.getMessage());
            ApexPages.addMessage(errorMessage);
        } 
        return null;                   
    }    
    
    public void readCSVFile() {
        lstOrders.clear();
        mapOrders = new Map<String, Order__c>();
        numOfRenewal = 0;
        Set<String> legacyIdSet = new Set<String>();
        Map<String, Id> accountIdMap = new Map<String, Id>();
        orderDataLines = orderDataAsString.split('\n');
        string[] csvFieldNames = orderDataLines[0].split(',');
        String objFieldName = '';
        Set<String> orderIdSet = new Set<String>();

        for (Integer i = 0; i < csvFieldNames.size(); i++) {
        //there are different columns for the different files
            if(selectedFileType.contains('Churn')){
                objFieldName =churnColumnMap.get(csvFieldNames[i].trim());
            }else if(selectedFileType.contains('Install')){
                objFieldName =installColumnMap.get(csvFieldNames[i].trim());
            }else{
                objFieldName =columnMap.get(csvFieldNames[i].trim());           
            }

            if(objFieldName != null || csvFieldNames[i].trim() =='RENEWAL_STATUS'){
                fieldNumberMap.put(objFieldName, i);
                 if(csvFieldNames[i].trim() =='RENEWAL_STATUS'){
                    fieldNumberMap.put(csvFieldNames[i].trim(), i);
                 }

            }
        }

        Id ctrRewRtID = Schema.SObjectType.Order__c.getRecordTypeInfosByDeveloperName().get('Contract_Renewal').getRecordTypeId();
        Integer rowCount = 0;
        for (Integer i = 1; i < orderDataLines.size(); i++) {                      
            string[] csvRecordData = orderDataLines[i].split(',');
            Boolean isRenewStatus = true;

             if(csvRecordData[0] != null && csvRecordData[0] != ''){
                ordObj = new Order__c();
                ordObj.RecordTypeId = ctrRewRtID;
                ordObj.SPC_Product__c = 'a2DC0000000TwPiMAK';
                ordObj.CurrencyIsoCode  = selectedCurrency;
                ordObj.Contract_Status__c= selectedFileType;
                if(selectedFileType != 'Renewal'){
                    ordObj.Order_Completion_Status__c = 'Complete';
                }else{
                    ordObj.Contract_Cancel_Reason__c = 'Contract Renewals';
                }
    
                String ordFieldName = '';
                
                for (String fieldName: csvFieldNames) { 
                    if(selectedFileType != 'Renewal' && fieldName == 'RENEWAL_STATUS'){
                        fieldNumber = fieldNumberMap.get(fieldName.trim());
                        fieldValue = csvRecordData[fieldNumber];
                        if(fieldValue != 'Renewed'){
                           isRenewStatus = false;
                           break;
                        }
                    }                 

                   if(selectedFileType.contains('Churn')){
                       ordFieldName =churnColumnMap.get(fieldName.trim());
                   }else if(selectedFileType.contains('Install')){
                       ordFieldName =installColumnMap.get(fieldName.trim());
                   }else{
                       ordFieldName =columnMap.get(fieldName.trim());           
                   }        

                    if(ordFieldName  != null){
                        fieldNumber = fieldNumberMap.get(ordFieldName);
                        fieldValue = csvRecordData[fieldNumber];

                        if(dateFields.contains(ordFieldName)){
                           Date x = null;
                           if(fieldValue != null &&  fieldValue.trim().length()>0 ){
                              x = Date.valueOf(fieldValue.trim());
                           }
                            ordObj.put(ordFieldName , x);
                        }else if(currencyFields.contains(ordFieldName)){
                            ordObj.put(ordFieldName ,Decimal.valueOf(fieldValue==null||fieldValue.trim()==''?'0':fieldValue.trim()) );                  
                        }else{
                            if(ordFieldName =='Account__c'){
                               legacyIdSet.add(fieldValue.trim());
                            }else if(ordFieldName =='Order_ID_for_Install_Contract__c'){
                               orderIdSet.add(fieldValue.trim());
                            }
                            ordObj.put(ordFieldName , fieldValue.trim());
                        }
                        
                     }
                }
            
                if((selectedFileType =='Renewal' && isRenewStatus ) || selectedFileType.contains('Churn') ||selectedFileType == 'Actual Install'){
                    mapOrders.put(ordObj.Contract_ID__c, ordObj);
                }else if(selectedFileType == 'Anticipated Install'){
                    mapOrders.put(ordObj.Order_ID_for_Install_Contract__c, ordObj); 
                }
              }          
        }
        numOfRenewal = mapOrders.size();
        //search whether there are the same contract Id within the same quarter of the same year. 
        List<Order__c> sameContractOrders = getSameContractOrders(ctrRewRtID , mapOrders.keyset(), selectedFileType );

        for(Order__c dupOrder : sameContractOrders){
            if(selectedFileType == 'Anticipated Install'){
                mapOrders.remove(dupOrder.Order_ID_for_Install_Contract__c);
            }else{
                mapOrders.remove(dupOrder.Contract_ID__c);
            }
        }
        
        //check whether there are anticipated churns/installs for the same contract #
        if(selectedFileType == 'Actual Install'){
            List<Order__c> antiOrders = getAnticipatedOrdersForSameContract(ctrRewRtID , orderIdSet, selectedFileType );

            for(Order__c antiOrder : antiOrders){
               for(Order__c actualOrder :mapOrders.values()){
                   if(actualOrder.Order_ID_for_Install_Contract__c == antiOrder.Order_ID_for_Install_Contract__c){
                       actualOrder.Id =  antiOrder.Id;
                       break;
                   }
               }
            }        
        }else if(selectedFileType == 'Actual Churn'){
            List<Order__c> antiOrders = getAnticipatedOrdersForSameContract(ctrRewRtID , mapOrders.keyset(), selectedFileType );

            Order__c actualOrder = new Order__c();
            for(Order__c antiOrder : antiOrders){
                actualOrder = mapOrders.get(antiOrder.Contract_ID__c);
                actualOrder.Id =  antiOrder.Id;
            }        
        }

        
        lstOrders = mapOrders.values();
        if(lstOrders.size() > 0){
            if(selectedCurrency == 'CAD'){
                for(Customer_Detail__c cd :[Select Legacy_Id__c, Parent_Account__c from Customer_Detail__c where Legacy_Id__c in :legacyIdSet]){
                    accountIdMap.put(cd.Legacy_Id__c, cd.Parent_Account__c);
                }
            }else{
                for(Customer_Detail__c cd :[Select ICC_Subscriber_ID__c, Parent_Account__c from Customer_Detail__c where ICC_Subscriber_ID__c in :legacyIdSet]){
                    accountIdMap.put(cd.ICC_Subscriber_ID__c, cd.Parent_Account__c);
                }                
            }
            
            for(Order__c o :lstOrders){
                 o.Account__c = accountIdMap.get(o.Account__c);
            }
            readSuccess = TRUE;
        } 
  }
   
  
  private List<Order__c> getSameContractOrders(Id reportyTypeId, Set<String> contractIds, String contractStatus) {
        Date today = Date.today();
        Integer q;
        
        if(today.month() != 3 && today.month() != 6 && today.month() != 9 && today.month() != 12){
            q = math.round((today.month())/3)*3;
        }else{
            q = math.round((today.month()-1)/3)*3;
        }
        Integer minQ = q + 1;
        Integer maxQ = q + 3;
        
        List<Order__c> sameOrders;
        if(contractStatus == 'Anticipated Install'){
           sameOrders=  [Select Id, Name, Contract_ID__c, createdDate, Order_ID_for_Install_Contract__c from Order__c where CALENDAR_YEAR(createdDate) = :today.year()
                and CALENDAR_MONTH(createdDate) >= :minQ and CALENDAR_MONTH(createdDate) <= :maxQ and RecordTypeId =:reportyTypeId
                and Order_ID_for_Install_Contract__c in :contractIds and Contract_Status__c = :contractStatus];

        }else{
           sameOrders= [Select Id, Name, Contract_ID__c, createdDate, Order_ID_for_Install_Contract__c from Order__c where CALENDAR_YEAR(createdDate) = :today.year()
                and CALENDAR_MONTH(createdDate) >= :minQ and CALENDAR_MONTH(createdDate) <= :maxQ and RecordTypeId =:reportyTypeId
                and Contract_ID__c in :contractIds and Contract_Status__c = :contractStatus];

        }
        
        return sameOrders;
  
  }
  
  private List<Order__c> getAnticipatedOrdersForSameContract(Id reportyTypeId, Set<String> contractIds, String contractStatus) {
        Date today = Date.today();
        Integer q;
        
        if(today.month() != 3 && today.month() != 6 && today.month() != 9 && today.month() != 12){
            q = math.round((today.month())/3)*3;
        }else{
            q = math.round((today.month()-1)/3)*3;
        }
        Integer minQ = q + 1;
        Integer maxQ = q + 3;
        
        String antiContractStatus;
        List<Order__c> antiOrders ;
        if(contractStatus == 'Actual Install'){
           antiContractStatus = 'Anticipated Install';
           antiOrders =   [Select Id, Name, Contract_ID__c, createdDate, Order_ID_for_Install_Contract__c from Order__c where CALENDAR_YEAR(createdDate) = :today.year()
                and CALENDAR_MONTH(createdDate) >= :minQ and CALENDAR_MONTH(createdDate) <= :maxQ and RecordTypeId =:reportyTypeId
                and Order_ID_for_Install_Contract__c in :contractIds and Contract_Status__c = :antiContractStatus];
           
           
        }else if(contractStatus == 'Actual Churn'){
           antiContractStatus = 'Anticipated Churn';    
           antiOrders =   [Select Id, Name, Contract_ID__c, createdDate, Order_ID_for_Install_Contract__c from Order__c where CALENDAR_YEAR(createdDate) = :today.year()
                and CALENDAR_MONTH(createdDate) >= :minQ and CALENDAR_MONTH(createdDate) <= :maxQ and RecordTypeId =:reportyTypeId
                and Contract_ID__c in :contractIds and Contract_Status__c = :antiContractStatus];

        }
        return antiOrders ;  
  }
  
 
  public void saveData() {
    try {
        Database.UpsertResult[] srList = Database.Upsert(lstOrders, false);  
      ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.INFO, lstOrders.size() +' Contract Renewal type Order records inserted successfully');
      ApexPages.addMessage(errorMessage);
      lstOrders.clear();
    } catch (Exception e) {
      ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR, 'An error has occured while saving data');
      ApexPages.addMessage(errorMessage);
    }
          readSuccess = FALSE;
          numOfRenewal =0;
  }
}