main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Locations within (related to) the Building object</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An explicit account lookup that should only be used if the order is not opportunity driven.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account-based Orders</relationshipLabel>
    <relationshipName>Account_Based_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <formula>IF(NOT(ISBLANK(Opportunity__r.Account.Id)), Opportunity__r.Account.Name, Account__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AccountName</label>
    <type>Text</type>
</CustomField>

main/default/objects/Order__c/fields/Customer_Requested_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Requested_Due_Date__c</fullName>
    <formula>Opportunity__r.Customer_Requested_Due_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Requested Due Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>IF(ISBLANK(Account__c), Opportunity__r.Account.Customer_Detail__r.ICC_Subscriber_ID__c, Account__r.Customer_Detail__r.ICC_Subscriber_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Build Location</description>
    <inlineHelpText>Build Location</inlineHelpText>
    <label>Location</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Order__c/recordTypes/Opportunity_Order.recordType-meta.xml
<RecordType>
    <fullName>Opportunity_Order</fullName>
    <active>true</active>
    <label>Opportunity Order</label>
</RecordType>

main/default/objects/Order_Property__c/Order_Property__c.object-meta.xml
<CustomObject>
    <label>Order Property</label>
    <nameField>
        <label>Order Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Order_Property__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Properties</relationshipLabel>
    <relationshipName>Order_Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Order_Property__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Order Properties</relationshipLabel>
    <relationshipName>Order_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Order_Property__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Install</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>iCert</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order_Property__c/recordTypes/External_Order.recordType-meta.xml
<RecordType>
    <fullName>External_Order</fullName>
    <active>true</active>
    <label>External Order</label>
</RecordType>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

objects/Service_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/Sub_Order__c.object-meta.xml
<CustomObject>
    <label>Sub-Order</label>
    <nameField>
        <label>Sub-Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Sub_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Order__r.Account_Link__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Service_Location__r.Location__r.Name</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

objects/Sub_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Sub_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Sub_Order__c/fields/Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Location</label>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Sub-Orders</relationshipLabel>
    <relationshipName>Sub_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sub_Order__c/fields/Workplan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Start_Date__c</fullName>
    <label>Workplan Start Date</label>
    <type>Date</type>
</CustomField>

main/default/classes/Test_OrderManagement.cls
@isTest
public with sharing class Test_OrderManagement extends TestUtils.TestClass {
    
    static testmethod void testController(){
        getTestData();
        
        test.startTest();
        
        PageReference pageReference = Page.OrderManagement;
        pageReference.getParameters().put('accountId', a.Id);
        test.setCurrentPage(pageReference);
        
        OrderManagementController om = new OrderManagementController();
        om.GetICCOrders();
        om.SelectedICCOrderIds = '[]';
        om.PrepareConfigurationPage();
        om.subOrderConfig.Workplan_Start_Date__c = Date.today();
        om.Save();
        om.SaveModifiedSubOrders();
        
        String str = om.EditedICCTempIds;
        str = om.ModifiedTempIds;
        str = om.SelectedICCOrderIds;
        
        OrderManagementController.OppDisplay oppDisp = new OrderManagementController.OppDisplay();
        oppDisp = new OrderManagementController.OppDisplay(null);
        oppDisp = new OrderManagementController.OppDisplay(new Opportunity(Name='Test'));
        
        System.debug(om.hasWorkstepCreate);
        om.hasWorkstepCreate = true;
        System.debug(om.getTestClass());
    }
    
    static testmethod void testOrder(){
        getTestData();
        
        RecordType rt = [select Id from RecordType where SobjectType = 'Opportunity' and Name = 'Retail'];
        Opportunity opp = new Opportunity(AccountId = a.Id
                                            ,Name = 'Test Opp'
                                            ,RecordTypeId = rt.Id
                                            ,StageName = OpportunityUtils.STAGE_QUALIFIED
                                            ,Type = 'Existing'
                                            ,Oppty_Sub_Type__c='Renewal'
                                            ,CloseDate = Date.today().addDays(30)
                                            ,Customer_Requested_Due_Date__c = Date.today());
        insert opp;
        
        rt = [select Id from RecordType where SobjectType = 'Order__c' and DeveloperName = 'Opportunity_Order'];
        ord = new Order__c(Opportunity__c = opp.Id, RecordTypeId = rt.Id);
        insert ord;
        ord = [select Id, Name, AccountName__c from Order__c where Id =: ord.Id];
        
        rt = [select Id from RecordType where SobjectType = 'Order_Property__c' and DeveloperName = 'External_Order'];
        Order_Property__c op = new Order_Property__c(Order__c = ord.Id, External_ID__c = '1234', RecordTypeId = rt.Id, Type__c = 'Install');
        insert op;
        
        subOrd = new Sub_Order__c(Order__c = ord.Id, Service_Location__c = sLoc.Id, Customer_Detail__c = cd.Id);
        insert subOrd;
        
        test.startTest();
        
        PageReference pageReference = Page.OrderManagement;
        pageReference.getParameters().put('orderId', ord.Name);
        test.setCurrentPage(pageReference);
        
        OrderManagementController om = new OrderManagementController();
        om.GetICCOrders();
        
        om.EditedICCTempIds = om.ModifiedTempIds = '["' + om.subOrderDisplay[0].tempId + '"]';
        om.SelectedOrderId = ord.Id;
        om.UpdateSelectedOrder();
        om.EditSubOrders();
        
        om.selectedOrderInfo.Order = ord;
        om.Save();
        om.SaveModifiedSubOrders();
         
        //Hit some config code
        om.getOrderProperties(ord.Id);
        
        OrderManagementController.OrderConfigurator oc = new OrderManagementController.OrderConfigurator();
        om.orderDisplay[0].compareTo(om.orderDisplay[0]);
        om.subOrderDisplay[0].compareTo(om.subOrderDisplay[0]);
    }
    
    private static Mocks testData = null;
    private static Customer_Detail__c cd = null;
    private static Account a = null;
    private static Service_Location__c sLoc = null;
    private static Order__c ord = null;
    private static Sub_Order__c subOrd = null;
    private static void getTestData(){
        testData = new Mocks();
        
        cd = new Customer_Detail__c(ICC_Subscriber_ID__c='12345');
        insert cd;
        
        a = new Account(Name = 'testAccount'
                        ,Customer_Detail__c = cd.Id
                        ,ShippingCountry = 'US'
                        ,ShippingStreet = '1234 Someplace ST'
                        ,ShippingCity = 'Nowhere'
                        ,ShippingState = 'WA'
                        ,ShippingPostalCode = '54321'
                        ,Phone = '800-123-1234'
                        ,Industry = 'Z - Unclassified');
        insert a;
        
        sLoc = new Service_Location__c(Account__c = a.Id
                                        ,Customer_Detail__c = cd.Id
                                        ,Location__c = testData.loc.Id);
        insert sLoc;
    }
    
    /*public static integraWS.SFOrderView getSubOrderSummaryBySubscriberID(Integer subscriberID){
        integraWS.SFOrderView o = new integraWS.SFOrderView();
        o.OrderProperties = new integraWS.ArrayOfSFOrderPropertyView();
        o.OrderProperties.SFOrderPropertyView = new List<integraWS.SFOrderPropertyView>();
        
        o.SubOrders = new integraWS.ArrayOfSFSubOrderView();
        o.SubOrders.SFSubOrderView = new List<integraWS.SFSubOrderView>();
        
        o.OrderProperties.SFOrderPropertyView.add(getMockProp(subscriberID, 1, 'Install Order'));
        o.SubOrders.SFSubOrderView.add(getMockSO(subscriberID, 1, o.OrderProperties.SFOrderPropertyView.get(o.OrderProperties.SFOrderPropertyView.size() - 1).ExternalID));
        
        return o;
    }*/
    
    public static integraWS.ArrayOfSFOrderPropertyView getSubOrderListBySubscriberID(Integer subscriberID){
        integraWS.ArrayOfSFOrderPropertyView op = new integraWS.ArrayOfSFOrderPropertyView();
        op.SFOrderPropertyView = new List<integraWS.SFOrderPropertyView>();
        op.SFOrderPropertyView.add(getMockProp(subscriberID, 1, 'Install Order'));
        return op;
    } 
    
    public static integraWS.SFOrderView getSubOrderSummaryByOrderIds(List<Integer> orderIDs, Integer subscriberID){
        
        integraWS.SFOrderView o = new integraWS.SFOrderView();
        o.OrderProperties = new integraWS.ArrayOfSFOrderPropertyView();
        o.OrderProperties.SFOrderPropertyView = new List<integraWS.SFOrderPropertyView>();
        
        o.SubOrders = new integraWS.ArrayOfSFSubOrderView();
        o.SubOrders.SFSubOrderView = new List<integraWS.SFSubOrderView>();
        
        o.OrderProperties.SFOrderPropertyView.add(getMockProp(subscriberID, 1, 'Install Order'));
        integraWS.SFSubOrderView sov = getMockSO(subscriberID, 1, o.OrderProperties.SFOrderPropertyView.get(o.OrderProperties.SFOrderPropertyView.size() - 1).ExternalID);
        if(subOrd != null) sov.SalesforceID = subOrd.Id;
        o.SubOrders.SFSubOrderView.add(sov);
        
        sov = getMockSO(subscriberID, 2, o.OrderProperties.SFOrderPropertyView.get(o.OrderProperties.SFOrderPropertyView.size() - 1).ExternalID);
        o.SubOrders.SFSubOrderView.add(sov);
        
        return o;
        
        /*integraWS.SFOrderView o = new integraWS.SFOrderView();
        return o;*/
    }
    
    private static integraWS.SFOrderPropertyView getMockProp(Integer subscriberID, Integer offset, String typeName){
        integraWS.SFOrderPropertyView p = new integraWS.SFOrderPropertyView();
        p.ExternalID = subscriberID + offset;
        p.OrderType = typeName;
        return p;
    }
    
    private static integraWS.SFSubOrderView getMockSO(Integer subscriberID, Integer offset, Integer propExternalID){
        integraWS.SFSubOrderView so = new integraWS.SFSubOrderView();
        so.OrderPropertyExternalOrderID = propExternalID;
        so.SPCProductID = 185;
        so.SubscriberID = subscriberID;
        so.Groups = new integraWS.ArrayOfSFSubOrderGroupView();
        so.Groups.SFSubOrderGroupView = new List<integraWS.SFSubOrderGroupView>();
        
        integraWS.SFSubOrderGroupView g = new integraWS.SFSubOrderGroupView();
        g.ExternalID = propExternalID + offset;
        g.Status = 'In Progress';
        g.Quantity = 3;
        g.ProductDescription = 'Test Product';
        g.MRC = 1000000;
        so.Groups.SFSubOrderGroupView.add(g);
        
        return so;
    }
}