main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>custom object for tracking network expense, parallel to Netx__c in legacy Zayo.</description>
    <label>Allstream Expense</label>
    <nameField>
        <displayFormat>ZEX-{0000}</displayFormat>
        <label>Zayo Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allstream Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Expense__c/fields/Business_Unit_Owner__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Owner__c</fullName>
    <description>OVS is added for transferring to Onvoy, as is ZEN. It should not show up on any record types. TTN-0000780304, TTN-0000955387.</description>
    <label>Business Unit Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Allstream_SMB</fullName>
                <default>true</default>
                <label>Allstream_SMB</label>
            </value>
            <value>
                <fullName>ZG</fullName>
            </value>
            <value>
                <fullName>ZC</fullName>
            </value>
            <value>
                <fullName>INTL</fullName>
            </value>
            <value>
                <fullName>INTL-GEO</fullName>
            </value>
            <value>
                <fullName>INTL-FibreSpeed</fullName>
            </value>
            <value>
                <fullName>ZB</fullName>
            </value>
            <value>
                <fullName>ZFS</fullName>
            </value>
            <value>
                <fullName>INTL-FR</fullName>
            </value>
            <value>
                <fullName>OVS</fullName>
            </value>
            <value>
                <fullName>ZEN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Expense__c/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <label>CurrencyCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

main/default/objects/Expense__c/fields/Escalation_Type__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Type__c</fullName>
    <label>Escalation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Schedule</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>CPI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Expense__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>Expense</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Expense__c/fields/Netex_Service__c.field-meta.xml
<CustomField>
    <fullName>Netex_Service__c</fullName>
    <description>Before adding or renaming any entries, check with the TEOCO integration team (currently Mikayla Gimelli). Netex Service can sometimes be used to determine the GL code for TEOCO updating. Also before adding any entries, understand the difference between existing options and why a new option is needed rather than using an existing option. 

Be sure to also add/update the options on the same field on Expense Builder.</description>
    <label>Netex Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DS1</fullName>
            </value>
            <value>
                <fullName>DS3</fullName>
            </value>
            <value>
                <fullName>OC3</fullName>
            </value>
            <value>
                <fullName>OC12</fullName>
            </value>
            <value>
                <fullName>OC48</fullName>
            </value>
            <value>
                <fullName>OC192</fullName>
            </value>
            <value>
                <fullName>1G wave</fullName>
            </value>
            <value>
                <fullName>2.5G wave</fullName>
            </value>
            <value>
                <fullName>10G wave</fullName>
            </value>
            <value>
                <fullName>100G Wave</fullName>
            </value>
            <value>
                <fullName>CO Mux (3:1)</fullName>
            </value>
            <value>
                <fullName>CO Colocation - Space</fullName>
            </value>
            <value>
                <fullName>CO Colocation - CFA augment</fullName>
            </value>
            <value>
                <fullName>CO Colocation - Power augment</fullName>
            </value>
            <value>
                <fullName>CO X-connect - Unmanaged Fiber</fullName>
            </value>
            <value>
                <fullName>CO X-connect - Managed Optical</fullName>
            </value>
            <value>
                <fullName>CO X-Connect DS3</fullName>
            </value>
            <value>
                <fullName>DS1 Cross Connect</fullName>
            </value>
            <value>
                <fullName>DS3 Cross Connect</fullName>
            </value>
            <value>
                <fullName>FE(Cat5) Cross Connect</fullName>
            </value>
            <value>
                <fullName>2-fiber Cross Connect</fullName>
            </value>
            <value>
                <fullName>4-fiber Cross Connect</fullName>
            </value>
            <value>
                <fullName>Fiber lease</fullName>
            </value>
            <value>
                <fullName>IP</fullName>
            </value>
            <value>
                <fullName>Peering</fullName>
            </value>
            <value>
                <fullName>Entrance Facility Rider - DS3</fullName>
            </value>
            <value>
                <fullName>Entrance Facility Rider - OC3</fullName>
            </value>
            <value>
                <fullName>Entrance Facility Rider - OC12</fullName>
            </value>
            <value>
                <fullName>Cable Link from Street</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Expense__c/fields/Netx_MRC__c.field-meta.xml
<CustomField>
    <fullName>Netx_MRC__c</fullName>
    <label>Expense MRC</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/default/objects/Expense__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal Use</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>Pending Disconnect</fullName>
            </value>
            <value>
                <fullName>Pending Change</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Expense__c/fields/Vendor_Account__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Netx</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Expense__c/fields/Vendor_Circuit_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Circuit_Id__c</fullName>
    <description>Modifying field length from Text(80) to Text(53) to support the Circuit Inventory feed integration with TEOCO, where EC_CIRCUIT_ID (Vendor_Circuit_Id__c) is limited to 53 characters.</description>
    <label>Vendor Circuit Id</label>
    <length>53</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Expense__c/recordTypes/NetEx.recordType-meta.xml
<RecordType>
    <fullName>NetEx</fullName>
    <active>true</active>
    <label>NetEx</label>
</RecordType>

classes/Test_CaseNetX.cls
@isTest
public with sharing class Test_CaseNetX extends TestUtils.TestClass {
  
    static testMethod void testCase(){
        Mocks testData = new Mocks();
    
    Account a = testData.parentAccount;
    
    Customer_Detail__c cd = new Customer_Detail__c(ICC_Subscriber_ID__c = '-1');
    insert cd;
    
    a.Customer_Detail__c = cd.Id;
    update a;
        
        Expense__c E3 = new Expense__c();  
        E3.Status__c = 'Active';
        E3.Vendor_Account__c = a.id;
        E3.Escalation_Type__c = 'NetX';
        E3.Netex_Service__c = 'DS1';
        E3.Product_Group__c = 'Voice';
        E3.CurrencyCode__c = 'USD';
        E3.Vendor_Circuit_Id__c = 'C123';
        E3.Netx_MRC__c = 3;
        E3.Business_Unit_Owner__c = 'Allstream_SMB';
        
        insert E3;
 //       System.AssertNotEquals(null, zExp1);
    
        test.startTest();
    
    //String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'NetEx Case'].Id;
    String strRecordTypeNetX     = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'NetEx Case'].Id;
    
    Case cs = new Case(AccountId = a.Id
            ,Status = 'New'
            ,Origin = 'Email'
            ,Alternate_Contact_First_Name__c = 'Test'
            ,Alternate_Contact_Last_Name__c = 'Guy'
            ,Alternate_Contact_Phone__c = '(000) 000-0000'
            ,Alternate_Contact_Email__c = 'test@test.com'
            ,Netx__c = E3.Id
            ,Subject = 'Test'
            ,Description = 'TEST'
            ,RecordTypeId = strRecordTypeNetX
            ,Commit_Date__c = Date.today());
    insert cs;
    
    Case cu = cs;
    cu.status = 'In Progress';
    cu.type = 'Netx';
    update cu;
    
    //cases no longer create contacts
    //cs = [select Id, ContactId from Case where Id =: cs.Id];
    //System.assert(cs.ContactId != null, 'Alternate Contact was not created');
  }
  
    static testMethod void testCaseComment(){
        Mocks testData = new Mocks();
    
    Account a = testData.parentAccount;
    
    Customer_Detail__c cd = new Customer_Detail__c(ICC_Subscriber_ID__c = '-1');
    insert cd;
    
    a.Customer_Detail__c = cd.Id;
    update a;
    
    String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'NetEx Case'].Id;
    
    Case cs = new Case(AccountId = a.Id
            ,Status = 'New'
            ,Origin = 'Email'
            ,Alternate_Contact_First_Name__c = 'Test'
            ,Alternate_Contact_Last_Name__c = 'Guy'
            ,Alternate_Contact_Phone__c = '(000) 000-0000'
            ,Alternate_Contact_Email__c = 'test@test.com'
            ,RecordTypeId = strRecordTypeId
            ,Commit_Date__c = Date.today());
    insert cs;
    
        test.startTest();
    
    CaseComment cc = new CaseComment(ParentId = cs.Id
                    ,CommentBody = 'blahblahblah');
    insert cc;
  }
}