main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Customer_Detail__c/fields/Billing_Main_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_City__c</fullName>
    <label>Billing Main City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Country__c</fullName>
    <label>Billing Main Country</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Name__c</fullName>
    <label>Billing Main Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Postal_Code__c</fullName>
    <label>Billing Main Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Billing_Main_Room_Suite__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Room_Suite__c</fullName>
    <label>Billing Main Room/Suite</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Billing_Main_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_State__c</fullName>
    <label>Billing Main State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Billing_Main_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Main_Street__c</fullName>
    <label>Billing Main Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Customer_Reference__c.field-meta.xml
<CustomField>
    <fullName>Customer_Reference__c</fullName>
    <description>Used for Phoenix Interface. This is for the  customer reference information that is placed on the invoice</description>
    <label>Customer Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Customer_Detail__c/fields/Invoice_PLL__c.field-meta.xml
<CustomField>
    <fullName>Invoice_PLL__c</fullName>
    <description>Invoice preference for Phoenix</description>
    <label>Invoice PLL Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online PDF</fullName>
                <default>true</default>
                <label>Online PDF</label>
            </value>
            <value>
                <fullName>Online PDF + Paper</fullName>
            </value>
            <value>
                <fullName>Online PDF + Paper Pull</fullName>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
            <value>
                <fullName>G</fullName>
                <isActive>false</isActive>
                <label>G</label>
            </value>
            <value>
                <fullName>N</fullName>
                <isActive>false</isActive>
                <label>N</label>
            </value>
            <value>
                <fullName>Non-revenue</fullName>
                <isActive>false</isActive>
                <label>Non-revenue</label>
            </value>
            <value>
                <fullName>S</fullName>
                <isActive>false</isActive>
                <label>S</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Y</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <description>Preferred customer language</description>
    <inlineHelpText>Preferred customer language</inlineHelpText>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Legacy_ID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_ID__c</fullName>
    <inlineHelpText>Customer Account Number from legacy billing system</inlineHelpText>
    <label>Legacy ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Area</label>
    <referenceTo>Market_Area__c</referenceTo>
    <relationshipLabel>Customer Details</relationshipLabel>
    <relationshipName>Customer_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <description>To leverage account security on this object, we set the parent account of this object to the root of the hierarchy associated with it OR a system account if it is detached.</description>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Customer Details</relationshipLabel>
    <relationshipName>Child_Customer_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Market_Area__c/Market_Area__c.object-meta.xml
<CustomObject>
    <label>Market Area</label>
    <nameField>
        <label>Market Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Phoenix_Account_Transaction__c/Phoenix_Account_Transaction__c.object-meta.xml
<CustomObject>
    <description>Trigger table for SFDC to Phoenix Account Creation</description>
    <label>Phoenix Account Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>Phoenix Account Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phoenix Account Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Phoenix_Account_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Phoenix Account Transactions</relationshipLabel>
    <relationshipName>Phoenix_Account_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Phoenix_Account_Transaction__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Create, Update, Delete</description>
    <label>Action</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Phoenix_Account_Transaction__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Phoenix Account Transactions</relationshipLabel>
    <relationshipName>Phoenix_Account_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Phoenix_Account_Transaction__c/fields/Field_History__c.field-meta.xml
<CustomField>
    <fullName>Field_History__c</fullName>
    <label>Field History</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Phoenix_Account_Transaction__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Phoenix_Account_Transaction__c/fields/In_Queue__c.field-meta.xml
<CustomField>
    <fullName>In_Queue__c</fullName>
    <description>Y or N</description>
    <label>In Queue</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

main/default/objects/Phoenix_Account_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Pending, Sent, Completed, Error, Requeued</description>
    <label>Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

classes/PhoenixTransactionController.cls
public class PhoenixTransactionController {
    private static Id MarketAreaNational;
    public static string FieldHistory;
    private static List<Id> existingTransactionsInQueue;
    private static List<Id> failedCreateTransactions;
    private static List<Id> completedCreateTransactions;
    static {
        MarketAreaNational = [select Id From Market_Area__c Where Name = 'National'].Id;
    }
    public static void processCustomerDetailChanges(List<Customer_Detail__c> tNew, Map<Id, Customer_Detail__c> tOldMap, Boolean isDelete){
        Set<Id> cDetailsToBeProcessedSet = new Set<Id>();
        FieldHistory = '';
        System.debug('processCustomerDetailChanges Started');
        List<Customer_Detail__c> cDetailsToBeProcessed = new List<Customer_Detail__c>();
        for (Customer_Detail__c cDetail: tNew){
        	if (String.isBlank(cDetail.ICC_Subscriber_ID__c)) continue;
            if (cDetail.Market_Area__c != MarketAreaNational) continue;
            if (cDetail.Billable__c != true) continue;
            if (customerDetailAlreadyProcessedInThisBatch(cDetailsToBeProcessed, cDetail.Id)) continue;
            cDetailsToBeProcessed.add(cDetail);
            cDetailsToBeProcessedSet.add(cDetail.Id);
            System.debug('cDetail added to List: ' + cDetail.Id + ', name: ' + cDetail.Name);
        }
        
        existingTransactionsInQueue = new List<Id>();
        failedCreateTransactions = new List<Id>();
        completedCreateTransactions = new List<Id>();
        for (Phoenix_Account_Transaction__c t : [SELECT Customer_Detail__c, In_Queue__c, Action__c, Status__c FROM Phoenix_Account_Transaction__c WHERE Customer_Detail__c IN :cDetailsToBeProcessedSet]){
            if (t.In_Queue__c == 'Y'){
                existingTransactionsInQueue.add(t.Customer_Detail__c); 
            }
            
            if (t.Action__c == 'Create' && t.In_Queue__c == 'N' && t.Status__c == 'Failed'){
                failedCreateTransactions.add(t.Customer_Detail__c);
            }
            
             if (t.Action__c == 'Create' && t.In_Queue__c == 'N' && t.Status__c == 'Completed'){
                completedCreateTransactions.add(t.Customer_Detail__c);
            }	  
        }
        
        List<Phoenix_Account_Transaction__c> transactions = new List<Phoenix_Account_Transaction__c>();
        for (Customer_Detail__c cDetail: cDetailsToBeProcessed) {
            // Don't create new transaction if there's one that hasn't been processed by .Net app for this Customer Detail     
            if (!requireNewTransaction(cDetail.Id)) continue;
            Customer_Detail__c oldDetail = tOldMap.get(cDetail.Id);
            
            // Delete
            if (isDelete){
                
            }
            else {
                // Customer Detail just got ICC Subsriber ID, add new Create transaction
                if (String.isBlank(oldDetail.ICC_Subscriber_ID__c)) {
                    System.debug('Create transaction because ICC Subsriber ID was blank. oldDetail.ICC_Subsriber_ID__c: ' + oldDetail.ICC_Subscriber_ID__c + ', newDetail.ICC_Subsriber_ID__c: ' + cDetail.ICC_Subscriber_ID__c);
                	transactions.add(createTransactionObject(cDetail,'Create'));	    
                }
                else{
                    // Check if previous Create transaction failed
                    if (requireNewCreateTransaction(cDetail.Id)){
                        System.debug('Create transaction because of New Create');
                    	transactions.add(createTransactionObject(cDetail,'Create'));     
                    } else if (requirePhoenixUpdate(oldDetail, cDetail)){
                		transactions.add(createTransactionObject(cDetail,'Update'));    
                	}	    
                }
                
            }
    	}    
        
        insert transactions;
    }
    
    public static Phoenix_Account_Transaction__c createTransactionObject(Customer_Detail__c cDetail, String action){
        system.debug('FieldHistory: ' + FieldHistory);
    	Phoenix_Account_Transaction__c t = new Phoenix_Account_Transaction__c();
        t.Account__c = cDetail.Parent_Account__c;
        t.Action__c = action;    
        t.Customer_Detail__c = cDetail.Id;
        t.ICC_Subscriber_ID__c = cDetail.ICC_Subscriber_ID__c;
        t.In_Queue__c = 'Y';
        t.Status__c = 'Queued';
        t.Field_History__c = FieldHistory;
        return t;
    }
    
    private static boolean requirePhoenixUpdate(Customer_Detail__c oldCD, Customer_Detail__c newCD){
        boolean hasChanges = false;
        FieldHistory = '';
        if (newCD.Billing_Main_Name__c == null && oldCD.Name != newCD.Name){
        	return true;    
        }
        //if (oldCD.Legacy_ID__c != newCD.Legacy_ID__c || oldCD.Language_Preference__c != newCD.Language_Preference__c || oldCD.Invoice_PLL__c != newCD.Invoice_PLL__c || oldCD.Billing_Main_Room_Suite__c != newCD.Billing_Main_Room_Suite__c || oldCD.Billing_Main_City__c != newCD.Billing_Main_City__c || oldCD.Billing_Main_Street__c != newCD.Billing_Main_Street__c || oldCD.Billing_Main_State__c != newCD.Billing_Main_State__c || oldCD.Billing_Main_Postal_Code__c != newCD.Billing_Main_Postal_Code__c || oldCD.Billing_Main_Name__c != newCD.Billing_Main_Name__c || oldCD.Billing_Main_Country__c != newCD.Billing_Main_Country__c || oldCD.Customer_Reference__c != newCD.Customer_Reference__c || oldCD.CurrencyIsoCode != newCD.CurrencyIsoCode) 
        if (oldCD.Legacy_ID__c != newCD.Legacy_ID__c)
        {
            FieldHistory += 'Legacy ID has changed from "' + oldCD.Legacy_ID__c + '"" to "' + newCD.Legacy_ID__c + '"" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        if (oldCD.Language_Preference__c != newCD.Language_Preference__c)
        {
            FieldHistory += 'Language Preference has changed from "' + oldCD.Language_Preference__c + '"" to "' + newCD.Language_Preference__c + '"" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        if (oldCD.Invoice_PLL__c != newCD.Invoice_PLL__c)
        {
            FieldHistory += 'Invoice PLL Indicator has changed from "' + oldCD.Invoice_PLL__c + '" to "' + newCD.Invoice_PLL__c + '" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        if (oldCD.Billing_Main_Room_Suite__c != newCD.Billing_Main_Room_Suite__c)
        {
            FieldHistory += 'Billing Main Room/Suite has changed from "' + oldCD.Billing_Main_Room_Suite__c + '" to "' + newCD.Billing_Main_Room_Suite__c + '" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        if (oldCD.Billing_Main_City__c != newCD.Billing_Main_City__c)
        {
            FieldHistory += 'Billing Main City has changed from "' + oldCD.Billing_Main_City__c + '" to "' + newCD.Billing_Main_City__c + '" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        if (oldCD.Billing_Main_Street__c != newCD.Billing_Main_Street__c)
        {
            FieldHistory += 'Billing Main Street has changed from "' + oldCD.Billing_Main_Street__c + '" to "' + newCD.Billing_Main_Street__c + '" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        if (oldCD.Billing_Main_State__c != newCD.Billing_Main_State__c)
        {
            FieldHistory += 'Billing Main State has changed from "' + oldCD.Billing_Main_State__c + '" to "' + newCD.Billing_Main_State__c + '" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        if (oldCD.Billing_Main_Postal_Code__c != newCD.Billing_Main_Postal_Code__c)
        {
            FieldHistory += 'Billing Main Postal Code has changed from "' + oldCD.Billing_Main_Postal_Code__c + '" to "' + newCD.Billing_Main_Postal_Code__c + '" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        if (oldCD.Billing_Main_Name__c != newCD.Billing_Main_Name__c)
        {
            FieldHistory += 'Billing Main Name has changed from "' + oldCD.Billing_Main_Name__c + '" to "' + newCD.Billing_Main_Name__c + '" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        if (oldCD.Billing_Main_Country__c != newCD.Billing_Main_Country__c)
        {
            FieldHistory += 'Billing Main Country has changed from "' + oldCD.Billing_Main_Country__c + '" to "' + newCD.Billing_Main_Country__c + '" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        if (oldCD.Customer_Reference__c != newCD.Customer_Reference__c)
        {
            FieldHistory += 'Customer Reference has changed from "' + oldCD.Customer_Reference__c + '" to "' + newCD.Customer_Reference__c + '" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        if (oldCD.CurrencyIsoCode != newCD.CurrencyIsoCode)
        {
            FieldHistory += 'Currency has changed from "' + oldCD.CurrencyIsoCode + '" to "' + newCD.CurrencyIsoCode + '" by ' + newCD.LastModifiedById + ' on ' + newCD.LastModifiedDate + '\n';
        	hasChanges = true;    
        }
        //System.debug('FieldHistory: ' + FieldHistory);
        if (hasChanges){
            return true;
        }
        else {
            return false;
        }
        
    }
    
    private static boolean requireNewTransaction(Id CDId){
        if (existingTransactionsInQueue.isEmpty() || !existingTransactionsInQueue.contains(CDId)){
            return true;
        }
        else{
            return false; 
        }
    }
    
     private static boolean requireNewCreateTransaction(Id CDId){
        if (!failedCreateTransactions.contains(CDId)){
            return false;
        }
        else{
            if (!completedCreateTransactions.contains(CDId)){
           		return true;
            }
            else{
            	return false;    
            }
        }
    }
    
    private static boolean customerDetailAlreadyProcessedInThisBatch(List<Customer_Detail__c> cDetails, Id customerDetailId){
        for (Customer_Detail__c cd : cDetails){
            if (cd.Id == customerDetailId) return true;
        }
        return false;
    }
}