main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/Customer_Main_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Main_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subscriber Address Type &#39;Customer Main&#39;</description>
    <label>Customer Main Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Customer Details (Customer Main Address)</relationshipLabel>
    <relationshipName>Customer_Main_Address_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Legacy_ID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_ID__c</fullName>
    <inlineHelpText>Customer Account Number from legacy billing system</inlineHelpText>
    <label>Legacy ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Customer_Detail__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Area</label>
    <referenceTo>Market_Area__c</referenceTo>
    <relationshipLabel>Customer Details</relationshipLabel>
    <relationshipName>Customer_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subscriber Address &#39;Service Address&#39;</description>
    <label>Service Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Customer Details (Service Address)</relationshipLabel>
    <relationshipName>Service_Address_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Market_Area__c/Market_Area__c.object-meta.xml
<CustomObject>
    <label>Market Area</label>
    <nameField>
        <label>Market Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_ImportDataFromCSVController.cls
@isTest
public with sharing class Test_ImportDataFromCSVController extends TestUtils.TestClass {
    static String str = 'RENEWAL_STATUS,CONTRACT,CUSTNO,CTR_END,CTR_PRICE,NEXT_START,NEXT_END,NEXT_PRICE \n Renewed,16-113101,468475,30/07/2018,154.5,31/07/2018,30/07/2019,154.5'; 
	static String churnStr = 'CONTRACT,CUSTNO,CURRENTCANCELDATE,CANCELLATIONDESCRIPTION,CURRENTSTARTDATE,CURRENTENDDATE,MRR \n 16-113101,468475,30/07/2018,test,31/07/2018,30/07/2019,154.5'; 
	static String installStr = 'Order,CUSTNBR,MRR \n 186756,468475,154.5';     

    public static String[] csvFileLines;
    public static Blob csvFileBody;
    private static Mocks testData = null;
    
    private static void getTestData(){
        testData = new Mocks();
		Market_Area__c ma = testData.marketArea;
        ma.Name = 'National';
        update ma;
        Account a = testData.parentAccount;
        
        Customer_Detail__c detail = new Customer_Detail__c(ICC_Subscriber_ID__c = '-9999'
                                                            ,Customer_Main_Address__c = testData.loc.Id
                                                            ,Service_Address__c = testData.loc.Id
                                                            ,Market_Area__c = testData.marketArea.Id
                                                            ,Legacy_Id__c = '468475');
        insert detail;
        
        a.Customer_Detail__c = detail.Id;
        update a;
    }
    
    static testmethod void testReadFromFile(){
        getTestData();
        Test.startTest();       
        csvFileBody = Blob.valueOf(str);
        String csvAsString = csvFileBody.toString();
        csvFileLines = csvAsString.split('\n'); 

        ImportDataFromCSVController importData = new ImportDataFromCSVController();
        importData.csvFileBody = csvFileBody;
        importData.selectedFileType = 'Renewal';
        importData.readFromFile();
        System.assert(importData.orderDataLines.size() ==csvFileLines.size() );
        importData.saveData();
        Test.stopTest();
    }         
    static testmethod void testReadFromChurnFile(){
        getTestData();
        Test.startTest();       
        csvFileBody = Blob.valueOf(churnStr);
        String csvAsString = csvFileBody.toString();
        csvFileLines = csvAsString.split('\n'); 

        ImportDataFromCSVController importData = new ImportDataFromCSVController();
        importData.csvFileBody = csvFileBody;
        importData.selectedFileType = 'Actual Churn';
        importData.readFromFile();
        System.assert(importData.orderDataLines.size() ==csvFileLines.size() );
        importData.saveData();        
        Test.stopTest();
    }         
    static testmethod void testReadFromInstallFile(){
        getTestData();
        Test.startTest();       
        csvFileBody = Blob.valueOf(installStr);
        String csvAsString = csvFileBody.toString();
        csvFileLines = csvAsString.split('\n'); 

        ImportDataFromCSVController importData = new ImportDataFromCSVController();
        importData.csvFileBody = csvFileBody;
        importData.selectedFileType = 'Actual Install';
        importData.readFromFile();
        System.assert(importData.orderDataLines.size() ==csvFileLines.size() );
        importData.saveData();
        Test.stopTest();
    }         
    
}