main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Customer_Detail__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pre-Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Customer_Detail__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Area</label>
    <referenceTo>Market_Area__c</referenceTo>
    <relationshipLabel>Customer Details</relationshipLabel>
    <relationshipName>Customer_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <description>To leverage account security on this object, we set the parent account of this object to the root of the hierarchy associated with it OR a system account if it is detached.</description>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Customer Details</relationshipLabel>
    <relationshipName>Child_Customer_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Market_Area__c/Market_Area__c.object-meta.xml
<CustomObject>
    <label>Market Area</label>
    <nameField>
        <label>Market Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Location__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Parent_Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Parent_Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Service Location</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__r.ICC_Subscriber_ID__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__r.ICC_Account_Number__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/CustomerIntegrationEndPoint.cls
global class CustomerIntegrationEndPoint {
    
   webservice static Integer integrateAccounts(Integer NumberOfAccounts, Boolean Billable) {
 
        List<Account> aList = [SELECT Id, Customer_Detail__c, 
                               (select Id, Customer_Detail__c from Account_Locations__r where ICC_Subscriber_ID__c = null and Customer_Detail__c != null), 
                               (select Id from Account_Based_Orders__r where RecordType.DeveloperName = 'Integration_Only_Order')
                              FROM Account where ICC_Account_Number__c = null and Customer_Detail__c != null 
                               	and Customer_Detail__r.Market_Area__r.Name = 'National' and CreatedById = '005C0000003NsFa' 
                                and Customer_Detail__r.Billable__c =: Billable
                                limit :NumberofAccounts];
    
        Set<Id> customerDetailIDs = new Set<Id>();
        Map<Id, Id> orderIDsByLocationID = new Map<Id, Id>();

        for(Account a : aList){
            if(a.Account_Locations__r.size() > 0 && a.Account_Based_Orders__r.size() > 0){
                for(Service_Location__c sLoc : a.Account_Locations__r) {
                    customerDetailIDs.add(a.Customer_Detail__c); 
                    customerDetailIDs.add(sLoc.Customer_Detail__c); 
                    orderIDsByLocationID.put(sLoc.Id, a.Account_Based_Orders__r[0].Id); 
                }
            }
        }

        //Integrate
        if(orderIDsByLocationID.size() > 0){
            List<string> errors = new List<string>{};
            If (!Test.isRunningTest())
             	errors = IntegrationUtils.createSubscribersFromOrderRelatedServiceLocations(orderIDsByLocationID, UserInfo.getSessionId());
            for(String error : errors) {
				system.debug(error);
            }
    	}
        
        return aList.size();
    }

	webservice static Integer integrateAccountServiceLocations(String AccountSFID, Boolean doBillable) {
 
        List<Customer_Detail__c> cdList = [SELECT id 
                      FROM Customer_Detail__c 
                      WHERE Parent_Account__c =: AccountSFID 
                      	AND ICC_Subscriber_ID__c = null
                        AND Billable__c =: doBillable
                      LIMIT 1];
    
        for (Customer_Detail__c cd: cdList) {
            Map<Id, Id> orderIDsByServiceLocationID = new Map<Id, Id>();
            
            Set<Id> sLocIDs = new Set<Id>();
            for(Service_Location__c sLoc : [select Id, Parent_Service_Location__c, Parent_Service_Location__r.Parent_Service_Location__c from Service_Location__c where Customer_Detail__c =: cd.id]){
                for(Id id : new List<Id>{ sLoc.Id, sLoc.Parent_Service_Location__c, sLoc.Parent_Service_Location__r != null ? sLoc.Parent_Service_Location__r.Parent_Service_Location__c : null }){
                    if(id != null) sLocIDs.add(id);
                }
            }
    
            for(Id sLocID : sLocIDs)
        		orderIDsByServiceLocationID.put(sLocID, null);
            
    		List<string> errors = new List<string>{};
            If (!Test.isRunningTest() && orderIDsByServiceLocationID.size() > 0)
            	errors = IntegrationUtils.createSubscribersFromOrderRelatedServiceLocations(orderIDsByServiceLocationID, UserInfo.getSessionId());
            for(String error : errors) {
				system.debug(cd.id + ' ' + error);
            }
    	}
        
        return cdList.size();
    }
 
    webservice static Integer integrateServiceLocation(Boolean doBillable, Boolean doNational) {
 
        List<Customer_Detail__c> cdList = new List<Customer_Detail__c>{};
        
        if (doNational)    
            cdList = [SELECT id FROM Customer_Detail__c WHERE ICC_Subscriber_ID__c = null
                        AND Billable__c =: doBillable and Market_Area__r.Name = 'National'
                        AND (Parent_Account__r.Customer_Detail__r.Integration_Status__c = 'Draft' OR Parent_Account__r.Customer_Detail__r.Integration_Status__c = 'Active') LIMIT 1];
    	else
            cdList = [SELECT id FROM Customer_Detail__c WHERE ICC_Subscriber_ID__c = null
                        AND Billable__c =: doBillable and Market_Area__r.Name != 'National' 
                        AND (Parent_Account__r.Customer_Detail__r.Integration_Status__c = 'Draft' OR Parent_Account__r.Customer_Detail__r.Integration_Status__c = 'Active') LIMIT 1];
 
        for (Customer_Detail__c cd: cdList) {
            Map<Id, Id> orderIDsByServiceLocationID = new Map<Id, Id>();
            Set<Id> sLocIDs = new Set<Id>();
            for(Service_Location__c sLoc : [select Id, Parent_Service_Location__c, Parent_Service_Location__r.Parent_Service_Location__c from Service_Location__c where Customer_Detail__c =: cd.id]){
                for(Id id : new List<Id>{ sLoc.Id, sLoc.Parent_Service_Location__c, sLoc.Parent_Service_Location__r != null ? sLoc.Parent_Service_Location__r.Parent_Service_Location__c : null }){
                    if(id != null) sLocIDs.add(id);
                }
            }
    
            for(Id sLocID : sLocIDs)
        		orderIDsByServiceLocationID.put(sLocID, null);
            
            List<string> errors = new List<string>{};
            If (!Test.isRunningTest() && orderIDsByServiceLocationID.size() > 0)
            	errors = IntegrationUtils.createSubscribersFromOrderRelatedServiceLocations(orderIDsByServiceLocationID, UserInfo.getSessionId());

            for(String error : errors) {
				system.debug(cd.id + ' ' + error);
            }
    	}
        
        return cdList.size();
    }    
}