main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Customer_Detail__c/fields/Care_Organization__c.field-meta.xml
<CustomField>
    <fullName>Care_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Organization</label>
    <referenceTo>Customer_Setting__c</referenceTo>
    <relationshipLabel>Customer Details (Care Organization)</relationshipLabel>
    <relationshipName>Care_Organization_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Detail__c/fields/Customer_Main_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Main_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subscriber Address Type &#39;Customer Main&#39;</description>
    <label>Customer Main Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Customer Details (Customer Main Address)</relationshipLabel>
    <relationshipName>Customer_Main_Address_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Legacy_ID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_ID__c</fullName>
    <inlineHelpText>Customer Account Number from legacy billing system</inlineHelpText>
    <label>Legacy ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subscriber Address &#39;Service Address&#39;</description>
    <label>Service Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Customer Details (Service Address)</relationshipLabel>
    <relationshipName>Service_Address_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Setting__c/Customer_Setting__c.object-meta.xml
<CustomObject>
    <label>Customer Setting</label>
    <nameField>
        <label>Customer Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Setting__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Customer Settings</relationshipLabel>
    <relationshipName>Customer_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Setting__c/recordTypes/Care_Organization.recordType-meta.xml
<RecordType>
    <fullName>Care_Organization</fullName>
    <active>true</active>
    <label>Care Organization</label>
</RecordType>

main/default/objects/Opportunity_Product__c/Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{0000000}</displayFormat>
        <label>Opportunity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Products</relationshipLabel>
    <relationshipName>Opportunity_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/Test_OppProdRecordTypeSelectController.cls
@isTest
public with sharing class Test_OppProdRecordTypeSelectController extends TestUtils.TestClass {    
    private static Mocks testData = null;
    
    private static void getTestData(){
        testData = new Mocks();
        Account a = testData.parentAccount;
        List<RecordType> rt = [select Id from RecordType where DeveloperName ='Care_Organization' limit 1];
        Customer_Setting__c cs = new Customer_Setting__c(RecordTypeId=rt.get(0).Id, Name='Wholesale Care Org', Value__c='Wholesale Care Org');
        insert cs;

        Customer_Detail__c detail = new Customer_Detail__c(Customer_Main_Address__c = testData.loc.Id
                                                            ,Service_Address__c = testData.loc.Id
                                                            ,Legacy_Id__c = '468475', care_Organization__c=cs.Id);

        insert detail;
        
        a.Customer_Detail__c = detail.Id;
        update a;
    }

    static testmethod void testRetailRT(){
        getTestData();
        Test.startTest(); 
        PageReference p= Page.OppProdRecordTypeSelector;
        Opportunity opp1 = testData.opportunity;
        opp1.Sell_To_Through__c = 'Sell Through';
        update opp1;
        p.getParameters().put('CF00NC0000005gStS_lkid',opp1.Id);        
        p.getParameters().put('CF00NC0000005gStS',opp1.Name);
        p.getParameters().put('retURL', '/'+ opp1.Id);

        Test.setCurrentPage(p);
        
        Apexpages.StandardController sc = new Apexpages.StandardController(new Opportunity_Product__c(Opportunity__c=opp1.Id));
        OppProdRecordTypeSelectController selectRT = new OppProdRecordTypeSelectController(sc);
        
        selectRT.continueMethod();        
        
        Test.stopTest();
    }    
    
    static testmethod void testWholesaleRT(){
        getTestData();
        Test.startTest(); 
        PageReference p= Page.OppProdRecordTypeSelector;
        Opportunity opp1 = testData.opportunity;
        RecordType rt = [Select r.SobjectType, r.Name, r.Id From RecordType r where r.SobjectType = 'Opportunity' and r.Name = 'Wholesale'];
        opp1.RecordTypeId = rt.Id;
        opp1.Service_Type_Detail__c ='T1';
        opp1.Service_Types__c = 'Voice Services';
        update opp1;
        p.getParameters().put('CF00NC0000005gStS_lkid',opp1.Id);        
        p.getParameters().put('CF00NC0000005gStS',opp1.Name);
        p.getParameters().put('retURL', '/'+ opp1.Id);

        Test.setCurrentPage(p);
        
        Apexpages.StandardController sc = new Apexpages.StandardController(new Opportunity_Product__c(Opportunity__c=opp1.Id));
        OppProdRecordTypeSelectController selectRT = new OppProdRecordTypeSelectController(sc);
        
        selectRT.continueMethod();        
        
        Test.stopTest();
    }    
    
}