main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Owned_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Detail__c/fields/Owner_Agency__c.field-meta.xml
<CustomField>
    <fullName>Owner_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner Agency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Indirect Channel Agency</value>
        </filterItems>
        <filterItems>
            <field>Account.AgentId__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Details (Owner Agency)</relationshipLabel>
    <relationshipName>Owned_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <description>To leverage account security on this object, we set the parent account of this object to the root of the hierarchy associated with it OR a system account if it is detached.</description>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Customer Details</relationshipLabel>
    <relationshipName>Child_Customer_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Customer_Detail__c/fields/Parent_Customer__c.field-meta.xml
<CustomField>
    <fullName>Parent_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Customer</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Child Customers</relationshipLabel>
    <relationshipName>Child_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Service_Location__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Indirect Channel Agency</value>
        </filterItems>
        <filterItems>
            <field>Account.AgentId__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations (Agency)</relationshipLabel>
    <relationshipName>ServiceLocationToAccountForAgency</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Location__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

objects/Service_Location__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Owned_Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Parent_Service_Location__c.field-meta.xml
<CustomField>
    <fullName>Parent_Service_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Service Location</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Service_Location__c.Parent_Service_Location__r.ICC_Subscriber_ID__c</field>
            <operation>equals</operation>
            <valueField>Service_Location__c.Account__r.ICC_Account_Number__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Location__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/ServiceLocationTriggers.cls
public without sharing class ServiceLocationTriggers {

    public static Boolean DisableIntegration = false;
	public static Boolean SynchronizingFields = false;
    
    public static void ServiceLocationModified(List<Service_Location__c> tNew, List<Service_Location__c> tOld, Boolean isUpdate, Boolean isBefore, Boolean isDelete){
		
    	if(!ApexUtils.executeTriggerMethods('Service_Location__c', isBefore, false)) return;
    	
    	if(isBefore){
    		if(!isDelete){
		        if(!isUpdate)
		        	fixCustomerDetails(tNew, true);
		        
		        handleNullOwners(tNew);
	            Map<Id, Service_Location__c> tOldMap = tOld != null ? new Map<Id, Service_Location__c>(tOld) : new Map<Id, Service_Location__c>();
				
				if(isUpdate && SecurityUtils.stopOwnershipUpdates(tNew, tOldMap)) return;
	            if(CustomerDetailUtils.checkRelatedObjectUpdated(tNew, tOldMap, false)){
	           		synchCustomerDetailFields(tNew, tOldMap);
	            }
    		}
    	}
    	else{
	        Map<Id, Service_Location__c> tOldMap = tOld != null ? new Map<Id, Service_Location__c>(tOld) : new Map<Id, Service_Location__c>();
    		if(!isDelete){
				
				if(!isUpdate)
		        	fixCustomerDetails(tNew, false);
				
				CustomerDetailUtils.handleNewCustomerDetailSet(tNew, tOldMap, false);
			}
			
        	CustomerDetailUtils.setCustomerDetailParents((List<sObject>)tNew, (List<sObject>)tOld, isDelete);
	        
			if(isUpdate) Batch_CalculateAccountOwnership.HandleOwnershipRecalculation(tNew, tOldMap);
			ApexUtils.afterTriggerComplete('Service_Location__c', isDelete);
    	}
    }
    
    private static void handleNullOwners(List<Service_Location__c> tNew){
    	Map<Id, Account> accounts = new Map<Id, Account>();
    	Set<Integer> fix = new Set<Integer>();
    	for(Integer i=0; i<tNew.size(); i++){
     		if(tNew[i].Owner__c == null){
     			accounts.put(tNew[i].Account__c, null);
     			fix.add(i);
     		}
    	}
    	
    	if(accounts.size() > 0){
    		accounts = new Map<Id, Account>([select Id, OwnerId from Account where Id in : accounts.keyset()]);
    		for(Integer f : fix){
				if(CustomerDetailTriggers.SynchronizingFields) tNew[f].addError('Owner is required');
    			else tNew[f].Owner__c = accounts.get(tNew[f].Account__c).OwnerId;
			}
    	}
    }
    
    public static void synchCustomerDetailFields(List<Service_Location__c> tNew, Map<Id, Service_Location__c> tOldMap){
		
		if(CustomerDetailTriggers.SynchronizingFields) return;
		
		Map<Id, Customer_Detail__c> cdUpdates = new Map<Id, Customer_Detail__c>();
		Map<Id, Service_Location__c> parentLocs = new Map<Id, Service_Location__c>();
		Map<Id, Account> accountParents = new Map<Id, Account>();
		Set<Service_Location__c> accountParentUpdated = new Set<Service_Location__c>();
     	for(Service_Location__c sNew : tNew){
     		Service_Location__c sOld = sNew.Id != null ? tOldMap.get(sNew.Id) : null;
			if(sOld == null || ((sOld.Account__c != sNew.Account__c || sOld.Parent_Service_Location__c != null) && sNew.Parent_Service_Location__c == null)) accountParentUpdated.add(sNew);
     		if(sNew.Customer_Detail__c != null
	     		&& (sOld == null
	     			|| sOld.Customer_Detail__c != sNew.Customer_Detail__c
	     			|| sOld.Name != sNew.Name
					|| sOld.Billable__c != sNew.Billable__c
	     			|| sOld.Phone__c != sNew.Phone__c
	     			//|| sOld.Agency__c != sNew.Agency__c
	     			|| sOld.Owner__c != sNew.Owner__c
					|| sOld.Parent_Service_Location__c != sNew.Parent_Service_Location__c
					|| accountParentUpdated.contains(sNew))){
     			cdUpdates.put(sNew.Customer_Detail__c, null);
				accountParents.put(sNew.Account__c, null);
				
				if(sNew.Id != null) parentLocs.put(sNew.Id, sNew);
				if(sNew.Parent_Service_Location__c != null) parentLocs.put(sNew.Parent_Service_Location__c, null);
			}
     	}
		
     	if(cdUpdates.size() > 0){
			cdUpdates = new Map<Id, Customer_Detail__c>([select Id, (select Name, Billable__c, Phone, OwnerId/*, Agency__c*/ from Accounts__r) from Customer_Detail__c where Id in: cdUpdates.keyset()]);
			for(Service_Location__c sLoc : [select Id, Customer_Detail__c, (select Id, Customer_Detail__r.Parent_Customer__c from Service_Locations__r) from Service_Location__c where Id in: parentLocs.keyset()]){
				if(parentLocs.get(sLoc.Id) == null) parentLocs.put(sLoc.Id, sLoc);
			}
			accountParents = new Map<Id, Account>([select Id, Customer_Detail__c from Account where Id in: accountParents.keyset()]);
			
	     	for(Service_Location__c s : tNew){
     			Service_Location__c sOld = s.Id != null ? tOldMap.get(s.Id) : null;
				Customer_Detail__c cd = s.Customer_Detail__c != null ? cdUpdates.get(s.Customer_Detail__c) : null;
				
				if(cd != null){
					Account a = (cd.Accounts__r != null && cd.Accounts__r.size() > 0) ? cd.Accounts__r[0] : null;
					Boolean useAccountFields = (sOld == null || sOld.Customer_Detail__c != s.Customer_Detail__c) && a != null;
					
					s.Name = cd.Name = (useAccountFields ? a.Name : s.Name);
					s.Billable__c = cd.Billable__c = (useAccountFields ? a.Billable__c : s.Billable__c);
					s.Phone__c = cd.Phone__c = ((useAccountFields && a.Phone != null) ? a.Phone : s.Phone__c);
					s.Owner__c = cd.Owner__c = (useAccountFields ? a.OwnerId : s.Owner__c);
					//s.Agency__c = cd.Owner_Agency__c = ((useAccountFields && a.Agency__c != null) ? a.Agency__c : s.Agency__c);
					
					Account sa = accountParents.get(s.Account__c);
					cd.Parent_Account__c = (a != null) ? a.Id : s.Account__c;
					cd.Parent_Customer__c = (s.Parent_Service_Location__c != null) ? parentLocs.get(s.Parent_Service_Location__c).Customer_Detail__c : ((sa.Customer_Detail__c != cd.Id) ? sa.Customer_Detail__c : null);
				}
	     	}
			
			Boolean oSynch = SynchronizingFields;
			SynchronizingFields = true;
			if(cdUpdates.size() > 0) update cdUpdates.values();
			SynchronizingFields = oSynch;
     	}
	}
    
    //If a new service location is inserted we may need to detach the customer detail value from a once single loc account
    private static void fixCustomerDetails(List<Service_Location__c> sLocs, Boolean isBefore){
    	Map<Id, Account> accounts = new Map<Id, Account>();
    	Map<Id, Map<Id, Service_Location__c>> serviceLocsByAccountID = new Map<Id, Map<Id, Service_Location__c>>();
    	for(Service_Location__c sLoc : sLocs){
    		if(sLoc.Account__c != null){
    			accounts.put(sLoc.Account__c, null);
    			
    			Map<Id, Service_Location__c> locs = serviceLocsByAccountID.get(sLoc.Account__c);
    			if(locs == null)
    				locs = new Map<Id, Service_Location__c>();
    			
    			locs.put(sLoc.Id, sLoc);
    			serviceLocsByAccountID.put(sLoc.Account__c, locs);
    		}
    	}
    	
    	accounts = new Map<Id, Account>([select Id
    											,ICC_Account_Number__c
    											,Customer_Detail__c
    											,(select Id, Account__c, ICC_Subscriber_ID__c, Customer_Detail__c from Account_Locations__r)
    											from Account where ICC_Account_Number__c = null and Customer_Detail__c != null and Id in : accounts.keyset()]);
    	
    	List<Service_Location__c> serviceLocsToUpdate = new List<Service_Location__c>();
    	Set<Id> serviceLocIDsToUpdate = new Set<Id>();
    	for(Id accountID : serviceLocsByAccountID.keyset()){
    		Account a = accounts.get(accountID);
    		Map<Id, Service_Location__c> newLocs = serviceLocsByAccountID.get(accountID);
    		
    		if(a == null || newLocs == null) continue;
    		
    		if(isBefore){
    			if(newLocs.size() == 1 && (a.Account_Locations__r == null || a.Account_Locations__r.size() == 0)
    					&& a.Customer_Detail__c != null && newLocs.values()[0].Customer_Detail__c == null)
    				newLocs.values()[0].Customer_Detail__c = a.Customer_Detail__c;
    		}
    		else if(a.Account_Locations__r.size() > 1){
	    		for(Service_Location__c accountLoc : a.Account_Locations__r){
	    			if(newLocs.get(accountLoc.Id) == null && accountLoc.Customer_Detail__c == a.Customer_Detail__c)
	    				serviceLocIDsToUpdate.add(accountLoc.Id);
	    		}
    		}
    	}
    	
    	if(serviceLocIDsToUpdate.size() > 0)
    		CustomerDetailUtils.cloneCustomerDetails(serviceLocIDsToUpdate, null);
    }
}