main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <description>Details for customer records</description>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Detail__c/fields/Customer_Main_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Main_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subscriber Address Type &#39;Customer Main&#39;</description>
    <label>Customer Main Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Customer Details (Customer Main Address)</relationshipLabel>
    <relationshipName>Customer_Main_Address_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Detail__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <externalId>true</externalId>
    <label>ICC Subscriber ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Customer_Detail__c/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subscriber Address &#39;Service Address&#39;</description>
    <label>Service Address</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Customer Details (Service Address)</relationshipLabel>
    <relationshipName>Service_Address_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/Service_Location__c.object-meta.xml
<CustomObject>
    <label>Service Location</label>
    <nameField>
        <label>Service Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Service_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Account_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Service_Location__c/fields/Customer_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customer_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Detail</label>
    <referenceTo>Customer_Detail__c</referenceTo>
    <relationshipLabel>Service Locations</relationshipLabel>
    <relationshipName>Service_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Service_Location__c/fields/ICC_Subscriber_ID__c.field-meta.xml
<CustomField>
    <fullName>ICC_Subscriber_ID__c</fullName>
    <formula>Customer_Detail__r.ICC_Subscriber_ID__c</formula>
    <label>ICC Subscriber ID</label>
    <type>Text</type>
</CustomField>

classes/Test_NotesViewer.cls
@isTest
public with sharing class Test_NotesViewer extends TestUtils.TestClass {
	
	static testMethod void testController() {
		Mocks testData = new Mocks();
		
		Account a = testData.parentAccount;
		Note__c note = new Note__c(Name='Test note', Account__c=a.Id);
		insert note;
		
    	Customer_Detail__c detail = new Customer_Detail__c(ICC_Subscriber_ID__c = '-9999'
															,Customer_Main_Address__c = testData.loc.Id
															,Service_Address__c = testData.loc.Id);
    	insert detail;
		
		a.Customer_Detail__c = detail.Id;
		update a;
		
		Service_Location__c sLoc = testData.serviceLocation;
		Note standardNote = new Note(Title='Standard note', ParentId=sLoc.Id, Body='bodyText');
		insert standardNote;
		
		Test.startTest();
		
		PageReference pageReference = Page.NotesViewer;
		pageReference.getParameters().put('id', a.Id);
		pageReference.getParameters().put('related', '[{"name":"Account_Locations__r"}]');
		
		Test.setCurrentPage(pageReference);
		
		Date sd = Date.today().addDays(-1);
		Date ed = Date.today().addDays(1);
		
		NotesViewerController nvc = new NotesViewerController();
		nvc.StartDateString = string.valueOf(sd.year()) + '-' + string.valueOf(sd.month()) + '-' + string.valueOf(sd.day());
		nvc.EndDateString = string.valueOf(ed.year()) + '-' + string.valueOf(ed.month()) + '-' + string.valueOf(ed.day());
		nvc.GetNotes();
		
		pageReference.getParameters().put('sortColumn', 'ParentName');
		nvc.changeSort();
		
		System.debug(nvc.getTestClass());
	}
}